### ISSUE TITLE
Many popular Helm charts are failing to install on version 1.5.0

### ISSUE THREAD

**Issue by alvarocantador** [rancher-sandbox/rancher-desktop#2668] opened 2022-08-01 20:11 UTC
### Actual Behavior

I upgraded Rancher Desktop from version 1.4.1 to 1.5.0 and it started to fail to spin up some famous Helm Charts.

### Steps to Reproduce

Just run `helm install redis bitnami/redis`

### Result

It will install the Redis Helm chart, but the pod never gets ready and the logs for the pod you can see:

```
/etc/profile: line 4: [: uid=1001 gid=0(root) groups=0(root),1001: integer expression expected
/opt/bitnami/redis/mounted-etc/master.conf: missing destination file operand after '/opt/bitnami/redis/etc/master.conf'
Try '/opt/bitnami/redis/mounted-etc/master.conf --help' for more information.
/opt/bitnami/redis/mounted-etc/redis.conf: missing destination file operand after '/opt/bitnami/redis/etc/redis.conf'
Try '/opt/bitnami/redis/mounted-etc/redis.conf --help' for more information.
/opt/bitnami/scripts/start-scripts/start-master.sh: line 15: exec: redis-server: not found
```

### Expected Behavior

The pod gets ready as in the Rancher version 1.4.1

### Additional Information

It worked fine in all Rancher Desktop's previous versions. I don't know if it is related to k3s or other stuff, and I don't exactly how to troubleshoot it.

### Rancher Desktop Version

1.5.0

### Rancher Desktop K8s Version

1.22.1

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.4

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by rak-phillip** [comment] 2022-08-02 17:19
@alvarocantador thanks for raising this issue and helping to make Rancher Desktop better!

I'm not able to reproduce this one at the moment. I can see that all the redis pods enter a running state after testing with `helm install redis bitnami/redis`. I'm also able to successfully run both examples provided after the install for `To connect to your Redis&reg; server:` & `To connect to your database from outside the cluster execute the following commands:`

Are you able to attach your rancher desktop logs to this issue? I think we'll need to take a look at them to get a better sense of what might be going on.

**Comment by mmhealey1** [comment] 2022-08-02 19:10
Might be related but I have issues when installing bitnami/redis-cluster helm chart with the same spec as above. I get "no such file or directory" errors for all of the redis pods when they are initializing

**Comment by jprelph** [comment] 2022-08-02 20:11
We're getting something that may be related to this with a hashibox we run Terraform in - worked absolutely fine in 1.4.1, if we install 1.5.0 we get an error that seems to suggest the command isn't being passed correctly from the script to the container (ie. `Usage: terraform [-version] [-help] <command> [args]: syntax error in expression (error token is ": terraform [-version] [-help] <command> [args]")` ). It's not even a particularly funky line it's throwing on as well:

`declare -i tf_version=$(eval "$terraform" --version | head -1 | cut -f2 -d.)`

There's nothing obviously being logged as an error, but that doesn't surprise me as the container itself seems to be running OK but the command passed in seems to be getting messed up. We've seen this on three separate machines now, so it's not a particular config.

**Comment by mook-as** [comment] 2022-08-02 21:57
There's something odd going on with argument parsing; given the command:
> `docker run --rm -t -i --entrypoint=/usr/bin/id docker.io/bitnami/redis:7.0.4-debian-11-r4 -u`

On x86_64 (actually, Linux host), I get:
> 1001

On M1 / RD 1.5.0 / moby, I get:
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> uid=1001 gid=0(root) groups=0(root)

The warning is… probably expected, though this may be related to #2659 (at least, as far as running images from different platforms).

Note that the same behaviour occurs in an interactive shell (that is, the issue isn't with `docker run…` argument parsing).  In the container on arm64:

> ```
> I have no name!@cac6b4751301:/$ id -u
> uid=1001 gid=0(root) groups=0(root)
> I have no name!@cac6b4751301:/$ id - -u 
> 1001

**Comment by ngraef** [comment] 2022-08-03 03:21
> worked absolutely fine in 1.4.1, if we install 1.5.0 we get an error that seems to suggest the command isn't being passed correctly

This is what we noticed too. We have an image created from a Dockerfile that looks something like this:
```Dockerfile
# ...
ENTRYPOINT ["node"]
CMD ["script.js", "<script-arg>"]
```

When it runs in Rancher Desktop 1.5.0 with moby, `node` throws the following error:
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '<script-arg>'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

This tells me that `node` is trying to process `<script-arg>` as the script to run, as if the first `CMD` parameter (`"script.js"`) is being dropped by the container runtime.

**Comment by mook-as** [comment] 2022-08-04 00:40
Going from my previous comment, it appears we need to opt in to this commit:
https://github.com/tonistiigi/binfmt/commit/c5e21394c9378124b17cdf9c4a1c09b119cfba17

This adds support for the [preserve-argv flag](https://docs.kernel.org/admin-guide/binfmt-misc.html) (`P`) in the `binfmt_misc` registration.  I haven't figured out yet why this is suddenly needed, though.

**Comment by mook-as** [comment] 2022-08-04 00:41
As a temporary workaround, run this as root in the VM:

> `echo ':qemu-x86_64:M:0:\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00:\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-x86_64:POCF' > /proc/sys/fs/binfmt_misc/register `

**Comment by mook-as** [comment] 2022-08-04 17:15
I can confirm that this also happens on x86_64 hosts running aarch64 images (which makes the problem easier).

**Comment by mook-as** [comment] 2022-08-04 18:16
Going to mark this as a duplicate of #2668 — it has the same underlying cause.

**Closed by mook-as** 2022-08-04 18:16 UTC
Labels: kind/bug

**Comment by colstrom** [comment] 2022-08-05 21:21
> * `binfmt_flags="POCF"`

I just hit this today, and can confirm that this resolves it for me.
