### ISSUE TITLE
Air-gapped install cannot start pods

### ISSUE THREAD

**Issue by btauras** [rancher-sandbox/rancher-desktop#3743] opened 2023-01-11 15:31 UTC
### Actual Behavior

With air-gapped Windows install following [running air-gapped](https://docs.rancherdesktop.io/how-to-guides/running-air-gapped/) instructions, Kubernetes cannot start pods and reports that it failed to pull the container images from online.

> FailedCreatePodSandBox: Pod coredns-597584b69b-rn4d9
Failed to create pod sandbox: rpc error: code = Unknown desc = failed pulling image "registry.k8s.io/pause:3.6": Error response from daemon: Get "https://registry.k8s.io/v2/": dial tcp: lookup registry.k8s.io on 172.29.233.121:53: lame referral

### Steps to Reproduce

1. Use air-gapped (offline) Windows host
2. Install Rancher Desktop 1.7.0
3. Import K3S image cache files:

    ```text
    C:\Users\USERNAME\AppData\Local\rancher-desktop\cache\
    ├── k3s
    │   └── v1.25.4+k3s1
    │       ├── k3s
    │       ├── k3s-airgap-images-amd64.tar.zst
    │       └── sha256sum-amd64.txt
    └── k3s-versions.json

    C:\Users\USERNAME\.kuberlr\windows-amd64\
    └── kubectl1.25.4.exe
    ```

    1. Checksums match the checksums file.
    2. Also tried `.tar` and `.tar.gz` K3S image files with no success.
    3. The `k3s-versions.json` file is from a functioning online install, including versions and channels, snippet below:

        ```json
        {
          "cacheVersion": 2,
          "versions": [
            "v1.25.4+k3s1"
          ],
          "channels": {
            "v1.25": "1.25.4"
          }
        }
        ```

5. Start Rancher Desktop and wait for Kubernetes to finish starting
6. View Rancher Desktop dashboard

### Result

Messages from dashboard:

> FailedCreatePodSandBox	Pod coredns-597584b69b-rn4d9
Failed to create pod sandbox: rpc error: code = Unknown desc = failed pulling image "registry.k8s.io/pause:3.6": Error response from daemon: Get "https://registry.k8s.io/v2/": dial tcp: lookup registry.k8s.io on 172.29.233.121:53: lame referral
Wed, Jan 11 2023  9:57:17 am
FailedCreatePodSandBox	Pod metrics-server-5c8978b444-d7rqg
Failed to create pod sandbox: rpc error: code = Unknown desc = failed pulling image "registry.k8s.io/pause:3.6": Error response from daemon: Get "https://registry.k8s.io/v2/": dial tcp: lookup registry.k8s.io on 172.29.233.121:53: lame referral
Wed, Jan 11 2023  9:57:14 am
FailedCreatePodSandBox	Pod helm-install-traefik-crd-lbjlq
Failed to create pod sandbox: rpc error: code = Unknown desc = failed pulling image "registry.k8s.io/pause:3.6": Error response from daemon: Get "https://registry.k8s.io/v2/": dial tcp: lookup registry.k8s.io on 172.29.233.121:53: lame referral
Wed, Jan 11 2023  9:57:12 am
FailedCreatePodSandBox	Pod helm-install-traefik-gqngl
Failed to create pod sandbox: rpc error: code = Unknown desc = failed pulling image "registry.k8s.io/pause:3.6": Error response from daemon: Get "https://registry.k8s.io/v2/": dial tcp: lookup registry.k8s.io on 172.29.233.121:53: lame referral
Wed, Jan 11 2023  9:57:10 am
FailedCreatePodSandBox	Pod local-path-provisioner-79f67d76f8-2pxjx
Failed to create pod sandbox: rpc error: code = Unknown desc = failed pulling image "registry.k8s.io/pause:3.6": Error response from daemon: Get "https://registry.k8s.io/v2/": dial tcp: lookup registry.k8s.io on 172.29.233.121:53: lame referral
Wed, Jan 11 2023  9:57:09 am
RegisteredNode	Node win-aetvtijl217
Node win-aetvtijl217 event: Registered Node win-aetvtijl217 in Controller
Wed, Jan 11 2023  9:32:14 am
NodeReady	Node win-aetvtijl217
Node win-aetvtijl217 status is now: NodeReady
Wed, Jan 11 2023  9:32:10 am
Starting	Node win-aetvtijl217	Wed, Jan 11 2023  9:32:04 am
AppliedManifest	Addon aggregated-metrics-reader
Applied manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/aggregated-metrics-reader.yaml"
Wed, Jan 11 2023  9:32:01 am
ApplyingManifest	Addon aggregated-metrics-reader
Applying manifest at "/var/lib/rancher/k3s/server/manifests/metrics-server/aggregated-metrics-reader.yaml"
Wed, Jan 11 2023  9:32:01 am

### Expected Behavior

Rancher Desktop finds the image cache and successfully starts all pods.

### Additional Information

User running Rancher Desktop is a non-administrator but has admin rights for installation/setup.

Offline install docs probably need updating to include the change to using compressed files (`.tar.zst`) in the K3S image cache.

### Rancher Desktop Version

1.7.0

### Rancher Desktop K8s Version

1.25.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

windows 10 pro current, windows server 2022 current

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

fresh windows installs with no other software and all updates as of 2023-01-10

**Comment by jandubois** [comment] 2023-02-14 06:39
The problem is that cri-dockerd is not using the sandbox image from the airgap tarball, but has `registry.k8s.io/pause:3.6` hardcoded in its configuration.

This should be fixed by #3929 as long as you are not using Kubernetes 1.24.1 to 1.24.3, as these are the only versions that will still use the cri-dockerd version supplied by Rancher Desktop instead of the one supplied by k3s.

**Closed** 2023-02-15 20:07 UTC
Labels: kind/bug, runtime/moby
