### ISSUE TITLE
UI of Diagnostics broken after changing symlink

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3020] opened 2022-09-27 00:19 UTC
### Actual Behavior

UI components of Diagnostics tab are breaking once user corrects docker-cli symlinks pointing to a wrong directory.

### Steps to Reproduce

1. Run Rancher Desktop 
2. Change the directories that the symlinks in docker cli are pointing to in ~/.rd/bin
`ln -sf ~/.bashrc docker-buildx`
`ln -sf ~/.rd/bin/docker-compose docker-compose`
3. Click Rerun to update the diagnostics warnings
4. Correct the symlinks by pointing them to the right directory: 
`ln -sf ~/.rd/bin/docker-buildx docker-buildx`
 `ln -sf ~/.rd/bin/docker-compose docker-compose`
5. Click rerun in the Diagnostics tab to check if warnings are updated
6. Click Other UI components in this same tab such as "Show Mute" and "Mute"

### Result

UI Components of Diagnostics are totally broken. Rerun does not update the warnings, mute does not hide selected warnings and show mute does not make muted warnings visible.
Error found in steve.log:
`2022-09-26T23:49:36.071Z: stderr: time="2022-09-26T16:49:36-07:00" level=error msg="Failed to read API for groups map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]"`
![components breaking in diagnostics](https://user-images.githubusercontent.com/70187881/192403225-abb6382b-5980-444e-8a3a-dcb14b489d4e.gif)

### Expected Behavior

Rerun button should update the warnings once clicked,
Mute must hide selected warnings from the table 
Show mute must make muted warnings visible.

### Rancher Desktop Version

1.5.0-701-g2d00a573

### Rancher Desktop K8s Version

1.25.0

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment] 2022-09-27 19:02
> 2\. Change the directories that the symlinks in docker cli are pointing to in ~/.rd/bin
>     `ln -sf ~/.bashrc docker-buildx`
>     `ln -sf ~/.rd/bin/docker-compose docker-compose`

This is not what the diagnostic is testing. It is checking the files in `~/.docker/cli-plugins` to make sure that *they* are symlinks to `~/.rd/bin`. It does not check the symlinks in `~/.rd/bin`.

The reason is that both other tools (e.g. Docker Desktop) or the user may install tools directly into `~/.docker/cli-plugins`, and we want to verify that they did not overwrite the symlinks pointing to our tools.

However, we **also** verify that the files in `~/.rd/bin` are symlinks into our app directory.

For me all the checks worked as expected, including the re-run and mute functionality. I was testing on macOS Catalina (Intel), and I don't think that you running Monterey makes a difference.

**Comment by rak-phillip** [comment] 2022-09-28 17:39
The root cause for this looks like it will be addressed in #3038

**Closed** 2022-09-29 17:07 UTC
Labels: kind/bug
