### ISSUE TITLE
Error starting Kubernetes

### ISSUE THREAD

**Issue by timanderson** [rancher-sandbox/rancher-desktop#267] opened 2021-05-06 06:50 UTC
Windows 10. Setup fails with "Error Starting kubernetes. Could not set up K3s; exited with status 4294967295"

Tried reset and same happens again.

**Comment by jandubois** [comment] 2021-05-06 07:18
Could you please try to start the app from the command line, like this:

```console
"C:\Users\Jan\AppData\Local\Programs\rancher-desktop\Rancher Desktop.exe"
```

(but using your own user name, of course), and the attach any log output to this issue? There is unfortunately no separate logfile yet.

**Comment by timanderson** [comment] 2021-05-06 07:44
Fetching releases from https://api.github.com/repos/k3s-io/k3s/releases?per_page=100 -> OK
Found old version v1.21.0+k3s1, stopping.
Got 49 versions.
{
  version: 2,
  kubernetes: { version: 'v1.19.10', memoryInGB: 2, numberCPUs: 2 },
  portForwarding: { includeKubernetesServices: false },
  images: { showAll: true },
  telemetry: false
}
Fetching releases from https://api.github.com/repos/k3s-io/k3s/releases?per_page=100 -> OK
Found old version v1.21.0+k3s1, stopping.
Got 49 versions.
Ensuring images available for K3s v1.19.10+k3s1
Cache at C:\Users\tim\AppData\Local\xdg.cache\rancher-desktop\k3s is valid.
Kubernetes was unable to start with exit code: undefined

**Comment by jandubois** [comment] 2021-05-06 18:41
Thanks @timanderson ! Unfortunately this is not enough information for us to figure out what went wrong. We'll expand the logging output in the next release; hopefully you can then try again and we get more comprehensive information.

Sorry for the hassle, but this is still the very first alpha release of the project. We'll ping you via this bug report once a new release is available for testing.

**Comment by bharath144** [comment] 2021-05-22 14:07
I faced the same issue. Turns out it was my WSL that had a problem. 

I ensured that I had WSL version 2 installed and set that as the default version. Then I restarted Rancher Desktop and the initial setup went through and a Kubernetes context got created. 

Followed the instructions here: https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by timanderson** [comment] 2021-05-23 09:04
Thanks, it turned out that although my default WSL distro was version 2, I needed to run:

wsl --set-default-version 2

and then did a "factory reset" which started successfully.

Tim

**Comment by borcherspm** [comment] 2022-01-25 19:15
I'm running into the same error.

> Error: wsl.exe exited with code 4294967295

I made sure to change my default version in wsl to 2.  And my windows version is 21H1 Build 19043.

This is the log running the exe directly.
```
C:\Users\borcherspm\AppData\Local\Programs\Rancher Desktop>"Rancher Desktop.exe"

C:\Users\borcherspm\AppData\Local\Programs\Rancher Desktop>
(node:4788) UnhandledPromiseRejectionWarning: Error: wsl.exe exited with code 4294967295
    at ChildProcess.<anonymous> (C:\Users\borcherspm\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:1:8014)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
(Use `Rancher Desktop --trace-warnings ...` to show where the warning was created)
(node:4788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by jandubois** [comment] 2022-01-25 19:23
I've created a new issue for the last comment, and am going to close this one. All previous participants have confirmed that the issue was resolved for them (and the penultimate comment on this issue was 9 months ago).

**Closed by jandubois** 2022-01-25 19:23 UTC
Labels: platform/windows
