### ISSUE TITLE
Windows Defender finds Trojan:Win32/Cinjo.O!cl

### ISSUE THREAD

**Issue by derkoe** [rancher-sandbox/rancher-desktop#1735] opened 2022-03-05 16:22 UTC
### Actual Behavior

Windows defender ATP finds "Trojan:Win32/Cinjo.O!cl" in
file: C:\Users\$USER\AppData\Local\Programs\Rancher Desktop\Rancher Desktop.exe

### Steps to Reproduce

Install Rancher Desktop on Windows 10 Professional with Defender ATP

### Result

![image](https://user-images.githubusercontent.com/123199/156891636-9c216f2c-a5ab-41c1-a419-1875f03aa938.png)

### Expected Behavior

Rancher Desktop should not be recogniced as a trojan

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

-

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro 21H2

### What CPU architecture are you using?

x64

### Windows User Only

Windows Defender Advanced Threat Protection (ATP)

**Comment by jandubois** [comment] 2022-03-05 20:45
I could not reproduce this. I've updated latest Defender updates and ran a full scan while Rancher Desktop 1.1.1 was installed and running, and got "No current threats".

I would run a full update on your system and try again, and if you continue to have issues, see if you maybe have some other infection. So far I have not seen any other reports of this issue either, so will close this for now.

**Closed by jandubois** 2022-03-05 20:45 UTC
Labels: kind/bug, platform/windows

**Comment by derkoe** [comment] 2022-03-07 07:26
@jandubois did you try the enterprise version of Defender ([Defender ATP/Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint)) or just the consumer edition? This only happens in the enterprise version.

**Comment by jandubois** [comment] 2022-03-07 08:30
> @jandubois did you try the enterprise version of Defender ([Defender ATP/Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint)) or just the consumer edition? This only happens in the enterprise version.

I only tried the consumer edition. Will see what we can do. If this continues to be reported, does your IT group have a way to report false positives back to Microsoft?

**Comment by derkoe** [comment] 2022-03-07 08:33
> If this continues to be reported, does your IT group have a way to report false positives back to Microsoft?

I'll try to report this via our support channel. Thx

**Comment by derkoe** [comment] 2022-03-09 16:25
I have tried the installation again today and this time the scanner did not block or report it. Seems that is has learned.

**Comment by jandubois** [comment] 2022-03-09 17:13
> I have tried the installation again today and this time the scanner did not block or report it. Seems that is has learned.

Thank you for reporting back!

**Comment by tomp83-gh** [comment] 2022-08-16 09:08
Hi, 
This issue has started to reoccur again with version 1.5.1

I have exactly the same symptoms as described above, also using Defender ATP/Defender for Endpoint. 

Is this something that the Rancher Desktop team can have any control over, or is this something I should take up with Microsoft/Defender team? 

For reference: 
![image](https://user-images.githubusercontent.com/99128358/184842195-87f6a3cc-012e-45d3-9fd6-7a5c2669e56d.png)

**Comment by jandubois** [comment] 2022-08-30 00:13
Hi @tomp83-gh, looks like nobody responded to you. :(

There isn't really anything the RD team can do, except to contact the corresponding AV vendor and informing them about their broken signature.

Unfortunately this happens quite frequently, with other AV companies too, that they create heuristics rules that often create false positives for newly released software. I suspect it will get even worse, as AV companies switch to machine learning to create rules to identify threats.
