### ISSUE TITLE
Rancher Desktop UI doesn't remove images without tags

### ISSUE THREAD

**Issue by absmith82** [rancher-sandbox/rancher-desktop#2785] opened 2022-08-19 17:55 UTC
### Actual Behavior

when an image has no tags associated with it, the UI will not remove and you get an error stating that <none>:<none> cannot be removed.[](url)

### Steps to Reproduce

build a container image.  modify the docker file to build a new container image and buid that new image with the same tags.  Lingering image is left behind with no tags.

OR

Build a container image with no tags

Then try and delete lingering container image from Rancher Desktop UI

### Result

Rancher desktop throws a cannot delete container <none>:<none> error

### Expected Behavior

Rancher desktop uses image id or hash rather than tag to delete the untagged image

### Rancher Desktop Version

1.5.1

### Rancher Desktop K8s Version

Not using this with K8s

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

windows 10 pro 10.0.22000 build 22000

### What CPU architecture are you using?

x64

**Comment by adamkpickering** [comment] 2022-08-22 20:35
Thanks for the bug report! I believe this issue is a duplicate of #2626, so I'm going to close it. If I'm wrong, please comment and we can reopen it.

**Closed by adamkpickering** 2022-08-22 20:35 UTC
Labels: kind/bug
