### ISSUE TITLE
.deb download is often painfully slow

### ISSUE THREAD

**Issue by nodakai** [rancher-sandbox/rancher-desktop#6123] opened 2023-12-05 13:23 UTC
### Actual Behavior

Download speed of .deb release is ~30 KB/s

This isn't just a one-day issue; it's been consistently slow for months, but today it's unbearably slow.

### Steps to Reproduce

`$ cat sources.list.d/isv-rancher-stable.list`
`deb [signed-by=/etc/apt/gpg.d/isv-rancher-stable-archive-keyring.gpg] https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/ ./`

```
$ LANG=C gpg --show-keys /etc/apt/gpg.d/isv-rancher-stable-archive-keyring.gpg 
pub   rsa2048 2021-10-29 [SC] [expires: 2024-01-07]
      322BDD0E231125AF14784FB21F833FA1A63FE758
uid                      isv:Rancher OBS Project <isv:Rancher@build.opensuse.org>
```

```
$ curl -s https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/Release.key | LANG=C gpg --show-keys 
pub   rsa2048 2021-10-29 [SC] [expires: 2024-01-07]
      322BDD0E231125AF14784FB21F833FA1A63FE758
uid                      isv:Rancher OBS Project <isv:Rancher@build.opensuse.org>
```

### Result

```
Need to get 480 MB/1344 MB of archives.
After this operation, 131 MB of additional disk space will be used.
Get:1 https://mirror.tspu.ru/opensuse/repositories/isv%3A/Rancher%3A/stable/deb ./ rancher-desktop 1.11.1-4.1 [480 MB]
96% [1 rancher-desktop 414 MB/480 MB 86%]
32.7 kB/s 33min 45s
```

### Expected Behavior

For reference, Docker Desktop downloads at a speed of 3 MB/s

```
$ curl -OL 'https://desktop.docker.com/linux/main/amd64/docker-desktop-4.26.0-amd64.deb?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-linux-amd64'                
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 15  406M   15 61.5M    0     0  2799k      0  0:02:28  0:00:22  0:02:06 3020k
```

### Rancher Desktop Version

N.A.

### Rancher Desktop K8s Version

N.A.

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Debian testing

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by jandubois** [comment] 2023-12-05 17:48
> Get:1 https://mirror.tspu.ru/opensuse/repositories/isv%3A/Rancher%3A/stable/deb ./ rancher-desktop 1.11.1-4.1 [480 MB]

The problem is between you and the mirror you are downloading from. Maybe check https://en.opensuse.org/openSUSE:Mirrors to find a faster mirror?

For reference, I get almost 8MB/s download speed from Canada (didn't check which mirror I got redirected to):

```console
$ curl -OL https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/amd64/rancher-desktop_1.11.1-4.1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  457M  100  457M    0     0  7707k      0  0:01:00  0:01:00 --:--:-- 10.7M
```

There is nothing we can do about this from the Rancher Desktop project, so I'm going to close this issue.

**Closed by jandubois** 2023-12-05 17:48 UTC
Labels: kind/bug
