### ISSUE TITLE
Rancher Desktop new install wont launch due to "Kubernetes Error"

### ISSUE THREAD

**Issue by maziaraskari2** [rancher-sandbox/rancher-desktop#6765] opened 2024-04-24 18:30 UTC
### Actual Behavior

installing Rancher Desktop has error running on MacBook Pro with Apple M2 Pro Chip throws error for kubernetes.

### Steps to Reproduce

install rancher desktop 1.13 on MacbookPro with Apple M2 Pro Chip and get erro for kubernettes when Rancher launches.

### Expected Behavior

rancher desktop to launch with no error.

### Rancher Desktop Version

1.13

### Rancher Desktop K8s Version

1.13

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Sonoma 14.4

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by maziaraskari2** [comment] 2024-04-24 18:31
![1](https://github.com/rancher-sandbox/rancher-desktop/assets/168022422/cf3afe29-5ea2-42a7-ba27-56fb822ad3c7)

**Comment by maziaraskari2** [comment] 2024-04-24 18:48
[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/15099050/logs.zip)

**Comment by maziaraskari** [comment] 2024-04-24 19:07
[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/15099228/logs.zip)

**Comment by maziaraskari** [comment] 2024-04-24 19:24
[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/15099427/logs.zip)

**Comment by jandubois** [comment] 2024-04-24 19:30
This turns out to be a duplicate of #797, which has a workaround documented in https://github.com/rancher-sandbox/rancher-desktop/issues/797#issuecomment-996510877.

**Closed by jandubois** 2024-04-24 19:30 UTC
Labels: kind/bug
