### ISSUE TITLE
macOS Ventura 13.0 "Waiting for service" stuck

### ISSUE THREAD

**Issue by mkubasz** [rancher-sandbox/rancher-desktop#3288] opened 2022-10-26 11:00 UTC
### Actual Behavior

After updating the system to Ventura and updating Rancher Desktop to 1.6.1, it hangs on the moment "Waiting for service". When I removed Rancher Desktop and installed a fresh instance has the same issue. 
But when I disable Kubernetes docker works. 

### Steps to Reproduce

Open Rancher Desktop.

### Result

"Waiting for service"

### Expected Behavior

Should be ready to work

### Rancher Desktop Version

1.6.1

### Rancher Desktop K8s Version

1.24

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura 13.0

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by GodDrinkTeJAVA** [comment] 2022-10-26 11:52
Same bug reproduces here. All the environments are same. Here are the issues I've got.

When I first clean install my Rancher Desktop, k8s got installed and nothing special happens. It is same for closing and launching app for the second time. The error occurs when I tried to shut down the app, the service doesn't seem to shut down.
When Quit Rancher Desktop is pressed multiple times, it works. But, if launched again, it seems like no back-end services seems to work. For example,
* Diagnostics tab says 

    'The application cannot reach the general internet for updated kubernetes versions and other components, but can still operate.'
* Any commands to kubectl alerts error.

    'I1026 11:27:55.647858 26652 versioner.go:56] Remote kubernetes server unreachable \ Unable to connect to the server: net/http: TLS handshake timeout'
* In verbose mode of above situation, this error message pops out.

    'I1026 16:43:16.141389 75669 helpers.go:264] Connection error: Get https://127.0.0.1:6443/api/v1/namespaces/default/pods?limit=500: net/http: TLS handshake timeout'

**Comment by roydejesus1031** [comment] 2022-10-26 14:56
Similar issue here and same environment, except I'm using k8s version 1.18.19. It was stuck on waiting for the API. I downgraded to Rancher Desktop 1.6.0 and it all works for me, will be using that until a fix is released.

**Comment by sleepingevil** [comment] 2022-10-26 15:43
Similar issue here, as well. It mostly hands at "Waiting for services...", but sometimes it hangs at "Waiting for Kubernetes API..." or at "Waiting for nodes..."

**Comment by GodDrinkTeJAVA** [comment] 2022-10-26 19:15
I've asked Slack for help and changing k8s version to 1.23.12 or 1.23.13 might help. For more detail, check out https://rancher-users.slack.com/archives/C0200L1N1MM/p1666784826204319 .

Huge thanks to every person seeking for help.

**Comment by GodDrinkTeJAVA** [comment] 2022-10-26 19:15
Changing k8s version to 1.23.12 or 1.23.13 might help. For more detail, check out https://rancher-users.slack.com/archives/C0200L1N1MM/p1666784826204319 .

Huge thanks to every person seeking for help.

**Comment by itsavvy-ankur** [comment] 2022-10-26 20:30
I ran into the same issue post upgrade to macOS Ventura, the work around was to disable kubernetes from settings which looks to have made it work with regards to a functional docker setup.

**Comment by delprofundo** [comment] 2022-10-27 11:25
I found that factory reset and then removing the old version of desktop, that had been installed from the dmg linked on the webpage, moving to the mac m1 .zip stabilised a lot of the behaviour, I dont get any of the above mentioned errors in the diagnostics page anymore.

I can run rancher desktop 1.6.1 normally once after installing it. 

However when i stop the application it will then always be stuck in the 'Waiting for Nodes' state on restart, the only way i can get it to run is factory reset -> uninstsall -> fresh install.

**Comment by sleepingevil** [comment] 2022-10-27 12:34
> I ran into the same issue post upgrade to macOS Ventura, the work around was to disable kubernetes from settings which looks to have made it work with regards to a functional docker setup.

Thanks for the tip! It's a viable workaround for me, too.

Here's what I did: 

1. I did a Factory Reset
2. I started Rancher Desktop with Kubernetes disabled
3. I installed minikube

Now I'm using Rancher to build docker images, but I use minikube as a local k8s environment.

**Comment by thorsager** [comment] 2022-10-28 13:27
I'm running into the _same_ issue, although it seems that it is the vm that is hanging. I'm unable to get a shell on the lima vm when rd is "waiting"

**Comment by jandubois** [comment] 2022-10-28 15:45
We have confirmed this issue. In our testing it only manifests when using Kubernetes 1.24.* or 1.25.*.

So downgrading to Kubernetes 1.23.13 might be a workaround until the root cause has been discovered and fixed.

**Comment by planetf1** [comment] 2022-10-31 14:49
Same issue here - and can confirm downgrading to k8s 1.23 allows k8s to come up ok (Ventura 13.1 beta)

**Comment by RobertDittmann** [comment] 2022-10-31 18:00
Same here seems @jandubois  solution works.

**Comment by shikanime** [comment] 2022-10-31 18:32
Many things around the network interfaces have stopped working, on Minikube the `minikube tunnel` no longer works because of something around the bridge interface, maybe it is related?

**Comment by nshores** [comment] 2022-10-31 23:23
I can also confirm on that on 13.0 using 1.23 of K8S allows the VM to start.

**Comment by delprofundo** [comment] 2022-11-01 01:18
Ok so I was having success running 1.23.13 however it still isnt working.

It will launch the first time after installation but then if I stop rancher desktop and later start it again it will go back into the hang cycle waiting for nodes.

I also notice (through a Tilt interface) that live reloading of a running image has stopped working, when Tilt detects the change to the application code it attempts unsuccessfully to update the container, its easy to work around I just have to click rebuild.

**Comment by jandubois** [comment] 2022-11-01 06:14
> Ok so I was having success running 1.23.13 however it still isnt working.
> 
> It will launch the first time after installation but then if I stop rancher desktop and later start it again it will go back into the hang cycle waiting for nodes.

@delprofundo Thank you so much for pointing this out! I hadn't realized this before, and it was confusing me testing results.

I can confirm that it fails on restart until you perform another Factory Reset (or at least delete `/var/lib/rancher` inside the VM).

**Comment by Bobses** [comment] 2022-11-01 06:57
The same issue here - the problem is not solved even after downgrading to 1.22. Steps to be able to use Rancher Desktop: Factory Reset, uninstall, reinstall and use the 1.22 k8s version - only until the next start.
On the next start, the Rancher Desktop app is stuck again at the **Waiting for services** message. It is incredibly annoying.

**Comment by karthichu** [comment] 2022-11-01 12:49
> The same issue here - the problem is not solved even after downgrading to 1.22. Steps to be able to use Rancher Desktop: Factory Reset, uninstall, reinstall and use the 1.22 k8s version - only until the next start. On the next start, the Rancher Desktop app is stuck again at the **Waiting for services** message. It is incredibly annoying.

Same here. Do we know the root cause yet?

**Comment by electroniceagle** [comment] 2022-11-01 17:21
I have a M1 Mac running Ventura.  Unfortunately, I started playing with rancher desktop a few days ago after the update so not even sure if I have everything configured correctly.  Initial install after factory reset I can use nerdctl following the hello-world example in the docs, but when I get to the second example using nginx I get this error from kubectl:

```
➜  nginx git:(main) ✗ kubectl run hello-world --image=nginx-helloworld:latest --image-pull-policy=Never --port=80 ;
kubectl port-forward pods/hello-world 8080:80
I1101 12:58:13.144530   69447 versioner.go:58] invalid configuration: no configuration has been provided
The connection to the server localhost:8080 was refused - did you specify the right host or port?
I1101 12:58:13.243141   69448 versioner.go:58] invalid configuration: no configuration has been provided
The connection to the server localhost:8080 was refused - did you specify the right host or port?
➜  nginx git:(main) ✗ kubectl delete pod hello-world
I1101 12:59:12.660922   69486 versioner.go:58] invalid configuration: no configuration has been provided
The connection to the server localhost:8080 was refused - did you specify the right host or port?
➜  nginx git:(main) ✗ kubectl cluster-info dump
I1101 13:05:52.379922   69608 versioner.go:58] invalid configuration: no configuration has been provided
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

I tried to reset Kubernetes in the desktop app, and then stuck in "Waiting for Services" loop.  Enabled debug and k8s.log has:

```
2022-11-01T15:47:27.383Z: Got 113 versions.
2022-11-01T15:48:06.766Z: Ensuring images available for K3s 1.25.3
2022-11-01T15:48:06.768Z: Will download exe https://github.com/k3s-io/k3s/releases/download/v1.25.3+k3s1/k3s-arm64 to /Users/bfschott/Library/Caches/rancher-desktop/k3s/tmp-v1.25.3+k3s1-aj7bD6/k3s-arm64
2022-11-01T15:48:06.771Z: Will download images https://github.com/k3s-io/k3s/releases/download/v1.25.3+k3s1/k3s-airgap-images-arm64.tar to /Users/bfschott/Library/Caches/rancher-desktop/k3s/tmp-v1.25.3+k3s1-aj7bD6/k3s-airgap-images-arm64.tar
2022-11-01T15:48:06.772Z: Will download checksum https://github.com/k3s-io/k3s/releases/download/v1.25.3+k3s1/sha256sum-arm64.txt to /Users/bfschott/Library/Caches/rancher-desktop/k3s/tmp-v1.25.3+k3s1-aj7bD6/sha256sum-arm64.txt
2022-11-01T15:48:43.326Z: Waiting for K3s server to be ready on port 6443...
2022-11-01T15:48:43.337Z: Error: connect ECONNREFUSED 127.0.0.1:6443
2022-11-01T15:48:45.592Z: Updating kubeconfig /Users/bfschott/.kube/config...
2022-11-01T15:48:49.101Z: [0;32mKubernetes control plane[0m is running at [0;33mhttps://127.0.0.1:6443[0m

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

2022-11-01T15:48:49.101Z: I1101 11:48:48.857599   65488 versioner.go:58] invalid configuration: no configuration has been provided

2022-11-01T17:12:30.371Z: Failed to get k3s version: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 127 - assuming not installed.
2022-11-01T17:12:30.375Z: Ensuring images available for K3s 1.25.3
2022-11-01T17:12:33.616Z: Cache at /Users/bfschott/Library/Caches/rancher-desktop/k3s is valid.
2022-11-01T17:12:34.320Z: Failed to get k3s version: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 127 - assuming not installed.
2022-11-01T17:12:52.320Z: Waiting for K3s server to be ready on port 6443...
2022-11-01T17:12:52.339Z: Error: connect ECONNREFUSED 127.0.0.1:6443
2022-11-01T17:12:54.596Z: Updating kubeconfig /Users/bfschott/.kube/config...

```

**Comment by Jack-Burnett** [comment] 2022-11-02 08:19
I get the issue on kubernetes version 1.20.15.
Same issue as above, Error: connect ECONNREFUSED 127.0.0.1:6443

**Comment by lqst** [comment] 2022-11-02 10:16
In the logs, it looked like some existing container could not be found some namespace (which I had kept the exact log line). 
I had to disable kubernetes then restart rancher desktop. Then removed all images (docker). Factory reset + another restart.

**Comment by electroniceagle** [comment] 2022-11-02 14:03
At first I thought it was my system.  I've got so many virtualization tools installed that could easily be interfering.  I've used docker desktop with Kubernetes flag and it works just fine.  One thing I'm not sure about is the 127.0.0.1:6443 server config below.  Does this look correct?  

```
➜  gitlab git:(main) grep -e "name:" -e "cluster" -e "server" ~/.kube/config
clusters:
  - name: docker-desktop
    cluster:
      server: https://kubernetes.docker.internal:6443
  - name: rancher-desktop
    cluster:
      server: https://127.0.0.1:6443
  - name: docker-desktop
  - name: rancher-desktop
  - name: docker-desktop
      cluster: docker-desktop
      name: docker-desktop
  - name: rancher-desktop
      cluster: rancher-desktop
      name: rancher-desktop
```

**Comment by electroniceagle** [comment] 2022-11-02 14:39
OK, I think my problems are unrelated.  I am needing to do the factory reset on every restart, but my configuration issues are not related.

```
➜  gitlab git:(main) mac-netstat | grep Rancher
proto: tcp4    addr.port: *.443              pid: 86106    name: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl
proto: tcp4    addr.port: *.80               pid: 86106    name: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl
proto: tcp4    addr.port: 127.0.0.1.9080     pid: 86863    name: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/internal/steve
proto: tcp4    addr.port: 127.0.0.1.9443     pid: 86863    name: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/internal/steve
proto: tcp4    addr.port: 127.0.0.1.52744    pid: 86120    name: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/qemu-system-aarch64
proto: tcp4    addr.port: 127.0.0.1.52746    pid: 86106    name: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/qemu-system-aarch64
proto: tcp4    addr.port: 127.0.0.1.6109     pid: 85746    name: /Applications/Rancher Desktop.app/Contents/MacOS/Rancher Desktop
proto: tcp4    addr.port: 127.0.0.1.6107     pid: 85746    name: /Applications/Rancher Desktop.app/Contents/MacOS/Rancher Desktop
proto: tcp4    addr.port: 127.0.0.1.6120     pid: 85746    name: /Applications/Rancher Desktop.app/Contents/MacOS/Rancher Desktop
```

**Comment by jandubois** [comment] 2022-11-03 01:08
I'm re-opening this issue because we only have a fix in the main branch; we need to create a corresponding fix for the `release-1.6` branch and prepare a 1.6.2 release with it.

I tried to cherry-pick the #3327 commits, but it turns out to be non-trivial: the source code layout has changed in `main`, but more importantly, the current tree includes more refactoring that does not exist in the `release-1.6` branch. So corresponding commits will have to be crafted and reviewed separately.

**Comment by jandubois** [comment] 2022-11-03 23:16
The fix has been released in https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v1.6.2.

Auto-update to this version will be enabled tomorrow.

**Closed by jandubois** 2022-11-03 23:16 UTC
Labels: kind/bug, platform/macos, priority/0

**Comment by omBratteng** [comment] 2022-11-03 23:34
Just downloaded and tested it, works superb. Everything starts up now as expected 😄

**Comment by jandubois** [comment] 2022-11-03 23:42
@omBratteng Thanks for letting us know!

**Comment by sleepingevil** [comment] 2022-11-04 08:28
I can also confirm, it's working.

**Comment by delprofundo** [comment] 2022-11-04 13:52
thanks so much @jandubois and everyone! I too can confirm I'm able to stop and start my environment without any fuss.

**Comment by senn** [comment] 2023-02-15 15:09
I'm currently experiencing the same issue on Mac M1 with Ventura.  Same errors as mentioned above.  I have Rancher Desktop 1.7.0 and have tried with Kubernetes version 1.22.*, 1.23*, 1.24* and the latest 1.26.1 yet it always results in Rancher Desktop hanging on "Waiting for services".

The log file says the same for every version I tried

> 2023-02-15T14:01:30.929Z: Waiting for K3s server to be ready on port 6443...
> 2023-02-15T14:01:56.844Z: Error: connect ETIMEDOUT 127.0.0.1:6443
> 2023-02-15T14:01:57.083Z: Updating kubeconfig /Users/JF09666/.kube/config...
> 2023-02-15T14:07:15.262Z: Waited more than 300 secs for kubernetes to fully start up. Giving up.
> 2023-02-15T14:09:30.449Z: Error priming kuberlr: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl exited with code 1
> 2023-02-15T14:09:30.450Z: Output from kuberlr:
> ex.stdout: [
> To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
> ],
> ex.stderr: [I0215 15:07:20.485794   99685 versioner.go:56] Remote kubernetes server unreachable

**Comment by KurtLehnardt** [comment] 2024-09-26 16:36
Enabling administrative access in the rancher desktop preferences fixed it for me.
![image](https://github.com/user-attachments/assets/752bd2c5-b8ec-49fa-a92b-2e678b867dea)

https://forums.rancher.com/t/cant-connect-docker-daemon-server/43482/2
