### ISSUE TITLE
Mac M1 migrated from Intel - Crash

### ISSUE THREAD

**Issue by bytearchive** [rancher-sandbox/rancher-desktop#5911] opened 2023-11-03 00:02 UTC
### Actual Behavior

Rancher Desktop crashes when started

Mac M1 migrated from Intel using timemachine migration assistant 

### Steps to Reproduce

Migrate from intel to apple silicon m1 using timemachine migration assistnnace

go to /Applications/Rancher\ Desktop/Contents/MacOs

type ./Rancher\ Desktop

### Result

```
> ./Rancher\ Desktop
2023-11-02 16:54:38.254 Rancher Desktop[95600:396875] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
objc[95626]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb4be04bc8) and /Applications/Rancher Desktop.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x1108ff250). One of the two will be used. Which one is undefined.

(node:95600) UnhandledPromiseRejectionWarning: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:9554)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
(Use `Rancher Desktop --trace-warnings ...` to show where the warning was created)
(node:95600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
>

```

### Expected Behavior

application starts

### Rancher Desktop Version

1.11

### Rancher Desktop K8s Version

1.27

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Mac Os Sanoma M1 

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment] 2023-11-03 01:53
Rancher Desktop is not a universal application; the x86_64 version does not run on aarch64. You can simply download and install the latest M1 version on top of your existing install.

You will also need to do a factory reset after installing the M1 version to get an aarch64 VM (so all your images etc. will be lost):

```console
$ /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/rdctl
```

**Comment by jandubois** [comment] 2023-11-03 01:54
I'm closing this issue as "by design". Please re-open if installing the correct platform-specific version and performing a factory reset does not resolve your problems!

**Closed by jandubois** 2023-11-03 01:54 UTC
Labels: kind/bug, triage/by-design
