### ISSUE TITLE
Deployment profile locked settings become unlocked after first launch

### ISSUE THREAD

**Issue by pshutt97** [rancher-sandbox/rancher-desktop#5007] opened 2023-06-21 02:13 UTC
### Actual Behavior

When created locked deployment profile (either on Windows or Darwin), opening the application after launching and closing it, causes all the settings to be unlocked and changeable (dockerd Moby can be changed to containerd)

### Steps to Reproduce

Install Rancher Desktop, setup locked and default deployment profiles, launch Rancher desktop, close the window and reopen Rancher Desktop. When you reopen the application, the various settings that were locked before, are no longer locked.

### Result

After opening the Rancher application the second time, all of the settings are unlocked and able to be changed.

### Expected Behavior

The expected behavior is that the settings should still be locked down no matter how many times the application window is closed.

### Rancher Desktop Version

1.9.0

### Rancher Desktop K8s Version

1.27.1?

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

MacOS 13.4

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by rak-phillip** [comment] 2023-06-21 16:26
Able to reproduce in Linux with the steps defined above. I suspect that the issue might apply to all platforms.

**Comment by mape2k** [comment] 2023-06-21 16:35
Can confirm this on Windows. 

Quitting Rancher Desktop via File ->  Exit and reopen Rancher Desktop shows locked settings again. 
Seems to be an issue when reopening the gui with running Rancher Desktop in background.

**Comment by jandubois** [comment] 2023-06-22 19:14
I believe this was fixed by #5018

**Comment by IsaSih** [comment] 2023-06-24 01:29
I'm still able to reproduce it on M1. Reopening the issue.

**Comment by jandubois** [comment] 2023-06-24 02:37
> I'm still able to reproduce it on M1. Reopening the issue.

Are you sure you tested with a CI build from the `release-1.9` branch? The fix has not been merged to `main` yet; this will only happen when we merge `release-1.9` back into `main` after the 1.9.1 release.

**Comment by IsaSih** [comment] 2023-06-24 03:03
Yes, it is happening in the `release-1.9` branch. However, just some specific fields are editable after quitting RD, instead of closing the window. Given that, I will close this issue and open new ones.

**Closed by IsaSih** 2023-06-24 03:03 UTC
Labels: kind/bug, priority/0, area/deployment
