### ISSUE TITLE
RDX: Hide extension images in the image list

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4413] opened 2023-04-11 16:43 UTC
Hide the extension images to avoid accidental deletion of the same from the images list table. We might be able to hide extension 
 images by Label I guess. Something like hide all images that have labels matching `com.docker.desktop.extension*` ?

**Comment by mook-as** [comment] 2023-04-11 19:00
We already force install/uninstall of extensions on startup according to preferences, I believe:
https://github.com/rancher-sandbox/rancher-desktop/blob/e5bca38b3c55d2658d9a7e6f6aaea00c292bcf7c/pkg/rancher-desktop/main/extensions/manager.ts#L189-L198

**Comment by jandubois** [comment] 2023-04-11 19:03
> We already force install/uninstall of extensions on startup according to preferences, I believe:

If we do, then it doesn't seem to work properly, as I deleted 10 different Epinio images manually last night. But I will re-test, just in case I never stopped and restarted RD all that time (which seems unlikely).

**Comment by mook-as** [comment] 2023-04-18 17:36
Closing as a dupe of #4466 because this one got polluted by talk about reinstalling extensions on startup.

**Closed by mook-as** 2023-04-18 17:36 UTC
Labels: kind/enhancement, component/ui, area/rdx
