### ISSUE TITLE
Disable details link for installed extensions not in catalog

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4424] opened 2023-04-11 18:17 UTC
In the Extension | Installed tab, when you click on an extension name that did not come from the catalog, you get to a broken details page.

It doesn't list the extension name, nor does it have a `<` back arrow to navigate back to the tab:

![CleanShot 2023-04-18 at 12 21 20](https://user-images.githubusercontent.com/78947/232883288-535136d4-b96c-49a5-a5dd-4b4f2a781a9d.gif)

Since the extension isn't provided by the catalog, we shouldn't link to the details page.  

### Acceptance Criteria

- [ ] Installed extensions that are not present in the Extensions Catalog should not contain a link to the Extensions Details page.
- [ ] The link to the Extensions Details page should only be present for extensions that are available in the Extensions Catalog.

### Original issue

In the Extension | Installed tab, when you click on an extension name instead of the "Uninstall" button, you get to a page that just has the "Uninstall" button.

It doesn't list the extension name, nor does it have a `<` back arrow to navigate back to the tab:

![CleanShot 2023-04-11 at 11 07 37](https://user-images.githubusercontent.com/78947/231252517-f306cba9-0066-413f-83d2-06dad65e65b4.gif)

I think the link should just go to the extension details page:

<img width="1045" alt="CleanShot 2023-04-11 at 11 11 40@2x" src="https://user-images.githubusercontent.com/78947/231252653-bce21a7c-c97b-421c-aebe-331736c722ae.png">

Note that the button in this screenshot should say "Uninstall" (see #4422).

**Comment by jandubois** [comment] 2023-04-13 23:10
> I think the link should just go to the extension details page:

This doesn't work for extensions not in the catalog, i.e. ones installed via `rdctl extension install`. Maybe the names for extensions outside the catalog should not by hyperlinks?

**Comment by rak-phillip** [comment] 2023-04-18 19:17
I'm not able to reproduce, is this still an issue?

https://user-images.githubusercontent.com/835961/232882064-4cd16559-f130-4fa7-9e36-a6441c57d904.mp4

**Comment by rak-phillip** [comment] 2023-04-18 19:18
> > I think the link should just go to the extension details page:
> 
> This doesn't work for extensions not in the catalog, i.e. ones installed via `rdctl extension install`. Maybe the names for extensions outside the catalog should not by hyperlinks?

I think this makes sense, it will be impossible to fetch details for any extensions not available in the catalog.

**Comment by jandubois** [comment] 2023-04-18 19:23
> I'm not able to reproduce, is this still an issue?

No, seems to work fine for extension in the catalog. For those not in the catalog it is still confusing:

![CleanShot 2023-04-18 at 12 21 20](https://user-images.githubusercontent.com/78947/232883288-535136d4-b96c-49a5-a5dd-4b4f2a781a9d.gif)

It doesn't make sense to show the Install button since the extension is already installed. And pressing Install will eventually fail (not included in the GIF above).

**Comment by rak-phillip** [comment] 2023-04-28 16:18
@gunamata @jandubois Dropping from epic & closing

**Closed by rak-phillip** 2023-04-28 16:18 UTC
Labels: kind/enhancement, component/ui, area/rdx
