### ISSUE TITLE
Waiting for image manager to be ready

### ISSUE THREAD

**Issue by agclqq** [rancher-sandbox/rancher-desktop#2510] opened 2022-07-11 06:41 UTC
How to handle this problem? Thank you very much!

## Environment and Settings
**os:** mac os Monterey 12.1  apple m1 pro
**rancher desktop version:** 1.41
**Container Runtime:** dockerd(moby)
![image](https://user-images.githubusercontent.com/12854967/178203355-e8b54f94-5e95-4ddc-ad5d-62d3a75b05c2.png)

## problem
**Images:** Waiting for image manager to be ready
![image](https://user-images.githubusercontent.com/12854967/178203391-47e92b55-7f90-4b65-92c2-ee2e9d7ca9ed.png)

**docker images:** Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
![image](https://user-images.githubusercontent.com/12854967/178203595-c4d00795-0253-4c8e-bc0e-66b92a4324df.png)

**Comment by jandubois** [comment] 2022-07-11 22:41
I cannot reproduce this; please attach log files (see "Troubleshooting" page for a link).

**Comment by agclqq** [comment] 2022-07-14 08:37
> I cannot reproduce this; please attach log files (see "Troubleshooting" page for a link).
[rancher-desktop.zip](https://github.com/rancher-sandbox/rancher-desktop/files/9110109/rancher-desktop.zip)

This is logs , thank you

**Comment by mhassan1** [comment] 2022-08-03 14:52
I am seeing a similar error in `images.log`:
```txt
2022-08-03T13:07:54.179Z: > moby images:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

2022-08-03T13:07:54.179Z: [object Object]
```

**Comment by jandubois** [comment] 2022-08-30 21:09
Looking at the current sources (1.5.1+), I see that the `runImagesCommand` in the `mobyImageProcessor.ts` file doesn't explicitly specify the docker context.

In 1.5.1 RD will automatically switch the context from `default` to `rancher-desktop` when running without administrative rights (sudo), but I don't know if this was also the case with 1.4.1.

Either way, the `runImagesCommand` should specify the context with either `DOCKER_CONTEXT` or `docker --context` to avoid problems when the user manually changes the context away from RD.

I also noticed that `src/utils/dockerDirManager.ts` has a `getDesiredDockerContext` function, that may be useful here, but I'm not sure how/when it is supposed to be used.

**Comment by Buddhimah** [comment] 2023-03-30 09:13
Im getting this issue as well

**Comment by gchiarapa** [comment] 2023-06-09 17:43
i'm getting this issue too, even using the nwe version 1.8.1

**Comment by pratheeshm** [comment] 2023-07-26 07:00
It started to work for after running `docker context use rancher-desktop`

**Comment by jandubois** [comment] 2023-07-26 07:24
@pratheeshm Can you please confirm which platform you are using (Windows, Linux, macOS)?

This sounds like #3156 would be the root cause then.

**Comment by pratheeshm** [comment] 2023-07-26 08:58
> @pratheeshm Can you please confirm which platform you are using (Windows, Linux, macOS)?


macOS(m1)

**Comment by ericpromislow** [comment] 2023-09-12 22:33
Now that we always specify the `rancher-desktop` context when running `docker images` (see   b82f284d244858e275c9133d6d3df61c37c85124 ) we can close this. Please reopen if it reoccurs.

**Closed by ericpromislow** 2023-09-12 22:33 UTC
Labels: kind/bug, triage/needs-information, platform/macos

**Comment by SawantDarshan** [comment] 2025-01-01 12:55
> It started to work for me after running `docker context use rancher-desktop`

thanks this works.

to check all existing contexts 
`docker context ls`

to use default context 
`docker context use default`
