### ISSUE TITLE
OpenSUSE 1.6.0 RC1 fails to open dashboard

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#3036] opened 2022-09-27 20:29 UTC
### Actual Behavior

This appears in the main window:
```
Error: ENOENT, resources/rancher-dashboard/index.html not found in /home/ericp/lab/rd/rd-v1.6.0-rc1/resources/app.asar
    at createError (node:electron/js2c/asar_bundle:5:1255)
    at Object.e.lstat (node:electron/js2c/asar_bundle:5:4278)
    at node:electron/js2c/asar_bundle:5:4681
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

### Steps to Reproduce

Click `Dashboard` on the tray menu

### Result

See above

### Expected Behavior

A dashboard

### Rancher Desktop Version

1.6.0rc1

### Rancher Desktop K8s Version

1.20.15

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.3

### What CPU architecture are you using?

x64

**Comment by rak-phillip** [comment] 2022-09-28 17:36
This is a duplicate of #3012. closing

**Closed by rak-phillip** 2022-09-28 17:36 UTC
Labels: kind/bug
