### ISSUE TITLE
Fails to Start due to long path issue

### ISSUE THREAD

**Issue by roopesh-bhat** [rancher-sandbox/rancher-desktop#6551] opened 2024-03-01 07:19 UTC
### Actual Behavior

<img width="1606" alt="Screenshot 2024-03-01 at 11 40 10" src="https://github.com/rancher-sandbox/rancher-desktop/assets/159158172/f77021da-6a03-47e0-a1b0-d91a82239438">
Error Message 
    '--tty=false',
    '/Users/prathikantamroopesh.bhat/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
  ],
  stdout: '',
  stderr: 'time="2024-03-01T12:35:32+05:30" level=info msg="Terminal is not available, proceeding without opening an editor"\n' +
    'time="2024-03-01T12:35:32+05:30" level=fatal msg="instance name \\"0\\" too long: \\"/Users/prathikantamroopesh.bhat/Library/Application Support/rancher-desktop/lima/0/ssh.sock.1234567890123456\\" must be less than UNIX_PATH_MAX=104 characters, but is 108"\n',
  code: 1,
  [Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura start --tty=false /Users/prathikantamroopesh.bhat/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
}

Last run command :  

/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura start --tty=false /Users/prathikantamroopesh.bhat/Library/Application Support/rancher-desktop/lima/_config/0.yaml

### Steps to Reproduce

1) Install Rancher Desktop - any mens Internet download, Brew install 
2) long user Name to mac  eg : prathikantamroopesh.bhat (This is my company given user name) which is not possible 
which make my path looks like : /Users/prathikantamroopesh.bhat/
3) start the rancher in apps the screen shot error will apperar 

### Result

<img width="1606" alt="Screenshot 2024-03-01 at 11 40 10" src="https://github.com/rancher-sandbox/rancher-desktop/assets/159158172/970ba6b4-71d2-4c62-96ab-5f5f4eadc57c">
Unable to run any containers, where as I am able to run my containers with docker 

### Expected Behavior

Should be able to Run all my containers , the same container setup is tested with Docker and Tested with Rancher in Windows. 

### Additional Information

I have installed Rancher first and as it faild and then installed Docker after uninstalling Rancher.  

### Rancher Desktop Version

Version: 1.12.3

### Rancher Desktop K8s Version

 Kubernetes: 1.29.1

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

MAC OS : 14.3 (23D56)

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

<img width="1606" alt="Screenshot 2024-03-01 at 11 40 10" src="https://github.com/rancher-sandbox/rancher-desktop/assets/159158172/f04ab582-ea3e-43cb-8cf2-703e30716160">

**Comment by jandubois** [comment] 2024-03-01 07:49
There are steps to work around this issue in https://github.com/rancher-sandbox/rancher-desktop/issues/797#issuecomment-996510877.

I'm closing this issue as a duplicate of #797.

**Closed by jandubois** 2024-03-01 07:49 UTC
Labels: kind/bug

**Comment by roopesh-bhat** [comment] 2024-03-01 11:06
This workaround is not working , for me can you please help 
  'start',
    '--tty=false',
    '/Users/prathikantamroopesh.bhat/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
  ],
  stdout: '',
  stderr: 'time="2024-03-01T16:35:36+05:30" level=fatal msg="open /Users/prathikantamroopesh.bhat/Library/Application Support/rancher-desktop/lima/_config/0.yaml: no such file or directory"\n',
  code: 1,
  [Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura start --tty=false /Users/prathikantamroopesh.bhat/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
}getting the above error

**Comment by Folivi95** [comment] 2024-03-08 08:51
This issue still persists and the workaround in #797 does not fix it for the system specs and rancher desktop version mentioned above.

**Comment by jandubois** [comment] 2024-03-08 09:11
It looks like you didn't create the symlink correctly; please double-check. What do you get for `ls -l ~/Library/Application\ Support/rancher-desktop/lima`?

**Comment by Folivi95** [comment] 2024-03-09 08:46
It works after duplicating and renaming the network.yaml file to 0.yaml under "lima/_config" folder and then creating the simlink. I use an M3 MacBook (for context).
