### ISSUE TITLE
Unable to clean start kubernetes on Mac: connect ECONNREFUSED

### ISSUE THREAD

**Issue by wodecki** [rancher-sandbox/rancher-desktop#3698] opened 2023-01-04 18:56 UTC
I have a clean installation of Rancher Desktop 1.7.0 on MacOS Ventura 13.1
I get the Error Starting Kubernetes: connect ECONNREFUSED 127.0.0.1:6443 (screen attached). 
<img width="595" alt="Rancher Error" src="https://user-images.githubusercontent.com/14348685/210628945-2466e5ba-67ed-42cd-a2d2-911ac2fa3660.png">

I would appreciate Your help/advise how to fix it?

Andy

**Comment by wodecki** [comment] 2023-01-04 19:13
Problem solved when I changed Container Engine from dockerd (moby) to containerd (in Preferences).

I keep the issue open since it seems to be a bug with dockerd (moby)

**Comment by ryancurrah** [comment] 2023-01-06 23:01
I'm currently using the `moby` runtime and not having this issue. I'm on macOS Sierra, amd64.

**Comment by jandubois** [comment] 2023-01-06 23:42
> I'm on macOS Sierra

Sorry, off-topic:

Uh oh, I think the changes in #3580 will not allow you to run on that version anymore (or anything before Catalina). And we are going to move the check up to require at least Big Sur in the next release. Maybe we need a hidden switch to disable the check?

Since you were asking about VZ support, I assumed you were using Ventura (it will not work on earlier versions).

**Comment by gaktive** [comment] 2023-01-23 23:55
Hi @wodecki 

Thanks for filing this and providing your update. We'll close this for now since we can't reproduce it. If this turns out to be a moby bug, perhaps file a ticket in that repo.

**Closed by gaktive** 2023-01-23 23:55 UTC
Labels: kind/bug, platform/macos

**Comment by Nedervino** [comment] 2023-02-06 14:30
@wodecki this likely has to do with the Kubernetes version you selected in your Rancher preferences. I ran into the same issue while running a freshly installed Rancher with K8s v1.26.1 , but when switching to v1.24.4 the issue was resolved

**Comment by harsh4870** [comment] 2024-01-04 08:46
i am facing the same error v1.28 is stable in Rancher 1.7 but I have not tried installing cleanup multiple times. Changed to containerd working fine now.
