### ISSUE TITLE
RD failed to start with version 1.1.0 or 1.1.1 or 1.2.1

### ISSUE THREAD

**Issue by ChBerrich** [rancher-sandbox/rancher-desktop#1927] opened 2022-03-29 20:35 UTC
### Actual Behavior

Same issue as #1740 with 1.2.1

### Steps to Reproduce

Scenario 1: From version 1.0.0 or 1.0.1 working on my PC with auto update activated, after new version download and RD restart, RD fail to start.

Scenario 2: After uninstall and clean all rancher-desktop directories, clean install with 1.2.1 produce same problem, RD fail to start with below error log

### Result

**server.log**
`2022-03-29T20:19:35.994Z: CLI server is now ready.`

**k8s.log**
`2022-03-29T20:19:35.971Z: Error reading cached version data, discarding: [Error: ENOENT: no such file or directory, open 'C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\rancher-desktop\cache\k3s-versions.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\myname.MYCOMPANY-EMEA\\AppData\\Local\\rancher-desktop\\cache\\k3s-versions.json'
}
2022-03-29T20:19:35.984Z: Error reading cached version data, discarding: [Error: ENOENT: no such file or directory, open 'C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\rancher-desktop\cache\k3s-versions.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\myname.MYCOMPANY-EMEA\\AppData\\Local\\rancher-desktop\\cache\\k3s-versions.json'
}
2022-03-29T20:19:35.984Z: Updating release version cache with 0 items in cache`

**background.log**
`2022-03-29T20:19:36.157Z: Error starting up: <ref *1> Error: spawnSync C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar.unpacked\node_modules\win-ca\lib\roots.exe ENOBUFS
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:821:24)
    at Object.execFileSync (node:child_process:867:15)
    at Object.func [as execFileSync] (node:electron/js2c/asar_bundle:5:2027)
    at Object.run (C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\win-ca\lib\fallback.js:43:26)
    at api (C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\win-ca\lib\index.js:60:10)
    at C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:170134
    at C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:170854 {
  errno: -4060,
  code: 'ENOBUFS',
  syscall: 'spawnSync C:\\Users\\myname.MYCOMPANY-EMEA\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\app.asar.unpacked\\node_modules\\win-ca\\lib\\roots.exe',
  path: 'C:\\Users\\myname.MYCOMPANY-EMEA\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\app.asar.unpacked\\node_modules\\win-ca\\lib\\roots.exe',
  spawnargs: [ 'root', 'ca' ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    <Buffer 33 30 38 32 30 36 31 61 33 30 38 32 30 34 30 32 61 30 30 33 30 32 30 31 30 32 30 32 31 32 31 31 32 30 32 30 63 38 34 66 37 35 33 36 62 62 61 65 38 39 ... 1049150 more bytes>,
    <Buffer >
  ],
  pid: 7400,
  stdout: <Buffer 33 30 38 32 30 36 31 61 33 30 38 32 30 34 30 32 61 30 30 33 30 32 30 31 30 32 30 32 31 32 31 31 32 30 32 30 63 38 34 66 37 35 33 36 62 62 61 65 38 39 ... 1049150 more bytes>,
  stderr: <Buffer >
}`

### Expected Behavior

Have RD running

### Rancher Desktop Version

1.2.1

### Rancher Desktop K8s Version

NA

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 21H2

### What CPU architecture are you using?

x64

### Windows User Only

VPN PulseSecure but not connected during the test/problem
No other specific rules, but my PC is managed by my company

Not that Rancher Desktop version 1.0.0 or 1.0.1 is still working on my PC after uninstall 1.2.1

**Comment by mook-as** [comment] 2022-03-29 21:00
Closing as a duplicate of #1740 — this should be fixed in the upcoming release.

**Closed by mook-as** 2022-03-29 21:00 UTC
Labels: kind/bug

**Comment by ChBerrich** [comment] 2022-04-29 17:32
I confirm, issue fix with version 1.3.0, thanks a lot :)
