### ISSUE TITLE
NodePort services are not accessible from host using localhost

### ISSUE THREAD

**Issue by Noksa** [rancher-sandbox/rancher-desktop#2489] opened 2022-07-06 08:04 UTC
### Actual Behavior

Trying to hit a nodeport service from the host using localhost:NODEPORT_SEVICE_PORT
Result:
```
❯ ~ curl localhost:55457
curl: (7) Failed to connect to localhost port 55457 after 6 ms: Connection refused
```

### Steps to Reproduce

* Install Rancher Desktop 1.4.1 on Mac M1
* Use dockerd as CR
* Allow sudo access
* Restart Rancher Desktop
* Create a deployment and create nodeport service mapped to the deployment
* Try to hit the nodeport using localhost

### Result

```
❯ ~ curl localhost:55457
curl: (7) Failed to connect to localhost port 55457 after 6 ms: Connection refused
```

### Expected Behavior

It should be accessible from the host using localhost as it works in DD for example.

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

1.22.11

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

MacOS Monterey 12.4

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by julianbartel** [comment] 2022-07-12 06:42
I experience the same on Windows 10.0.19044.
- Rancher Desktop 1.4.1
- k8s 1.22 and 1.23
- containerd

**Comment by ernestorocha** [comment] 2022-07-25 23:05
I'm having the exact problem on the same configuration.

But if I come to this menu and click on `Forward` and use that port instead, I can access the service normally.


<img width="236" alt="image" src="https://user-images.githubusercontent.com/36022/180889145-eaae8839-a2f1-4422-814d-a368fa7df668.png">

**Comment by jandubois** [comment] 2022-07-25 23:09
The issue turns out to be an upstream change in Kubernetes itself. You can get the list of versions that don't forward the port properly anymore from https://github.com/rancher-sandbox/rancher-desktop/issues/2593#issuecomment-1192278825.

So #2593 is actually a duplicate of this one, but we'll keep both open for now because the other issue has more details about the problem already.

**Comment by itsnagaraj** [comment] 2022-07-28 00:24
Kubernetes version 1.19.x and 1.20.x seem to work fine but I couldn't get it working for 1.21.x

**Comment by bharathkarnam** [comment] 2022-07-28 01:49
Same here, doesn’t work for 1.21.x on  my Mac M1 chip

**Comment by sonia-rattan** [comment] 2022-07-28 06:15
Same here. So upvoting.

**Comment by jandubois** [comment] 2022-07-28 07:29
Please report the exact configuration you are testing and not make some generalization like "Doesn't work on 1.21.x" if you only tested a specific version, and not all of them.

I assume you only tested 1.21.12, as 1.21.11 and 1.21.10 worked in my testing.

I'm going to close this as a duplicate of #2593.

Feel free to re-open if it fails for you for any version not yet listed in https://github.com/rancher-sandbox/rancher-desktop/issues/2593#issuecomment-1192278825 (I just updated it to include 1.21.12) and please specify the exact configuration that you are running.

**Closed by jandubois** 2022-07-28 07:29 UTC
Labels: kind/bug

**Comment by jandubois** [comment] 2022-07-28 07:36
Apologies to @Noksa as this is actually the first bug report about this issue, but we didn't realize until recently that #2593 is the same thing. Normally I would close the later issue as a duplicate of the earlier one, but in this case the information about the root cause is already included in the other issue, so we need to keep that one open for the developer who is going to fix it..

We will make a 1.5.1 release next month that will add support for automatic port forwarding with the newer Kubernetes releases; it has not yet been addressed in the 1.5.0 release from earlier today.

**Comment by itsnagaraj** [comment] 2022-07-28 09:18
> Please report the exact configuration you are testing and not make some generalization like "Doesn't work on 1.21.x" if you only tested a specific version, and not all of them.
> 
> I assume you only tested 1.21.12, as 1.21.11 and 1.21.10 worked in my testing.
> 
> I'm going to close this as a duplicate of #2593.
> 
> Feel free to re-open if it fails for you for any version not yet listed in [#2593 (comment)](https://github.com/rancher-sandbox/rancher-desktop/issues/2593#issuecomment-1192278825) (I just updated it to include 1.21.12) and please specify the exact configuration that you are running.

Yes I only tried 1.21.12 as that was the EKS version we were using. When node port did not work I switched to 1.20.15 as that was recommend list. I can confirm that 1.21.11 is working on M1 and I have switched to this version

**Comment by jandubois** [comment] 2022-07-28 19:22
> Yes I only tried 1.21.12 as that was the EKS version we were using. When node port did not work I switched to 1.20.15 as that was in recommend list. I can confirm that 1.21.11 is working on M1 and I have switched to this version

@itsnagaraj Thank you for confirming! And sorry I was a bit grumpy last night about the `1.21.x` issue!

**Comment by davidwincent** [comment] 2023-06-30 05:33
Is it suposed to work on kubernetes v1.27.2? I am still having problems with port-forward to kube-dns
