### ISSUE TITLE
Menubar should show actual k8s status

### ISSUE THREAD

**Issue by 589290** [rancher-sandbox/rancher-desktop#2114] opened 2022-04-27 13:17 UTC
### Actual Behavior

k8s not running, but shows running in menubar
<img width="956" alt="Screen Shot 2022-04-27 at 8 11 03 AM" src="https://user-images.githubusercontent.com/69643994/165526315-25c7d7c8-b5a2-400a-b4e3-3352ebbb67e2.png">

### Steps to Reproduce

Disable k8s

### Result

Menubar says k8s still running

### Expected Behavior

Menubar says k8s NOT running

### Rancher Desktop Version

1.2.1

### Rancher Desktop K8s Version

1.23.x

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

12.3.1

### What CPU architecture are you using?

x64

**Comment by 589290** [comment] 2022-04-27 13:23
Ideally, I'd like to see two statuses in the menubar:

k8s status (shows correct k8s running status)
dockerd status (docker daemon status -- can't be disabled, but nice to have the status shown so you know it's still running even when k8s is disabled!)

**Comment by rak-phillip** [comment] 2022-04-27 15:46
closing as this looks to be a duplicate of #1734

**Closed by rak-phillip** 2022-04-27 15:46 UTC
Labels: kind/bug
