### ISSUE TITLE
Rancher Desktop 1.1.1 install failed

### ISSUE THREAD

**Issue by aresnasa** [rancher-sandbox/rancher-desktop#1851] opened 2022-03-21 07:21 UTC
### Actual Behavior

Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1

### Steps to Reproduce

/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl start --tty=false 0

### Result

time="2022-03-21T15:18:06+08:00" level=info msg="Using the existing instance \"0\""
time="2022-03-21T15:18:06+08:00" level=info msg="Starting switch daemon for \"bridged_en0\" network"
time="2022-03-21T15:18:06+08:00" level=fatal msg="\"/private/var/run/rancher-desktop-lima\" doesn't seem to be writable by the daemon (gid:1) group"
2022-03-21T07:18:06.288Z: + limactl start --tty=false 0
2022-03-21T07:18:06.289Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-03-21T07:18:06.290Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8692)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)

### Expected Behavior

cp Rancher-Desktop.app to Application then run app, then through error

### Additional Information

Mac OSX 12.3 Montery M1

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

1.22.7

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

12.3

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by t40mas** [comment] 2022-03-21 10:14
### Workaround

- Stop Rancher-Desktop
- Delete /private/var/run/rancher-desktop-lima manually
	- sudo rm -rf /private/var/run/rancher-desktop-lima
- Create folder with permissions
	- sudo mkdir -m 775 /private/var/run/rancher-desktop-lima
- Start Rancher-Desktop

Hopefully this will be fixed in future releases

**Comment by aresnasa** [comment] 2022-03-21 13:14
> ### Workaround
> * Stop Rancher-Desktop
> * Delete /private/var/run/rancher-desktop-lima manually
>   
>   * sudo rm -rf /private/var/run/rancher-desktop-lima
> * Create folder with permissions
>   
>   * sudo mkdir -m 775 /private/var/run/rancher-desktop-lima
> * Start Rancher-Desktop
> 
> Hopefully this will be fixed in future releases

Thanks ,it works!!!

**Closed** 2022-03-21 14:06 UTC
Labels: kind/bug

**Comment by jandubois** [comment] 2022-03-21 16:00
Duplicate of #1815
