### ISSUE TITLE
Starting RD gives Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by sysadmin75** [rancher-sandbox/rancher-desktop#5165] opened 2023-07-14 14:10 UTC
### Actual Behavior

Starting RD on MacOS goes through it's startup. After about 5 min, it produces this error:
```
2023-07-12T18:44:31.521Z: Error starting lima: Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1532:34)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket._finishInit (node:_tls_wrap:946:8)
    at ssl.onhandshakedone (node:_tls_wrap:727:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
```

### Steps to Reproduce

Start RD by clicking the RD icon in launchpad.

### Result

```
2023-07-12T18:44:31.521Z: Error starting lima: Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1532:34)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket._finishInit (node:_tls_wrap:946:8)
    at ssl.onhandshakedone (node:_tls_wrap:727:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
```

### Expected Behavior

RD to start without error.

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

1.27.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Ventura 13.4.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by sysadmin75** [comment] 2023-07-14 14:11
I have tried the `Reset Kubernetes` and `Factory Reset` buttons and it the same error persists.

**Comment by gaktive** [comment] 2023-07-20 00:02
Hi @sysadmin75! The error definitely highlights something happening in your certificate chain.

What type of networking setup are you running on: do you rely on a system proxy or connect through a VPN? 

Could you also provide the logs; you can get to the logs folder by navigating to Troubleshooting tab in the application and Show logs. It's possible that I may need more information about your local certificates but I want to see what other details exist there first.

**Comment by sysadmin75** [comment] 2023-07-27 22:23
I deleted an expired cert in my certificate chain and RD started successfully.  Thank you for pointing this out to me.

**Comment by jandubois** [comment] 2023-07-28 06:35
Looks like the issue has been resolved, so I will close it.

Just for the record, I just ran into the same symptoms, but the cause was different: I had another VM running (using Lima), so the 6443 port was already in use by a different cluster, so Rancher Desktop could not forward the 6443 port to the host, and connections using the Rancher Desktop kubeconfig were connecting to the other VM. This of course caused the certificate mismatch because the other cluster cert was not signed by the Rancher Desktop CA.

**Closed by jandubois** 2023-07-28 06:35 UTC
Labels: kind/bug, triage/needs-information, platform/macos

**Comment by strophy** [comment] 2024-07-02 08:01
I'm getting this error as well, with 1.14.2 on Ubuntu 24.04. How can I inspect the certificate chain and delete potentially expired certificates?

**Comment by rumstead** [comment] 2024-07-17 15:45
Same here, can we reopen?

**Comment by jandubois** [comment] 2024-07-17 20:11
Are you on a machine that needs to use a proxy to connect to the internet?

**Comment by rumstead** [comment] 2024-07-17 21:09
> Are you on a machine that needs to use a proxy to connect to the internet?

Yes and follow what I did [here](https://github.com/rancher-sandbox/rancher-desktop/issues/897#issuecomment-1163141719) to get image pulls working 

I see in update.log

```
2024-07-12T17:18:14.608Z: Checking for update
2024-07-12T17:18:15.796Z: Error: FetchError: request to https://desktop.version.rancher.io/v1/checkupgrade failed, reason: self signed certificate in certificate chain
```

I tried setting `NODE_EXTRA_CA_CERTS` to the ca bundle that is in my key chain (for browser access) and what I use when making https calls over the proxy.

**Comment by jandubois** [comment] 2024-07-17 21:31
@rumstead Since you are on macOS, the environment variables are not inherited by GUI apps.

You can try to run Rancher Desktop from the shell like this:

```shell
export NODE_EXTRA_CA_CERTS=…
/Applications/Rancher\ Desktop.app/Contents/MacOS/Rancher\ Desktop
```

This shell window will hang until you quit Rancher Desktop; it is just to test if setting the variable makes any difference.

If it does, you could try setting it globally in `launchd`, which is what will start GUI apps for `Finder.app`:

```shell
launchctl setenv NODE_EXTRA_CA_CERTS "…"
```

And then start Rancher Desktop normally as before.

Let me know if this makes a difference or not.

**Comment by rumstead** [comment] 2024-07-18 12:39
Thanks for the suggestion! Doesn't seem to address it.

```
❯ export NODE_EXTRA_CA_CERTS="/Users/rumstead/tmp/certs/internal-ca-bundle.crt" && echo $NODE_EXTRA_CA_CERTS && /Applications/Rancher\ Desktop.app/Contents/MacOS/Rancher\ Desktop
/Users/rumstead/tmp/certs/internal-ca-bundle.crt
2024-07-18 08:38:33.064 Rancher Desktop[77676:2280691] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
```

```
2024-07-18T12:33:43.444Z: Setting up updater... enabled=true doInstall=true
2024-07-18T12:33:43.454Z: Checking for update
2024-07-18T12:33:43.454Z: update: checking for update
2024-07-18T12:33:43.474Z: Checking https://desktop.version.rancher.io/v1/checkupgrade for updates
2024-07-18T12:33:44.578Z: Error: FetchError: request to https://desktop.version.rancher.io/v1/checkupgrade failed, reason: self signed certificate in certificate chain
```

**Comment by mook-as** [comment] 2024-07-18 17:06
On macOS, we basically run `/usr/bin/security find-certificate -a -p` to find the set of certificates; does that list your certificate? (The relevant code is at https://github.com/rancher-sandbox/rancher-desktop/blob/v1.14.2/pkg/rancher-desktop/main/networking/mac-ca.ts )

There's also a chance that we're screwing up actually adding the certificates; we set those certificates on the global HTTP(S) agent instance: https://github.com/rancher-sandbox/rancher-desktop/blob/v1.14.2/pkg/rancher-desktop/main/networking/index.ts#L27-L42 but we should be setting the correct agent at https://github.com/rancher-sandbox/rancher-desktop/blob/v1.14.2/pkg/rancher-desktop/utils/fetch.ts#L124

**Comment by rumstead** [comment] 2024-07-19 17:25
Yeah I see all the internal certs when I bump out `/usr/bin/security find-certificate -a -p`

**Comment by rumstead** [comment] 2024-07-19 22:48
When I debug the `mac-ca.ts` I see all the certs in the bundle hitting the "[yield](https://github.com/rancher-sandbox/rancher-desktop/blob/3686c1aab004014c6608242885fdcf6dbd6e0dd7/pkg/rancher-desktop/main/networking/mac-ca.ts#L81)" line... now I am just really confused.

**Comment by mook-as** [comment] 2024-07-19 23:10
Yep, when they hit that they get returned (individually) to the caller:
https://github.com/rancher-sandbox/rancher-desktop/blob/3686c1aab004014c6608242885fdcf6dbd6e0dd7/pkg/rancher-desktop/main/networking/index.ts#L28-L29
And the agent is set to use those CAs:
https://github.com/rancher-sandbox/rancher-desktop/blob/3686c1aab004014c6608242885fdcf6dbd6e0dd7/pkg/rancher-desktop/main/networking/index.ts#L36-L42
Eventually we end up using the agent when doing a `fetch()`:
https://github.com/rancher-sandbox/rancher-desktop/blob/3686c1aab004014c6608242885fdcf6dbd6e0dd7/pkg/rancher-desktop/utils/fetch.ts#L124
We actually end up trapping SSL errors to better handle errors (for dealing with k3s, because the CA that uses is generated later):
https://github.com/rancher-sandbox/rancher-desktop/blob/3686c1aab004014c6608242885fdcf6dbd6e0dd7/pkg/rancher-desktop/utils/fetch.ts#L71
So that would be a good spot to try to set a breakpoint and check if the agent in that scope has the correct CAs set.

**Comment by rumstead** [comment] 2024-08-05 17:42
Ok got distracted with some other things but I am back. 

What I don't understand is the majority of the URLs work fine. Here is what I did. 

I first "hide" the `k3s-versions.json` and `k3s` file and folder respectively. 
```bash
~/Library/Caches/rancher-desktop                                                                                                                                                                                 
❯ ls
k3s-versions.json_bak     k3s_bak                   updater-longhorn.json_bak
```
```
Mon Aug 05 2024 13:06:27 GMT-0400 (Eastern Daylight Time): Error reading cached version data, discarding: Error: ENOENT: no such file or directory, open '/Users/rumstead/Library/Caches/rancher-desktop/k3s-versions.json'
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1249:14)
    at async K3sHelper.readCache (/Users/rumstead/IdeaProjects/rancher-desktop/dist/app/background.js:19771:42)
    at async /Users/rumstead/IdeaProjects/rancher-desktop/dist/app/background.js:20053:17 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/rumstead/Library/Caches/rancher-desktop/k3s-versions.json'
}
Mon Aug 05 2024 13:06:30 GMT-0400 (Eastern Daylight Time): Error reading cached version data, discarding: Error: ENOENT: no such file or directory, open '/Users/rumstead/Library/Caches/rancher-desktop/k3s-versions.json'
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1249:14)
    at async K3sHelper.readCache (/Users/rumstead/IdeaProjects/rancher-desktop/dist/app/background.js:19771:42)
    at async K3sHelper.updateCache (/Users/rumstead/IdeaProjects/rancher-desktop/dist/app/background.js:19942:13)
    at async /Users/rumstead/IdeaProjects/rancher-desktop/dist/app/background.js:20061:17 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/rumstead/Library/Caches/rancher-desktop/k3s-versions.json'
}
```
Then I see successful requests to `https://update.k3s.io/v1-release/channels` and `https://api.github.com/repos/k3s-io/k3s/releases?per_page=100`.

```
Mon Aug 05 2024 13:06:30 GMT-0400 (Eastern Daylight Time): Updating release version cache with 0 items in cache
Mon Aug 05 2024 13:08:57 GMT-0400 (Eastern Daylight Time): Got K3s update channel data: stable,latest,testing,v1.16,v1.16-testing,v1.17,v1.17-testing,v1.18,v1.18-testing,v1.19,v1.20,v1.21,v1.22,v1.23,v1.24,v1.25,v1.26,v1.27,v1.28,v1.29,v1.30
Mon Aug 05 2024 13:10:18 GMT-0400 (Eastern Daylight Time): Recommended versions: {
  stable: 'v1.30.3+k3s1',
  latest: 'v1.30.3+k3s1',
  testing: 'v1.30.3-rc2+k3s1',
  'v1.16': 'v1.16.15+k3s1',
  'v1.16-testing': 'v1.16.14-rc1+k3s1',
  'v1.17': 'v1.17.17+k3s1',
  'v1.17-testing': 'v1.17.17-rc1+k3s1',
  'v1.18': 'v1.18.20+k3s1',
  'v1.18-testing': 'v1.18.20-rc1+k3s1',
  'v1.19': 'v1.19.16+k3s1',
  'v1.20': 'v1.20.15+k3s1',
  'v1.21': 'v1.21.14+k3s1',
  'v1.22': 'v1.22.17+k3s1',
  'v1.23': 'v1.23.17+k3s1',
  'v1.24': 'v1.24.17+k3s1',
  'v1.25': 'v1.25.16+k3s4',
  'v1.26': 'v1.26.15+k3s1',
  'v1.27': 'v1.27.16+k3s1',
  'v1.28': 'v1.28.12+k3s1',
  'v1.29': 'v1.29.7+k3s1',
  'v1.30': 'v1.30.3+k3s1'
}
Mon Aug 05 2024 13:11:45 GMT-0400 (Eastern Daylight Time): Fetching releases from https://api.github.com/repos/k3s-io/k3s/releases?per_page=100 -> OK
...
Mon Aug 05 2024 13:13:30 GMT-0400 (Eastern Daylight Time): Fetching releases from https://api.github.com/repositories/135516270/releases?per_page=100&page=2 -> OK
...
Mon Aug 05 2024 13:13:36 GMT-0400 (Eastern Daylight Time): Fetching releases from https://api.github.com/repositories/135516270/releases?per_page=100&page=3 -> OK
...
Mon Aug 05 2024 13:14:07 GMT-0400 (Eastern Daylight Time): Fetching releases from https://api.github.com/repositories/135516270/releases?per_page=100&page=8 -> OK
...
Mon Aug 05 2024 13:15:11 GMT-0400 (Eastern Daylight Time): Got 198 versions.
Mon Aug 05 2024 13:15:12 GMT-0400 (Eastern Daylight Time): Wrote versions cache: {
  cacheVersion: 2,
  versions: [
    'v1.16.7+k3s1',  'v1.16.9+k3s1',  'v1.16.10+k3s1', 'v1.16.11+k3s1',
    'v1.16.13+k3s1', 'v1.16.14+k3s1', 'v1.16.15+k3s1', 'v1.17.2+k3s1',
    'v1.17.3+k3s1',  'v1.17.4+k3s1',  'v1.17.5+k3s1',  'v1.17.6+k3s1',
    'v1.17.7+k3s1',  'v1.17.9+k3s1',  'v1.17.11+k3s1', 'v1.17.12+k3s1',
    'v1.17.13+k3s2', 'v1.17.14+k3s3', 'v1.17.15+k3s1', 'v1.17.17+k3s1',
    'v1.18.2+k3s1',  'v1.18.3+k3s1',  'v1.18.4+k3s1',  'v1.18.6+k3s1',
    'v1.18.8+k3s1',  'v1.18.9+k3s1',  'v1.18.10+k3s2', 'v1.18.12+k3s2',
    'v1.18.13+k3s1', 'v1.18.15+k3s1', 'v1.18.16+k3s1', 'v1.18.17+k3s1',
    'v1.18.18+k3s1', 'v1.18.19+k3s1', 'v1.18.20+k3s1', 'v1.19.1+k3s1',
    'v1.19.2+k3s1',  'v1.19.3+k3s3',  'v1.19.4+k3s2',  'v1.19.5+k3s2',
    'v1.19.7+k3s1',  'v1.19.8+k3s1',  'v1.19.9+k3s1',  'v1.19.10+k3s1',
    'v1.19.11+k3s1', 'v1.19.12+k3s1', 'v1.19.13+k3s1', 'v1.19.14+k3s1',
    'v1.19.15+k3s2', 'v1.19.16+k3s1', 'v1.20.0+k3s2',  'v1.20.2+k3s1',
    'v1.20.4+k3s1',  'v1.20.5+k3s1',  'v1.20.6+k3s1',  'v1.20.7+k3s1',
    'v1.20.8+k3s1',  'v1.20.9+k3s1',  'v1.20.10+k3s1', 'v1.20.11+k3s2',
    'v1.20.12+k3s1', 'v1.20.13+k3s1', 'v1.20.14+k3s2', 'v1.20.15+k3s1',
    'v1.21.0+k3s1',  'v1.21.1+k3s1',  'v1.21.2+k3s1',  'v1.21.3+k3s1',
    'v1.21.4+k3s1',  'v1.21.5+k3s2',  'v1.21.6+k3s1',  'v1.21.7+k3s1',
    'v1.21.8+k3s2',  'v1.21.9+k3s1',  'v1.21.10+k3s1', 'v1.21.11+k3s1',
    'v1.21.12+k3s1', 'v1.21.13+k3s1', 'v1.21.14+k3s1', 'v1.22.2+k3s2',
    'v1.22.3+k3s1',  'v1.22.4+k3s1',  'v1.22.5+k3s2',  'v1.22.6+k3s1',
    'v1.22.7+k3s1',  'v1.22.8+k3s1',  'v1.22.9+k3s1',  'v1.22.10+k3s1',
    'v1.22.11+k3s2', 'v1.22.12+k3s1', 'v1.22.13+k3s1', 'v1.22.15+k3s1',
    'v1.22.16+k3s1', 'v1.22.17+k3s1', 'v1.23.1+k3s2',  'v1.23.2+k3s1',
    'v1.23.3+k3s1',  'v1.23.4+k3s1',  'v1.23.5+k3s1',  'v1.23.6+k3s1',
    ... 98 more items
  ],
  channels: {
    'v1.29': '1.29.7',
    'v1.28': '1.28.12',
    'v1.27': '1.27.16',
    stable: '1.30.3',
    latest: '1.30.3',
    'v1.30': '1.30.3',
    'v1.26': '1.26.15',
    'v1.25': '1.25.16',
    'v1.24': '1.24.17',
    'v1.23': '1.23.17',
    'v1.22': '1.22.17',
    'v1.21': '1.21.14',
    'v1.20': '1.20.15',
    'v1.19': '1.19.16',
    'v1.18': '1.18.20',
    'v1.17': '1.17.17',
    'v1.16': '1.16.15'
  }
}
```

Now my `k3s-versions.json` is back
```
~/Library/Caches/rancher-desktop                                                                                                                                                                                 
❯ ls
k3s-versions.json         k3s-versions.json_bak     k3s_bak                   updater-longhorn.json_bak
```

However, the second I launch the app via launchctl, the GUI, or even my shell I get the cert errors again.

I don't think the env variables I export make it to the process when I do 
```bash
export ... && /Applications/Rancher\ Desktop.app/Contents/MacOS/Rancher\ Desktop
```
