### ISSUE TITLE
aarch64 DMG isn't

### ISSUE THREAD

**Issue by treaves** [rancher-sandbox/rancher-desktop#1791] opened 2022-03-11 18:27 UTC
### Actual Behavior

The 1.1.1 release for Mac M1 silicon is actually for Intel, not M1.  Don't know if it was bundled incorrectly, or what.

### Steps to Reproduce

Download the 1.1.1 Mac aarch64 release
Look at the Rancher Desktop supported application kind

### Result

It's Intel

### Expected Behavior

M1 (aarch64)

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

1.99.9

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

12.2.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by mook-as** [comment] 2022-03-11 19:59
This is intended (for now) — the aarch64 DMG actually ships a x86_64 electron (which we expect to run under Rosetta) plus aarch64-native qemu to run VMs with.  We do plan to transition later, but there's no defined timeline yet.

Closing this as a duplicate of #1416.

**Closed by mook-as** 2022-03-11 19:59 UTC
Labels: kind/bug
