### ISSUE TITLE
RD does not detect running instance

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#1437] opened 2022-02-01 14:22 UTC
### Rancher Desktop Version

1.0.0 & 1.1.1

### Rancher Desktop K8s Version

1.21.7

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 PRO / Windows 11

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

### Actual Behavior

You can execute more than one application instance on Windows. One application will work and the another will stop, but it will keep running in the system.

### Steps to Reproduce

1. Open RD application and wait until app loads.
2. Open another RD instance.
3. Check on system tray, one instance will be running and another will have a failure

#### Windows 10 PRO
<img width="1218" alt="Screen Shot 2022-02-01 at 11 07 17 AM" src="https://user-images.githubusercontent.com/37411123/151985300-6f903f3f-b896-492e-bc07-bd771ee32fc5.png">

#### Windows 11
On Windows 11 has a different behaviour, where it does not load another RD instance UI, but it keeps on system tray.
<img width="1222" alt="Screen Shot 2022-02-01 at 11 13 40 AM" src="https://user-images.githubusercontent.com/37411123/151985333-417083bb-4c12-41c3-b188-63ecd2bc0640.png">

### Expected Behavior

RD should detect an existing running instance and display a warning to the user, avoiding loading another RD instance.

**Comment by jandubois** [comment] 2022-03-09 21:42
This was supposed to be fixed by #238

**Comment by Nino-K** [comment] 2022-03-09 21:42
@ericpromislow it looks like the issue is happing again. https://github.com/rancher-sandbox/rancher-desktop/issues/238

**Comment by gaktive** [comment] 2022-08-02 20:55
Closing as a duplicate of a newer ticket #2437

**Closed by gaktive** 2022-08-02 20:55 UTC
Labels: kind/bug, triage/duplicate, platform/windows
