### ISSUE TITLE
provide option for specifying a diffferent basepath for wsl2 distros during installation

### ISSUE THREAD

**Issue by tristanbarcelon** [rancher-sandbox/rancher-desktop#2843] opened 2022-08-30 19:06 UTC
### Problem Description

When installing Rancher Desktop in Windows, it installs WSL2 distros rancher-desktop and rancher-desktop-data within rancher-desktop folder in user's %LOCALAPPDATA%. While this works for the majority of cases, it would be nice if we can specify a different folder to use instead of %LOCALAPPDATA% which almost always relies on system drive. For developers who use VDI, Windows365, or laptops, their system drives are often small so a separate but larger drive is installed. Having the ability to specify a value other than %LOCALAPPDATA% to rancher desktop state and distros would be helpful.

### Proposed Solution

During setup, default to %LOCALAPPDATA% unless overridden. This path would container all the rancher-desktop state including distro states for rancher-desktop and rancher-desktop-data. Expose an installation parameter in the nullsoft installer that would overwrite this default if provided.

**Comment by jandubois** [comment] 2022-08-30 19:21
Thank you for filing this enhancement request!

I think this is a duplicate of #2232. Please follow that issue, and add any additional information there!

**Closed by jandubois** 2022-08-30 19:21 UTC
Labels: kind/enhancement, platform/windows, area/installer
