### ISSUE TITLE
Dockerfile ADD with remote (https) URL failing

### ISSUE THREAD

**Issue by dougbreaux** [rancher-sandbox/rancher-desktop#2652] opened 2022-07-28 20:55 UTC
### Actual Behavior

`nerdctl build .` with a Dockerfile containing :
```dockerfile
ARG DB2_VERSION=11.5.7.0
ADD --chown=1001:0 https://repo1.maven.org/maven2/com/ibm/db2/jcc/$DB2_VERSION/jcc-$DB2_VERSION.jar /config/db2jcc4.jar
```

Fails as shown in the below section.

This builds fine under our CI environment, GitHub Actions, which is using `docker`.

### Steps to Reproduce

```console
nerdctl build .
```

### Result

```
...
 => ERROR [5/6] ADD --chown=1001:0 https://repo1.maven.org/maven2/com/ibm/db2/jcc/11.5.7.0/jcc-11.5.7.0.jar /conf  0.0s
------
 > [5/6] ADD --chown=1001:0 https://repo1.maven.org/maven2/com/ibm/db2/jcc/11.5.7.0/jcc-11.5.7.0.jar /config/db2jcc4.jar:
------
Dockerfile:30
--------------------
  28 |     # this simple, but dependent on specific version, and undocumented
  29 |     ARG DB2_VERSION=11.5.7.0
  30 | >>> ADD --chown=1001:0 https://repo1.maven.org/maven2/com/ibm/db2/jcc/$DB2_VERSION/jcc-$DB2_VERSION.jar /config/db2jcc4.jar
  31 |
  32 |     # https://docs.openshift.com/container-platform/4.5/openshift_images/create-images.html#use-uid_create-images
--------------------
error: failed to solve: snapshot  does not exist: not found
FATA[0000] unrecognized image format
```

### Expected Behavior

Expect the add to succeed in pulling the remote file and placing it correctly in the image.

### Additional Information

The following does work instead, so it's not connectivity or typos:
```dockerfile
...
ARG DB2_VERSION=11.5.7.0
USER root
RUN curl https://repo1.maven.org/maven2/com/ibm/db2/jcc/$DB2_VERSION/jcc-$DB2_VERSION.jar -o db2jcc4.jar && \
    cp db2jcc4.jar /config/ && \
    chown 1001:0 /config/db2jcc4.jar
USER 1001
...
```

### Rancher Desktop Version

1.5.0

### Rancher Desktop K8s Version

N/A

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise, Version 21H2 (OS Build 19044.1526)

### What CPU architecture are you using?

x64

### Windows User Only

Windows Defender

**Comment by rak-phillip** [comment] 2022-07-29 17:27
@dougbreaux thanks for raising this issue and helping to make Rancher Desktop better.

We tested with the following Dockerfile and didn't encounter the problem as described

```
FROM scratch
ARG DB2_VERSION=11.5.7.0
ADD --chown=1001:0 https://repo1.maven.org/maven2/com/ibm/db2/jcc/$DB2_VERSION/jcc-$DB2_VERSION.jar /config/db2jcc4.jar
```

I'm closing this issue because we're not able to reproduce with the information provided. Please follow up with more information if you feel this issue should remain open.

**Closed by rak-phillip** 2022-07-29 17:27 UTC
Labels: kind/bug

**Comment by dougbreaux** [comment] 2022-07-29 17:38
Still failing here with that Dockerfile:
```
$ nerdctl build -t scratch -f Dockerfile.scratch .
[+] Building 5.5s (4/4) FINISHED
 => [internal] load build definition from Dockerfile.scratch                                                       0.1s
 => => transferring dockerfile: 205B                                                                               0.1s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.1s
 => CACHED https://repo1.maven.org/maven2/com/ibm/db2/jcc/11.5.7.0/jcc-11.5.7.0.jar                                5.3s
 => ERROR [1/1] ADD --chown=1001:0 https://repo1.maven.org/maven2/com/ibm/db2/jcc/11.5.7.0/jcc-11.5.7.0.jar /conf  0.0s
------
 > [1/1] ADD --chown=1001:0 https://repo1.maven.org/maven2/com/ibm/db2/jcc/11.5.7.0/jcc-11.5.7.0.jar /config/db2jcc4.jar:
------
Dockerfile.scratch:3
--------------------
   1 |     FROM scratch
   2 |     ARG DB2_VERSION=11.5.7.0
   3 | >>> ADD --chown=1001:0 https://repo1.maven.org/maven2/com/ibm/db2/jcc/$DB2_VERSION/jcc-$DB2_VERSION.jar /config/db2jcc4.jar
   4 |
--------------------
error: failed to solve: snapshot  does not exist: not found
FATA[0005] unrecognized image format
```

**Comment by dougbreaux** [comment] 2022-07-29 17:42
Happens in git bash or cmd.exe, whether run in Administrator mode or not.

**Comment by dougbreaux** [comment] 2022-08-01 21:07
@rak-phillip please see my updates after you closed. What's different between what I ran and what you ran?

**Comment by rak-phillip** [comment] 2022-08-02 17:34
I'm testing in a directory that contains a single Dockerfile with the contents as they are posted above. I'm willing to have another go at a repro to see if I can't coerce some sort of failure.

In the meantime, would you be willing to attach any rancher desktop logs or dockerfiles that you're working with that might be relevant in reproducing the issue?

**Comment by dougbreaux** [comment] 2022-08-02 17:51
Well, I can reproduce it with just the Dockerfile above. Clean directory, no special name, etc.

```
/c/Projects/ranchertest
$ ls -al
total 41
drwxr-xr-x 1 GMX+527309897 4096   0 Aug  2 12:50 .
drwxr-xr-x 1 GMX+527309897 4096   0 Aug  2 12:46 ..
-rw-r--r-- 1 GMX+527309897 4096 158 Aug  2 12:50 Dockerfile

/c/Projects/ranchertest
$ nerdctl build .
[+] Building 0.1s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 197B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => CACHED https://repo1.maven.org/maven2/com/ibm/db2/jcc/11.5.7.0/jcc-11.5.7.0.jar                                0.0s
 => ERROR [1/1] ADD --chown=1001:0 https://repo1.maven.org/maven2/com/ibm/db2/jcc/11.5.7.0/jcc-11.5.7.0.jar /conf  0.0s
------
 > [1/1] ADD --chown=1001:0 https://repo1.maven.org/maven2/com/ibm/db2/jcc/11.5.7.0/jcc-11.5.7.0.jar /config/db2jcc4.jar:
------
Dockerfile:3
--------------------
   1 |     FROM scratch
   2 |     ARG DB2_VERSION=11.5.7.0
   3 | >>> ADD --chown=1001:0 https://repo1.maven.org/maven2/com/ibm/db2/jcc/$DB2_VERSION/jcc-$DB2_VERSION.jar /config/db2jcc4.jar
   4 |
--------------------
error: failed to solve: snapshot  does not exist: not found
FATA[0000] unrecognized image format
```

Are you running nerdctl and using containerd? 

I can certainly attach any relevant RD logs. Is there a way to clear them out before running the above?

**Comment by dougbreaux** [comment] 2022-08-12 13:42
@rak-phillip In case you missed the above

**Comment by rak-phillip** [comment] 2022-08-15 15:30
@dougbreaux we tested using `containerd` as the container runtime but we're unable to reproduce on our end after several attempts. 

If you can, please provide us with Rancher Desktop logs. This way, we can look to see if anything might be amiss.

**Comment by dougbreaux** [comment] 2022-08-15 18:09
@rak-phillip I enabled debug and captured logs. Which file(s) do you need, and is there any chance there's anything sensitive in them?

**Comment by rak-phillip** [comment] 2022-08-16 20:08
We might be interested in any logs related to `lima`, `background`, `networking`, and `wsl`. If you aren't comfortable posting logs publicly on github, you can send them my way via email at `phillip.rak@suse.com` and I can relay to the rest of the team.

**Comment by dougbreaux** [comment] 2022-08-16 21:16
@rak-phillip 

`lima` and `networking` are empty. `background`, `wsl`, and `wsl-exec` are not. I'll send those.

**Comment by dougbreaux** [comment] 2022-09-28 14:57
@rak-phillip @jandubois this is still happening for me, though ☹️

**Comment by dougbreaux** [comment] 2022-10-18 11:46
@rak-phillip @jandubois Same behavior RD 1.6.0

**Comment by dougbreaux** [comment] 2023-05-06 14:25
Confirm that in my current 1.8.1 this is not occurring.
