### ISSUE TITLE
Starting RD should raise existing instance instead of starting a new one

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2437] opened 2022-06-21 17:35 UTC
Normally when you double-click the RD icon while RD is already running, you just get some weird flickering, but the new instance detects the running instance and shuts down again.

But if you close the **window** of the running instance, and then double-click the RD icon, a second instance will start up. You can then use the tray icon to re-create the app window of the first instance as well, but off course they don't really work properly, as they both try to interact with the same WSL backend.

I was just about to write that if you merely minimize the window, then double-clicking on the RD icon will just raise the minimized window. Which it does. But if you wait a little longer, you get a second instance once again.

<img width="1196" alt="Screen Shot 2022-06-21 at 10 35 18 AM" src="https://user-images.githubusercontent.com/78947/174862440-017d663b-7659-4cad-a54e-c619aa8f6fc3.png">

**Comment by gaktive** [comment] 2022-08-02 20:55
Dupe of #1437 though this ticket has an expanded behaviour description.

**Comment by ericpromislow** [comment] 2022-09-14 23:08
macOS `npm run dev`: the second instance succeeds at getting the single-instance-lock, so we get two separate processes running (although with only one icon in the menu bar).

macOS `open /App'n/Rancher Desktop (dev build): this just opens the first process' main window, which is desired behavior. So no regression observed here.

Windows: observed same behavior as for macOS `npm run dev`.  I filed an issue at https://github.com/electron/electron/issues/35680 on this.

**Comment by rak-phillip** [comment] 2022-09-15 15:53
I think issue #2772 could be related to this one

@jandubois

**Comment by jandubois** [comment] 2022-09-15 16:52
> I think issue #2772 could be related to this one

I don't think so. #2772 is about clicking on the Dock icon on macOS during first-run. You still only have a single instance.

This issue is about clicking the shortcut link on the desktop on Windows when the RD app window is closed (but still running and accessible via the notification area). This creates a second instance of the app.

**Comment by adamkpickering** [comment] 2022-10-26 21:05
I ran into this as well while working on #3260 and #3261, which have some overlap with this issue. When run with 1.6.1 on openSUSE Leap 15.3, both instances start without any sign of `requestSingleInstanceLock()` doing what it's supposed to. Additionally, there is a error dialog that pops up:

![image](https://user-images.githubusercontent.com/19395776/198137133-fb6176e0-77a4-4fd9-9999-959702c6908f.png)

Though after a quick look at the code, I don't think this would happen if `requestSingleInstanceLock()` was working correctly.

**Comment by rak-phillip** [comment] 2022-10-27 16:22
The Rancher Dashboard server listens on port 6120. 

The Dashboard Server is a singleton, but we won't have an existing instance in a new Electron window, so the Dashboard Server looks like it's attempting to listen on port 6120 again. I think you're correct in stating that this wouldn't be an issue if `requestSingleInstanceLock()` worked, but we still might be able to guard against this error by

1. Handling the error and logging
2. Asserting that port 6120 is available before attempting to instantiate the Dashboard Server process

**Comment by adamkpickering** [comment] 2022-11-23 21:52
I want to record what I've learned so far, since I have made some progress on this (though there is much left to do). All of this is for Linux, though it probably applies on other platforms.

- Removing the call to `app.setName('Rancher Desktop')` causes a second instance to be able to identify that it is a second instance through `app.requestSingleInstanceLock`.

- While running with `strace`, I noticed that there were references to `SingletonLock`, `SingletonSocket` and `SingletonCookie` in two different directories: `~/.config/rancher-desktop`, and `~/.config/Rancher Desktop`. `~/.config/rancher-desktop` appears to contain things we have programmed in, whereas `~/.config/Rancher Desktop` appears to contain things that are internal to Electron. When the call to `app.setName('Rancher Desktop')` is removed, the contents of these two directories are merged in `~/.config/rancher-desktop`.

- There is an additional call to `app.requestSingleInstanceLock` in `pkg/rancher-desktop/utils/logging.ts`. I believe this is part of the confusion, since it would have run before the call to `app.setName`.

At the moment I think the best course of action is to put the `app.requestSingleInstanceLock` check at the top of `background.ts`, before all imports, other than the `Electron.app` import of course. I also think we should remove the call to `app.requestSingleInstanceLock` from `logging.ts`, and implement a behavior that is the same across all runs.

**Closed** 2022-12-06 20:05 UTC
Labels: kind/bug, platform/windows
