### ISSUE TITLE
Test case 151: `Success` button in the RDX Host-APIs Test extension not responsive

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#6278] opened 2024-01-05 18:51 UTC
**QASE Id:**  151
**1.12 RC4 build:** https://github.com/rancher-sandbox/rancher-desktop/actions/runs/7413086519

The `Success` button doesn't show any toast on my Ubuntu. The `Warning` and `Error` buttons show their respective pop ups toasts though.

**Comment by mook-as** [comment] 2024-01-05 18:56
Duplicate of #5483

**Closed by mook-as** 2024-01-05 18:56 UTC
Labels: platform/linux, area/rdx
