### ISSUE TITLE
Invite to Rancher slack fails with "Not a permitted channel"

### ISSUE THREAD

**Issue by oppressive** [rancher-sandbox/rancher-desktop#598] opened 2021-09-10 18:15 UTC
Attempted to join the Rancher slack using the link in the Rancher Desktop UI (v0.4.1), and using the slack icon link at https://rancher.com/contact/ to see if a issue was already discussed there. Tried with three different email addresses, and each time, when I clicked the "Get my invite" button, I got the response "Not a permitted channel".

**Comment by jandubois** [comment] 2021-09-10 18:23
Thank you! I get the same error when I try to invite a new email address; will report this internally.

**Comment by jandubois** [comment] 2021-09-10 21:14
Looks like ownership of the user-slack was recently transferred to a different group, and the invite system may have been broken by that. It has been escalated internally, but it may take until next week to get fixed.

**Comment by oppressive** [comment] 2021-09-10 21:33
No problem.  I'll hang on a bit before reporting anything. I saw a couple of similar issues in here, but they're not exactly the same thing. Plus I suspect that it's due to something missing on my end.

**Comment by jandubois** [comment] 2021-09-10 22:14
Please create a new issue if you don't think it is covered by any existing one! It is better to close it later as a duplicate than to miss it, and having to open it against the next release...

**Comment by mattfarina** [comment] 2021-09-14 18:55
This should be fixed now. If there is still an issue please let us know.

**Comment by jandubois** [comment] 2021-09-14 18:57
> This should be fixed now. If there is still an issue please let us know.

Confirmed that it works.

**Closed by jandubois** 2021-09-14 18:57 UTC
