### ISSUE TITLE
nerdctl file not found

### ISSUE THREAD

**Issue by hossko** [rancher-sandbox/rancher-desktop#2720] opened 2022-08-10 16:35 UTC
### Actual Behavior

using Rancher-Desktop for WSL2. i have tried building an image with nerdctl command line tool.
The tool itself is working just fine as i can spinup containers as expected. But once i try to build an image with Dockerfile, i get the below error about a mounting point mismatch.

WARN[0000] lstat /mnt/wslg/rancher-desktop/run/nerdctl-tmp.2012909157/input.1650504545/Dockerfile: no such file or directory, using Containerfile as fallback
FATA[0000] lstat /mnt/wslg/rancher-desktop/run/nerdctl-tmp.2012909157/input.1650504545/Containerfile: no such file or directory

### Steps to Reproduce

in a workspace contains a Dockerfile, run:
nerdctl build -t local/test .

WARN[0000] lstat /mnt/wslg/rancher-desktop/run/nerdctl-tmp.2012909157/input.1650504545/Dockerfile: no such file or directory, using Containerfile as fallback
FATA[0000] lstat /mnt/wslg/rancher-desktop/run/nerdctl-tmp.2012909157/input.1650504545/Containerfile: no such file or directory

### Result

error in mount point

### Expected Behavior

image build into the default namespace

### Rancher Desktop Version

1.5.0

### Rancher Desktop K8s Version

v1.24.3+k3s1

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

WSL2 with ubuntu 20.0

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

### Windows User Only

N/A

**Comment by mook-as** [comment] 2022-08-11 17:51
Hi! Sorry for the problem; I believe this is because we're not correctly detecting the mount prefix on Windows 11.  This appears to be the same as #1993 — please see that for details.

Closing as a duplicate of #1993.

**Closed by mook-as** 2022-08-11 17:51 UTC
Labels: kind/bug

**Comment by hossko** [comment] 2022-10-11 08:40
Hello Mark,

Sorry but I didn’t get the feedback. Is this a bug or a configuration issue that can be fixed.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jandubois** [comment] 2022-10-13 00:16
@hossko 

> Sorry but I didn’t get the feedback. Is this a bug or a configuration issue that can be fixed.

It is a bug that has not been fixed yet. There is a workaround in https://github.com/rancher-sandbox/rancher-desktop/issues/1993#issuecomment-1254296050
