### ISSUE TITLE
docker/nerdctl timeout on login/pull with version 1.1.0 on Windows

### ISSUE THREAD

**Issue by jluzio** [rancher-sandbox/rancher-desktop#1723] opened 2022-03-04 13:07 UTC
### Actual Behavior

docker/nerdctl isn't able to login or pull with any registry/repository (private or Docker Hub).
The result for docker login is a timeout, similar results for docker pull. 
Nerdctl using containerd has the same issues.

Reinstalled version 1.1.0, it had the same results.
With version 1.0.1 or 1.0.0 login/pull work perfectly, without issues.

### Steps to Reproduce

docker login <server>

### Result

Error response from daemon: Get "https://<server>/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### Expected Behavior

Successful login or pulled image

### Rancher Desktop Version

1.1.0

### Rancher Desktop K8s Version

1.2.7

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro

### What CPU architecture are you using?

x64

### Windows User Only

None

**Comment by evertonlperes** [comment] 2022-03-04 14:32
Thanks for filing this issue @jluzio 
Based on your comments, it seems to be similar to the issue #1714.
Closing this for now. Feel free to jump in on #1714 and share your thoughts.

**Closed by evertonlperes** 2022-03-04 14:32 UTC
Labels: kind/bug

**Comment by jandubois** [comment] 2022-03-05 06:19
Looks like a duplicate of #1702. Please verify that 1.1.1 has fixed your problem.

**Comment by jluzio** [comment] 2022-03-07 09:26
Problem solved! Thanks for the support
