### ISSUE TITLE
Apple Silicon build is actually Intel ?

### ISSUE THREAD

**Issue by udf2457** [rancher-sandbox/rancher-desktop#4270] opened 2023-03-24 13:19 UTC
### Actual Behavior

I downloaded `Rancher.Desktop-1.8.1.aarch64`, but the Application binary is of type `Intel` and looking in `Activity Monitor` there are lots of Rancher processes running as `Intel`.

Seems the Apple Silicon build is only partially that ?

### Steps to Reproduce

1. Download https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.8.1/Rancher.Desktop-1.8.1.aarch64.dmg
2. Do "File->Get Info" on "Rancher Desktop", note "Intel"
3. Install and run, then open "Application->Utilities->Activity Monitor", note lots of "Intel" rancher processes

### Result

As above

### Expected Behavior

1. "Rancher Desktop" application binary is of type Apple Silicon
2. "Activity Monitor" only shows Apple Silicon in relation to Rancher Desktop and its sub-processes

### Rancher Desktop Version

1.8.1

### Rancher Desktop K8s Version

1.25.7

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

OS X 13.2.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment] 2023-03-24 18:38
This is a duplicate of #1416

**Closed by jandubois** 2023-03-24 18:38 UTC
Labels: kind/bug
