### ISSUE TITLE
DNS unmarshal error when pulling from private repo with long url

### ISSUE THREAD

**Issue by kingrichard2005** [rancher-sandbox/rancher-desktop#1736] opened 2022-03-05 16:31 UTC
### Actual Behavior

Recently updated to 1.1.1 hoping it'd resolve, but still having this same issue which I was also having with 1.1.0 and commented on thru issue [893](https://github.com/rancher-sandbox/rancher-desktop/issues/893#issuecomment-1050376531)

Pulling from public repos works fine, but when I try to pull from my team's private repos over our company VPN and containing long urls, I get back `cannot unmarshal DNS message` below.  This does not happen with Docker Desktop which uses `kubernetes.docker.internal` that's mapped to my local (Windows) host in `c/Windows/System32/drivers/etc/hosts`.

`docker pull teams-docker-dev-repo.docker.artifactory.my-company.com/base/service-img:10b2d1bb`

`Error response from daemon: Get "teams-docker-dev-repo.docker.artifactory.my-company.com/v2/": dial tcp: lookup teams-docker-dev-repo.docker.artifactory.my-company.com on 172.18.71.212:53: cannot unmarshal DNS message`

Since my local Docker Desktop instance can pull the same private repo image down w/o issue while connected to the same VPN, I don't think it has anything to do with the DNS issue in the Rancher Desktop context, but added that detail in case it does for any reason(s).

### Steps to Reproduce

Try to pull an image from a long repo url, e.g. `docker pull teams-docker-dev-repo.docker.artifactory.my-company.com/base/service-img:10b2d1bb`.  This same url works w/o issue on Docker Desktop, not sure what the deltas are and why it would be able to handle the same url w/o issue

### Result

`Error response from daemon: Get "teams-docker-dev-repo.docker.artifactory.my-company.com/v2/": dial tcp: lookup teams-docker-dev-repo.docker.artifactory.my-company.com on 172.18.71.212:53: cannot unmarshal DNS message`

### Expected Behavior

I should be able to pull from both public and private docker image repos with longer urls the same way I can in my Docker Desktop context

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

1.21.9

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

 10.0.18363 Build 18363

### What CPU architecture are you using?

x64

### Windows User Only

Using Cisco AnyConnect VPN

**Comment by Nino-K** [comment] 2022-03-08 00:38
@kingrichard2005 It looks like you have a split VPN setup where all the corporate domains are going through VPN DNS server(s) and everything else (public) is going to the local DNS server in this case DNSmasq in this case. Unfortunately, this is a known issue on windows and we are actively looking at a solution for a split VPN scenario.

**Comment by kingrichard2005** [comment] 2022-03-10 22:52
> @kingrichard2005 It looks like you have a split VPN setup where all the corporate domains are going through VPN DNS server(s) and everything else (public) is going to the local DNS server in this case DNSmasq in this case. Unfortunately, this is a known issue on windows and we are actively looking at a solution for a split VPN scenario.

Thank you for the follow-up @Nino-K , glad at least it's a known issue that's being worked on.  I'd mentioned in issue [893](https://github.com/rancher-sandbox/rancher-desktop/issues/893#issuecomment-1050055294) that there was at one time (i.e circa 2016) a related [bug](https://github.com/docker/for-win/issues/249) reported for Docker Desktop which has since been resolved.  

Again I'm not sure whether or not their solution is/was proprietary, but if not maybe that's something that could be generalized and applied in Rancher Desktop.  Just suggesting since the current Docker Desktop instance I have installed has no issue referencing those same private artifactory docker img repos w/o any additional configuration other than the default installation I started with.

**Comment by AaronFriel** [comment] 2022-03-15 15:31
@Nino-K I have good news, I'd root caused this and worked with the Go team to ensure this was released & backported: https://github.com/golang/go/issues/51127

**Comment by kingrichard2005** [comment] 2022-03-16 05:11
@AaronFriel , that is great to hear and glad the issue was rooted out and identified.  Looking forward to the next Rancher Desktop release with the updated GoLang version :relaxed:

**Comment by Nino-K** [comment] 2022-03-16 19:54
@AaronFriel thanks for the heads up, we have just bumped up the go version to 1.18 as of yesterday and a new release will be out of the door soon.

**Comment by Nino-K** [comment] 2022-03-16 19:56
@kingrichard2005 I'm going to close this issue, however, feel to reopen at any time if this is not resolved by our next release. 
Thanks again for your contribution.

**Closed by Nino-K** 2022-03-16 19:56 UTC
Labels: kind/bug, area/vpn
