### ISSUE TITLE
Rancher will not update

### ISSUE THREAD

**Issue by giggio** [rancher-sandbox/rancher-desktop#1488] opened 2022-02-03 23:18 UTC
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

1.23.3 (latest)

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Microsoft Windows [Version 10.0.22000.469]

### What CPU architecture are you using?

x64

### Windows User Only

No.

### Actual Behavior

The application does not update on restart.

### Steps to Reproduce

This are the steps:

1. You see the message "An update to version v1.0.1 is available. Restart the application to apply the update."
2. You close Rancher Desktop
3. You start Rancher Desktop

### Result

The app does not update, the message is still there.

### Expected Behavior

The app is updated.

### Additional Information

~I got to workaround it by shutting down Rancher Desktop and later shutting down WSL with `wsl --shutdown` (on Windows/PowerShell). Then, after restarting it was updated.
My guess is that the WSL distro is still running, and Rancher desktop does not close it when it closes, and restarting it is not actually a full restart.~
(incorrect, see comment bellow)

**Comment by mook-as** [comment] 2022-02-03 23:30
We don't actually update the WSL distro in the app update (it gets updated next time we start the app instead), so I wouldn't expect that to be an issue.

If you could still duplicate the issue, could you turn on debug mode in the Troubleshooting tab, restart, and grab `update.log` and `backgroundl.log` in the logs directory (which can be found in the same Troubleshooting tab)?  Thanks!

**Comment by jandubois** [comment] 2022-02-03 23:35
I would bet that his is my pet-peeve with the RD UI: when you click the "close window" button (the red X in the top right hand corner), it destroys the window, but doesn't stop the app. You have to use either the "File | Exit" menu item, or the context menu from the notification bar icon to really stop the app.

So closing the window and "restarting" it is not actually restarting the app. This would be helped by #895.

**Comment by giggio** [comment] 2022-02-04 15:20
I'm closing it by right clicking the app logo in the system tray and selecting "Quit Rancher Desktop".
This time the Rancher wsl distro was shut down, so, yes, my hypothesis of that being the issue was wrong.
I installed v1.0.0 again, shut it down, and it rebooted to 1.0.1, so I can't repro it anymore. Feel free to close the issue.

**Comment by mook-as** [comment] 2022-02-04 19:11
Closing this for now, because there's nothing we can do here.  If we do get a good step of steps to reproduce, we should fix this… but we can't at the moment.

**Closed by mook-as** 2022-02-04 19:11 UTC
Labels: kind/bug

**Comment by tanob** [comment] 2022-02-07 09:49
@mook-as I have the same issue in Mac, I've already cmd-q Rancher desktop but after reopening it still displays the same message "An update to version v1.0.1 is available. Restart the application to apply the update."
