### ISSUE TITLE
Network does not include all of the aliased domains

### ISSUE THREAD

**Issue by gpechiro** [rancher-sandbox/rancher-desktop#5239] opened 2023-07-26 19:51 UTC
### Actual Behavior

When requesting a CNAME for a domain inside a container the IP is resolved properly but it does not include the domain the CNAME alias is for, the A record.

### Steps to Reproduce

Start an ubuntu docker container `docker run --rm -it --entrypoint /bin/bash ubuntu`
Install dnsutils `apt update && apt install -y dnsutils`
Run nslookup on a url with a CNAME `nslookup test.xiphoid24.com`

### Result

The proper IP address is resolved but the CNAME is returned as the Name and not an alias. The actual name (loc.xiphoid24.com) is not returned.

```
# nslookup test.xiphoid24.com
Server:         172.30.59.98
Address:        172.30.59.98#53

Non-authoritative answer:
Name:   test.xiphoid24.com
Address: 127.0.0.1
```

### Expected Behavior

The proper IP address is resolved, the A record is listed as the name and the CNAME is listed as an Alias.

```
Address:  192.168.1.1

Non-authoritative answer:
Name:    loc.xiphoid24.com
Address:  127.0.0.1
Aliases:  test.xiphoid24.com
```

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro 22H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

No

**Comment by gunamata** [comment] 2023-07-28 00:43
I could reproduce the behavior stated in the issue description. Also, when I directly run the command in Powershell on the host machine, I see the actual name (loc.xiphoid24.com) printed in the output. 

@Nino-K , Do you have any quick insights on what could be the reason `nslookup` command doesn't show the actual name from within a container?

In Powershell
```
> nslookup test.xiphoid24.com
Server:  UnKnown
Address:  fe80::d635:1dff:fead:319a

Non-authoritative answer:
Name:    loc.xiphoid24.com
Address:  127.0.0.1
Aliases:  test.xiphoid24.com
 
```

**Comment by jandubois** [comment] 2023-07-28 06:47
This looks like a bug in the Rancher Desktop host resolver.

Could you check if the bug is fixed by enabling the experimental network tunnel feature (see https://docs.rancherdesktop.io/ui/preferences/wsl/network), as that bypasses the host resolver?

**Comment by xiphoid24** [comment] 2023-07-28 11:37
@jandubois I enabled the experimental network tunnel and I am getting the same results.
![image](https://github.com/rancher-sandbox/rancher-desktop/assets/4960656/7ac6898e-f977-43b2-b161-452d337a71bc)

```
# nslookup test.xiphoid24.com
Server:         192.168.127.1
Address:        192.168.127.1#53

Non-authoritative answer:
Name:   test.xiphoid24.com
Address: 127.0.0.1
```

**Comment by gpechiro** [comment] 2023-07-28 11:39
@jandubois I enabled the experimental network tunnel and I am getting the same results.

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/137785078/22fc673a-9d64-4d0e-ac4c-a4d2f3991f32)

```
# nslookup test.xiphoid24.com
Server:         192.168.127.1
Address:        192.168.127.1#53

Non-authoritative answer:
Name:   test.xiphoid24.com
Address: 127.0.0.1
```

**Comment by Nino-K** [comment] 2023-10-10 20:44
I verified this and it looks like that's how gvisor-tap-vsock DNS library behaves. I will move this to 1.12 and will try to address it then.

**Comment by Nino-K** [comment] 2024-07-18 18:55
You have attached the output of the `nslookup` from Windows as an expected behavior. When you run the query you have attached on different platforms you'll get different output. I have also run the query on the Ubuntu distro and it looks like I get the correct output. 

Windows
```
nslookup test.xiphoid24.com
Server:  pd2nsc5.st.vc.shawcable.net
Address:  2001:4e8:0:4009::15

Non-authoritative answer:
Name:    loc.xiphoid24.com
Address:  127.0.0.1
Aliases:  test.xiphoid24.com
```
MacOS
```
nslookup test.xiphoid24.com
Server:		2001:4e8:0:4009::15
Address:	2001:4e8:0:4009::15#53

Non-authoritative answer:
test.xiphoid24.com	canonical name = loc.xiphoid24.com.
Name:	loc.xiphoid24.com
Address: 127.0.0.1
```
Ubuntu Distro on Rancher Desktop
```
nslookup test.xiphoid24.com
Server:         172.27.176.1
Address:        172.27.176.1#53

Non-authoritative answer:
test.xiphoid24.com      canonical name = loc.xiphoid24.com.
Name:   loc.xiphoid24.com
Address: 127.0.0.1
```
Furthermore, different output from nslookup on different platforms is only related to the implementation of the nslookup itself on that specific platform. 

I'm going to close this issue as it does not seem to be a real problem.

**Closed by Nino-K** 2024-07-18 18:55 UTC
Labels: kind/bug, release-note, area/networking, triage/confirmed
