### ISSUE TITLE
Option to upgrade to latest version within the app

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#372] opened 2021-06-22 16:44 UTC
May be a nice to have feature beyond 1.0.0
Feature to update the app to the latest version. There can be a button in the header that gets enabled when a latest version is available. Users just click the button to get the patch/version installed.

**Comment by jandubois** [comment] 2021-06-22 16:46
I believe this is a duplicate of #329. Please re-open with more details if it is not!

**Closed by jandubois** 2021-06-22 16:46 UTC
