### ISSUE TITLE
Unexpected timeouts pulling images through moby/containerd

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#1714] opened 2022-03-03 21:32 UTC
### Actual Behavior

Upgrading RD app from `1.0.1` to `1.1.0`, I cannot pull images through `moby and containerd`.

### Steps to Reproduce

1. Make sure you have installed RD `1.0.1`
2. Try to pull images with `moby / containerd`: e.g.: `docker pull alpine` and `nerdctl pull nginx`
3. It should pull the images properly without timeouts
4. Upgrade RD version from `1.0.1` to `1.1.0` (install 1.1.0 version on top of 1.0.1 version)
5. Wait until the app be ready to use
6. Try to pull images with `moby / containerd`: e.g.: `docker pull alpine` and `nerdctl pull nginx`
7. You should see the daemon errors related to timeouts.

### Result

Upgrade from `1.0.1` to `1.1.0`
```bash
PS C:\Users\everton.peres> nerdctl pull alpine
docker.io/library/alpine:latest: resolving      |--------------------------------------|
elapsed: 19.9s                   total:   0.0 B (0.0 B/s)
INFO[0020] trying next host                              error="failed to do request: Head \"https://registry-1.docker.io/v2/library/alpine/manifests/latest\": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:58358->[::1]:53: i/o timeout" host=registry-1.docker.io
FATA[0020] failed to resolve reference "docker.io/library/alpine:latest": failed to do request: Head "https://registry-1.docker.io/v2/library/alpine/manifests/latest": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:58358->[::1]:53: i/o timeout
PS C:\Users\everton.peres> nerdctl pull nginx
docker.io/library/nginx:latest: resolving      |--------------------------------------|
elapsed: 19.9s                  total:   0.0 B (0.0 B/s)
INFO[0020] trying next host                              error="failed to do request: Head \"https://registry-1.docker.io/v2/library/nginx/manifests/latest\": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:42512->[::1]:53: i/o timeout" host=registry-1.docker.io
FATA[0020] failed to resolve reference "docker.io/library/nginx:latest": failed to do request: Head "https://registry-1.docker.io/v2/library/nginx/manifests/latest": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:42512->[::1]:53: i/o timeout
PS C:\Users\everton.peres> docker pull alpine
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
PS C:\Users\everton.peres> docker pull ubuntu
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
PS C:\Users\everton.peres>
```

Downgrade from `1.1.0` to `1.0.1`
```bash
PS C:\Users\everton.peres> docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
59bf1c3509f3: Pull complete
Digest: sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
Status: Downloaded newer image for alpine:latest
docker.io/library/alpine:latest
PS C:\Users\everton.peres> docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
7c3b88808835: Pull complete
Digest: sha256:f454154bd8670e52ab840d7bfe26a8f9e830731c6964760c6c2cee21e8fd57d0
Status: Downloaded newer image for ubuntu:latest
docker.io/library/ubuntu:latest
PS C:\Users\everton.peres> nerdctl pull alpine
docker.io/library/alpine:latest:                                                  resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:e7d88de73db3d3fd9b2d63aa7f447a10fd0220b7cbf39803c803f2af9ba256b3: done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:c059bfaa849c4d8e4aecaeb3a10c2d9b3d85f5165c66ad3a4d937758128c4d18:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 2.8 s                                                                    total:  2.7 Mi (983.7 KiB/s)      
PS C:\Users\everton.peres> nerdctl pull ubuntu
docker.io/library/ubuntu:latest:                                                  resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:f454154bd8670e52ab840d7bfe26a8f9e830731c6964760c6c2cee21e8fd57d0:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:9c152418e380c6e6dd7e19567bb6762b67e22b1d0612e4f5074bda6e6040c64a: done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:2b4cba85892afc2ad8ce258a8e3d9daa4a1626ba380677cee93ef2338da442ab:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:7c3b88808835aa80f1ef7f03083c5ae781d0f44e644537cd72de4ce6c5e62e00:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 4.5 s                                                                    total:  27.2 M (6.1 MiB/s)        
PS C:\Users\everton.peres>
```

### Expected Behavior

Pulling images with both container runtime should work.

### Additional Information

Downgrading it from `1.1.0` to `1.0.1` seems to fix the problem.

### Rancher Desktop Version

1.1.0

### Rancher Desktop K8s Version

1.22.7

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 PRO

### What CPU architecture are you using?

x64

### Windows User Only

Azure VM instance - Dv4 machine

**Comment by christophernruud** [comment] 2022-03-04 08:19
Possible duplicate of #1702

**Comment by wertone-gh** [comment] 2022-03-04 15:36
I experience similar issues. I installed version 1.1.0 after uninstalling 1.0.1.
As a result, I cannot pull any image from any repository. Once I revert to 1.0.1 the problem no longer occurs.
The issue also does not exist once I uninstall Rancher Desktop and try the same scenario with Docker Desktop.
host.docker.internal is also not working in 1.1.0 as intended.

**Comment by jandubois** [comment] 2022-03-05 06:18
Closing as a duplicate of #1702. Please reopen if this failure still happens with Rancher Desktop 1.1.1.

**Closed by jandubois** 2022-03-05 06:18 UTC
Labels: kind/bug, platform/windows, runtime/moby, runtime/containerd
