### ISSUE TITLE
rancher-desktop 1.1.1 does not start on windows after fresh installation

### ISSUE THREAD

**Issue by waffel** [rancher-sandbox/rancher-desktop#1877] opened 2022-03-23 13:18 UTC
### Actual Behavior

Simple install rancher-desktop. The installation finished successful but after a click to launch the app, only a short DOS windows is shown and nothing more happen.

### Steps to Reproduce

Install fresh rancher-desktop without reboot and try to start.

### Result

Nothing is started.

### Expected Behavior

It will show any UI (I'm a very new user ... so no clue what should happen after first startup)

### Additional Information

I found only one log (I do not found any information how to get useful logs on windows on the website)

The background.log has following entries:

2022-03-23T13:11:31.452Z: Error starting up: <ref *1> Error: spawnSync C:\Users\me\AppData\Local\Programs\Rancher Desktop\resources\app.asar.unpacked\node_modules\win-ca\lib\roots.exe ENOBUFS
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:821:24)
    at Object.execFileSync (node:child_process:867:15)
    at Object.func [as execFileSync] (node:electron/js2c/asar_bundle:5:2027)
    at Object.run (C:\Users\me\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\win-ca\lib\fallback.js:43:26)
    at api (C:\Users\me\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\win-ca\lib\index.js:60:10)
    at C:\Users\me\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:161624
    at C:\Users\me\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:162210 {
  errno: -4060,
  code: 'ENOBUFS',
  syscall: 'spawnSync C:\\Users\\me\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\app.asar.unpacked\\node_modules\\win-ca\\lib\\roots.exe',
  path: 'C:\\Users\\me\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\app.asar.unpacked\\node_modules\\win-ca\\lib\\roots.exe',
  spawnargs: [ 'root', 'ca' ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    <Buffer 33 30 38 32 30 32 30 39 33 30 38 32 30 31 37 32 61 30 30 33 30 32 30 31 30 32 30 32 31 30 32 31 34 35 39 61 63 34 62 66 39 31 63 62 62 35 34 36 35 63 ... 1048963 more bytes>,
    <Buffer >
  ],
  pid: 13268,
  stdout: <Buffer 33 30 38 32 30 32 30 39 33 30 38 32 30 31 37 32 61 30 30 33 30 32 30 31 30 32 30 32 31 30 32 31 34 35 39 61 63 34 62 66 39 31 63 62 62 35 34 36 35 63 ... 1048963 more bytes>,
  stderr: <Buffer >
}

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

unknown

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 20H2

### What CPU architecture are you using?

x64

### Windows User Only

Yes ... running in a firm envrionment with proxy, tunnels and unknown architecture about the network.

**Comment by jandubois** [comment] 2022-03-23 16:40
This is a duplicate of #1072. It is caused by a fixed buffer size for certificates in one of our external dependencies. Sometimes deleting expired certs helps to get below that buffer size. Unfortunately there is no other workaround than deleting certs until this gets fixed.

**Closed by jandubois** 2022-03-23 16:40 UTC
Labels: kind/bug
