### ISSUE TITLE
`rancher-desktop/rdx-proxy` Image create 292 years ago

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#5360] opened 2023-08-17 17:37 UTC
It appears that the `rancher-desktop/rdx-proxy` needs to be updated with a valid created date. 

```
➤ docker images                                                                              10:23:15
REPOSITORY                                          TAG                    IMAGE ID       CREATED         SIZE

ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy   latest                 9d111955b096   292 years ago   5.1MB
```

**Comment by gaktive** [comment] 2023-08-17 17:59
Duplicate of https://github.com/rancher-sandbox/rancher-desktop/issues/5145, which is already addressed for 1.10.

**Closed** 2023-08-17 18:05 UTC
Labels: kind/bug
