### ISSUE TITLE
Images not listed when sudo access is not allowed

### ISSUE THREAD

**Issue by cdivita** [rancher-sandbox/rancher-desktop#2358] opened 2022-06-09 14:35 UTC
On Mac, when _sudo access_ is disabled, the Images are not listed in the UI.

From `images.log` it seems that Rancher Desktop is looking for `docker.sock` in the wrong location:

> `2022-06-09T14:13:37.517Z: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

On my laptop I solved the issue creating a symbolic link to `~/.rd/docker.sock` at `/var/run/docker.sock`, but maybe Rancher Desktop should take into account the _sudo access_ configuration when looking for `docker.sock`.

That's my shell profile configuration:
```
# Rancher Desktop
export PATH=${PATH}:~/.rd/bin
export DOCKER_CONTEXT=rancher-desktop
```

**Comment by jandubois** [comment] 2022-10-13 21:08
I cannot reproduce this issue with Rancher Desktop 1.6. I believe it has been fixed by #3082.

There is still a related issue though, and I've file #3156 to deal with it.

**Closed by jandubois** 2022-10-13 21:08 UTC
