### ISSUE TITLE
Rancher Desktop issue while setup kubernetes

### ISSUE THREAD

**Issue by sjkeerthi** [rancher-sandbox/rancher-desktop#784] opened 2021-10-13 07:35 UTC
I have using Rancher Desktop 0.6.0 on Fedora 34 after successful installation and when I try to setup the Kubernetes
while choose the verion 1.19.15 after download and installed I got below error.

![image](https://user-images.githubusercontent.com/4696166/137088060-613cf336-ea62-4627-8da4-70e7a9ccb78b.png)

**Comment by hojmark** [comment] 2021-12-01 19:03
I can confirm this issue. I got exactly the same message as @sjkeerthi when starting up Rancher Desktop for the first time. After a reboot everything is OK.

Fedora 35
Rancher Desktop 0.6.1
Kubernetes 1.21.6

**Comment by adamkpickering** [comment] 2022-01-17 22:54
Thanks for the bug report! Unfortunately I was unable to reproduce this issue on Fedora 35 and Rancher Desktop 0.6.1 (installed using the rpm package available from releases) using Kubernetes 1.21.6.

Either way, we no longer (at the moment) support installation of Rancher Desktop using the rpm package on Fedora and other Red Hat related distros because of the way they package QEMU. For these distros please use the AppImage. You may also find that your issues are resolved with a more recent version of Rancher Desktop.

I'm going to close this issue because the combo of rpm + Red Hat is no longer supported. I'm assuming that you installed Rancher Desktop using the rpm package. If this is not the case please comment below and we can reopen the issue.

**Closed by adamkpickering** 2022-01-17 22:54 UTC
Labels: kind/bug, platform/linux
