### ISSUE TITLE
Provide an option for not running k8s 

### ISSUE THREAD

**Issue by AlexeyRaga** [rancher-sandbox/rancher-desktop#1413] opened 2022-01-31 05:00 UTC
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Containers != Kubernetes ;)
Am option to be able to run containers locally without having k8s cluster running would be great.

### Proposed Solution

Add a checkbox in the UI to control whether to run k8s cluster or not

**Comment by jandubois** [comment] 2022-01-31 05:45
Thank you! I think this is a duplicate of #985

**Closed by jandubois** 2022-01-31 05:45 UTC
Labels: kind/enhancement
