### ISSUE TITLE
Main Window breaks by running `rdctl factory-reset --wait=false`

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3467] opened 2022-11-25 18:59 UTC
### Actual Behavior

By running `rdctl factory-reset --wait=false` from CLI, Rancher Desktop main Window is not closing up, and the UI is broken after running factory-reset. 

### Steps to Reproduce

1.Launch Rancher Desktop
2. Run `rdctl factory-reset --wait=false` from CLI 
3. Observe UI components from the main Window

### Result

This behaviour only occurs when flag `wait` is set to `false`.

Main Window stays visible on screen, with no functional UI.

### Expected Behavior

All windows from Rancher Desktop must be closed after running factory reset.

### Rancher Desktop Version

1.6.0-394-gec3b1074

### Rancher Desktop K8s Version

1.25.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by ericpromislow** [comment] 2022-11-28 20:33
I can't repro on an intel mac, the window disappears and the app shuts down almost immediately after I issue the `rdctl` command.

**Comment by ericpromislow** [comment] 2022-12-01 19:55
Duplicate of #3493

**Closed by ericpromislow** 2022-12-01 19:55 UTC
Labels: kind/bug, area/rdctl
