### ISSUE TITLE
[Node/NPM update] Node 16 LTS - NPM 8.x

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#1073] opened 2021-12-06 17:28 UTC
As we're planing to move to the nest Node LTS version (16.x) on the next release, we should bump `npm` version (8.x) either.

On the latest `npm` version, there's a new lockfile format (v2) and performing `npm install` using an old npm version, it will make many changes in the package-lock.json due a new file format.

Actions:
* Update Node version locally (16.x)
* Update NPM version locally (8.x)
* Update `readme.md`
* Update/Fix package-lock.json (if needed)

Pipelines:
* We already have a PR from a contributor https://github.com/rancher-sandbox/rancher-desktop/pull/994
* Update Cirrus CI workflow

**Comment by mook-as** [comment] 2021-12-15 19:32
Closing as dupe of #438

**Closed by mook-as** 2021-12-15 19:32 UTC
Labels: documentation, enhancement
