### ISSUE TITLE
Rancher Desktop fails to start on macOS when the home user directory name is a long email address

### ISSUE THREAD

**Issue by gcobr** [rancher-sandbox/rancher-desktop#4482] opened 2023-04-18 01:54 UTC
### Actual Behavior

Rancher desktop fails to start with error:
```
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura exited with code 1
```

### Steps to Reproduce

Install it on a system where the name of the user's home folder is a long email address. Example:
```
/Users/ausername@averylongemailaddressgoeshere.com
```

### Result

In `lima.log`:

```
2023-04-18T01:41:40.977Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8136)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  stdout: '',
  stderr: 'time="2023-04-18T11:41:40+10:00" level=info msg="Terminal is not available, proceeding without opening an editor"\n' +
    'time="2023-04-18T11:41:40+10:00" level=fatal msg="instance name \\"0\\" too long: \\"/Users/myusername@averylongdomainnamehere.com.au/Library/Application Support/rancher-desktop/lima/0/ssh.sock.1234567890123456\\" must be less than UNIX_PATH_MAX=104 characters, but is 114"\n',
  code: 1,
  command: [
    '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
    'start',
    '--tty=false',
    '/Users/myusername@averylongdomainnamehere.com.au/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
  ]
}
```

### Expected Behavior

Rancher Desktop starts normally.

### Rancher Desktop Version

1.8.1 (1.8.1)

### Rancher Desktop K8s Version

Not using

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

13.2.1 (22D68)

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment] 2023-04-18 06:22
This is a duplicate of #797.

There is a workaround in https://github.com/rancher-sandbox/rancher-desktop/issues/797#issuecomment-996510877

**Closed by jandubois** 2023-04-18 06:22 UTC
Labels: kind/bug
