### ISSUE TITLE
Don't allow scanning on nerdctl '<none>:latest' images

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#3094] opened 2022-10-05 19:44 UTC
### Problem Description

These images seem to be some kind of artefact of using containerd. Pulling in other images pulls them in as well. Trying to scan one of them gives an error message `Error trying to scan <none>:latest`.

The underlying trivy error messages report that it failed to parse the image name '<none>:latest'.

### Proposed Solution

Disable scanning of these images.

**Comment by jandubois** [comment] 2022-10-05 19:47
Duplicate of #2626

**Closed by jandubois** 2022-10-05 19:47 UTC
Labels: kind/enhancement
