### ISSUE TITLE
K3s download: use compressed airgapped image archives.

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#2633] opened 2022-07-26 18:00 UTC
### Problem Description

We currently always download the uncompressed tarball for the k3s airgap images:

https://github.com/rancher-sandbox/rancher-desktop/blob/171c29e1ddd4865fa026a237bb22dd7f219aba57/src/k8s-engine/k3sHelper.ts#L247-L258

We should use the compressed versions, as that is a significant reduction in traffic.

### Proposed Solution

Use the gzip-compressed tarball (`k3s-airgap-images-amd64.tar.gz`) where available.  Using Zstd is probably harder as I don't believe we have the appropriate decompressors available.

### Additional Information

The gzip and Zstd images are available starting with k3s 1.21.0.

**Comment by jandubois** [comment] 2022-07-26 18:12
Duplicate of #1680

**Closed by jandubois** 2022-07-26 18:12 UTC
Labels: kind/enhancement
