### ISSUE TITLE
Windows CI does a mismatch on the kubernetes config file

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#3344] opened 2022-11-04 23:00 UTC
### Actual Behavior

When the Windows Github CI starts up, it has an empty kubernetes context and can't run

### Steps to Reproduce

See Isabela :)

### Result

Kubernetes fails to start up

### Expected Behavior

It should just work ^trademark

### Additional Information

The source code is all deployed at and run from

`C:/actions-runner/_work/rancher-desktop/rancher-desktop`

and there's a pseudo-home-directory at 

`C:/Windows/ServiceProfiles/NetworkService`

Contents of `C:\Windows\ServiceProfiles\NetworkService\.kube\config`: empty default, like `contexts: []`

but all the local files are at `C:/Windows/ServiceProfiles/NetworkService/AppData/{Local,Roaming}/rancher-desktop`

However, there is another populated `.kube/config` file at `c:/Users/chivo/.kube/config` , that defines the `rancher-desktop` cluster and context, and sets current-context to `rancher-desktop`

The problem seems to be that most of the time, the home-directory is accessed at `c:/Users/chivo` and sometimes it's at 
`C:/Windows/ServiceProfiles/NetworkService/AppData/{Local,Roaming}/rancher-desktop`.

I think the github runner is using `.../NetworkService` as the home directory, but at some point we populate the `.kube/config` file in a different directory.

### Rancher Desktop Version

1.6.2

### Rancher Desktop K8s Version

1.25.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

### Windows User Only

No

**Comment by ericpromislow** [comment] 2022-11-04 23:05
Question: why are we still using our own `findHomeDir` and not the one in https://github.com/kubernetes-client/javascript ?

**Comment by jandubois** [comment] 2022-11-04 23:53
> Question: why are we still using our own `findHomeDir` and not the one in https://github.com/kubernetes-client/javascript ?

See #2527

Note: regardless of how we deal with this particular issue; we should **also** create a diagnostics that triggers when the user has `.kube/config` files in multiple locations.

**Comment by jandubois** [comment] 2022-11-04 23:57
@ericpromislow Because no good deed should go unpunished, I've now pulled #2527 into the "Next" milestone and assigned it to you. 😄

**Comment by ericpromislow** [comment] 2022-11-04 23:57
We didn't prioritize this issue because we didn't see it as a problem before.

**Comment by jandubois** [comment] 2022-11-04 23:59
@ericpromislow Please create a separate story for creating the diagnostic, with the details on what it should check for etc. That one doesn't have to go into this release, but I want to have an open issue, so we'll remember it.

**Comment by jandubois** [comment] 2022-11-05 00:02
It is not quite clear to me if this issue is just a duplicate of #2527, or if there would be something else to do as well. Feel free to close this one as a duplicate (after creating the diagnostics issue)...

**Comment by ericpromislow** [comment] 2022-11-05 00:17
I'm expecting #3344 is a symptom of #2527

**Comment by ericpromislow** [comment] 2022-11-07 17:59
Very likely that it's running as `NetworkService`

**Closed** 2022-11-09 21:45 UTC
Labels: kind/bug, platform/windows, component/ci
