### ISSUE TITLE
Error startin Kubernetes - PATH too long

### ISSUE THREAD

**Issue by foxmulder4223** [rancher-sandbox/rancher-desktop#7183] opened 2024-07-12 09:05 UTC
### Actual Behavior

After rancher is installed, right on every start the error message is thrown

`Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura exited with code 1`

### Steps to Reproduce

Install Rancher Desktop 1.14.2 aarch64
start....

### Result

Here is the log with my anonymous username:

`  '--tty=false',
    '/Users/###USERNAME####/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
  ],
  stdout: '',
  stderr: 'time="2024-07-12T10:46:37+02:00" level=info msg="Terminal is not available, proceeding without opening an editor"\n' +
    'time="2024-07-12T10:46:37+02:00" level=fatal msg="instance name \\"0\\" too long: \\"/Users/###USERNAME####/Library/Application Support/rancher-desktop/lima/0/ssh.sock.1234567890123456\\" must be less than UNIX_PATH_MAX=104 characters, but is 105"\n',
  code: 1,
  [Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura start --tty=false /Users/###USERNAME####/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
}`

### Expected Behavior

Kubernetes to start.

### Additional Information

Here is the complete lima log file:

`2024-07-12T08:46:37.368Z: > /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura list --json
time="2024-07-12T10:46:37+02:00" level=warning msg="No instance found. Run `limactl create` to create an instance."

2024-07-12T08:46:37.369Z: Administrator access disallowed, not using vde/socket_vmnet.
2024-07-12T08:46:37.474Z: > /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura list --json
time="2024-07-12T10:46:37+02:00" level=warning msg="No instance found. Run `limactl create` to create an instance."

2024-07-12T08:46:37.475Z: Administrator access disallowed, not using vde/socket_vmnet.
2024-07-12T08:46:37.550Z: > /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura list --json
time="2024-07-12T10:46:37+02:00" level=warning msg="No instance found. Run `limactl create` to create an instance."

2024-07-12T08:46:37.564Z: > limactl start --tty=false /Users/#####USERNAME#####/Library/Application Support/rancher-desktop/lima/_config/0.yaml
$ c [Error]: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:2:156858)
    at ChildProcess.emit (node:events:513:28)
    at Process.onexit (node:internal/child_process:291:12) {
  command: [
    '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
    'start',
    '--tty=false',
    '/Users/#####USERNAME#####/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
  ],
  stdout: '',
  stderr: 'time="2024-07-12T10:46:37+02:00" level=info msg="Terminal is not available, proceeding without opening an editor"\n' +
    'time="2024-07-12T10:46:37+02:00" level=fatal msg="instance name \\"0\\" too long: \\"/Users/#####USERNAME#####/Library/Application Support/rancher-desktop/lima/0/ssh.sock.1234567890123456\\" must be less than UNIX_PATH_MAX=104 characters, but is 105"\n',
  code: 1,
  [Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura start --tty=false /Users/#####USERNAME#####/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
}
2024-07-12T08:46:37.565Z: Error starting lima: c [Error]: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:2:156858)
    at ChildProcess.emit (node:events:513:28)
    at Process.onexit (node:internal/child_process:291:12) {
  command: [
    '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
    'start',
    '--tty=false',
    '/Users/#####USERNAME#####/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
  ],
  stdout: '',
  stderr: 'time="2024-07-12T10:46:37+02:00" level=info msg="Terminal is not available, proceeding without opening an editor"\n' +
    'time="2024-07-12T10:46:37+02:00" level=fatal msg="instance name \\"0\\" too long: \\"/Users/#####USERNAME#####/Library/Application Support/rancher-desktop/lima/0/ssh.sock.1234567890123456\\" must be less than UNIX_PATH_MAX=104 characters, but is 105"\n',
  code: 1,
  [Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura start --tty=false /Users/#####USERNAME#####/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
}
`

### Rancher Desktop Version

1.14.2

### Rancher Desktop K8s Version

1.29.6

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Sonoma 14.5 

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by kentarohorie** [comment] 2024-08-14 00:06
I'm encountering the same issue👀

**Comment by kentarohorie** [comment] 2024-08-14 03:01
I encountered the same issue.
I fixed by this flow.

1. Downgrade to 1.13.1(from 115.1)
2. run this commands https://github.com/rancher-sandbox/rancher-desktop/issues/797#issuecomment-996510877
3. restart rancher desktop

**Comment by mook-as** [comment] 2024-08-14 16:54
The downgrade should not be necessary (just doing the symlink as described by https://github.com/rancher-sandbox/rancher-desktop/issues/797#issuecomment-996510877 should be enough).

Closing this issue as it's a duplicate of #797, where we'll track the work.

**Closed by mook-as** 2024-08-14 16:54 UTC
Labels: kind/bug
