### ISSUE TITLE
Wrong and missing features in documentation of Preferences > Application

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4014] opened 2023-02-22 17:31 UTC
### Actual Behavior

By clicking the question mark button in Preferences > Application, user is redirected to a docs.io page where there is the following mismatched information:
- macOS and Linux:
Administrative Access, Automatic Updates and Statistics are currently under Application > General, not Application > Behaviour
Wrong screenshots showing only 2 out of the 3 tabs under application. General tab is missing.
Missing options of Application > Behaviour, that is, Startup, Background and Notification Icon

-windows:

### Steps to Reproduce

Launch Application UI, go to Preferences > Application
Click the question mark button 
Check the information under docs.rancherdesktop.io

### Result

Links contains wrong and missing information 

### Expected Behavior

Documentation must reflect the application's current stage

### Rancher Desktop Version

1.7.0-400-gcad1ad97

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by torchiaf** [comment] 2023-02-22 17:40
We still have to align the documentation for the new Application tab: https://github.com/rancher-sandbox/rancher-desktop/issues/3775

**Comment by gaktive** [comment] 2023-02-27 23:09
Marking as a duplicate of #3775. Closing this.

**Closed by gaktive** 2023-02-27 23:09 UTC
Labels: kind/bug, kind/documentation-ready
