### ISSUE TITLE
Dashboard conflict Logitech Ghub on 9080

### ISSUE THREAD

**Issue by ChameleonRed** [rancher-sandbox/rancher-desktop#2585] opened 2022-07-20 19:28 UTC
### Actual Behavior

Rancher Desktop not starting 404 error on page.

### Steps to Reproduce

Create service listening on 9080.

### Result

Impossible to use.

### Expected Behavior

Problem should be reported and port should configurable.

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

latest

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

10

### What CPU architecture are you using?

x64

### Windows User Only

Not.

**Comment by adamkpickering** [comment] 2022-07-22 16:41
Can you please provide more details? I am confused as to whether the problem is due to RD not starting, RD producing a 404 itself, a service you are running on RD producing a 404, or a service you are running on RD being impossible to reach. Also, what does Logitech G Hub have to do with this?

**Comment by jandubois** [comment] 2022-07-22 23:00
@adamkpickering This is a port conflict, both G Hub and Steve (a dashboard component) use port 9080.

This issue is a duplicate of #1890.

**Closed by jandubois** 2022-07-22 23:00 UTC
Labels: kind/bug, platform/windows

**Comment by televi** [comment] 2022-08-22 18:50
In case someone finds this, as a workaround on Mac OS Monterey, I was able to start RD first, then start Ghub.  Ghub will pick a different port if it finds 9080 already in use (for me, it picked 9081).  I don't have a Windows box to try this on but I would hope that part of the code is common.

Similar comment added to #1880 to maybe help others with the same issue I have.
