### ISSUE TITLE
ERR_UPDATER_ASSET_NOT_FOUND - Rancher Desktop won't start

### ISSUE THREAD

**Issue by mklueh** [rancher-sandbox/rancher-desktop#5338] opened 2023-08-14 11:53 UTC
### Actual Behavior

Freshly installed Rancher Desktop won't start

### Steps to Reproduce

Inside VMWare Windows 11 install Rancher Desktop and start. WSL2 enabled and in use with Docker Desktop

### Result

```
2023-08-14T11:43:41.683Z: Stopping background process Win32 socket proxy.
2023-08-14T11:43:41.689Z: mainEvents settings-update: {"version":4,"application":{"adminAccess":false,"debug":false,"extensions":{"allowed":{"enabled":false,"list":[]}},"pathManagementStrategy":"manual","telemetry":{"enabled":true},"updater":{"enabled":true},"autoStart":false,"startInBackground":false,"hideNotificationIcon":false,"window":{"quitOnClose":false}},"containerEngine":{"allowedImages":{"enabled":false,"patterns":[]},"name":"moby"},"virtualMachine":{"memoryInGB":2,"numberCPUs":2,"hostResolver":true},"WSL":{"integrations":{}},"kubernetes":{"version":"","port":6443,"enabled":true,"options":{"traefik":true,"flannel":true},"ingress":{"localhostOnly":false},"memoryInGB":2,"numberCPUs":2,"containerEngine":"containerd","checkForExistingKimBuilder":false,"WSLIntegrations":{},"suppressSudo":false,"hostResolver":true},"portForwarding":{"includeKubernetesServices":false},"images":{"showAll":true,"namespace":"k8s.io"},"diagnostics":{"showMuted":false,"mutedChecks":{}},"extensions":{},"experimental":{"virtualMachine":{"type":"qemu","useRosetta":false,"socketVMNet":false,"mount":{"type":"reverse-sshfs","9p":{"securityModel":"none","protocolVersion":"9p2000.L","msizeInKib":128,"cacheMode":"mmap"}},"networkingTunnel":false,"proxy":{"enabled":false,"address":"","password":"","port":3128,"username":""}}},"telemetry":true,"updater":true,"debug":false,"pathManagementStrategy":"notset"}
2023-08-14T11:43:41.755Z: Stopping background process Win32 socket proxy.
2023-08-14T11:43:42.421Z: UnhandledRejectionWarning: Error: Could not find suitable assets in release Rancher Desktop 1.9.1
    at t.newError (C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:1:16614)
    at ai.checkForUpdates (C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:46521)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ai.getLatestVersion (C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:47174)
    at async NsisUpdater.getUpdateInfoAndProvider (C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:305:19)
    at async NsisUpdater.doCheckForUpdates (C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:319:24)
    at async gi (C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:50563) {
  code: 'ERR_UPDATER_ASSET_NOT_FOUND'
}
2023-08-14T11:43:42.754Z: UnhandledRejectionWarning: Error: C:\WINDOWS\system32\wsl.exe exited with code 1
    at ChildProcess.<anonymous> (C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:17:142946)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  stdout: '',
  code: 1,
  command: [
    'C:\\WINDOWS\\system32\\wsl.exe',
    '--distribution',
    'Ubuntu-20.04',
    '--exec',
    '/bin/wslpath',
    '-a',
    '-u',
    'C:\\Users\\myuser\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\resources\\linux\\bin\\docker-compose'
  ]
}
2023-08-14T11:43:42.766Z: Error starting up: Error: C:\WINDOWS\system32\wsl.exe exited with code 1
    at ChildProcess.<anonymous> (C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:17:142946)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  stdout: '',
  code: 1,
  command: [
    'C:\\WINDOWS\\system32\\wsl.exe',
    '--distribution',
    'Ubuntu-20.04',
    '--exec',
    '/bin/wslpath',
    '-a',
    '-u',
    'C:\\Users\\myuser\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\resources\\linux\\bin\\docker-compose'
  ]
}

```

### Expected Behavior

To launch UI

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

1.9.1

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Enterprise 10.0.22000 Build 22000

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by adamkpickering** [comment] 2023-08-14 22:12
So when Rancher Desktop starts up, one of the things it does is check for updates. It seems that your installation is erroring out on this step. Specifically, it is not finding a specific asset it looks for in the [latest github release](https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v1.9.1). This is strange, because all it does it look for an asset ending with `.msi`, and such an asset exists in the release.

Have you tried:
- running RD multiple times?
- doing a factory reset?
- reinstalling?

**Comment by mklueh** [comment] 2023-08-15 11:15
Thanks. I've reinstalled it, and now I'm getting

```
2023-08-15T11:13:46.143Z: Stopping background process Win32 socket proxy (pid <none>).
2023-08-15T11:13:46.919Z: Error starting up: c [Error]: C:\WINDOWS\system32\wsl.exe exited with code 1
    at ChildProcess.<anonymous> (C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:1:15549)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  command: [
    'C:\\WINDOWS\\system32\\wsl.exe',
    '--distribution',
    'Ubuntu-20.04',
    '--exec',
    '/bin/wslpath',
    '-a',
    '-u',
    'C:\\Users\\myuser\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\resources\\linux\\bin\\docker-buildx'
  ],
  stdout: '',
  code: 1,
  [Symbol(child-process.command)]: 'C:\\WINDOWS\\system32\\wsl.exe --distribution Ubuntu-20.04 --exec /bin/wslpath -a -u C:\\Users\\myuser\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\resources\\linux\\bin\\docker-buildx'
}

```

**Comment by adamkpickering** [comment] 2023-08-15 19:55
I'm puzzled. It isn't typical to run RD in a Windows VM, so maybe that is the source of the problem? It seems like things are failing randomly.

Do you have some kind of security software installed on your machine that may be messing with RD? Sometimes this sort of thing happens with macOS and jamf.

If none of that helps: can you enable debug mode, reproduce the problem, and post the resultant logs here? There may be clues there.

**Comment by adamkpickering** [comment] 2023-08-18 20:55
@mklueh were you able to get it working?

**Comment by mklueh** [comment] 2023-08-19 06:12
@adamkpickering haven't had the time to try again. 

I have no problems running Docker Desktop and manually logging into WSL, however, so I'm wondering what's so special about RD that might be the issue. 


I've tried to run this command manually, and as far as I remember it did not work. The distribution is correct, as for the other arguments I do not know. Have to check next week
> 'C:\\WINDOWS\\system32\\wsl.exe --distribution Ubuntu-20.04 --exec /bin/wslpath -a -u C:\\Users\\myuser\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\resources\\linux\\bin\\docker-buildx


The normal Windows Defender is used, nothing special.

**Comment by adamkpickering** [comment] 2023-08-29 20:36
I'm going to close this issue for now since we haven't made any progress. Please comment again if you are able to get it working, or have some time to work on it with us :smile:

**Closed by adamkpickering** 2023-08-29 20:36 UTC
Labels: kind/bug
