### ISSUE TITLE
Allow to select the distro-data location on Windows

### ISSUE THREAD

**Issue by afrancoc2000** [rancher-sandbox/rancher-desktop#2194] opened 2022-05-09 18:00 UTC
### Problem Description

My problem is that Rancher Desktop creates a 50GB virtual machine in the C drive, and as C gets full easily I would like to move the distro-data to the D drive.

### Proposed Solution

Allow to select the distro data location on installation

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

**Comment by jandubois** [comment] 2022-05-09 20:56
This is a duplicate of #369

**Closed by jandubois** 2022-05-09 20:56 UTC
Labels: kind/enhancement

**Comment by mook-as** [comment] 2022-05-09 21:24
Note that, independent of us fixing this (which we should), you may want to consider moving local appdata away from small disks in general. (Of course, that was more meant for roaming profiles on SMB shares, where the local appdata is _not_ on a share, but this maps well to small disks in modern times.)

**Comment by afrancoc2000** [comment] 2022-05-11 17:02
ok, thank you
