### ISSUE TITLE
docker stats stops retrieving information

### ISSUE THREAD

**Issue by gpechiro** [rancher-sandbox/rancher-desktop#5246] opened 2023-07-28 12:52 UTC
### Actual Behavior

Running `docker stats` returns `0`s for all information.

### Steps to Reproduce

- Run `docker stats`
- See if it returns all `0`s or actual resource consumption.

### Result

`0`s are returned instead of consumed resources

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/137785078/a2ab2933-625d-452a-9c59-fe8cdc9b6ecf)

### Expected Behavior

Actual consumed resources for the running containers should be returned.

![be851129-76bb-4028-b11a-00a1009f10dc](https://github.com/rancher-sandbox/rancher-desktop/assets/137785078/564f3b3b-9e27-4e5d-8d6d-550a8372e33d)

### Additional Information

This seems to be an inconsistent issue. I am unable to determine any patterns right now. We are in the process of replacing Docker Desktop with Rancher Desktop. There are 8 developers who have made the transition. Of those 8, 3 of them are seeing this issue. It is also persisting after a full system restart.

I found some information on this issue when running docker natively on Linux. I could not find any real issue based on those results but I am also hesitant to modify anything in the `rancher-desktop`  wsl distribution.

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro 22H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

**Comment by gunamata** [comment] 2023-07-28 17:04
duplicate of #5241

**Closed by gunamata** 2023-07-28 17:04 UTC
Labels: kind/bug
