### ISSUE TITLE
Blank preferences windows

### ISSUE THREAD

**Issue by Nino-K** [rancher-sandbox/rancher-desktop#3500] opened 2022-11-30 19:40 UTC
After installing the latest [CI Build](https://github.com/rancher-sandbox/rancher-desktop/issues/3500) on windows 10 I encountered that the preferences for windows are not loading and rather display a blank window. The issue also persisted after restarting Rancher Desktop.

![Screen Shot 2022-11-30 at 10 15 13 AM](https://user-images.githubusercontent.com/10409174/204892642-cd5e04e5-04a4-4bc3-8d28-84052b605c25.png)

**Comment by Nino-K** [comment] 2022-11-30 19:43
Furthermore, I encountered that the issue persisted after restarting Rancher Desktop. Also, as per our offline discussion during the standup, other users may have potentially seen this behavior on macOS.

**Comment by gaktive** [comment] 2022-11-30 19:46
Logs would help here. @rak-phillip to try repro but we're seeing across macos and Windows

**Comment by rak-phillip** [comment] 2022-11-30 20:41
Able to reproduce on Windows 10 Pro using https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3580187427

**Comment by rak-phillip** [comment] 2022-11-30 21:16
Unable to repro with build from yesterday, this is a recent regression

https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3575881586

**Comment by rak-phillip** [comment] 2022-11-30 21:47
Looks like this was introduced in 

- https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3578237270
- https://github.com/rancher-sandbox/rancher-desktop/pull/3484

**Comment by IsaSih** [comment] 2022-11-30 22:13
Was able to repro on windows 11. Tested in a signed CI build (1.6.0-448-g00891346). The window is in blank even after closing the window and relaunching it. I am submitting all logs as well as a screenshot

**Closed** 2022-12-01 23:06 UTC
Labels: kind/bug
