### ISSUE TITLE
AUR/Appimage build of Rancher Desktop crashes on k3s installation

### ISSUE THREAD

**Issue by EmmettPostill** [rancher-sandbox/rancher-desktop#2238] opened 2022-05-18 23:13 UTC
### Actual Behavior

When booting rancher desktop from the aur, it crashes when installing k3s with the message:

`Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 255`

the land command is ran was:

`/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl copy /tmp/rd-k3s-install-cq12RC/install-k3s 0:bin/install-k3s`

the logfile given is
```
 * /var/log/containerd.log: creating file
 * Starting Container Daemon ... [ ok ]
/usr/bin/scp: Connection closed
2022-05-18T23:09:13.992Z: + limactl copy /tmp/rd-k3s-install-cq12RC/install-k3s 0:bin/install-k3s
2022-05-18T23:09:13.992Z: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 255
2022-05-18T23:09:13.992Z: Error starting lima: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 255
    at ChildProcess.<anonymous> (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:17:141690)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

### Steps to Reproduce

open AUR and build rancher desktop 1.3.0-1
open the app

### Result

Kubernetes Error

### Expected Behavior

k3s is installed and runs on startup

### Additional Information

This is off of a fresh install of manjaro. So I don't have many packages installed, however if there are any missing dependencies they should be noted.

### Rancher Desktop Version

1.3.0 - linux x64

### Rancher Desktop K8s Version

1.23.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Manjaro 21.2.6 GNOME

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

AUR and AppImage

**Comment by rak-phillip** [comment] 2022-05-19 14:33
@EmmettPostill thanks for raising the issue 😁

This one sounds similar to #1856 & #2139.. @adamkpickering what do you think?

**Comment by EmmettPostill** [comment] 2022-05-19 14:44
Ah I missed those other threads, I tried the fix listed in #2139 and it's working for me now :)

> Created the following file here: ~/.local/share/rancher-desktop/lima/_config/override.yaml
> 
> provision:
> - mode: system
>   script: |
>     #!/bin/sh
>     apk add --no-cache openssh-sftp-server
> If that also fixes it for you, guess they should include that package.

**Comment by rak-phillip** [comment] 2022-05-19 17:25
Excellent, I'm glad to hear there's a solution to keep you moving along! 

I'm going to close this as a duplicate of #2139.

**Closed by rak-phillip** 2022-05-19 17:25 UTC
Labels: kind/bug, platform/linux

**Comment by alisianoi** [comment] 2022-05-20 12:49
Thank you, helped me on ArchLinux, originally had same problem on start with the AUR package:

`rancher-desktop 1.3.0-1`
