### ISSUE TITLE
Can't start Kubernetes after upgrade to 1.3.0

### ISSUE THREAD

**Issue by christopher-cudennec** [rancher-sandbox/rancher-desktop#2134] opened 2022-04-29 07:41 UTC
### Actual Behavior

Rancher could not start Kubernetes anymore. I get a "Kubernetes Error" instead.

### Steps to Reproduce

Just starting Rancher Desktop.

### Result

Error Starting Kubernetes
```
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
```

Last command run:
```
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl shell --workdir=. 0 sudo bin/install-k3s v1.22.7+k3s1 /Users/christophercudennec/Library/Caches/rancher-desktop/k3s
```

Context:
```
Installing k3s
```

Some recent logfile lines:
```
* /var/log/docker.log: correcting owner
 * Starting Docker Daemon ... [ ok ]
Directory /Users/christophercudennec/Library/Caches/rancher-desktop/k3s/v1.22.7+k3s1 does not exist
2022-04-29T07:31:55.861Z: + limactl shell --workdir=. 0 sudo bin/install-k3s v1.22.7+k3s1 /Users/christophercudennec/Library/Caches/rancher-desktop/k3s
2022-04-29T07:31:55.862Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-04-29T07:31:55.864Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:17:141690)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

### Expected Behavior

Kubernetes should startup.

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

v1.22.7

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by jandubois** [comment] 2022-04-29 16:07
Is this using the `9p` mount option?

**Comment by christopher-cudennec** [comment] 2022-05-02 05:19
No, I don't think that I use `9p` mount option or any `override.yaml` at all. I did not change the configuration. Can you point me to some documentation about it?

**Comment by dgiebert** [comment] 2022-05-02 08:08
I have a similar issue on Arch while trying to bump the AUR package

```
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 11
/usr/bin/scp: Connection closed
2022-05-02T07:53:56.091Z: + limactl --debug copy /tmp/rd-k3s-install-NMxTzE/install-k3s 0:bin/install-k3s
2022-05-02T07:53:56.091Z: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 255
2022-05-02T07:53:56.092Z: Error starting lima: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 255
    at ChildProcess.<anonymous> (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:17:141690)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

Checking the lima.log in debug mode it tells me:
```
Executing: program /usr/bin/ssh host 127.0.0.1, user dgiebert, command sftp
OpenSSH_9.0p1, OpenSSL 1.1.1n  15 Mar 2022
debug1: Reading configuration data /dev/null
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 11
/usr/bin/scp: Connection closed
```
The executed scp command is right above the error and on manual execution fails as well

Seems like sftp is missing in the VM, so I installed `openssh-sftp-server` and restarted the VM, which makes the scp command succeed.

**Comment by jandubois** [comment] 2022-05-10 22:35
@christopher-cudennec I have no idea what can be causing this error (if you are not using `9p`, which is **very** experimental and not recommended):

```
Directory /Users/christophercudennec/Library/Caches/rancher-desktop/k3s/v1.22.7+k3s1
```

Can you check on your host if the directory exists there?

If it does, can you see if you can get a shell inside the VM (start RD and leave it hanging at the error dialog):

```console
$ rdctl shell mount | grep /Users
:/Users/jan/Library/Caches/rancher-desktop/k3s on /Users/jan/Library/Caches/rancher-desktop/k3s type fuse.sshfs (ro,nosuid,nodev,relatime,user_id=501,group_id=1000,allow_other)
:/Users/jan on /Users/jan type fuse.sshfs (rw,nosuid,nodev,relatime,user_id=501,group_id=1000,allow_other)
$ rdctl shell ls -l $HOME
[...]
```

Do you get both mount points and can you see the content of the home directory?

**Comment by jandubois** [comment] 2022-05-10 22:38
@dee-kryvenko You put a 👍 reaction on this issue; do you have any further information that would help to repro it?

**Comment by dee-kryvenko** [comment] 2022-05-10 22:52
Hey @jandubois - mine was definitely related to 9p, and after applying a workaround you provided in Slack - it went away. I am not able to reproduce it without 9p.

**Comment by jandubois** [comment] 2022-05-10 22:55
> mine was definitely related to 9p, and after applying a workaround you provided in Slack - it went away. I am not able to reproduce it without 9p.

Yeah, that's why I asked about `9p`. I've seen this issue too when enabling `9p` by itself without fixing the mounts.

I've not see this reported by anybody else, so unless @christopher-cudennec can provide more details, I would have to close this as non-reproducible.

**Comment by christopher-cudennec** [comment] 2022-05-11 05:13
Hi @jandubois !

> Can you check on your host if the directory exists there?

Yes, the directory exists:
```
$ ls /Users/christophercudennec/Library/Caches/rancher-desktop/k3s/v1.22.7+k3s1
k3s-airgap-images-arm64.tar k3s-arm64                   sha256sum-arm64.txt
```

> If it does, can you see if you can get a shell inside the VM (start RD and leave it hanging at the error dialog):

Executing `rdctl shell mount | grep /Users` shows me nothing.

"Some recent logfile lines" still shows:
```
* /var/log/docker.log: correcting owner
 * Starting Docker Daemon ... [ ok ]
Directory /Users/christophercudennec/Library/Caches/rancher-desktop/k3s/v1.22.7+k3s1 does not exist
2022-05-11T05:08:35.112Z: + limactl shell --workdir=. 0 sudo bin/install-k3s v1.22.7+k3s1 /Users/christophercudennec/Library/Caches/rancher-desktop/k3s
2022-05-11T05:08:35.113Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-05-11T05:08:35.115Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:17:141690)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

**Comment by jandubois** [comment] 2022-05-11 05:50
@christopher-cudennec Something is going wrong with the mounting into the VM.

Could you attach the following 2 log files:

```
~/Library/Logs/rancher-desktop/lima.log
~/Library/Logs/rancher-desktop/lima.ha.stderr.log
```

plus the cloud-init log file from inside the VM:

```
rdctl shell cat /var/log/cloud-init-output.log > cloud-init-output.log
```

**Comment by christopher-cudennec** [comment] 2022-05-11 05:56
[lima.log](https://github.com/rancher-sandbox/rancher-desktop/files/8667114/lima.log)
[lima.ha.stderr.log](https://github.com/rancher-sandbox/rancher-desktop/files/8667115/lima.ha.stderr.log)
[cloud-init-output.log](https://github.com/rancher-sandbox/rancher-desktop/files/8667127/cloud-init-output.log)

Thanks for diving into the details! 🌻

**Comment by jandubois** [comment] 2022-05-11 06:27
There seems to be something wrong with the `/etc/fuse.conf` file inside your VM.

Can you show a dump of the file, e.g.

```console
$ rdctl shell hexdump -C /etc/fuse.conf
00000000  23 20 53 65 74 20 74 68  65 20 6d 61 78 69 6d 75  |# Set the maximu|
00000010  6d 20 6e 75 6d 62 65 72  20 6f 66 20 46 55 53 45  |m number of FUSE|
00000020  20 6d 6f 75 6e 74 73 20  61 6c 6c 6f 77 65 64 20  | mounts allowed |
00000030  74 6f 20 6e 6f 6e 2d 72  6f 6f 74 20 75 73 65 72  |to non-root user|
00000040  73 2e 0a 23 20 54 68 65  20 64 65 66 61 75 6c 74  |s..# The default|
00000050  20 69 73 20 31 30 30 30  2e 0a 23 0a 23 6d 6f 75  | is 1000..#.#mou|
00000060  6e 74 5f 6d 61 78 20 3d  20 31 30 30 30 0a 0a 23  |nt_max = 1000..#|
00000070  20 41 6c 6c 6f 77 20 6e  6f 6e 2d 72 6f 6f 74 20  | Allow non-root |
00000080  75 73 65 72 73 20 74 6f  20 73 70 65 63 69 66 79  |users to specify|
00000090  20 74 68 65 20 27 61 6c  6c 6f 77 5f 6f 74 68 65  | the 'allow_othe|
000000a0  72 27 20 6f 72 20 27 61  6c 6c 6f 77 5f 72 6f 6f  |r' or 'allow_roo|
000000b0  74 27 0a 23 20 6d 6f 75  6e 74 20 6f 70 74 69 6f  |t'.# mount optio|
000000c0  6e 73 2e 0a 23 0a 23 75  73 65 72 5f 61 6c 6c 6f  |ns..#.#user_allo|
000000d0  77 5f 6f 74 68 65 72 0a  75 73 65 72 5f 61 6c 6c  |w_other.user_all|
000000e0  6f 77 5f 6f 74 68 65 72  0a                       |ow_other.|
000000e9
```

**Comment by christopher-cudennec** [comment] 2022-05-11 13:26
Sure:
```
00000000  23 20 53 65 74 20 74 68  65 20 6d 61 78 69 6d 75  |# Set the maximu|
00000010  6d 20 6e 75 6d 62 65 72  20 6f 66 20 46 55 53 45  |m number of FUSE|
00000020  20 6d 6f 75 6e 74 73 20  61 6c 6c 6f 77 65 64 20  | mounts allowed |
00000030  74 6f 20 6e 6f 6e 2d 72  6f 6f 74 20 75 73 65 72  |to non-root user|
00000040  73 2e 0a 23 20 54 68 65  20 64 65 66 61 75 6c 74  |s..# The default|
00000050  20 69 73 20 31 30 30 30  2e 0a 23 0a 23 6d 6f 75  | is 1000..#.#mou|
00000060  6e 74 5f 6d 61 78 20 3d  20 31 30 30 30 0a 0a 23  |nt_max = 1000..#|
00000070  20 41 6c 6c 6f 77 20 6e  6f 6e 2d 72 6f 6f 74 20  | Allow non-root |
00000080  75 73 65 72 73 20 74 6f  20 73 70 65 63 69 66 79  |users to specify|
00000090  20 74 68 65 20 27 61 6c  6c 6f 77 5f 6f 74 68 65  | the 'allow_othe|
000000a0  72 27 20 6f 72 20 27 61  6c 6c 6f 77 5f 72 6f 6f  |r' or 'allow_roo|
000000b0  74 27 0a 23 20 6d 6f 75  6e 74 20 6f 70 74 69 6f  |t'.# mount optio|
000000c0  6e 73 2e 0a 23 0a 23 75  73 65 72 5f 61 6c 6c 6f  |ns..#.#user_allo|
000000d0  77 5f 6f 74 68 65 72 0a  00 00 00 00 00 00 00 00  |w_other.........|
000000e0  00 00 00 00 00 00 00 00  00 75 73 65 72 5f 61 6c  |.........user_al|
000000f0  6c 6f 77 5f 6f 74 68 65  72 0a                    |low_other.|
000000fa
```

I can see some additional zeros.... 🤔

**Comment by jandubois** [comment] 2022-05-11 17:47
> I can see some additional zeros...

I have no idea where they would come from. This should be fixed by a "Factory Reset", but if you want to keep the content of the current VM, then you should be able remove the stray NUL bytes with this command:

```console
rdctl shell sh -c 'tr -d \\0 < /etc/fuse.conf > /tmp/fuse.conf; sudo mv -f /tmp/fuse.conf /etc/'
```

Then restart Rancher Desktop and it should work again.

I would really like to understand how you got into this situation, but since this is the only report of this issue (that is not related with `9p` which has a totally different root cause), I don't think there is any way to figure it out.

**Comment by jandubois** [comment] 2022-05-11 21:22
> since this is the only report of this issue

I've decided to close this issue. I have no idea how your VM got into this state, but I don't see anything we can do to figure this out. I assume the command in the previous comment is fixing things for you.

**Closed by jandubois** 2022-05-11 21:22 UTC
Labels: kind/bug, triage/needs-information, platform/macos

**Comment by christopher-cudennec** [comment] 2022-05-12 05:14
Hi @jandubois !

Thanks a lot for debugging! 🌻 
"Factory reset" indeed helped! I'm pretty sure that I tried re-installing with `brew`. Seems like that did not clean up enough files to have the same effect.

Cheers,

Christopher
