### ISSUE TITLE
Test Plan 1.4: OpenSUSE: Test #11 - failed to helm-install rancher 2.6

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#2275] opened 2022-05-26 19:57 UTC
### Actual Behavior

Ran the following code:
```### Linux ONLY
$ sudo sysctl -w net.ipv4.ip_unprivileged_port_start=443
###
 
helm repo add cert-manager https://charts.jetstack.io
 
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
 
helm upgrade --install cert-manager --namespace cert-manager cert-manager/cert-manager --set installCRDs=true --set "extraArgs[0]=--enable-certificate-owner-ref=true" --create-namespace
 
kubectl get pods --namespace cert-manager
 
helm upgrade --install rancher rancher-latest/rancher   --namespace cattle-system --set hostname=localhost --wait --timeout=10m --create-namespace
#	Should be able to access Rancher UI at https://localhost
```

Got the following error message on the final command (`helm upgrade --install rancher rancher-latest/rancher  ..`):

```
Error: Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.43.211.247:443: connect: connection refused
```

### Steps to Reproduce

See above

### Result

See above

### Expected Behavior

See above

### Rancher Desktop Version

1.3.0-298-c1ed19db

### Rancher Desktop K8s Version

1.22.9

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

OpenSUSE Leap 15

### What CPU architecture are you using?

x64

**Comment by adamkpickering** [comment] 2022-05-27 18:11
Possible duplicate of #1862.

**Comment by dpmerrill** [comment] 2022-10-14 18:35
Closing as a duplicate of #1862

**Closed by dpmerrill** 2022-10-14 18:35 UTC
Labels: kind/bug, platform/linux
