### ISSUE TITLE
Pods Logs and Shell Access Unavailable Until Dashboard is Reopened After Deployment in Rancher Desktop v1.16

### ISSUE THREAD

**Issue by kkurt** [rancher-sandbox/rancher-desktop#7555] opened 2024-09-27 08:05 UTC
### Actual Behavior

When a new pod is created after a deployment in Rancher Desktop v1.16, I am unable to access the pod logs or open a shell from the Rancher Cluster Dashboard. The logs do not load, and the shell fails to open. However, if I close the dashboard and then reopen it, I am able to access both the logs and the shell without any issues.

This issue was also present in previous versions of Rancher Desktop and persists in v1.16. Our team is facing the same problem across multiple environments, all running on different Windows 11 platforms. The behavior is consistent, regardless of the specific workload or deployment.

### Steps to Reproduce

1. Open Rancher Desktop v1.16 and navigate to the Rancher Cluster Dashboard.
2. Deploy a new application that creates a pod.
3. Once the pod is running, try accessing the pod’s logs or opening a shell from the dashboard.
4. Observe that the logs do not load and the shell does not open.
5. Close the Rancher Cluster Dashboard.
6. Reopen the Rancher Cluster Dashboard.
7. Now, attempt to access the logs or open a shell for the same pod. Observe that the logs and shell access work as expected after reopening the dashboard.

### Result

When attempting to access the logs or open a shell for a new pod immediately after deployment, the following behaviors are observed:

- Logs: The log window opens, but no log data is displayed. It remains blank, with no indication of an error.

- Shell Access: Clicking to open a shell does not open the terminal window, or it opens and immediately closes without providing access.

No explicit error messages appear in the UI, and the logs/shell remain inaccessible until the Rancher Cluster Dashboard is closed and reopened. After reopening the dashboard, both the logs and shell become accessible and function correctly.

### Expected Behavior

After deploying a new application and creating pods in Rancher Desktop v1.16, I should be able to access the logs and open a shell for the pod directly from the Rancher Cluster Dashboard without needing to close and reopen the dashboard. The logs should load automatically, and the shell access should open seamlessly on the first attempt.

### Additional Information

Environment:

- Rancher Desktop Version: v1.16
- OS: Windows 11
- Kubernetes Version: 1.30.3

Logs:

- Unfortunately, no explicit error messages are displayed within the Rancher Dashboard logs when the issue occurs. The logs remain blank during the initial access attempt. After reopening the dashboard, logs become accessible, but no error messages are shown in either case.

Context:

- The issue occurs consistently after deploying new applications and creating pods. It seems isolated to initial access attempts immediately after deployment, but no other signs of resource or network issues are present.
- Reproduced the issue across several environments with different workloads.

Workaround:

- Temporarily resolved by closing and reopening the Rancher Cluster Dashboard, but this is not an ideal workflow.

If necessary, I can provide more detailed logs or screenshots upon request.

### Rancher Desktop Version

1.16

### Rancher Desktop K8s Version

1.30.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Microsoft Windows 11 Pro Version	10.0.22631 Build 22631

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Eset Internet Security 17.2.8

**Comment by jandubois** [comment] 2024-09-27 18:20
This looks like a duplicate of #3212. Please see https://github.com/rancher-sandbox/rancher-desktop/issues/3212#issuecomment-2379396075 for a possible workaround.

I'm closing this as a duplicated; feel free to reopen if you think it is not.

**Closed by jandubois** 2024-09-27 18:20 UTC
Labels: kind/bug
