### ISSUE TITLE
Docker process does not quit after being run

### ISSUE THREAD

**Issue by Raglin** [rancher-sandbox/rancher-desktop#1361] opened 2022-01-27 08:32 UTC
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

1.23.3

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro Build 9044.1466

### What CPU architecture are you using?

x64

### Actual Behavior

docker process hangs after running a container.

### Steps to Reproduce

docker run hello-world

### Result

![image](https://user-images.githubusercontent.com/11681568/151321295-3d71de4c-a0e6-467c-b72d-3fbd5eae4641.png)

### Expected Behavior

docker process should stop, and return to terminal after being run

**Comment by evertonlperes** [comment] 2022-01-27 12:39
Hi @Raglin 
It seems to be similar as https://github.com/rancher-sandbox/rancher-desktop/issues/1171
There's a bug on Windows that you need to press a key in order to exit the execution.

**Comment by Raglin** [comment] 2022-01-27 12:48
Thanks @evertonlperes 
I read through that issue, and my experience is slightly different. Key presses do not exit the execution. 

I can only exit the process via Task Manager, which the returns control to the terminal.

**Comment by evertonlperes** [comment] 2022-01-27 14:52
> Thanks @evertonlperes I read through that issue, and my experience is slightly different. Key presses do not exit the execution.
> 
> I can only exit the process via Task Manager, which the returns control to the terminal.

It is, indeed.
The behaviour is quite odd, it actually hold the docker process and it does not accept any keystroke (e.g.: `ctrl+c`). You need to force/manuall quit the process.

I have duplicated this issue on both Windows 10 PRO 20H2 and Windows 11.
On macOS and Linux are working properly.

@mook-as - this is probably a different issue from #1171

**Comment by mook-as** [comment] 2022-01-29 00:58
#1374 is now merged (and #1171 is closed); I've checked a local build and these steps don't reproduce the issue for me any more.  Closing this; please let us know if this is still an issue and we can reopen! (Either using a [CI build](https://github.com/rancher-sandbox/rancher-desktop/actions/workflows/package.yaml?query=is%3Acompleted+branch%3Amain) or waiting for the next release, of course.)

**Closed by mook-as** 2022-01-29 00:58 UTC
Labels: kind/bug, platform/windows, runtime/moby

**Comment by Raglin** [comment] 2022-01-31 07:08
Awesome, thanks! I've checked, and it is resolved.
