### ISSUE TITLE
Does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by SeanKnight** [rancher-sandbox/rancher-desktop#771] opened 2021-10-12 00:47 UTC
![image](https://user-images.githubusercontent.com/13762100/136871242-1739531f-70ee-4b48-be24-5fd00c1e6e05.png)

Found this line in the logs:

`INFO[0073] [hostagent] time="2021-10-11T16:13:13-07:00" level=fatal msg="failed to run [/usr/bin/qemu-system-x86_64 -M none -netdev help]: stdout=\"\", stderr=\"Possible accelerators: kvm, xen, hax, tcg\\nqemu-system-x86_64: -netdev help: Parameter 'id' is missing\\n\"" `

If I upgrade the system from Ubuntu 18.04 to 20.04 then rancher-desktop starts working. It would be nice for 18.04 to work since that version is still has supported until April 2023, and I have several teammates that use 18.04 who can not upgrade.

Ubuntu 18.04 has qemu 2.11.1, and Ubuntu 20.04 has qemu 4.2.1. Perhaps some command line flags changed between the versions?

**Comment by simonflood** [comment] 2021-10-13 09:58
On Ubuntu 18.04 you can add a third-party PPA which provides QEMU 2.12 - see https://launchpad.net/~jacob/+archive/ubuntu/virtualisation?field.series_filter=bionic

Once I did this the Rancher Desktop seemed to work! :-)

**Comment by simonflood** [comment] 2021-10-13 11:00
After a Factory Reset and selecting Kubernetes version v1.21.5 Rancher Desktop downloads Kubernetes, checks k3s images, and does something else quickly then the error pops up.

background.log:
current-port: 6443
Kubernetes was unable to start: Error: /opt/Rancher Desktop/resources/resources/linux/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/opt/Rancher Desktop/resources/app.asar/dist/app/background.js:1:7901)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

lima.log:
level=info msg="Terminal is not available, proceeding without opening an editor"
time="2021-10-13T11:58:08+01:00" level=info msg="Attempting to download the image from \"/opt/Rancher Desktop/resources/resources/linux/alpine-lima-v0.1.8-rd-3.13.5.iso\""
time="2021-10-13T11:58:09+01:00" level=fatal msg="failed to download the image, attempted 1 candidates, errors=[failed to download \"/opt/Rancher Desktop/resources/resources/linux/alpine-lima-v0.1.8-rd-3.13.5.iso\": userspace copy failed: %!w(<nil>)]"
+ limactl start --tty=false /home/simonf/.local/share/rancher-desktop/lima/_config/0.yaml
Error: /opt/Rancher Desktop/resources/resources/linux/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/opt/Rancher Desktop/resources/app.asar/dist/app/background.js:1:7901)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
Error starting lima: Error: /opt/Rancher Desktop/resources/resources/linux/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/opt/Rancher Desktop/resources/app.asar/dist/app/background.js:1:7901)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

**Comment by davidcassany** [comment] 2021-11-04 15:57
I confirm that while the former issue about QEMU arguments reported here and fixed by lima-vm/lima#331 RD still fails for Ubuntu 18.04. With the mentioned fix it launched the VM, but as soon as it starts to operate with ssh and scp to copy files from host to guest it fails with a file not found error... It is still unclear why this is happening, probably due to an old openssh (currently using v7.6p1) that does not play well with sshfs?

**Comment by davidcassany** [comment] 2021-11-05 13:59
Right, I finally found the root cause of this issue. Lima does not properly support openSSH earlier than v8.0. Ubuntu Bionic ships with openSSH v7.6 which does not include URI support in command line clients. See lima-vm/lima#386.

**Comment by gaktive** [comment] 2021-12-01 19:26
@adamkpickering this may be sorted out by a Lima update. Can you test this out?

**Comment by jandubois** [comment] 2021-12-01 19:52
I've just checked, and https://github.com/lima-vm/lima/pull/386 is not yet in RD; we need another bump to `lima-and-qemu` to pull it in.

@adamkpickering Don't bother testing until we have done the lima bump.

**Closed** 2021-12-09 21:45 UTC
Labels: bug, platform/linux
