### ISSUE TITLE
Multiple Kubernetes versions with (latest) tag appear after new Kubernetes versions become available

### ISSUE THREAD

**Issue by mcekovic** [rancher-sandbox/rancher-desktop#1676] opened 2022-02-28 14:27 UTC
### Actual Behavior

After new Kubernetes versions becomes available, it is just added (in `rancher-desktop/cache/k3s-versions.json` file) to the list of versions with the (latest) tag, leaving previous latest versions also with (latest) tag.
For example, after the latest Kubernetes version 1.23.4 has become available, both 1.23.4 and 1.23.3 have the (latest) tag.

### Steps to Reproduce

Wait for new Kubernetes version to become available and check Rancher Desktop Kubernetes version selection GUI for the duplicate (latest) versions.

### Result

`  {
    "version": "v1.23.3+k3s1",
    "channels": [
      "latest",
      "v1.23"
    ]
  },
  {
    "version": "v1.21.10+k3s1",
    "channels": [
      "v1.21"
    ]
  },
  {
    "version": "v1.22.7+k3s1",
    "channels": [
      "v1.22"
    ]
  },
  {
    "version": "v1.23.4+k3s1",
    "channels": [
      "latest",
      "v1.23"
    ]
  }`

### Expected Behavior

After new Kubernetes version is available, the (latest) tag should be removed from the previous latest version in the `rancher-desktop/cache/k3s-versions.json` file.

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.23.4

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment] 2022-02-28 17:48
This is very likely a duplicate of #1584

**Comment by mcekovic** [comment] 2022-03-04 17:38
Yes it is, sorry for a duplicate. Added comment in the original issue when the issue manifests.

**Closed** 2022-03-04 17:38 UTC
Labels: kind/bug, component/ui
