### ISSUE TITLE
Startup Stuck "Waiting for Kubernetes API"

### ISSUE THREAD

**Issue by DerekJi** [rancher-sandbox/rancher-desktop#2413] opened 2022-06-17 00:38 UTC
### Actual Behavior

After compressed the C drive on Windows 10, Rancher Desktop cannot be launched and stops at the step "Waiting for Kubernetes API" for ever.

#### Initial Installation
* Install Rancher Desktop (the latest version 1.4.1) on Windows 10 Pro
* Select the latest stable version of Kubernetes (1.23.6)
* Select docker (moby)
* **It runs very well.** ✔
* Quit Rancher Desktop

#### Windows Update
* Right click "C:" drive
* Run Disk Cleanup
* Tick "_Compress this drive to save disk space_" and OK
![image](https://user-images.githubusercontent.com/33775203/174197515-58c19f92-9d75-419f-8a64-433e1988b1be.png)

#### Restart Rancher Desktop
It stops at the step "Waiting for Kubernetes API" for ever. 😂

### Result

Rancher Desktop stops at "Waiting for Kubernetes API" for ever, with no error messages.

### Expected Behavior

1. Able to be started after compressed the system drive "C:", OR
2. Show meaningful error message

#### What I've Found
I checked the logs, but didn't understand what k3s was complaining: 
```
k3s no default routes found in \"/proc/net/route\" or \"/proc/net/ipv6_route\"
```

Tried to select different versions of Kubernetes, but no luck.

Tried to uninstall and reinstall Rancher Desktop 1.2, 1.3, 1.4. No luck.

Then, tried "Factory Reset", and found it failed at
```bash
wsl.exe --import rancher-desktop C:\Users\%USER%\AppData\Local\rancher-desktop\distro "C:\Users\%USER%\AppData\Local\Programs\Rancher Desktop\resources\resources\win32\distro-0.24.tar" --version **2**
```

it said something like 
```
The requested operation could not be completed due to a virtual disk system limitation. Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.
```

Unticked the checkbox "_Compress this drive to save disk space_" and OK

Then it works.

#### Summary
I understand it's not Rancher's fault, but it would be great if it could show proper error messages somewhere (UI or logs).

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

1.23.6

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro, 20H2

### What CPU architecture are you using?

x64

### Windows User Only

FortiClient VPN

**Comment by jandubois** [comment] 2022-06-17 06:31
As you already said, this is a limitation of WSL2 and not of Rancher Desktop itself. We do need to detect this, and present an understandable error though.

I haven't tested it, but it may be possible to just uncompress the `%LOCALAPPDATA%\rancher-desktop\distro` folder:

You can do this in the "Advanced" property settings of the folder:

<img width="356" alt="Screen Shot 2022-06-16 at 11 27 45 PM" src="https://user-images.githubusercontent.com/78947/174238683-01811466-7ffc-496d-9a02-2d0d4c73e275.png">

Make sure that both compression and encryption are de-selected:

<img width="377" alt="Screen Shot 2022-06-16 at 11 28 07 PM" src="https://user-images.githubusercontent.com/78947/174238727-5bf51300-6e4e-4003-8822-1f544a82d012.png">

That would still allow you to keep the rest of your disk compressed.

**Comment by DerekJi** [comment] 2022-06-17 13:12
yeah, that works as I tested. Thanks @jandubois

**Comment by jandubois** [comment] 2022-06-21 21:16
Closing this bug report; the enhancement to detect and report the issue during installation will be tracked in #2439.

**Closed by jandubois** 2022-06-21 21:16 UTC
Labels: kind/bug, kind/documentation-ready, platform/windows

**Comment by jandubois** [comment] 2022-06-21 21:20
@DerekJi You previously confirmed that disabling compression just on the folder worked, but it looks like the comment is gone now. Did you delete it because it didn't work after all, or did Github drop this by itself?
