### ISSUE TITLE
[macOS] Cannot delete dangling images - Invalid reference format

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#2850] opened 2022-08-31 21:04 UTC
### Actual Behavior

Cannot delete dangling images named `<none>` throws an error: `Error response from daemon: invalid reference format`

### Steps to Reproduce

1. Build any Dockerfile using dockerd container runtime.
2. Open RD UI and check if it is listing any `<none>` named images
3. Try to delete it using UI.

### Result

`Error response from daemon: invalid reference format`

### Expected Behavior

Should delete dangling images properly

### Additional Information

https://user-images.githubusercontent.com/37411123/187781732-202279ca-8b24-47d2-9487-bb881fbfe0f9.mov

### Rancher Desktop Version

1.5.1

### Rancher Desktop K8s Version

1.24.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS 12.5.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by jandubois** [comment] 2022-08-31 21:08
Hi Everton! Long time no talk!

Looks like a duplicate of #2626, so closing this one.

**Closed by jandubois** 2022-08-31 21:08 UTC
Labels: kind/bug

**Comment by gunamata** [comment] 2022-08-31 21:13
Hi Everton, Good to hear from you, Keep the feedback coming 😊

**Comment by evertonlperes** [comment] 2022-08-31 21:21
Hey @jandubois and @gunamata,
Hope you guys are doing well (sorry for spamming here). 

Thanks for pointing out the #2626 issue!

**Comment by gaktive** [comment] 2022-08-31 21:22
Hi @evertonlperes! Hope all is well with you!

**Comment by evertonlperes** [comment] 2022-08-31 21:23
Hi @gaktive,
I'm doing good, thanks! Hope you are doing good too!
