### ISSUE TITLE
v1.0.1 contains nerdctl 0.16.0

### ISSUE THREAD

**Issue by kdambekalns** [rancher-sandbox/rancher-desktop#1499] opened 2022-02-04 11:14 UTC
### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.23.1

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.2

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Actual Behavior

Even though 1.0.1 is supposed to contain `nerdctl` 0.16.1 (see https://github.com/rancher-sandbox/rancher-desktop/pull/1429), it comes with 0.16.0 for me:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/95873/152519348-b4222b5e-9273-4968-932a-b0a2f00f0b99.png">

### Steps to Reproduce

1. Install Rancher Desktop 1.0.1 on macOS / Apple Silicon
2. Run `nerdctl --version`

### Result

The unexpected version 0.16.0 is shown. Also, `nerdctl compose up --remove-orphans` returns `FATA[0000] unknown flag: --remove-orphans` even though 0.16.1 supports that.

### Expected Behavior

`nerdctl` 0.16.1 with support for `--orphan-removal` is available.

**Comment by jandubois** [comment] 2022-02-04 17:05
Thank you for your report. This is a bug in the upgrade logic (the new `nerdctl` is not installed correctly during upgrades). You can work around this by doing a "Factory Reset" (on the Troubleshooting page), but you will lose all you workloads/images/settings (it is like a fresh reinstall).

Closing as a duplicate of #1474.

**Closed by jandubois** 2022-02-04 17:05 UTC
Labels: kind/bug
