### ISSUE TITLE
I downloaded the Apple Silicon version but I get an Intel version instead

### ISSUE THREAD

**Issue by scottfwalter** [rancher-sandbox/rancher-desktop#4370] opened 2023-04-06 12:59 UTC
### Actual Behavior

I've downloaded the Apple Silicone DMG https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.8.1/Rancher.Desktop-1.8.1.aarch64.dmg.  However, after inspecting the properties on the executable it's an Intel version and not Apple Silicone nor Universal.

![CleanShot 2023-04-06 at 07 54 09@2x](https://user-images.githubusercontent.com/1752854/230385084-0d7f1443-6021-4023-aa18-a9cc195bfa47.png)

### Steps to Reproduce

Go to https://rancherdesktop.io and click the "Download Mac (Apple Silicon)" link.

### Result

The DMG contains an Intel executable

### Expected Behavior

The DMG should contain an Apple Silicone or Universal executable.

### Rancher Desktop Version

1.8.1

### Rancher Desktop K8s Version

Unknown

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

13.2.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment] 2023-04-06 16:25
This is a duplicate of #1416

Only the Electron app (and kuberlr) are Intel binaries; all the performance-critical parts are native ARM.

**Closed by jandubois** 2023-04-06 16:25 UTC
Labels: kind/bug, platform/macos, cpu/aarch64

**Comment by geertpingen** [comment] 2023-04-12 09:30
Hi, not sure if this is related but I'm running into an issue on macOS M1 where a local `docker build` builds an amd64 image, and `docker run` complains that. it's not `linux/arm64`. I would've expected `docker build` to build ARM images, right? Please let me know if I should open up a seperate issue for this.

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
