### ISSUE TITLE
General tab network status not updated

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#4211] opened 2023-03-16 20:05 UTC
### Actual Behavior

When the machine is offline, the **Network status** text in the _General_ tab still displays _online_.  This happens even if I close and reopen the main window.

### Steps to Reproduce

1. Start Rancher Desktop until it settles, then quit again, to ensure caches are filled.
2. Disable any network interfaces.
3. Start Rancher Desktop again.

### Result

![image](https://user-images.githubusercontent.com/3977982/225739218-2dd9850c-b578-440a-9834-c134b007d0e0.png)

The General tab still claims to be online.

### Expected Behavior

The General tab should say offline.

### Additional Information

The other parts of the application detects state correctly:
- The notification icon context menu ![image](https://user-images.githubusercontent.com/3977982/225739606-8d11c797-3c7c-467d-94d0-0c94ab9f97b0.png)
- Diagnostics ![image](https://user-images.githubusercontent.com/3977982/225739703-9330d08c-02db-4a37-b7b8-8910c8ff4d4d.png)

### Rancher Desktop Version

1.7.0-636-g1091a64f

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 21H2 (Build 22000.1516)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Fresh VM, no VPNs.

**Comment by jandubois** [comment] 2023-03-16 20:52
Isn't this a duplicate of #4195, which has been fixed by #4196?

**Comment by rak-phillip** [comment] 2023-03-16 21:31
This could have regressed in #4066

**Closed** 2023-03-16 22:18 UTC
Labels: kind/bug, component/ui
