### ISSUE TITLE
svclb-traefik in CrashLoopBackOff   mode

### ISSUE THREAD

**Issue by dvgitit** [rancher-sandbox/rancher-desktop#5091] opened 2023-07-04 08:48 UTC
### Actual Behavior

After installation (air gapped) of Rancher Desktop 1.9.0 the svclb-traefik pod does not come up:

`kubectl get pods -n kube-system`

```
faulted container "lb-tcp-80" out of: lb-tcp-80, lb-tcp-443
+ trap exit TERM INT
+ echo <ipv4>
+ grep -Eq :
+ cat /proc/sys/net/ipv4/ip_forward
+ '[' 0 '!=' 1 ]
+ exit 1
```

### Steps to Reproduce

1. Install Rancher Desktop 1.9.0 (including provisioning scripts) air-gapped

### Result

`kubectl get pods -n kube-system`

```
faulted container "lb-tcp-80" out of: lb-tcp-80, lb-tcp-443
+ trap exit TERM INT
+ echo <ipv4>
+ grep -Eq :
+ cat /proc/sys/net/ipv4/ip_forward
+ '[' 0 '!=' 1 ]
+ exit 1
```

### Expected Behavior

All pods should be running and traefik is functioning.

### Additional Information

- Disabling traefik and installing nginx ingress controller works.
- The mitigation described here does not work: https://www.suse.com/support/kb/doc/?id=000020166

### Rancher Desktop Version

1.9.0

### Rancher Desktop K8s Version

v1.21.14

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Version 21H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

VPN, Proxy

**Comment by jandubois** [comment] 2024-05-25 05:33
#5341 is a duplicate of this issue, but I'm going to close this one because I already left my comments on #5341 instead.

While it is not entirely clear why this behaviour is triggered, it seems to be resolved by upgrading to Kubernetes 1.25.3 or later.

**Closed by jandubois** 2024-05-25 05:33 UTC
Labels: kind/bug
