### ISSUE TITLE
Unhandled exception thrown on shut down

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#333] opened 2021-06-04 19:36 UTC
```
Powering down machine now...
Stopping "default"...
(node:26281) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 192.168.64.19:6443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
(node:26281) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:26281) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 192.168.64.19:6443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
(node:26281) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
Machine "default" was stopped.
```

This is thrown when exiting the app through the menu while it is being run in dev mode.

**Comment by ericpromislow** [comment] 2021-06-04 20:51
I can't repro the event emitter warning  now, but I'll take this on

**Comment by ericpromislow** [comment] 2021-06-04 23:59
The cause of this is a bit weird.

The hyperkit client runs the following code:
```
driver = ".../docker-machine-driver-hyperkit";
args = ["--storage-path", "/.../driver", "stop"];
await new Promise((resolve, reject) => {
  const child = childProcess.spawn(driver, args);
  child.on('error', reject); // this line isn't called
  child.on('exit', (status, signal) => {
   if (status == 0) {
     resolve();
   }
 });
});
return;
```

Here's the order of events:
1. Run `childProcess.spawn`
2. Complain about the unhandled rejection
3. Handle the `exit(status == 0, signal == null);` // i.e. the stop call finished successfully

By not creating a `promise`, only for the `stop` command, we avoid this warning message.

And I think the warning message is spurious anyway -- if I run the main process with the `--unhandled-rejections=strict` flag I get the same behaviour.

**Comment by ericpromislow** [comment] 2021-06-08 17:12
Merged at https://github.com/rancher-sandbox/rancher-desktop/pull/340#event-4859891063

**Closed by ericpromislow** 2021-06-08 17:12 UTC
Labels: bug, macos
