### ISSUE TITLE
Does  Rancher desktop work on M1 mac with arm ?

### ISSUE THREAD

**Issue by kiranchavala** [rancher-sandbox/rancher-desktop#530] opened 2021-08-23 06:28 UTC
I tried the steps 

For some reason, I am unable to start the lima on mac m1 

https://github.com/lima-vm/lima/issues/42#issuecomment-903454392

Also followed these steps 

https://github.com/rancher-sandbox/rancher-desktop/issues/518

**Comment by jandubois** [comment] 2021-08-23 07:02
Rancher Desktop does not yet support Apple Silicon CPUs. It is on our roadmap but not yet done.

There are more things to do beyond replacing the lima version with one compiled for ARM; you also need a corresponding alpine-lima ISO image, and the GUI code needs to be updated to fetch/use ARM assets instead of AMD64.

Closing this issue as a duplicate of #16.

**Closed by jandubois** 2021-08-23 07:02 UTC
