### ISSUE TITLE
Kube config in WSL is group/world writable

### ISSUE THREAD

**Issue by agracey** [rancher-sandbox/rancher-desktop#1252] opened 2022-01-16 20:10 UTC
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

0.21.7

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro, build 22000.434

### What CPU architecture are you using?

x64

### Windows User Only

No additional network setup

### Actual Behavior

When running helm commands, every command returns a warning (followed by correct behavior) 
```
agracey@agracey-desktop ~/P/examples> helm version
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/agracey/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/agracey/.kube/config
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```

I'm pretty sure this is due to the file being a symlink to a Windows filesystem and likely can't be fixed but wanted to raise it anyways. 

### Steps to Reproduce

- Delete ~/.kube/config 
- Restart RD
- Run `helm version` from WSL2 distro

### Result

Helm prints the following lines for every command:

```
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/agracey/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/agracey/.kube/config
```

### Expected Behavior

Helm doesn't prefix output with warnings.

**Comment by jandubois** [comment] 2022-01-17 05:09
Duplicate of #965

**Closed by jandubois** 2022-01-17 05:09 UTC
Labels: kind/bug
