### ISSUE TITLE
Incorrectly created kube config file on opening Rancher Desktop during Windows startup

### ISSUE THREAD

**Issue by ashhSAG93** [rancher-sandbox/rancher-desktop#5981] opened 2023-11-16 09:54 UTC
### Actual Behavior

We have enabled opening Rancher Desktop on startup of Windows. (WSL2 enabled). 

On running K8S commands like kubectl get pods, we get errors related to the kube config file as follows:

error: error loading config file "C:\Users\<user>\.kube\config": yaml: control characters are not allowed

This is because, on examination we see that either the current context or the users isnt filled up properly, leading to key value pair with a blank value. 

The issue is resolved on Quitting and reopening Rancher Desktop

### Steps to Reproduce

Boot up a Windows machine. 

Rancher Desktop starts up. 

Once its done, run a kubectl command, like kubectl get pods. 

### Result

On running K8S commands like kubectl get pods, we get errors related to the kube config file as follows:

error: error loading config file "C:\Users\<user>\.kube\config": yaml: control characters are not allowed

### Expected Behavior

kube config should be configured correctly when Rancher Desktop is opened on Windows. 

Kubectl commands should work properly. 

There should be no need to restart Rancher Desktop

### Rancher Desktop Version

1.11.0

### Rancher Desktop K8s Version

1.27.6

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 22H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

N/A

**Comment by jandubois** [comment] 2023-11-16 16:45
Closing as a duplicate of #5946. Feel free to re-open with additional information if you this this is a different problem!

**Closed by jandubois** 2023-11-16 16:45 UTC
Labels: kind/bug
