### ISSUE TITLE
Error loading Rancher Desktop after upgrade to Monterey 12.5.1 apple silicon M1

### ISSUE THREAD

**Issue by brainpicker** [rancher-sandbox/rancher-desktop#2806] opened 2022-08-23 06:35 UTC
### Actual Behavior

After updating the OS to Monterey 12.5.1 I can't run Rancher Desktop.

### Steps to Reproduce

Run Rancher desktop

### Result

time="2022-08-23T09:33:14+03:00" level=info msg="Using the existing instance \"0\""
time="2022-08-23T09:33:14+03:00" level=info msg="Starting switch daemon for \"bridged_en0\" network"
time="2022-08-23T09:33:15+03:00" level=fatal msg="\"/private/var/run/rancher-desktop-lima\" doesn't seem to be writable by the daemon (gid:1) group"
2022-08-23T06:33:15.073Z: + limactl start --tty=false 0
2022-08-23T06:33:15.074Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-08-23T06:33:15.074Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8692)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)

<img width="806" alt="image" src="https://user-images.githubusercontent.com/5030167/186087216-514e5411-55c3-44a9-8705-c9748cd4767f.png">

### Expected Behavior

Be able to run Rancher Desktop

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

1.18.20

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

12.5.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by adamkpickering** [comment] 2022-08-23 22:13
Closing as this is a duplicate of #2798.

**Comment by AkihiroSuda** [comment] 2022-08-24 03:01
> Thanks for your bug report! However, it is a duplicate of #2798. I'm going to close it so that discussion can take place there.

Not sure.
The error message seems quite different.

**Comment by adamkpickering** [comment] 2022-08-24 15:51
Hmm you're right. I'll reopen this.

**Comment by jandubois** [comment] 2022-08-26 21:44
This is a known issue with Rancher Desktop 1.1.1 (see https://github.com/rancher-sandbox/rancher-desktop/issues/1815#issuecomment-1068522900). Please update to a newer release (current is 1.5.1) or use the workaround from the comment I just linked to.

**Closed by jandubois** 2022-08-26 21:44 UTC
Labels: kind/bug, platform/macos
