### ISSUE TITLE
WSLKERNELINSTALLED seems to be broken in the WIX check

### ISSUE THREAD

**Issue by byjrack** [rancher-sandbox/rancher-desktop#5951] opened 2023-11-10 15:06 UTC
### Actual Behavior

running the 1.11 MSI I am by default forced into machine scoped install

No existing installs and guessing https://github.com/rancher-sandbox/rancher-desktop/blob/main/build/wix/main.wxs#L42 isn't returning the correct data as the comment notes.  Likely need a different type of test that can run as User.

Unsure if any of the work done in #5600 might be reusable, but don't have much stick time w WIX.

> wsl --version
WSL version: 2.0.4.0
Kernel version: 5.15.123.1-1
WSLg version: 1.0.58
MSRDC version: 1.2.4485
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.19044.3570

> wsl --status
Default Distribution: Ubuntu
Default Version: 2

### Steps to Reproduce

Have WSL 2.0 and a WSL kernel installed via whatever mechanism

Run MSI.  You will be prompted that the install will install WSL and be machine scoped after accepting the license instead of giving the option for User or Machine

### Result

Machine install instead of Installation Scope dialog

### Expected Behavior

Installation scope dialog

### Additional Information

If you run the MSI w the property you can force the dialog to show as a workaround.

`Rancher.Desktop.Setup.1.11.0.msi WSLKERNELINSTALLED=1`

### Rancher Desktop Version

1.11.0

### Rancher Desktop K8s Version

n/a

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

19044.3570

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by mook-as** [comment] 2023-11-13 18:47
Note that this will be changed in #5875 — but we'll be using a different MSI property to override the detection (`WSLINSTALLED` instead of `WSLKERNELINSTALLED`).  That PR is based on the work in #5600.

I believe this is a duplicate of #2718.  When WSL is installed from the Store (which is the case these days unless you specifically do `wsl --install --inbox`), the kernel package is no longer installed separately, which is why the previous detection now fails.

Thanks for the detailed report anyway!

**Comment by byjrack** [comment] 2023-11-13 18:54
Yeah in this case it was using the 2.x major Github release (not from Store specifically as we have a different issue there) but yeah been watching some of the work on WSL preflight and I figured it was a moving target.  When the new feature is merged I can swing back through and check the experience.

Trying to pave a path to the User scoped installs since it avoids a number of challenges with keeping up with releases which hit UAC and require some messier workarounds.  The fewer tweaks to the out of box the happier I will be.

**Closed** 2023-11-29 22:19 UTC
Labels: kind/bug, platform/windows, area/installer
