### ISSUE TITLE
JavaScript Error in Rancher Desktop on OS X M1 Chip

### ISSUE THREAD

**Issue by uromahn** [rancher-sandbox/rancher-desktop#5085] opened 2023-07-01 00:01 UTC
### Actual Behavior

Since the upgrade RD 1.9.0 on my Macbook Pro M1 Chip, I am getting intermittent popups reporting a JavaScript error. See attached screenshot.
![Screenshot 2023-06-30 at 4 56 17 PM](https://github.com/rancher-sandbox/rancher-desktop/assets/2626468/5283d49b-6b0a-43a0-80e4-7c5f0a4754bb)

### Steps to Reproduce

Unknown - the error sporadically pops up after starting RD and stops after exiting RD.

### Result

See attached Screenshot

### Expected Behavior

No JavaScript error

### Additional Information

I do not see any missing feature or other bad behavior. Except for this error popup, RD seems to keep working still fine.

### Rancher Desktop Version

1.9.0

### Rancher Desktop K8s Version

1.27.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Ventura 13.4.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment] 2023-07-01 04:09
This is a duplicate of #5009 and has been fixed in the 1.9.1 release.

**Closed by jandubois** 2023-07-01 04:09 UTC
Labels: kind/bug
