### ISSUE TITLE
0.7.0.beta.1 docker socket not available after sleep/wake

### ISSUE THREAD

**Issue by davidwalter0** [rancher-sandbox/rancher-desktop#1119] opened 2021-12-16 15:23 UTC
### Rancher Desktop Version

0.7.0.beta.1

### Rancher Desktop K8s Version

1.18.20

### What operating system are you using?

macOS

### Operating System / Build Version

macos Monteray 12.0.1

### What CPU architecture are you using?

x64

### Actual Behavior

configure with directions works, but after sleep and wake the service doesn't restart in the VM
```
docker context rm -f rancher-desktop
docker context create rancher-desktop --docker host=unix://${HOME}/Library/Application\ Support/rancher-desktop/lima/0/sock/docker --description "Rancher Desktop"
docker context list; docker context use rancher-desktop
docker ps 
CONTAINER ID   IMAGE               COMMAND                  CREATED          STATUS          PORTS     NAMES
253183341cda   cf14c5e88c0e        "buildkitd --addr=un…"   31 seconds ago   Up 29 seconds             k8s_buildkit_builder-g99h4_kube-image_dcd7937f-25cb-4570-96c6-183c356d1d1b_1223
3c21c08d55a8   913759b56a73        "/app"                   3 minutes ago    Up 3 minutes              k8s_app_app-5fc4ff6c45-hpzff_api_5a1659cc-330a-4a2b-b5e6-82fe972fb222_2

```
but after sleep wake docker service is not available, even with repeating the above steps
```
docker ps
Cannot connect to the Docker daemon at unix:///...home.../Library/Application Support/rancher-desktop/lima/0/sock/docker. Is the docker daemon running?
```

after restarting rancher-desktop it works again
![image](https://user-images.githubusercontent.com/192699/146398469-ac206de6-64f8-4fcf-8472-0ac0526bd573.png)

### Steps to Reproduce

select dockerd
![image](https://user-images.githubusercontent.com/192699/146398586-b048cd62-4bbe-41dd-a7ef-2a5b70aa27aa.png)

configure docker socket export 
```
docker context rm -f rancher-desktop
docker context create rancher-desktop --docker host=unix://${HOME}/Library/Application\ Support/rancher-desktop/lima/0/sock/docker --description "Rancher Desktop"
docker context list; docker context use rancher-desktop
```

### Result

docker ps and other commands work until sleep and wake of mac
after wake unable to connect to docker daemon
```
docker ps
Cannot connect to the Docker daemon at unix:///...home.../Library/Application Support/rancher-desktop/lima/0/sock/docker. Is the docker daemon running?
```

### Expected Behavior

after wake daemon should be reachable via socket

### Additional Information

not sure how to jump into this vm to debug further

are there directions for accessing this vm via lima/limactl?

**Comment by jandubois** [comment] 2021-12-16 15:27
I suspect that the ssh forwarding of the socket gets broken when the host sleeps.

> are there directions for accessing this vm via lima/limactl?

This should work:

```
LIMA_HOME=$HOME/Library/Application\ Support/rancher-desktop/lima /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl shell 0
```

**Comment by gamerson** [comment] 2021-12-23 01:50
I am seeing a problem after sleep/wake.  the `date -u` command in any pod after the mac wakes are behind, seemingly the same amount of time the laptop was asleep.  In my application, this is causing any new oauth tokens to be invalid (i guess because of the time delta).  If I shell into the LIMA VM and manually set the `date` command to the correct time, the app in the pod can now make new oauth connections.

**Comment by davidwalter0** [comment] 2022-01-04 15:40
> I suspect that the ssh forwarding of the socket gets broken when the host sleeps.
> 
> > are there directions for accessing this vm via lima/limactl?
> 
> This should work:
> 
> ```
> LIMA_HOME=$HOME/Library/Application\ Support/rancher-desktop/lima /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl shell 0
> ```

Thanks

In my case the lima commands were installed in a different path. The following worked.

```
LIMA_HOME=$HOME/Library/Application\ Support/rancher-desktop/lima limactl shell 0
```

Testing with version: 0.7.1

**Comment by davidwalter0** [comment] 2022-01-04 22:05
> I am seeing a problem after sleep/wake. the `date -u` command in any pod after the mac wakes are behind, seemingly the same amount of time the laptop was asleep. In my application, this is causing any new oauth tokens to be invalid (i guess because of the time delta). If I shell into the LIMA VM and manually set the `date` command to the correct time, the app in the pod can now make new oauth connections.

I don't see this currently with 0.7.1, but I'll try letting it sleep for a longer time

**Comment by davidwalter0** [comment] 2022-01-05 15:53
Slept the system overnight
```
docker ps
Cannot connect to the Docker daemon at unix://${HOME}/Library/Application Support/rancher-desktop/lima/0/sock/docker. Is the docker daemon running?
```

```
date -u; LIMA_HOME=$HOME/Library/Application\ Support/rancher-desktop/lima limactl shell 0 date; date -u
Wed Jan  5 15:38:20 UTC 2022
Wed Jan  5 02:36:02 UTC 2022
Wed Jan  5 15:38:20 UTC 2022
```
I do see the time failed to update but resetting the time in the vm didn't work

```
date -u; LIMA_HOME=$HOME/Library/Application\ Support/rancher-desktop/lima limactl shell 0 sudo date "$(date -u +%H:%M:%S)"; date -u; docker ps
Wed Jan  5 15:47:06 UTC 2022
Wed Jan  5 15:47:06 UTC 2022
Wed Jan  5 15:47:06 UTC 2022
Cannot connect to the Docker daemon at unix://${HOME}/Library/Application Support/rancher-desktop/lima/0/sock/docker. Is the docker daemon running?
```

**Comment by gamerson** [comment] 2022-01-05 15:57
> Slept the system overnight
> 
> ```
> docker ps
> Cannot connect to the Docker daemon at unix://${HOME}/Library/Application Support/rancher-desktop/lima/0/sock/docker. Is the docker daemon running?
> ```
> 
> ```
> date -u; LIMA_HOME=$HOME/Library/Application\ Support/rancher-desktop/lima limactl shell 0 date; date -u
> Wed Jan  5 15:38:20 UTC 2022
> Wed Jan  5 02:36:02 UTC 2022
> Wed Jan  5 15:38:20 UTC 2022
> ```
> 
> I do see the time failed to update but resetting the time in the vm didn't work
> 
> ```
> date -u; LIMA_HOME=$HOME/Library/Application\ Support/rancher-desktop/lima limactl shell 0 sudo date "$(date -u +%H:%M:%S)"; date -u; docker ps
> Wed Jan  5 15:47:06 UTC 2022
> Wed Jan  5 15:47:06 UTC 2022
> Wed Jan  5 15:47:06 UTC 2022
> Cannot connect to the Docker daemon at unix://${HOME}/Library/Application Support/rancher-desktop/lima/0/sock/docker. Is the docker daemon running?
> ```

I will try to reproduce my behavior again with latest RD 0.7.1.  What other system information should I include? Some RD logs? or enable debug mode?  Because there could be other variables between our systems that could be the reason for the different.

**Comment by dolfelt** [comment] 2022-01-05 16:51
I am also having this issue on the latest version 0.7.1. Seems to happen when sleeping overnight.

**Comment by dhruv-paystack** [comment] 2022-01-08 06:31
I am seeing this issue too on 0.7.1. Is there a command we can run to fix this? I went into the lima VM and ran the following command to fix the date
```
$ sudo hwclock --hctosys
```

**Comment by jandubois** [comment] 2022-01-08 07:17
I've reviewed and tested https://github.com/lima-vm/lima/pull/490 today, and confirmed that it will reset the clock inside the VM within 10s after waking up from sleep.

I do not know if this will fix the docker socket issue. I hope the lima fix will be merged early next week and make it into Rancher Desktop in time for the 1.0.0-beta release expected around January 17 (Monday in a week). We would very much appreciate if you could retest the the issue once the beta is released.

**Comment by dhruvbaldawa** [comment] 2022-01-11 06:16
These are the logs from the lima VM if it helps
```
{"level":"debug","msg":"executing ssh for script \"boot scripts must have finished\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/dhruv/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSS
{"level":"info","msg":"Forwarding \"/run/lima-guestagent.sock\" (guest) to \"/Users/dhruv/Library/Application Support/rancher-desktop/lima/0/ga.sock\" (host)","time":"2022-01-09T00:42:42+05:30"}
{"level":"debug","msg":"stdout=\"\", stderr=\"+ timeout 30s bash -c 'until sudo diff -q /run/lima-boot-done /mnt/lima-cidata/meta-data 2\u003e/dev/null; do sleep 3; done'\\n\", err=\u003cnil\u003e","time":"2022-01-09T00:42:42+05:30"}
{"level":"info","msg":"The final requirement 1 of 1 is satisfied","time":"2022-01-09T00:42:42+05:30"}
{"level":"debug","msg":"guest agent info: \u0026{LocalPorts:[{IP:0.0.0.0 Port:22} {IP::: Port:22}]}","time":"2022-01-09T00:42:42+05:30"}
{"level":"debug","msg":"guest agent event: {Time:2022-01-08 19:12:41.489103589 +0000 UTC LocalPortsAdded:[{IP:0.0.0.0 Port:22} {IP::: Port:22}] LocalPortsRemoved:[] Errors:[]}","time":"2022-01-09T00:42:42+05:30"}
{"level":"info","msg":"Not forwarding TCP 0.0.0.0:22","time":"2022-01-09T00:42:42+05:30"}
{"level":"info","msg":"Not forwarding TCP [::]:22","time":"2022-01-09T00:42:42+05:30"}
{"level":"debug","msg":"guest agent event: {Time:2022-01-08 19:12:50.49376951 +0000 UTC LocalPortsAdded:[{IP:127.0.0.1 Port:6444} {IP::: Port:6443}] LocalPortsRemoved:[] Errors:[]}","time":"2022-01-09T00:42:51+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:6444 to 0.0.0.0:6444","time":"2022-01-09T00:42:51+05:30"}
{"level":"info","msg":"Forwarding TCP from [::]:6443 to 0.0.0.0:6443","time":"2022-01-09T00:42:51+05:30"}
{"level":"debug","msg":"guest agent event: {Time:2022-01-08 19:12:53.494885678 +0000 UTC LocalPortsAdded:[{IP:127.0.0.1 Port:10257}] LocalPortsRemoved:[] Errors:[]}","time":"2022-01-09T00:42:54+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:10257 to 0.0.0.0:10257","time":"2022-01-09T00:42:54+05:30"}
{"level":"debug","msg":"guest agent event: {Time:2022-01-08 19:12:56.497335013 +0000 UTC LocalPortsAdded:[{IP:127.0.0.1 Port:10258} {IP:127.0.0.1 Port:38427} {IP:127.0.0.1 Port:10248} {IP:127.0.0.1 Port:10249} {IP:127.0.0.1 Port:10256} {IP::: Port:10250}] LocalPortsRemoved:[] Errors:[]}","time":"2022-01-09T00:42:57+0
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:10258 to 0.0.0.0:10258","time":"2022-01-09T00:42:57+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:38427 to 0.0.0.0:38427","time":"2022-01-09T00:42:57+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:10248 to 0.0.0.0:10248","time":"2022-01-09T00:42:57+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:10249 to 0.0.0.0:10249","time":"2022-01-09T00:42:57+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:10256 to 0.0.0.0:10256","time":"2022-01-09T00:42:57+05:30"}
{"level":"info","msg":"Forwarding TCP from [::]:10250 to 0.0.0.0:10250","time":"2022-01-09T00:42:57+05:30"}
{"level":"debug","msg":"guest agent event: {Time:2022-01-08 19:12:59.492653931 +0000 UTC LocalPortsAdded:[{IP:127.0.0.1 Port:10259} {IP::: Port:10251}] LocalPortsRemoved:[] Errors:[]}","time":"2022-01-09T00:43:00+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:10259 to 0.0.0.0:10259","time":"2022-01-09T00:43:00+05:30"}
{"level":"info","msg":"Forwarding TCP from [::]:10251 to 0.0.0.0:10251","time":"2022-01-09T00:43:00+05:30"}
{"level":"debug","msg":"guest agent event: {Time:2022-01-08 19:13:11.49291602 +0000 UTC LocalPortsAdded:[{IP:0.0.0.0 Port:31295} {IP:0.0.0.0 Port:30244}] LocalPortsRemoved:[] Errors:[]}","time":"2022-01-09T00:43:12+05:30"}
{"level":"info","msg":"Forwarding TCP from 0.0.0.0:31295 to 0.0.0.0:31295","time":"2022-01-09T00:43:12+05:30"}
{"level":"info","msg":"Forwarding TCP from 0.0.0.0:30244 to 0.0.0.0:30244","time":"2022-01-09T00:43:12+05:30"}
{"level":"debug","msg":"guest agent event: {Time:2022-01-08 19:13:29.497613987 +0000 UTC LocalPortsAdded:[{IP:127.0.0.1 Port:80} {IP:127.0.0.1 Port:443}] LocalPortsRemoved:[] Errors:[]}","time":"2022-01-09T00:43:30+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:80 to 0.0.0.0:80","time":"2022-01-09T00:43:30+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:443 to 0.0.0.0:443","time":"2022-01-09T00:43:30+05:30"}
{"level":"debug","msg":"guest agent event: {Time:2022-01-09 00:58:29.01513819 +0000 UTC LocalPortsAdded:[] LocalPortsRemoved:[] Errors:[exit status 4]}","time":"2022-01-10T22:27:28+05:30"}
{"level":"warning","msg":"received error from the guest: \"exit status 4\"","time":"2022-01-10T22:27:29+05:30"}
{"level":"debug","msg":"guest agent event: {Time:2022-01-09 00:58:29.499346691 +0000 UTC LocalPortsAdded:[{IP:127.0.0.1 Port:80} {IP:127.0.0.1 Port:443}] LocalPortsRemoved:[] Errors:[]}","time":"2022-01-10T22:27:29+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:80 to 0.0.0.0:80","time":"2022-01-10T22:27:29+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:443 to 0.0.0.0:443","time":"2022-01-10T22:27:29+05:30"}
{"error":"unexpected EOF","level":"warning","msg":"connection to the guest agent was closed unexpectedly","time":"2022-01-11T11:24:50+05:30"}
{"error":"EOF","level":"debug","msg":"sftp server for /Users/dhruv exited with EOF (negligible)","time":"2022-01-11T11:24:50+05:30"}
{"error":"EOF","level":"debug","msg":"sftp server for /Users/dhruv/Library/Caches/rancher-desktop/k3s exited with EOF (negligible)","time":"2022-01-11T11:24:50+05:30"}
{"error":"EOF","level":"debug","msg":"sftp server for /tmp/rancher-desktop exited with EOF (negligible)","time":"2022-01-11T11:24:50+05:30"}
{"level":"info","msg":"Forwarding \"/run/lima-guestagent.sock\" (guest) to \"/Users/dhruv/Library/Application Support/rancher-desktop/lima/0/ga.sock\" (host)","time":"2022-01-11T11:25:00+05:30"}
{"level":"debug","msg":"guest agent info: \u0026{LocalPorts:[{IP:127.0.0.1 Port:10257} {IP:127.0.0.1 Port:10258} {IP:127.0.0.1 Port:10259} {IP:0.0.0.0 Port:22} {IP:127.0.0.1 Port:38427} {IP:0.0.0.0 Port:31295} {IP:0.0.0.0 Port:30244} {IP:127.0.0.1 Port:10248} {IP:127.0.0.1 Port:10249} {IP:127.0.0.1 Port:6444} {IP:127
{"level":"debug","msg":"guest agent event: {Time:2022-01-09 02:39:32.039044081 +0000 UTC LocalPortsAdded:[{IP:127.0.0.1 Port:10257} {IP:127.0.0.1 Port:10258} {IP:127.0.0.1 Port:10259} {IP:0.0.0.0 Port:22} {IP:127.0.0.1 Port:38427} {IP:0.0.0.0 Port:31295} {IP:0.0.0.0 Port:30244} {IP:127.0.0.1 Port:10248} {IP:127.0.0.1
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:10257 to 0.0.0.0:10257","time":"2022-01-11T11:25:00+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:10258 to 0.0.0.0:10258","time":"2022-01-11T11:25:00+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:10259 to 0.0.0.0:10259","time":"2022-01-11T11:25:00+05:30"}
{"level":"info","msg":"Not forwarding TCP 0.0.0.0:22","time":"2022-01-11T11:25:01+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:38427 to 0.0.0.0:38427","time":"2022-01-11T11:25:01+05:30"}
{"level":"info","msg":"Forwarding TCP from 0.0.0.0:31295 to 0.0.0.0:31295","time":"2022-01-11T11:25:01+05:30"}
{"level":"info","msg":"Forwarding TCP from 0.0.0.0:30244 to 0.0.0.0:30244","time":"2022-01-11T11:25:01+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:10248 to 0.0.0.0:10248","time":"2022-01-11T11:25:01+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:10249 to 0.0.0.0:10249","time":"2022-01-11T11:25:01+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:6444 to 0.0.0.0:6444","time":"2022-01-11T11:25:01+05:30"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:10256 to 0.0.0.0:10256","time":"2022-01-11T11:25:01+05:30"}
{"level":"info","msg":"Not forwarding TCP [::]:22","time":"2022-01-11T11:25:01+05:30"}
```

**Comment by gaktive** [comment] 2022-01-15 01:02
Version 1.0.0 beta1 was released today and has a change in Lima that syncs the clock between the host and the guest. 

Please test the same scenario with this version and if the problem still exists, please reopen this.

**Closed by gaktive** 2022-01-15 01:02 UTC
Labels: kind/bug, platform/macos

**Comment by alvarocantador** [comment] 2022-01-18 22:11
I'm running version 1.0.0 beta1 and looks like the date problem was solved. However, it still happens every time the host OS gets in sleep mode for more than an hour-ish. 

I connected to the Lima VM via ssh, the looks like the docker engine still running, but inaccessible from outside.

Which information can I get that would help to identify the issue properly?

Host OS: macOS Monterey 12.1
Chip: Apple M1
Rancher desktop: 1.0.0-beta.1

**Comment by jandubois** [comment] 2022-01-18 22:42
> Which information can I get that would help to identify the issue properly? Should I open another issue?

Thank you for the update. We don't need a new issue; let's just keep this one open. I think the issue (or at least the fix) will be in lima. I think we need to be able to recover from broken ssh connections.

Will move this to a later milestone; this isn't going to be resolved within a week anymore.

**Comment by jandubois** [comment] 2022-01-18 22:44
@alvarocantador Oops, didn't realize this issue was closed already.

So yes, please create a new one, and include a link back to this closed issue.

**Comment by alvarocantador** [comment] 2022-01-19 12:37
@jandubois I just created #1274. Thank you! I appreciate your help.
