### ISSUE TITLE
Docker stats not working

### ISSUE THREAD

**Issue by dperez83** [rancher-sandbox/rancher-desktop#7693] opened 2024-10-29 14:09 UTC
### Actual Behavior

`docker stats` should show the statistics (cpu memory io etc)

### Steps to Reproduce

Run Rancher Desktop 1.16.0 and run `docker stats`

### Result

Every single statistics shows a zero value

![image](https://github.com/user-attachments/assets/c2264aca-960e-4d05-8806-4e6eedc8bcfd)

### Expected Behavior

Should show actual statistics

### Rancher Desktop Version

1.16.0

### Rancher Desktop K8s Version

-

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 23H2 22631.4317

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Windows Defender

**Comment by jandubois** [comment] 2024-10-29 19:12
This is a duplicate of #5241.

I've looked into this a little more again, and the root cause remains a mystery. I have however found a potential workaround in https://github.com/rancher-sandbox/rancher-desktop/issues/5241#issuecomment-2445119511.

**Closed by jandubois** 2024-10-29 19:12 UTC
Labels: kind/bug, platform/windows, runtime/moby

**Comment by dperez83** [comment] 2025-06-25 13:11
It's fixed on the 1.19.3 

![Image](https://github.com/user-attachments/assets/adc6f211-7d4b-4d55-bdab-89dcde3dfc48)
