### ISSUE TITLE
macOS download 1.6.0 ARM doesn't contain an arm-only version

### ISSUE THREAD

**Issue by suschizu** [rancher-sandbox/rancher-desktop#3229] opened 2022-10-20 15:46 UTC
### Actual Behavior

The downloaded file doesn't contain an arm build 

https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.6.0/Rancher.Desktop-1.6.0.aarch64.dmg

### Steps to Reproduce

```
file path/to/Rancher Desktop.app/Contents/MacOS/Rancher Desktop

>> Mach-O 64-bit executable x86_64
```

### Result

not an arm build

### Expected Behavior

should not work on intel 

### Rancher Desktop Version

1.6.0

### Rancher Desktop K8s Version

1.

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.3

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment] 2022-10-20 15:53
This is a duplicate of #2387.

The UI for the macOS ARM version is currently still using Rosetta, but the VM, container engine, Kubernetes etc. are all running native aarch64 code.

The only other part besides the UI that may need Rosetta is `kubectl` for older versions of Kubernetes, because those were never released as aarch64 binaries from upstream.

**Closed by jandubois** 2022-10-20 15:53 UTC
Labels: kind/bug, triage/duplicate, platform/macos, cpu/aarch64
