### ISSUE TITLE
1.3.0, docker.socket file is a link to a file that does not exist

### ISSUE THREAD

**Issue by a4z** [rancher-sandbox/rancher-desktop#2158] opened 2022-05-02 10:11 UTC
### Actual Behavior

since the update to version 1.3.0, docker stopped working

I think the reason is, that now the socker file is a link to a file that does not exist

### Steps to Reproduce

`docker ps`

### Result

`error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json": EOF`

### Expected Behavior

docker shows images

### Additional Information

```
 ls -l /var/run/docker.sock
lrwxr-xr-x  1 root  daemon  29 May  2 12:06 /var/run/docker.sock -> /Users/me/.rd/docker.sock
```

```
cat /Users/me/.rd/docker.sock
cat: /Users/me/.rd/docker.sock: No such file or directory
```

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

1.22.7

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by a4z** [comment] 2022-05-02 10:18
Info: Reset the installation, and restart fixed the issue

**Comment by jandubois** [comment] 2022-05-02 16:42
Not sure why the socket didn't exist before, but this has not been reproducible. Closing for now, but if somebody else experiences this too, please leave a comment!

**Closed by jandubois** 2022-05-02 16:42 UTC
Labels: kind/bug

**Comment by danlester** [comment] 2022-05-03 10:32
Actually, I am also having this problem. Not sure what started it. Maybe there was an upgrade to Rancher Desktop.

I am also on 1.3.0 running moby, but not running kubernetes.

It is an Intel Mac with MacOS version 10.15.7.

I have tried Factory Reset, plus uninstall and reinstall with no success...

Thank you if anyone has any thoughts!

**Comment by a4z** [comment] 2022-05-03 11:08
when I remember right, I did also remove all files created, + the socket files.
so make a factory reset,  then be sure everything is deleted (/var/run/docker.sock and ~/.rd)
and when it starts, be sure to not run without sudo, run with sudo when the question comes
the dialog is now, and a little bit small 
hope that helps

**Comment by danlester** [comment] 2022-05-03 11:13
Thank you @a4z. I have tried that too, and at least then it does recreate the symlink (after asking for root access) and now to something that does exist.

`/var/run/docker.sock -> /Users/dan/.rd/docker.sock`

But I still get the same 'error during connect'. In fact, I get that even if I first do `docker context use rancher-desktop` (which should mean it's accessing the Rancher socket directly), so I'm not sure what's going on really.

**Comment by moznion** [comment] 2022-05-07 04:03
I faced the same issue but I changed the container runtime to `dockerd` from `containerd` then it has begun to work fine. This is a workaround just in my environment, FYI.

**Comment by a4z** [comment] 2022-05-07 06:37
@jandubois , maybe time to re-open the issue, since you have now multiple user reports? 

It's hard to find when it's closed, and given that we have here 3 different users facing the problem, the real number is for sure much higher.

I understand that it's hard if it is not reproducible, but maybe with an open ticket additional info will be provided

**Comment by jandubois** [comment] 2022-05-07 07:09
> @jandubois , maybe time to re-open the issue, since you have now multiple user reports?

I will re-open if people can confirm that they ran into this issue while having "administrative access" (sudo) enabled!

If you run without sudo access, then RD cannot update the symlink and you have to run

```
docker context use rancher-desktop
```

to tell `docker` to use the RD context to find the socket.

I know the dialogs are not really clear about this and have opened #2178 to improve this.

So if anybody experiences this issue while using "sudo" mode, please respond here, and I'll re-open. I still don't know what we can do about it, as there hasn't been enough information to reproduce the problem, but let's see what people report!

**Comment by a4z** [comment] 2022-05-07 07:15
That could actually be the solution, you describe here. 
Good that this is now added to the issue + a link to the more descriptive issue.
Thanks a lot, @jandubois !

**Comment by danlester** [comment] 2022-05-10 07:48
@jandubois I have definitely never attempted to run in anything other than sudo mode. Having said that, I don't believe that Rancher always ends up asking for my password when it starts up, so I think there could be something wrong there instead...

**Comment by netpoetica** [comment] 2022-05-31 23:45
I personally cannot get Rancher Desktop to work at all because of this series of issues, including downgrading to previous version. Have tried all suggestions from this and associated Issues, but there is something really borked with accessing the sock file.
```
$ docker context ls
NAME                DESCRIPTION                               DOCKER ENDPOINT                            KUBERNETES ENDPOINT                ORCHESTRATOR
colima              colima                                    unix:///Users/XXXX/.colima/docker.sock                                      
default             Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                https://127.0.0.1:6443 (default)   swarm
rancher-desktop *   Rancher Desktop moby context              unix:///Users/XXXX/.rd/docker.sock       https://127.0.0.1:6443 (default)   

$ docker ps
Cannot connect to the Docker daemon at unix:///Users/XXXX/.rd/docker.sock. Is the docker daemon running?

$ ls -lash ~/.rd
ls: /Users/XXXX/.rd: No such file or directory

$ ls -lash /var/run/ | grep docker
0 srw-rw-rw-   1 root             daemon              0B May 31 14:20 com.docker.vmnetd.sock
```

I use Rancher Desktop on windows without issue, but here on my Mac, I just can't find a way around this

**Comment by jandubois** [comment] 2022-05-31 23:49
@netpoetica Which version of Rancher Desktop are you running? With 1.3.0 you should definitely have a `~/.rd` directory; I don't see how that can not be created without throwing an error.

If this is 1.3.0, can you share the log files? Or at least look through them yourself to see if you find anything suspicious?

**Comment by netpoetica** [comment] 2022-05-31 23:51
When i was running 1.3.0, I did had that folder, but then I downgraded to 1.2.1. Everything you are seeing there is from 1.2.1. I can try to reinstall 1.3.0 again and see if logs give me anything. It is not clear to me why 1.2.1 was still looking for ~/.rd though

**Comment by jandubois** [comment] 2022-05-31 23:53
> It is not clear to me why 1.2.1 was still looking for ~/.rd though

It isn't. I think 1.2.1 does not create a docker context at all; it relies on being able to create the symlink at `/var/run/docker.sock` and you need to switch back to the default context to use it.
