### ISSUE TITLE
official redis containers do not launch on 1.2.1

### ISSUE THREAD

**Issue by bwhicks-colpal** [rancher-sandbox/rancher-desktop#2104] opened 2022-04-26 14:33 UTC
### Actual Behavior

When attempting to run any official redis container on MacOS 12.1, `nerdctl` fails to start a container (also when invoked as part of `nerdctl` compose) and complains that it could not start shim.

### Steps to Reproduce

Run `nerdct run redis`

### Result

```
FATA[0000] failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: time="2022-04-26T14:29:20Z" level=fatal msg="json: cannot unmarshal array into Go struct field Meta.ExtraHosts of type map[string]string"
Failed to write to log, write /var/lib/nerdctl/dbb19c5e/containers/default/694c406adec76d3bc7819af298297e763da9ca3a42644858de4cd4431b7a5d56/oci-hook.createRuntime.log: file already closed: unknown
```

### Expected Behavior

Container starts

### Rancher Desktop Version

1.2.1

### Rancher Desktop K8s Version

1.21.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Mac OS 10.2

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment] 2022-05-10 22:17
I cannot reproduce this I tried both macOS 10.15.5 and 12.3.1, and it worked fine on either setup:

```console
$ sw_vers
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258

$ nerdctl run redis
1:C 10 May 2022 22:14:58.369 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 10 May 2022 22:14:58.369 # Redis version=7.0.0, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 10 May 2022 22:14:58.369 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 10 May 2022 22:14:58.370 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
1:M 10 May 2022 22:14:58.371 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
1:M 10 May 2022 22:14:58.371 # Current maximum open files is 1024. maxclients has been reduced to 992 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
1:M 10 May 2022 22:14:58.371 * monotonic clock: POSIX clock_gettime
1:M 10 May 2022 22:14:58.371 * Running mode=standalone, port=6379.
1:M 10 May 2022 22:14:58.372 # Server initialized
1:M 10 May 2022 22:14:58.372 * The AOF directory appendonlydir doesn't exist
1:M 10 May 2022 22:14:58.372 * Ready to accept connections
```

I have to close this as non-reproducible; feel free to re-open if you have additional information that would help to reproduce the issue!

**Closed by jandubois** 2022-05-10 22:17 UTC
Labels: kind/bug, platform/macos
