### ISSUE TITLE
Setting irrelevant settings should not cause a restart

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#3601] opened 2022-12-10 00:50 UTC
### Actual Behavior

Setting the Kubernetes version when it's disabled still causes a restart. It should not do so.

### Steps to Reproduce

1. `rdctl set --container-engine containerd --kubernetes-enabled=false --kubernetes-version=1.24.3`
  This may cause a restart; that's fine.
2. `rdctl set --container-engine containerd --kubernetes-enabled=false --kubernetes-version=1.25.4`

### Result

> `Status: reconfiguring Rancher Desktop to apply changes (this may take a while).`

The backend restarts.

### Expected Behavior

The backend does not restart, as the Kubernetes version does not matter while it's disabled.

### Additional Information

It's unclear if we need to wipe (unused) Kubernetes data on downgrades. But I think we already have code to handle that?

### Rancher Desktop Version

1.6.0-525-g675b482e

### Rancher Desktop K8s Version

1.24.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 21H2 (Build 22000.1042)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

None applicable.

**Comment by jandubois** [comment] 2022-12-10 05:50
Duplicate of #3269

**Closed by jandubois** 2022-12-10 05:50 UTC
Labels: kind/bug, platform/windows, area/kubernetes
