### ISSUE TITLE
Home directory is not shared with Lima VM on MacOS

### ISSUE THREAD

**Issue by shubb30** [rancher-sandbox/rancher-desktop#1238] opened 2022-01-13 13:06 UTC
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

1.21.7

### What operating system are you using?

macOS

### Operating System / Build Version

OSX Catalina 10.15.7

### What CPU architecture are you using?

x64

### Actual Behavior

Per a comment in the Slack channel, the `/tmp/rancher-desktop` and `$HOME` directories are supposed to be shared between the host and guest VM via sshfs.  The `$HOME` directory should be `/home/$USER.linux` on the Lima VM.

I have mounted the `/` partition in the VM into `/mnt/root` in a container, and when I look in the mount on the container, all I see is `/home/<username>.linux/bin/install-k3s`.

I do see that files in `/tmp/rancher-desktop` are visible inside the Lima VM's filesystem, but `$HOME` is not.

### Steps to Reproduce

Apply the manifest:  

```
apiVersion: v1
kind: Namespace
metadata:
  name: voltest

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mylabel: voltest
  name: voltest
  namespace: voltest
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      mylabel: voltest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        mylabel: voltest
    spec:
      affinity: {}
      containers:
      - image: alpine:3.13
        imagePullPolicy: Always
        name: container-0
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /mnt/root
          name: host-mount
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /
          type: Directory
        name: host-mount
```

### Result

Then exec into the container and see that there is only the `install-k3s` binary in HOME, but /tmp/rancher-desktop does share files with the host:

```
$ k get pods -n voltest
NAME                       READY   STATUS    RESTARTS   AGE
voltest-5f58c84d6d-dsxf5   1/1     Running   0          20s
$ k exec -it -n voltest voltest-5f58c84d6d-dsxf5 sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
/ # ls -al /mnt/root/home/<username>.linux/
total 20
drwxr-xr-x    4 501      1000          4096 Jan 13 12:26 .
drwxr-xr-x    3 root     root          4096 Dec  2 21:24 ..
-rw-r--r--    1 501      1000            62 Jan 13 12:26 .profile
drwx------    2 501      1000          4096 Dec  2 21:24 .ssh
drwxr-xr-x    2 501      1000          4096 Dec  2 21:24 bin
/ # ls -al /mnt/root/home/<username>.linux/bin/
total 12
drwxr-xr-x    2 501      1000          4096 Dec  2 21:24 .
drwxr-xr-x    4 501      1000          4096 Jan 13 12:26 ..
-rwxr-xr-x    1 501      1000           821 Jan 13 12:26 install-k3s
/ #
/ # ls -al /mnt/root/tmp/rancher-desktop/
total 0
-rw-r--r--    1 501      root             0 Jan 12 18:23 ISTHISHERE
-rw-r--r--    1 501      root             0 Jan 13 12:51 WHATABOUTTHIS
/ #
```

### Expected Behavior

The contents of `/mnt/root/home/<username>.linux/` should be the same as `/Users/<username>` on the Mac

**Comment by jandubois** [comment] 2022-02-09 00:06
Sorry, this issue somehow fell through the cracks! 😞 

> The contents of /mnt/root/home/<username>.linux/ should be the same as /Users/<username> on the Mac

They are intentionally not the same. The `/Users/<username>` is available under the same name as on the host, so there is no need to map filenames between guest and host locations.

The `/home/<username>.linux` directory is the actual user home directory inside the VM. It contains things like the authorized ssh keys used to log into the VM. You obviously wouldn't want those to overwrite the corresponding file on the host.

Also the `<username>` in `/home/<username>.linux` does not always match the user name on the host. When the macOS username is not a valid Linux username (e.g. it is all numeric, or an email address, or some other things people are using when authenticating via a directory service), then the name inside the VM is just `lima` instead.

I'm going to close this issue because everything is as designed. If you still have questions, please ask on Slack, or in the Github discussions.

**Closed by jandubois** 2022-02-09 00:06 UTC
Labels: kind/bug, platform/macos, component/lima
