### ISSUE TITLE
MacOS battery life punished

### ISSUE THREAD

**Issue by dancaugherty** [rancher-sandbox/rancher-desktop#935] opened 2021-11-10 14:37 UTC
**Description**
Rancher Desktop, once started, keeps the battery on MacOS machines from charging, and depletes the battery even when a MacBook is using AC power. (This is an issue that also plagues Docker Desktop.)

**Desired Solution**
It would be really nice to have a workaround  at least for this problem.

**Reproduction Steps**
Steps to reproduce the behaviour:
- Install Rancher Desktop
- Start the app

**Result**
My battery loses about 4% charge every 5 minutes.

**Expected behaviour**
The battery either charges, or at least doesn't deplete so quickly.

**Screenshots**
![Screen Shot 2021-11-10 at 9 35 09 AM](https://user-images.githubusercontent.com/3246565/141132675-fcb6c79b-48af-4847-a00b-d530aec58fd4.png)

![Screen Shot 2021-11-10 at 9 36 27 AM](https://user-images.githubusercontent.com/3246565/141132779-0db08391-dd16-4734-aec4-fac16d0a4a1e.png)

**Setup (please complete the following information):**
 - OS: MacOS Big Sur 11.5.2
 - Rancher Desktop version: 0.6.1
 - Kubernetes version: v1.21.6

**Additional context**
None

**Comment by mattfarina** [comment] 2021-11-10 20:12
Thanks for reporting this, @dancaugherty. I have some additional questions as several Rancher Desktop developers use Mac and can't reproduce your situation. I would like to better understand it. We have some follow-up questions for you?

Can you provide the model and year of the mac you're using?

Can you open _Activity Monitory_, go to the _Energy_ tab, and share what Rancher Desktop is using? If you could also share where it ranks compared to your other apps, that would be helpful.

Is the charger you're using on your Mac the one that came with it? If not, do you know what wattage it is?

Do any other apps cause a similar issue with power, aside from Docker Desktop which you've already mentioned? For example, do all electron apps or apps to manage virtual machines cause the same problem?

**Comment by dancaugherty** [comment] 2021-11-16 15:15
I think I'd like to close this for now. It turns out that I can't replicate this issue either, because of a separate one that I'm about to file.

RD seems to be behaving for me, but I'm having authN issues with pulling images from a private registry. Until I can solve that problem, I can't reproduce this one. 

Sorry for any inconvenience.

**Comment by mattfarina** [comment] 2021-11-16 16:44
Thanks for following up. Closing.

**Closed by mattfarina** 2021-11-16 16:44 UTC
Labels: platform/macos

**Comment by ramsesk** [comment] 2026-06-24 08:27
Even though this is closed and that is fine, I must say that I also do see that Rancher Desktop app is really consuming a lot of my battery, still in 2026. It is not like my battery isn't charging, but it is draining at least 2x faster compared to turning Rancher off. 

- OS: Tahoe 26.5
- Device: Macbook M1 Pro (4 years old)
- Rancher Desktop Version: 1.22.3

Not sure if this is an issue though, but I can see how someone with an old laptop and poor battery might write up this issue.
