### ISSUE TITLE
Rancher Desktop-1.12.3 fails to start on MacOS Sonoma 14.3.1 with Apple M3 Chip

### ISSUE THREAD

**Issue by francisalexander02** [rancher-sandbox/rancher-desktop#6583] opened 2024-03-07 07:26 UTC
### Actual Behavior

Error Starting Kubernetes when opening rancher desktop
Rancher Desktop 1.12.3 - darwin (aarch64)

### Steps to Reproduce

Install & run rancher desktop in Apple M3 Chip

### Result

Error Starting Kubernetes
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura exited with code 255

Last Command Run
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura shell --workdir=. 0 sudo /bin/sh -c rm -f /usr/local/share/ca-certificates/rd-*.crt

### Expected Behavior

Kubernetes should run successfully on Macos Sonoma

### Rancher Desktop Version

1.12.3

### Rancher Desktop K8s Version

1.28.6

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Macos Sonoma 14.3.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment] 2024-03-07 08:10
Most likely a duplicate of #5943 (M3 chips are incompatible with the version of QEMU included in Rancher Desktop; need to use VZ emulation). If that is the case, use instructions in https://github.com/rancher-sandbox/rancher-desktop/issues/5943#issuecomment-1899101789 to cleanup and get started with VZ mode.

This will be fixed in the next release.

Please re-open and add log files if this wasn't the issue.

**Closed by jandubois** 2024-03-07 08:10 UTC
Labels: kind/bug
