### ISSUE TITLE
Dashboard 404 not found on Rancher desktop

### ISSUE THREAD

**Issue by sherifosama92** [rancher-sandbox/rancher-desktop#2121] opened 2022-04-28 12:21 UTC
### Actual Behavior

After fresh installation of rancher desktop v1.2.1, when trying to open the dashboard it shows 404 not found

### Steps to Reproduce

Open rancher desktop
Go to rancher icon in taskbar
right click icon and open dashboard

### Result

![Capture](https://user-images.githubusercontent.com/46084706/165750633-6517d74b-8ae8-40dc-bc14-4f69f28609a3.PNG)

### Expected Behavior

Dashboard opens normally

### Rancher Desktop Version

1.21

### Rancher Desktop K8s Version

1.23.5

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise

### What CPU architecture are you using?

x64

### Windows User Only

Sometimes I use my company VPN

**Comment by rak-phillip** [comment] 2022-04-28 17:40
@sherifosama92 thanks for raising this issue 🙂

The API that we use for the dashboard listens on ports `9080` and `9443`, can you check to see if these are already in use? If so, that might be the source of your problem.

**Comment by hsuchan** [comment] 2022-05-11 18:43
I am experiencing the same issue, going to the dashboard gives the a "404 not found" error.

OS: macOS Monterey 12.3
Rancher Desktop: v1.3.0

I checked ports 9080 and 9443 on my laptop

```
$ netstat -an | egrep "9080|9443"
tcp4       0      0  127.0.0.1.9080         *.*                    LISTEN
```

Only port 9090 is in use, and curling it returns 404
```
$ curl http://127.0.0.1:9080
<html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
```
I also tried to curl `/dashboard` but it's possible that the dashboard is located on a different path

**Comment by jandubois** [comment] 2022-05-11 20:54
> It looks like another process is already listening on tcp/9080

I'm closing this as a duplicate of #1890.

**Closed by jandubois** 2022-05-11 20:54 UTC
Labels: kind/bug, triage/needs-information, platform/windows
