### ISSUE TITLE
RD fails to start on Windows: no-modal-dialogs not supported by WSL

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#5238] opened 2023-07-26 17:46 UTC
### Actual Behavior

Right at the start up, RD fails with the following error: 
 `internalError: noModalDialogs shouldn't be used in WSL`

### Steps to Reproduce

1. Start Rancher Desktop (build from https://github.com/rancher-sandbox/rancher-desktop/actions/runs/5662045223)

### Result

From `background.log`: 

```
2023-07-26T17:14:12.579Z: Kubernetes was unable to start: Error: internalError: noModalDialogs shouldn't be used in WSL
    at get noModalDialogs [as noModalDialogs] (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:31:211721)
```
[background.zip](https://github.com/rancher-sandbox/rancher-desktop/files/12175840/background.zip)

### Expected Behavior

RD should start with no errors

### Rancher Desktop Version

1.9.1-375-g7689f076

### Rancher Desktop K8s Version

1.27.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment] 2023-07-26 18:00
Looks like a duplicate of #5228

**Closed by jandubois** 2023-07-26 18:00 UTC
Labels: kind/bug
