### ISSUE TITLE
NetworkingMode wsl2 problem

### ISSUE THREAD

**Issue by thazalega** [rancher-sandbox/rancher-desktop#7106] opened 2024-06-27 18:05 UTC
### Actual Behavior

if you have set the networkingmode in the .wslconfig file set to mirrored the setup of rancher desktop will stop at "waiting for kubernetes api"

### Steps to Reproduce

set networking mode in the .wslconfig file to mirroed(since windows 11 posible)

### Result

not able to finish the setup of kubernetes

### Expected Behavior

if posible checking if a .wslconfig file exists in the users directory and  if exists looking for a line with "networkingMode=mirrored" when it is the case inform the user to change it. 

### Rancher Desktop Version

1.14.2

### Rancher Desktop K8s Version

1.29.5

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Home, 23H2, 22635.3672

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by oidualc** [comment] 2024-07-09 07:58
Duplicate of #6665

**Comment by jandubois** [comment] 2024-07-09 18:10
> Duplicate of #6665

Thanks!

**Closed by jandubois** 2024-07-09 18:10 UTC
Labels: kind/bug, triage/duplicate
