### ISSUE TITLE
Containers Should Reload periodically or have a refresh button

### ISSUE THREAD

**Issue by RamiKassouf** [rancher-sandbox/rancher-desktop#6385] opened 2024-01-29 13:11 UTC
### Problem Description

When you open the containers tab you can only see the containers running or not at the moment :
That means that any update is not shown on the GUI and you would need to go to another section then back to containers again to update it

### Proposed Solution

Periodic Update

or

A simple Refresh button

**Comment by jandubois** [comment] 2024-01-29 16:57
This looks like a duplicate of #5775

**Closed by jandubois** 2024-01-29 16:57 UTC
Labels: kind/enhancement
