### ISSUE TITLE
"No active cluster" when run as non-Admin

### ISSUE THREAD

**Issue by fmabx** [rancher-sandbox/rancher-desktop#1574] opened 2022-02-11 12:18 UTC
### Actual Behavior

RD is only able to start up WSL distribution when run as administrator.

### Steps to Reproduce

Close Rancher Desktop and shutdown the Rancher distro in WSL (or any other action that will shut it down). Now start RD without administrator privileges.

### Result

`Error: No active cluster!`

### Expected Behavior

Either RD starts the WSL distro or prompts the user for administrator privileges.

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.23.3

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise, Version 10.0.19042 Build 19042

### What CPU architecture are you using?

x64

### Windows User Only

Corporate VPN (F5 client) and proxy (http) is used. Been able to make it work by adding env variables for proxy to "/etc/rc.conf". 
My company uses Palo Alto Cortex.

**Comment by adamkpickering** [comment] 2022-02-11 21:06
Thanks for the bug report! Have you tried doing a factory reset? Have you always been running RD as an admin? What actions did you take when you first installed it?

> shutdown the Rancher distro in WSL (or any other action that will shut it down)

If you're shutting RD down by killing the VM I could see this causing problems. The recommended way to shut it down is by opening the menu from the system tray (should be on the menu bar on the bottom right) and quitting RD from there.

If you're able to post some logs that would help. If you're able, can you enable debug mode, reproduce the problem and then post your logs?

**Comment by Shabahang** [comment] 2022-02-15 09:13
Same for me , on both containerd and moby . 
same windows client and RD 1.0.0 and 1.0.1

**Comment by jandubois** [comment] 2022-02-16 00:27
I think this is a duplicate of #1536 (and #1470).

Can you please double-check if you have different settings for `%USERPROFILE%` vs `%HOMEDRIVE%%HOMEPATH%`.

In that case this bug should be fixed by the next release (probably later next week). If you can still reproduce your problem with that version, please re-open this issue or create a new one.

**Closed by jandubois** 2022-02-16 00:27 UTC
Labels: kind/bug, platform/windows, runtime/moby

**Comment by fmabx** [comment] 2022-02-16 07:15
> I think this is a duplicate of #1536 (and #1470).
> 
> Can you please double-check if you have different settings for `%USERPROFILE%` vs `%HOMEDRIVE%%HOMEPATH%`.
> 
> In that case this bug should be fixed by the next release (probably later next week). If you can still reproduce your problem with that version, please re-open this issue or create a new one.

I can confirm. My company has set "C:\Users\username for " `%USERPROFILE%` and `%HOMEDRIVE%%HOMEPATH%` points to a network share.
