### ISSUE TITLE
After installing Rancher Desktop 1.6.0 Docker and nerdctl are not recognized on reboot 

### ISSUE THREAD

**Issue by Mavrick2020** [rancher-sandbox/rancher-desktop#3194] opened 2022-10-18 11:39 UTC
### Actual Behavior

C:\>docker -v
'docker' is not recognized as an internal or external command,
operable program or batch file.

### Steps to Reproduce

Install Rancher Desktop
Check the docker and/or nerdctl commands via windows Command prompt, one can see the appropriate execution.
Reboot the system
Check the docker and/or nerdctl commands via windows Command prompt. This time system doesn't recognize docker and/or nerdctl.

### Result

C:\>docker -v
'docker' is not recognized as an internal or external command,
operable program or batch file.

There are no other errors observed.

### Expected Behavior

the system should be recognizing docker and/or nerdctl commands via windows Command prompt

### Additional Information

1]
C:\>wsl -l -v
  NAME                    STATE           VERSION
* rancher-desktop         Running         2
  rancher-desktop-data    Stopped         2

2] List of images is getting populated

3] Diagnostics 
No problems detected
Rancher Desktop appears to be functioning correctly.

### Rancher Desktop Version

1.6.0

### Rancher Desktop K8s Version

1.24.6

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Professional ver 10.0.19041

### What CPU architecture are you using?

x64

### Windows User Only

N/A

**Comment by Mavrick2020** [comment] 2022-10-19 07:50
Identified the issue. The Rancher Desktop installation path is not persisted on the subsequent reboot.  
Remedy:
After manually adding the path to the environment variable it recognizes the docker and nerdctl commands.

This needs to be fixed in the upcoming release.

**Comment by gunamata** [comment] 2022-11-01 19:50
I couldn't reproduce the issue on Windows 10 Professional and Enterprise machines. I followed below steps.

- Installed Rancher Desktop 1.6.1
- Verified that `docker` command works in a terminal
- Rebooted machine
- Verified that `docker` command works in a terminal

@Mavrick2020 - Are you able to consistently reproduce this issue?

**Comment by gunamata** [comment] 2023-02-08 04:44
Closing the issue as we could not reproduce. @Mavrick2020 , Please feel free to reopen with steps to reproduce, if you run into this issue again.

**Closed by gunamata** 2023-02-08 04:44 UTC
Labels: kind/bug, platform/windows, area/utilities, triage/need-to-repro
