### ISSUE TITLE
Can't disable WSL integrations

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5724] opened 2023-10-12 21:06 UTC
### Actual Behavior

At the pref panel `WSL/Integrations` I have checkboxes for both `Debian` and `Ubuntu`. Once I check one of them, if I try to uncheck it, the next time the pref panel comes up, after a restart, it's still checked.

### Steps to Reproduce

See above

### Result

See above

### Expected Behavior

The uncheckedness should persist until it's checked again.

### Rancher Desktop Version

1.10

### Rancher Desktop K8s Version

1.28.2

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

n/a

**Comment by jandubois** [comment] 2023-10-12 21:31
I've put this into 1.11 because it looks like a regression to me. If it isn't, then it can be moved to 1.12.

**Comment by ericpromislow** [comment] 2023-10-12 21:42
I don't know if it is -- my windows box is tied up reviewing PRs, but I had 1.10 installed and it failed there.

**Comment by ericpromislow** [comment] 2023-10-12 22:35
Same problem with the 1.9 release

**Comment by gunamata** [comment] 2023-10-30 22:43
Is this a duplicate of #5805 @ericpromislow ?

**Closed** 2023-10-30 23:05 UTC
Labels: kind/bug, platform/windows, area/preferences
