### ISSUE TITLE
Image scanning appears broken

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#481] opened 2021-08-11 14:39 UTC
If I click on the "Scan" option for an image it appears as though nothing happens.

![Capture](https://user-images.githubusercontent.com/62991/129049352-e2184055-0f1b-48a9-9a31-5a04c70362b5.PNG)

This is because the text area that shows the output is below the list. There is no scrolling to it. If you don't know it's there you don't discover it. The feature just looks broken.

**Comment by mook-as** [comment] 2021-08-12 16:52
#488 is a dupe of this, but it looks like @ericpromislow is already working on it.

**Closed** 2021-08-12 17:05 UTC
