### ISSUE TITLE
Putting the computer in sleep mode makes container time go out of sync

### ISSUE THREAD

**Issue by snelson3** [rancher-sandbox/rancher-desktop#1170] opened 2021-12-31 00:33 UTC
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

1.21.8

### What operating system are you using?

macOS

### Operating System / Build Version

Big Sur 11.6.2 Macbook Pro

### What CPU architecture are you using?

x64

### Actual Behavior

When the computer is put into sleep mode while Rancher Desktop is running, when it is brought out of sleep mode the system clock of the docker containers will be out of sync with the host machine, by however long the computer was in sleep mode for

### Steps to Reproduce

Start Rancher Desktop
Verify that date is the same on the host and inside the docker container
Put the computer in sleep mode
Wait 5 minutes
Wake the computer up
Check date again and see the time is out of sync

### Result

* Started Rancher Desktop

```
(base) AMAC02FD37XMD6R:~ sam.s.nelson$ date
Thu Dec 30 16:19:45 PST 2021
(base) AMAC02FD37XMD6R:~ sam.s.nelson$ nerdctl run -ti alpine
WARN[0000] kernel support for cgroup blkio weight missing, weight discarded
/ # date
Fri Dec 31 00:19:53 UTC 2021
/ # exit
```

* Computer put in sleep mode, set 5 minute time, wake it up when timer goes off

```
(base) AMAC02FD37XMD6R:~ sam.s.nelson$ date
Thu Dec 30 16:25:53 PST 2021
(base) AMAC02FD37XMD6R:~ sam.s.nelson$ nerdctl run -ti alpine
WARN[0000] kernel support for cgroup blkio weight missing, weight discarded
/ # date
Fri Dec 31 00:21:43 UTC 2021
```

### Expected Behavior

The time to still be in sync between host and container. This makes things like AWS commands in the container fail because AWS requires the client system time to be within a few minutes of the AWS servers time.

**Comment by jandubois** [comment] 2021-12-31 05:43
Duplicate of #839. Will be fixed by https://github.com/lima-vm/lima/pull/490.

**Closed by jandubois** 2021-12-31 05:43 UTC
Labels: bug, duplicate
