### ISSUE TITLE
Time in containers is off

### ISSUE THREAD

**Issue by some-user123** [rancher-sandbox/rancher-desktop#3782] opened 2023-01-16 14:32 UTC
### Actual Behavior

The time in my container and the time on the host machine differ significantly:

```bash
$ date -R; docker run -it ubuntu date -R
Mon, 16 Jan 2023 15:22:01 +0100
Mon, 16 Jan 2023 12:52:52 +0000
```

The time on the host machine is correct.

### Steps to Reproduce

Unfortunately, I don't know for sure, when this happens. It's fixed by rebooting the host machine. Stopping & starting Rancher Desktop does not help.

### Result

See above, time differs, time in container is wrong.

### Expected Behavior

Time in container and host should be the same (apart from time zone issues...).

### Rancher Desktop Version

1.7.0

### Rancher Desktop K8s Version

K8s is not enabled

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Enterprise 22H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

GlobalProctect VPN (but not always running)
Trellix AntiVirus (always on)

**Comment by mook-as** [comment] 2023-01-16 19:20
Hmm, odd; we're not doing anything about time on Windows at all (it's all managed by WSL). That's also the reason that restarting Rancher Desktop doesn't work — you will also need to run `wsl --shutdown` to force the WSL VM to terminate.

**Comment by gunamata** [comment] 2023-01-17 00:26
I couldn't repro on my machine. I have tried locking the machine, trying after hibernate etc., but couldn't reproduce. A quick google search lead me to this issue thread (https://github.com/microsoft/WSL/issues/4245)  on the WSL repo where  running `sudo hwclock -s` or `sudo ntpdate pool.ntp.org` seem to have helped some users. @some-user123 , You may want to try these commands when you run into the issue next time.

Closing the issue for now as we are not able to repro, and the issue doesn't seem like something we can address in Rancher Desktop.

**Closed by gunamata** 2023-01-17 00:26 UTC
Labels: kind/bug
