### ISSUE TITLE
Not able to install Rancher Desktop on MAC

### ISSUE THREAD

**Issue by vidhyasgr** [rancher-sandbox/rancher-desktop#1434] opened 2022-02-01 10:23 UTC
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

1.22.6

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Big Sur Version 11.6

### What CPU architecture are you using?

x64

### Actual Behavior

Showing exception

### Steps to Reproduce

Just a normal installation cause this issue.

### Result

![Uploading Bildschirmfoto 2022-02-01 um 10.40.33.png…]()

### Expected Behavior

It works properly

**Comment by evertonlperes** [comment] 2022-02-01 12:16
@vidhyasgr 
Could you provide some logs about your issue?
You can find the logs on `Troubleshooting tab` - see more [here](https://docs.rancherdesktop.io/preferences#show-logs)

**Comment by mook-as** [comment] 2022-02-01 20:53
FWIW, this was spawned from #1433 and the screenshot there indicates the issue is that the lima path is too long — which makes this a duplicate of #797.  There's a workaround there, and we _do_ intend to fix the issue so that the workaround would not be necessary, but that will be tracked in #797 instead.

Thanks for reporting the issue!

**Closed by mook-as** 2022-02-01 20:53 UTC
Labels: kind/bug, triage/needs-information, platform/macos
