### ISSUE TITLE
Issues with root certificates seems to keep Rancher Desktop from even starting

### ISSUE THREAD

**Issue by mar1ged** [rancher-sandbox/rancher-desktop#1072] opened 2021-12-06 10:12 UTC
### Rancher Desktop Version

0.6.1

### Rancher Desktop K8s Version

(none, I'm not even able to choose)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 20H2

### What CPU architecture are you using?

x64

### Windows User Only

authenticating proxy needed for Internet Access

### Actual Behavior

Rancher Desktop stays silent and doesn't even display something on screen.

### Steps to Reproduce

Start executable

### Result

output as can be seen in the log. Btw: when I run the executable directly from commandline it creates a file with 2.3 MB of content when redirected to a file

[background.log](https://github.com/rancher-sandbox/rancher-desktop/files/7659850/background.log)

### Expected Behavior

Rancher Desktop on screen, silent log ;-)

### Additional Information

For some other issue I saw I created a separate issue: https://github.com/rancher-sandbox/rancher-desktop/issues/1071

**Comment by mattfarina** [comment] 2021-12-06 17:44
@mar1ged Thanks for filing this issue. Would you be able to share you wsl.log as well.

**Comment by mar1ged** [comment] 2021-12-08 08:49
@mattfarina I would like to, but it is exactly 0 byte. Similar to all the other log files, only k8s.log contains a single line stating: `Updating release version cache`

**Comment by mar1ged** [comment] 2022-02-09 07:06
Just wanted to let you know that when I checked https://github.com/rancher-sandbox/rancher-desktop/issues/1071 with release 1.0.1 I saw that the problem with the `ENOBUFS` error still exists.

Could it be that the buffer is just too small to keep the 2,3MB of content that the executable creates due to the big amount of CAs on my machine ?

**Comment by jstsddg** [comment] 2022-02-11 10:16
I have the same problem with release 1.0.1 on Windows 10 Enterprise 1909.
For me the executable creates `1.072.472 Bytes`, so the buffer size might be around 1MB?

**Comment by justusbunsi** [comment] 2022-02-21 14:04
Thanks for the hint with the CAs amount. Got it working by removing approx. 60 expired root certificates.
`Get-ChildItem cert:\LocalMachine\root|Where {$_.NotAfter -lt  (Get-Date).AddDays(60)}` to list those expired 60 days in the past.
`Get-ChildItem cert:\LocalMachine\root|Where {$_.NotAfter -lt  (Get-Date).AddDays(60)} | Remove-Item` to actually remove these.

🙏 Thanks. Now I am able to develop properly.

**Comment by hsolon** [comment] 2022-02-21 19:55
> Thanks for the hint with the CAs amount. Got it working by removing approx. 60 expired root certificates. `Get-ChildItem cert:\LocalMachine\root|Where {$_.NotAfter -lt (Get-Date).AddDays(60)}` to list those expired 60 days in the past. `Get-ChildItem cert:\LocalMachine\root|Where {$_.NotAfter -lt (Get-Date).AddDays(60)} | Remove-Item` to actually remove these.
> 
> pray Thanks. Now I am able to develop properly.

This was my issue too.  I had found an expired cert in the cert chain and removed the offending proxy cert and it is working now: I made a variable for the specific cert and removed it: 
`$thumb = <cert thumbprint>`
`get-childitem Cert:/ -recurse | where-object {$_.thumbprint -contains "$thumb"}`

**Comment by jandubois** [comment] 2022-02-22 03:52
We will automatically exclude expired certs in the next release: #1613 

Not sure how this relates to the `ENOBUFS` error though, so leaving this issue open. It would be helpful if @justusbunsi and @hsolon could confirm if they got the `ENOBUFS` error as well, or some other certificate related error message, like a `FetchError`!

**Comment by justusbunsi** [comment] 2022-02-22 05:14
> We will automatically exclude expired certs in the next release: #1613 
> 
> Not sure how this relates to the `ENOBUFS` error though, so leaving this issue open. It would be helpful if @justusbunsi and @hsolon could confirm if they got the `ENOBUFS` error as well, or some other certificate related error message, like a `FetchError`!

I can confirm that my background.log looked exactly the same as from the initial issue description including `ENOBUFS` caused by win-ca.

**Comment by hsolon** [comment] 2022-02-23 13:04
@jandubois I am not able to confirm if I had the ENOBUFS error.  I had uninstall/reinstall for unrelated reasons and did not grab the log file :(

**Comment by mantawolf** [comment] 2022-03-11 20:11
I removed my expired certs, didnt have that many, and still getting fail for same reason.

2022-03-11T20:10:35.123Z: Error starting up: <ref *1> Error: spawnSync C:\Users\meads\AppData\Local\Programs\Rancher Desktop\resources\app.asar.unpacked\node_modules\win-ca\lib\roots.exe ENOBUFS
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:821:24)
    at Object.execFileSync (node:child_process:867:15)
    at Object.func [as execFileSync] (node:electron/js2c/asar_bundle:5:2027)
    at Object.run (C:\Users\meads\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\win-ca\lib\fallback.js:43:26)
    at api (C:\Users\meads\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\win-ca\lib\index.js:60:10)
    at C:\Users\meads\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:161624
    at C:\Users\meads\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:162210 {
  errno: -4060,
  code: 'ENOBUFS',
  syscall: 'spawnSync C:\\Users\\meads\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\app.asar.unpacked\\node_modules\\win-ca\\lib\\roots.exe',
  path: 'C:\\Users\\meads\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\app.asar.unpacked\\node_modules\\win-ca\\lib\\roots.exe',
  spawnargs: [ 'root', 'ca' ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    <Buffer 33 30 38 32 30 33 62 32 33 30 38 32 30 32 39 61 61 30 30 33 30 32 30 31 30 32 30 32 31 30 31 63 65 39 39 36 31 31 38 33 35 30 65 63 61 35 34 35 62 34 ... 1049134 more bytes>,
    <Buffer >
  ],
  pid: 31828,
  stdout: <Buffer 33 30 38 32 30 33 62 32 33 30 38 32 30 32 39 61 61 30 30 33 30 32 30 31 30 32 30 32 31 30 31 63 65 39 39 36 31 31 38 33 35 30 65 63 61 35 34 35 62 34 ... 1049134 more bytes>,
  stderr: <Buffer >
}

**Comment by jandubois** [comment] 2022-03-12 01:29
> I removed my expired certs, didnt have that many, and still getting fail for same reason.

@mantawolf I think deleting expired certs is just accidentally helping some users to get the total size of all certs below 1MB. This will need to be fixed by dynamically allocated a larger buffer, or by reading the data in chunks.

**Comment by mantawolf** [comment] 2022-03-12 13:37
Yea, was hoping it would accidentally help me too 🙂

**Comment by cronventis** [comment] 2022-03-16 10:04
I'm unable to clean the certs.. So this actually makes it impossible for me to use RD.... Is there a fix on the way?

**Comment by vladonemo** [comment] 2022-03-17 10:58
Still failing for me even after clearing expired certs. Work if I downgrade to version 1.0.0.

**Comment by jandubois** [comment] 2022-03-17 17:55
> I believe that this is a regression of #1572

Yes, I think so too. The additional `ca` certs are most likely pushing you over the buffer limit.

The failing code is in an external library, and not directly part of Rancher Desktop, so it will take some additional effort to get this fixed. Unfortunately this will not make it into the next release (next week).

**Comment by vladonemo** [comment] 2022-03-18 06:25
> > I believe that this is a regression of #1572
> 
> Yes, I think so too. The additional `ca` certs are most likely pushing you over the buffer limit.
> 
> The failing code is in an external library, and not directly part of Rancher Desktop, so it will take some additional effort to get this fixed. Unfortunately this will not make it into the next release (next week).

Would it be possible to introduce a feature toggle (configuration option/switch) to disable loading of additional `ca` certs to avoid this issue? Until it gets fixed properly.

**Closed** 2022-03-28 19:55 UTC
Labels: kind/bug, platform/windows, area/proxy
