### ISSUE TITLE
After upgrade to Mac OS to Ventura (13.0 (22A380) Rancher desktop wont start if CPU memory params are modified and traefik disabled

### ISSUE THREAD

**Issue by karthichu** [rancher-sandbox/rancher-desktop#3297] opened 2022-10-28 10:03 UTC
### Actual Behavior

It gets stuck at starting services

### Steps to Reproduce

- Install Rancher desktop in Mac OS Ventura(13.0 (22A380))
- Modify memory specs of the VM to 8 GB and disable traefik
- Wait for racher desktop to start

### Result

It stays stuck at stage Waiting for services

### Expected Behavior

Racher desktop should start without any issues

### Rancher Desktop Version

1.6.1

### Rancher Desktop K8s Version

v1.25.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Mac OS Ventura(13.0 (22A380)

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment] 2022-10-28 15:48
I don't think this is related to changing CPU/memory or traefik. In our testing is looks like Kubernetes 1.24.* and 1.25.* don't work properly on Ventura, so this is likely a duplicate of #3288.

**Closed by jandubois** 2022-10-28 15:48 UTC
Labels: kind/bug

**Comment by ash-au** [comment] 2022-10-29 12:42
@jandubois this issue appears with kubernetes version 1.23.13 as well

**Comment by mboiman** [comment] 2022-11-03 06:10
have the same problem
