### ISSUE TITLE
Windows: rancher-desktop unable to import into wsl2 when username contains a space

### ISSUE THREAD

**Issue by thehejik** [rancher-sandbox/rancher-desktop#1502] opened 2022-02-04 13:02 UTC
### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

v1.22.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Win10 Pro 21H2

### What CPU architecture are you using?

x64

### Actual Behavior

After successfull installation of rancher-desktop on win 10 pro 21h2 the rancher-desktop is throwing an error that wsl2 is unable to import the rancher-desktop wsl image.

After a sec following error will show up in a new window:

```
Kubernetes Error
Error Starting Kubernetes
Error: wsl.exe exited with code 4294967295
Last command run:
wsl --import rancher-desktop C:\Users\Mighty User\AppData\Local\rancher-desktop\distro C:\Users\Mighty User\AppData\Local\Programs\Rancher Desktop\resources\resources\win32\distro-0.12.1.tar --version 2

Context:
Starting Kubernetes

Some recent logfile lines:
2022-02-04T12:47:17.572Z: Running command wsl --list --quiet...
2022-02-04T12:47:17.865Z: Registered distributions: 
2022-02-04T12:47:17.873Z: Running command wsl --list --quiet...
2022-02-04T12:47:17.944Z: Registered distributions: 
2022-02-04T12:47:17.944Z: Running command wsl --list --quiet...
2022-02-04T12:47:18.003Z: Registered distributions: 
2022-02-04T12:47:18.005Z: Running command wsl --import rancher-desktop C:\Users\Mighty User\AppData\Local\rancher-desktop\distro C:\Users\Mighty User\AppData\Local\Programs\Rancher Desktop\resources\resources\win32\distro-0.12.1.tar --version 2...
2022-02-04T12:47:18.315Z: WSL failed to execute wsl.exe --import rancher-desktop C:\Users\Mighty User\AppData\Local\rancher-desktop\distro C:\Users\Mighty User\AppData\Local\Programs\Rancher Desktop\resources\resources\win32\distro-0.12.1.tar --version 2: Error: wsl.exe exited with code 4294967295
```

### Steps to Reproduce

Create an user in Windows with space in his username like 'Mighty User', install rancher-desktop 1.0.1 and run Rancher Desktop by using desktop icon. 

Wait for the error window.

### Result

Error in wsl2 import.

### Expected Behavior

Even with space in username it should be able to run.

### Additional Information

Once user escape the paths in cmd shell and execute the command then rancher-deskop is able to run.

```
wsl.exe --import rancher-desktop "C:\Users\Mighty User\AppData\Local\rancher-desktop\distro" "C:\Users\Mighty Userl\AppData\Local\Programs\Rancher Desktop\resources\resources\win32\distro-0.12.1.tar" --version 2
```

**Comment by ericpromislow** [comment] 2022-02-04 18:27
Well, spaces are indeed valid username characters on Windows, and we've always tried to ensure any command-line argument that can contain user-supplied content is quoted, so thanks. But I noticed in the sample command you've got `wsl.exe --import rancher-desktop "C:\Users\Mighty User\…" "C:\Users\Mighty Userl\…` . Is that a verbatim copy-paste, or did you retype it and add the extraneous `l` in the second path argument? Because if it's verbatim, that's a different problem.

**Comment by mook-as** [comment] 2022-02-04 18:43
Odd, I'd have expected that to work (my test user in my VM is named `Jöé Smîth` to catch spaces and non-ASCII names).  I suspect there's some _other_ difference here, though I'm not sure what that might be.

As noted, this is a VM, so there's no fancy roaming profiles involved here…

**Comment by thehejik** [comment] 2022-02-07 08:37
>`wsl.exe --import rancher-desktop "C:\Users\Mighty User\…" "C:\Users\Mighty Userl\…` . Is that a verbatim copy-paste, or did you retype it and add the extraneous `l` in the second path argument? Because if it's verbatim, that's a different problem.

Sorry, it's just a typo, I retype my original username here (which also doesn't contain any non-ASCII character).

**Comment by ericpromislow** [comment] 2022-02-08 02:27
I can't figure this out. I did discover that I can't run a build or a dev run from a directory that contains a space, but that's not surprising. But on all our platforms production runs usually involve a path containing at least one space, without a problem.

The workaround isn't straightforward -- you can run that `import` command from the command-line, but the procedure to set up the `rancher-desktop-data` is a little more involved. Rather than walk you through it, what happens if you start up Rancher Desktop again?

Also, it might help to delete `AppData/Local/rancher-desktop` and `AppData/Roaming/rancher-desktop` before re-running.

**Comment by thehejik** [comment] 2022-02-09 14:46
I'm unable reproduce it anymore, this is what I did before (fresh) re-installing 1.0.1, I was using the exactly same env as before.

* uninstalled the rancher-desktop app
* `wsl --unregister rancher-desktop`
* `wsl --unregister rancher-desktop-data`
* removed `AppData/rancher-desktop*` and `AppData/Roaming/rancher-desktop`

The rancher-desktop is running and everything seems to be ok now. 

Only difference IIRC is that [wsl kernel update](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi) has been already in place prior re-running the rd installer.

**Comment by jandubois** [comment] 2022-02-09 18:52
Closing as not reproducible. Please re-open if it happens again!

**Closed by jandubois** 2022-02-09 18:52 UTC
Labels: kind/bug
