### ISSUE TITLE
Unable to start k8s in Rancher desktop 

### ISSUE THREAD

**Issue by satya543212003** [rancher-sandbox/rancher-desktop#4605] opened 2023-05-04 11:29 UTC
### Actual Behavior

on rancher desktop restart in Mac, I get the following error starting k8s
on installation earlier it started fine.
even after rest , uninstall, reinstall same issue:

2023-05-04T10:58:46.965Z: > /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura shell --workdir=. 0 sudo /bin/sh -c if [ -e /etc/init.d/k3s ]; then /sbin/rc-service --ifstarted k3s stop; fi
2023-05-04T10:58:47.086Z: > limactl copy /var/folders/w8/qzscy4hj2jq3mryj1b1f58c00000gn/T/rd-nginx.conf-DlZlSI/nginx.conf 0:/tmp/rd-nginx.conf-DlZlSI.nginx.conf
$ Error: spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
  path: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
  spawnargs: [
    'copy',
    '/var/folders/w8/qzscy4hj2jq3mryj1b1f58c00000gn/T/rd-nginx.conf-DlZlSI/nginx.conf',
    '0:/tmp/rd-nginx.conf-DlZlSI.nginx.conf'
  ]
}
2023-05-04T10:58:47.151Z: Lima: executing: sudo rm -f /tmp/rd-nginx.conf-DlZlSI.nginx.conf: Error: spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura EACCES
2023-05-04T10:58:47.151Z: Error starting lima: Error: spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
  path: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
  spawnargs: [
    'shell',
    '--workdir=.',
    '0',
    'sudo',
    'rm',
    '-f',
    '/tmp/rd-nginx.conf-DlZlSI.nginx.conf'
  ]
}
2023-05-04T10:58:47.206Z: > limactl copy /var/folders/w8/qzscy4hj2jq3mryj1b1f58c00000gn/T/rd-nerdctl-xkKoa3/nerdctl 0:/tmp/rd-nerdctl-xkKoa3.nerdctl
2023-05-04T10:58:47.225Z: Lima: executing: chmod 755 /tmp/rd-nerdctl-xkKoa3.nerdctl: Error: spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura EACCES
2023-05-04T10:58:47.332Z: > /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura shell --workdir=. 0 sudo rm -f /tmp/rd-nerdctl-xkKoa3.nerdctl
2023-05-04T10:58:47.333Z: Error trying to start/update containerd: Error: spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura EACCES:  Error: spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
  path: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
  spawnargs: [
    'shell',
    '--workdir=.',
    '0',
    'chmod',
    '755',
    '/tmp/rd-nerdctl-xkKoa3.nerdctl'
  ]
}
2023-05-04T10:58:50.749Z: > /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura shell --workdir=. 0 sudo /bin/sh -c rm -f /usr/local/share/ca-certificates/rd-*.crt
2023-05-04T10:58:50.881Z: > limactl copy /var/folders/w8/qzscy4hj2jq3mryj1b1f58c00000gn/T/rd-ca-gO7k4N/certs.tar 0:/tmp/certs.tar
2023-05-04T10:58:50.979Z: > /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura shell --workdir=. 0 sudo tar xf /tmp/certs.tar -C /usr/local/share/ca-certificates/
2023-05-04T10:58:51.141Z: > /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura shell --workdir=. 0 sudo update-ca-certificates

### Steps to Reproduce

I restarted Rachel desktop on Mac after several days.
"Kubernetes has encountered and error."

/var/folders/w8/qzscy4hj2jq3mryj1b1f58c00000gn/T/rd-nginx.conf-DlZlSI/nginx.conf  is not even present. 
why is it trying to copy nginx?
where is it picking up this location from?

similarly /tmp/rd-nginx.conf-DlZlSI.nginx.conf' is not present.

### Result

cannot use k8s

### Expected Behavior

should start up flawlessly.

### Rancher Desktop Version

1.8.1

### Rancher Desktop K8s Version

1.26.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Venture 13.3.1

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by dpmerrill** [comment] 2023-07-10 17:30
Unable to reproduce so far.  Rancher Desktop starts and runs with no errors after running for days.  There are also no NGINX files in any of my /var/folders or /tmp directories...
I'll give it another try in a few days.  If you can think of anything else to help us reproduce this, let us know.

**Comment by dpmerrill** [comment] 2023-07-19 16:42
Unable to reproduce on Ventura 13.4

**Comment by jandubois** [comment] 2023-09-14 21:01
> An interesting tidbit is that the UI says x86_64

That is normal; the UI bits are still x86_64 code executing via Rosetta; only the VM running the container engine and kubernetes are native aarch64 code right now.

**Comment by jandubois** [comment] 2023-09-14 21:24
It is very confusing that some early `limactl.ventura shell` commands fail with `EACCES`, but others later on seem to succeed.

Can you attach a full set of log files?

**Comment by seshaTarget** [comment] 2023-09-17 15:11
I am facing this same issue as well after upgrading from macos Monterey to ventura 13.5.2

**Comment by seshaTarget** [comment] 2023-09-17 15:13
[background.log](https://github.com/rancher-sandbox/rancher-desktop/files/12643109/background.log)

**Comment by seshaTarget** [comment] 2023-09-18 13:45
2023-09-18T13:41:04.770Z: > limactl copy /var/folders/fh/6hrhj3n91w3by20bgn10x3k80000gp/T/rd-nginx.conf-9cWgwT/nginx.conf 0:/tmp/rd-nginx.conf-9cWgwT.nginx.conf
2023-09-18T13:41:04.777Z: Lima: executing: chmod 644 /tmp/rd-nginx.conf-9cWgwT.nginx.conf: Error: spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura EACCES
2023-09-18T13:41:04.778Z: > limactl copy /var/folders/fh/6hrhj3n91w3by20bgn10x3k80000gp/T/rd-nerdctl-f3gPkv/nerdctl 0:/tmp/rd-nerdctl-f3gPkv.nerdctl
2023-09-18T13:41:04.831Z: > /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura shell --workdir=. 0 chmod 755 /tmp/rd-nerdctl-f3gPkv.nerdctl
2023-09-18T13:41:04.837Z: Lima: executing: sudo mv /tmp/rd-nerdctl-f3gPkv.nerdctl /usr/local/bin/nerdctl: Error: spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura EACCES
2023-09-18T13:41:04.844Z: Lima: executing: sudo rm -f /tmp/rd-nerdctl-f3gPkv.nerdctl: Error: spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura EACCES
2023-09-18T13:41:04.844Z: Error trying to start/update containerd: Error: spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura EACCES:  Error: spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
  path: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
  spawnargs: [
    'shell',
    '--workdir=.',
    '0',
    'sudo',
    'rm',
    '-f',
    '/tmp/rd-nerdctl-f3gPkv.nerdctl'
  ]
}
2023-09-18T13:41:04.845Z: > /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura shell --workdir=. 0 sudo rm -f /tmp/rd-nginx.conf-9cWgwT.nginx.conf
2023-09-18T13:41:04.845Z: Error starting lima: Error: spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
  path: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
  spawnargs: [
    'shell',
    '--workdir=.',
    '0',
    'chmod',
    '644',
    '/tmp/rd-nginx.conf-9cWgwT.nginx.conf'
  ]
}

**Comment by ryoma-k** [comment] 2023-09-19 01:52
Resetting Kubernetes in the Troubleshooting tab fixed the issue for me.

**Comment by seshaTarget** [comment] 2023-09-20 13:44
@ryoma-k  doesnt fix for me
which version of kubernetes you are using?

**Comment by jandubois** [comment] 2023-09-21 17:41
I wonder if #4867 is the same issue as well. The common symptom seems that `limectl.ventura` cannot be spawned because of an `EACCES` error.

**Comment by seshaTarget** [comment] 2023-09-21 17:49
@jandubois  it is the same issue
Only difference is the architecture of the macbooks
I am facing the same issue in Intel I7 whereas the other issue #4867  deals with M2 / apple Silicon

**Comment by jandubois** [comment] 2023-11-02 23:40
I'm closing this issue as a duplicate of #4867. Even though this is the older issue, there is more information in the discussion thread of the other one. Please post any further comments on #4867.

**Closed by jandubois** 2023-11-02 23:40 UTC
Labels: kind/bug, platform/macos
