### ISSUE TITLE
The WSL kernel does not appear to be installed

### ISSUE THREAD

**Issue by jack-liew** [rancher-sandbox/rancher-desktop#3705] opened 2023-01-06 03:28 UTC
### Actual Behavior

Just because there was no "" in the command.
"/mnt/c/Users/jack/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper"

`2023-01-06T03:16:02.224Z: Capturing output: wsl.exe --distribution rancher-desktop --exec /mnt/c/Users/jack/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper k3s kubeconfig`

and, WSL is normally, but RD'Diagnostics allways :
`The WSL kernel does not appear to be installed.`

didn't do the basic test?

Thanks

### Steps to Reproduce

change Container Engine from containerd to docker

### Result

`2023-01-06T03:16:02.224Z: Capturing output: wsl.exe --distribution rancher-desktop --exec /mnt/c/Users/jack/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper k3s kubeconfig`

### Expected Behavior

do the right test,please

### Rancher Desktop Version

1.7

### Rancher Desktop K8s Version

1.26

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

windows 11

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment] 2023-01-06 03:55
> Just because there was no "" in the command. "/mnt/c/Users/jack/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper"
> 
> `2023-01-06T03:16:02.224Z: Capturing output: wsl.exe --distribution rancher-desktop --exec /mnt/c/Users/jack/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper k3s kubeconfig`

I'm sorry, I don't understand what you are trying to say. Is the problem that the log file doesn't include the quotes to show the individual arguments?

> and, WSL is normally, but RD'Diagnostics allways : `The WSL kernel does not appear to be installed.`

This seems unrelated to what you write before. Is this test always triggering on your machine? Did you install WSL yourself from the App store? What is the output of `wsl --status` on your machine?

**Comment by jack-liew** [comment] 2023-01-06 04:06
> 
sorry for my english.

It's two problem.
1. RD exec [wsl.exe --distribution rancher-desktop --exec /mnt/c/Users/jack/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper k3s kubeconfig], the path [/mnt/......] should be enclosed in quotation marks.
because it has **Spaces** in the  [Rancher Desktop]. and I've seen same problem few times in log files

2. my wsl been reinstall. Since then, RD has been showing this error. 
`The WSL kernel does not appear to be installed.`

```
>wsl --status
 distribution: Debian
 version: 2
```

**Comment by jack-liew** [comment] 2023-01-06 04:08
> > 只是因为命令中没有“”。/mnt/c/Users/jack/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper”
> > `2023-01-06T03:16:02.224Z: Capturing output: wsl.exe --distribution rancher-desktop --exec /mnt/c/Users/jack/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper k3s kubeconfig`
> 
> 对不起，我不明白你想说什么。日志文件不包含引号以显示各个参数的问题是否？
> 
> > 并且，WSL通常是，但RD'Diagnostics所有方式：`The WSL kernel does not appear to be installed.`
> 
> 这似乎与您之前写的内容无关。此测试是否始终在您的计算机上触发？您是否自己从应用商店安装了 WSL？您机器上的输出是什么？`wsl --status`

=============
sorry for my english.

It's two problem.

1. RD exec [wsl.exe --distribution rancher-desktop --exec /mnt/c/Users/jack/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper k3s kubeconfig], the path [/mnt/.../Rancher Desktop/...] should be enclosed in quotation marks.
because it has Spaces in the [Rancher Desktop]. and I've seen same problem few times in log

2.my wsl been reinstall. Since then, RD has been showing this error.
`The WSL kernel does not appear to be installed.`

```
>wsl --status
 distribution: Debian
 version: 2
```

Thanks

**Comment by jack-liew** [comment] 2023-01-06 04:10
> > Just because there was no "" in the command. "/mnt/c/Users/jack/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper"
> > `2023-01-06T03:16:02.224Z: Capturing output: wsl.exe --distribution rancher-desktop --exec /mnt/c/Users/jack/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper k3s kubeconfig`
> 
> I'm sorry, I don't understand what you are trying to say. Is the problem that the log file doesn't include the quotes to show the individual arguments?
> 
> > and, WSL is normally, but RD'Diagnostics allways : `The WSL kernel does not appear to be installed.`
> 
> This seems unrelated to what you write before. Is this test always triggering on your machine? Did you install WSL yourself from the App store? What is the output of `wsl --status` on your machine?

sorry for my english.

It's two problem.

1. RD exec [wsl.exe --distribution rancher-desktop --exec /mnt/c/Users/jack/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper k3s kubeconfig], the path [/mnt/.../Rancher Desktop/...] should be enclosed in quotation marks.
because it has Spaces in the [Rancher Desktop]. and I've seen same problem few times in log

2.my wsl been reinstall. Since then, RD has been showing this error.
`The WSL kernel does not appear to be installed.`

```
>wsl --status
 distribution: Debian
 version: 2
```

Thanks

**Comment by jandubois** [comment] 2023-01-06 04:15
> It's two problem.
> 
> 1. RD exec [wsl.exe --distribution rancher-desktop --exec /mnt/c/Users/jack/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper k3s kubeconfig], the path [/mnt/.../Rancher Desktop/...] should be enclosed in quotation marks.
>    because it has Spaces in the [Rancher Desktop]. and I've seen same problem few times in log


I understand, but this "problem" is purely cosmetic, right? Or did you try to copy the commands from the log file and paste them into a terminal? Which will not work, as it is missing the quotes, as you mentioned.

Or do you see commands issued by Rancher Desktop itself failing and think it is due to quoting issues? In that case, please include the failing command, and the corresponding output from the logs!

> 2.my wsl been reinstall. Since then, RD has been showing this error. `The WSL kernel does not appear to be installed.`
> 
> ```
> >wsl --status
>  distribution: Debian
>  version: 2
> ```

This is interesting; normally the output includes the kernel version, e.g.

```
C:\Users\Jan>wsl --status
Default Distribution: Ubuntu-20.04
Default Version: 2

Windows Subsystem for Linux was last updated on 4/8/2022
The Windows Subsystem for Linux kernel can be manually updated with 'wsl --update', but automatic updates cannot occur due to your system settings.
To receive automatic kernel updates, please enable the Windows Update setting: 'Receive updates for other Microsoft products when you update Windows'.
For more information please visit https://aka.ms/wsl2kernel.

Kernel version: 5.10.16
```

Maybe this has changed recently. How did you reinstall WSL?

**Comment by jandubois** [comment] 2023-01-06 04:18
I just updated WSL using Windows Update, and the Kernel version is still displayed:

```
C:\Users\Jan>wsl --status
Default Distribution: Ubuntu-20.04
Default Version: 2

Windows Subsystem for Linux was last updated on 1/5/2023
WSL automatic updates are on.

Kernel version: 5.10.102.1
```

But this is Windows 10; I don't have access to a Windows 11 machine right now.

**Comment by jack-liew** [comment] 2023-01-06 04:32
Yes, I did  try to copy the commands from the log file and paste them into a terminal. but everytime I want change to docker, this error occurred:
![image](https://user-images.githubusercontent.com/102201538/210929995-ea2501e0-1986-492e-b6d2-1749d68f5aa3.png)

I copy [rancher desktop] to d:\MyPrograms\rancher-desktop then run it. But same error, that means it is not a question of quotation marks.
```
2023-01-06T04:25:26.257Z: Running: wsl.exe --distribution rancher-desktop --exec docker images
2023-01-06T04:25:26.402Z: Running: wsl.exe --distribution rancher-desktop --exec /sbin/rc-update --update
2023-01-06T04:25:26.548Z: Running: wsl.exe --distribution rancher-desktop --exec /usr/local/bin/wsl-service k3s start
2023-01-06T04:25:32.642Z: Capturing output: wsl.exe --distribution rancher-desktop --exec cat /proc/net/route
2023-01-06T04:25:32.801Z: Capturing output: wsl.exe --distribution rancher-desktop --exec cat /proc/net/fib_trie
2023-01-06T04:25:33.483Z: Capturing output: wsl.exe --distribution rancher-desktop --exec /bin/sh -c if test -r /etc/rancher/k3s/k3s.yaml; then echo yes; else echo no; fi
2023-01-06T04:25:33.639Z: Capturing output: wsl.exe --distribution rancher-desktop --exec wslpath -a -u D:\MyPrograms\rancher-desktop\resources\resources\linux\wsl-helper
2023-01-06T04:25:33.789Z: Capturing output: wsl.exe --distribution rancher-desktop --exec /mnt/d/MyPrograms/rancher-desktop/resources/resources/linux/wsl-helper k3s kubeconfig
```

Thank U

**Comment by mook-as** [comment] 2023-01-09 23:20
Actually, looking at my other main reminded me…

@jack-liew is (probably) in China (behind the Great Firewall), so the underlying issue might just be us looking for some assets on GitHub on startup. Which would make this a duplicate of #3690, or possibly other things to help with airgapped installs (see also [the documentation](https://docs.rancherdesktop.io/how-to-guides/running-air-gapped)).

@jack-liew I believe this would then just be a duplicate of #3632; does that sound correct?

**Comment by gunamata** [comment] 2023-01-17 00:37
Closing this issue as it seems to be a duplicate of https://github.com/rancher-sandbox/rancher-desktop/issues/3632.

**Closed by gunamata** 2023-01-17 00:37 UTC
Labels: kind/bug, platform/windows

**Comment by jack-liew** [comment] 2023-01-28 00:45
> 
My RD work normally, but still prompts this error. I don't care about it.

Thank U.
