### ISSUE TITLE
Rancher Desktop not working on M1 mac

### ISSUE THREAD

**Issue by gautampachnandamat** [rancher-sandbox/rancher-desktop#1835] opened 2022-03-17 09:37 UTC
### Actual Behavior

After installing m1 mac the desktop fails to complete setup due to an error must be less than UNIX_PATH_MAX=104 

### Steps to Reproduce

Install Rancher desktop
Start Rancher desktop
You get a prompt with the error  must be less than UNIX_PATH_MAX=104 characters, but is 114"
2022-03-17T09:25:52.199Z: + limactl start --tty=false during executing limactl

### Result

 must be less than UNIX_PATH_MAX=104 characters, but is 114"
2022-03-17T09:25:52.199Z: + limactl start --tty=false

022-03-17T09:25:51.978Z: Running command limactl list --json...
2022-03-17T09:25:52.098Z: Running command limactl start --tty=false /Users/xxxxxxxxxxxxxxxx@xxxxx.com/Library/Application Support/rancher-desktop/lima/_config/0.yaml...
time="2022-03-17T09:25:52Z" level=fatal msg="instance name \"0\" too long: \"/Users/xxxxxxxxxxxxxxxx@xxxxxxx.com/Library/Application Support/rancher-desktop/lima/0/ssh.sock.1234567890123456\" must be less than UNIX_PATH_MAX=104 characters, but is 114"
2022-03-17T09:25:52.199Z: + limactl start --tty=false 

### Expected Behavior

Install should complete without error

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

1.22.7

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Montery 12.2.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by MacFlurry** [comment] 2022-03-17 09:48
same for me :

## Kubernetes Error*

**Error Starting Kubernetes**

```
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
Last command run:
limactl start --tty=false /Users/macflurry/Library/Application Support/rancher-desktop/lima/_config/0.yaml
```

### Context:
Starting virtual machine

> Some recent logfile lines:

```
time="2022-03-17T10:42:17+01:00" level=error msg="instance \"0\" does not exist?" error="open /Users/macflurry/Library/Application Support/rancher-desktop/lima/0/lima.yaml: no such file or directory"
2022-03-17T09:42:17.275Z: Running command limactl start --tty=false /Users/macflurry/Library/Application Support/rancher-desktop/lima/_config/0.yaml...
time="2022-03-17T10:42:17+01:00" level=fatal msg="instance \"0\" already exists (\"/Users/macflurry/Library/Application Support/rancher-desktop/lima/0\")"
2022-03-17T09:42:17.342Z: + limactl start --tty=false /Users/macflurry/Library/Application Support/rancher-desktop/lima/_config/0.yaml
2022-03-17T09:42:17.342Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-03-17T09:42:17.343Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8692)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

**Comment by grnxi** [comment] 2022-03-17 10:11
Same for me also macOS 12.3 M1 Pro

Error Starting Kubernetes
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
Last command run:
limactl start --tty=false /Users/thomasgrantham/Library/Application Support/rancher-desktop/lima/_config/0.yaml

Context:
Starting virtual machine

Some recent logfile lines:
time="2022-03-17T10:10:19Z" level=info msg="Terminal is not available, proceeding without opening an editor"
time="2022-03-17T10:10:19Z" level=info msg="Starting switch daemon for \"bridged_en0\" network"
time="2022-03-17T10:10:19Z" level=fatal msg="\"/private/var/run/rancher-desktop-lima\" doesn't seem to be writable by the daemon (gid:1) group"
2022-03-17T10:10:20.000Z: + limactl start --tty=false /Users/thomasgrantham/Library/Application Support/rancher-desktop/lima/_config/0.yaml
2022-03-17T10:10:20.000Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-03-17T10:10:20.001Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8692)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)

**Comment by gauravaquarious** [comment] 2022-03-17 12:10
Same for me

**Comment by MacFlurry** [comment] 2022-03-17 13:09
I solved it by noticing the change on `/private/var/run/rancher-desktop-lima` permission.
to solve it, change the permission to `775`


regards

**Comment by grnxi** [comment] 2022-03-17 14:26
> 

applied fix now working Thanks @MacFlurry

**Comment by jandubois** [comment] 2022-03-17 16:50
@gautampachnandamat A workaround for your problem can be found in https://github.com/rancher-sandbox/rancher-desktop/issues/797#issuecomment-996510877. There is still no fix for it, but the workaround only needs to be applied once (unless you do a Factory Reset).

@MacFlurry I can't tell from your error message what the root cause is. Since you are on Monterey 12.3 I assume it is the same as for @grnx: an explanation and workaround is at https://github.com/rancher-sandbox/rancher-desktop/issues/1815#issuecomment-1068522900. This issue will be fixed in a release next week.

**Closed by jandubois** 2022-03-17 16:50 UTC
Labels: kind/bug
