### ISSUE TITLE
GUI shows local (sinhala) Unicode characters instead of English

### ISSUE THREAD

**Issue by Lakith-Rambukkanage** [rancher-sandbox/rancher-desktop#3230] opened 2022-10-20 15:48 UTC
### Actual Behavior

Displays Text with local (Sinhala) Unicode characters. (when text is copied to a different location it shows correctly)

### Steps to Reproduce

Install from a location with specific Unicode characters. I assume the issue comes from the location of installation. (Sri Lanka)
Note : I do not use any translators, local keyboard layouts or anything of sorts on this laptop. (not included in windows language preferences as well. only English)

### Result

![image](https://user-images.githubusercontent.com/44548749/196993828-90157686-162b-4054-a80f-36d6236fe781.png)

### Expected Behavior

Show the text in default language and correct characters (in English)

### Additional Information

Possible i18n (ember-intl) bug

### Rancher Desktop Version

1.6.0

### Rancher Desktop K8s Version

1.23.6

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro 64-bit (10.0, Build 19044)

### What CPU architecture are you using?

x64

**Comment by mook-as** [comment] 2022-10-21 00:16
This is a duplicate of #1518 (thank you for identifying that it's Sinhala; it made the search much easier).  You appear to be using a different font, but it sounds like it's not atypical for people in the region to install a font that reuses the ASCII code points and rely on font name matching to not get used in places where it's unexpected (and somehow failing here).

Closing as a duplicate, but we would still need to fix the underlying issue.

It would be good if you could identify the font involved (and, if possible, how to obtain it) so that we could reproduce it on our end to test any possible fixes.

**Closed by mook-as** 2022-10-21 00:16 UTC
Labels: kind/bug, platform/windows, component/ui
