### ISSUE TITLE
Ventura update break ~/.docker/cli-plugins/docker symlink ?

### ISSUE THREAD

**Issue by smesguich-orange** [rancher-sandbox/rancher-desktop#3290] opened 2022-10-27 09:14 UTC
### Actual Behavior

After updating the system to Ventura and updating Rancher Desktop to 1.6.1, Diagnostics show 2 fails and after setting manually through terminal, erreur still persist

> The file ~/.docker/cli-plugins/docker-buildx should be a symlink to ~/.rd/bin/docker-buildx, but points to ~/.rd/bin/docker-buildx
> The file ~/.docker/cli-plugins/docker-compose should be a symlink to ~/.rd/bin/docker-compose, but points to ~/.rd/bin/docker-compose.

### Steps to Reproduce

MacOS Ventura update on M1

### Result

![Uploading image.png…]()

### Expected Behavior

No error

### Rancher Desktop Version

1.6.1

### Rancher Desktop K8s Version

1.24

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura 13.0

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by jandubois** [comment] 2022-10-27 17:55
First off, some general feedback on Ventura: Rancher Desktop seems to break when you enable Kubernetes 1.24+ on Ventura, but it seems to work ok with earlier versions, including 1.23.13.

Also: I cannot reproduce this diagnostic failure:

> The file ~/.docker/cli-plugins/docker-buildx should be a symlink to ~/.rd/bin/docker-buildx, but points to ~/.rd/bin/docker-buildx

This looks very suspicious to me, as the last path in the error should be the result of a `readlink`. This should not return a path starting with a `~` because that is a shell feature, not a filesystem feature:

```console
$ cd .docker/cli-plugins/

$ rm docker-buildx
$ ln -s ~/.rd/bin/docker-buildx
$ ls -l docker-buildx
lrwxr-xr-x  1 jan  staff  32 26 Oct 09:19 docker-buildx -> /Users/jan/.rd/bin/docker-buildx

$ rm docker-buildx
$ ln -s "~/.rd/bin/docker-buildx" docker-buildx
$ ls -l docker-buildx
lrwxr-xr-x  1 jan  staff  23 27 Oct 10:46 docker-buildx -> ~/.rd/bin/docker-buildx
```

Did you create the symlink manually, and maybe quoted it in the shell, like I did in the bottom part of the output quoted above?

Maybe the original failed diagnostic had a different message, you tried to fix it manually, and created a different issue?

The easiest way to fix it would be to remove the symlinks and restart Rancher Desktop, at which point it should re-create them with the proper target.

If you still get a diagnostic error after that, please show this original error (and the logs, as explained above by @adamkpickering)! Thanks!

**Comment by adamkpickering** [comment] 2022-10-27 21:07
> This looks very suspicious to me, as the last path in the error should be the result of a readlink.

Note that we process the absolute path returned by `fs.promises.readlink` to make it more readable - see https://github.com/rancher-sandbox/rancher-desktop/blob/753fb75b00dd64fe1f0a09acd6fc801c5e8af2b1/src/main/diagnostics/dockerCliSymlinks.ts#L13 and https://github.com/rancher-sandbox/rancher-desktop/blob/753fb75b00dd64fe1f0a09acd6fc801c5e8af2b1/src/main/diagnostics/dockerCliSymlinks.ts#L42.

But I agree, I could see manual symlinking leading to an edge case that the diagnostic wasn't written to handle. Looking forward to hearing from you @smesguich-orange.

**Comment by jandubois** [comment] 2022-10-28 03:13
> Note that we process the absolute path returned by `fs.promises.readlink` to make it more readable

Interesting! In that case I don't understand why the diagnostic would have failed, as the desired and actual path seem to be identical.

**Comment by smesguich-orange** [comment] 2022-11-02 15:31
> That's very strange. Can you please try a couple of things:
> 
>     1. Try running on 1.6.0 and macOS Ventura. Does this still occur?
> 
>     2. Enable debug mode (Troubleshooting > Enable debug mode), then restart and make sure the problem is occurring. Then, upload logs (you can get to the log folder via Troubleshooting > Show Logs).
> 
> 
> Thanks!

Hello
Issue is stil present after downgrade in 1.6.0. Also persist with debug mode.
<img width="931" alt="image" src="https://user-images.githubusercontent.com/95211953/199529263-43215062-38d1-41c0-b472-a69cf8d70e54.png">

Wich logs files do you need ? (to check and remove potentials internal URL)



> First off, some general feedback on Ventura: Rancher Desktop seems to break when you enable Kubernetes 1.24+ on Ventura, but it seems to work ok with earlier versions, including 1.23.13.
> 

I confirm this issue but I didn't repost it. Just following topic https://github.com/rancher-sandbox/rancher-desktop/issues/3288


> Also: I cannot reproduce this diagnostic failure:
> 
> > The file ~/.docker/cli-plugins/docker-buildx should be a symlink to ~/.rd/bin/docker-buildx, but points to ~/.rd/bin/docker-buildx
> 
> This looks very suspicious to me, as the last path in the error should be the result of a `readlink`. This should not return a path starting with a `~` because that is a shell feature, not a filesystem feature:
> 
> ```
> $ cd .docker/cli-plugins/
> 
> $ rm docker-buildx
> $ ln -s ~/.rd/bin/docker-buildx
> $ ls -l docker-buildx
> lrwxr-xr-x  1 jan  staff  32 26 Oct 09:19 docker-buildx -> /Users/jan/.rd/bin/docker-buildx
> 
> $ rm docker-buildx
> $ ln -s "~/.rd/bin/docker-buildx" docker-buildx
> $ ls -l docker-buildx
> lrwxr-xr-x  1 jan  staff  23 27 Oct 10:46 docker-buildx -> ~/.rd/bin/docker-buildx
> ```
> 
> Did you create the symlink manually, and maybe quoted it in the shell, like I did in the bottom part of the output quoted above?
> 
> Maybe the original failed diagnostic had a different message, you tried to fix it manually, and created a different issue?
> 
> The easiest way to fix it would be to remove the symlinks and restart Rancher Desktop, at which point it should re-create them with the proper target.
> 
> If you still get a diagnostic error after that, please show this original error (and the logs, as explained above by @adamkpickering)! Thanks!

Yeah, I've created them regarding the botom option.
My output :
``` bash
Last login: Fri Oct 28 10:44:33 on console
❯ cd .docker/cli-plugins
❯ ls
docker-buildx  docker-compose
❯ ls -ali
total 0
 3081383 drwxr-xr-x  4 samuel  staff  128 27 oct 10:38 .
 3081382 drwxr-xr-x  5 samuel  staff  160 26 oct 16:05 ..
22895107 lrwxr-xr-x  1 samuel  staff   23 27 oct 10:37 docker-buildx -> ~/.rd/bin/docker-buildx
22895191 lrwxr-xr-x  1 samuel  staff   24 27 oct 10:38 docker-compose -> ~/.rd/bin/docker-compose
~/.docker/cli-plugins ❯```

I've remove them and restart rancher (in 1.6.0) => it works and warning disapear.

Updated to 1.6.1, everythings is good.

IDK why and by what simlink after upgrade have been touched

**Comment by adamkpickering** [comment] 2022-11-03 16:05
> Wich logs files do you need ? (to check and remove potentials internal URL)

All of them, if you can. Though I doubt they contain any useful info now.

I'm going to close this issue for now. Let us know if it happens again and we can reopen it.

**Closed by adamkpickering** 2022-11-03 16:05 UTC
Labels: kind/bug, triage/needs-information, platform/macos, area/diagnostics

**Comment by grahambunce** [comment] 2022-11-05 23:03
FYI: I've had this on my ubuntu (22.04.01 LTS) and macos (montery) rancher desktop installation after I upgraded to 1.6.1. Rancher docker commands all seem to work though so it's a little confusing.

- The file ~/.docker/cli-plugins/docker-buildx should be a symlink to ~/.rd/bin/docker-buildx, but points to /opt/rancher-desktop/resources/resources/linux/bin/docker-buildx.	
- The file ~/.docker/cli-plugins/docker-compose is not a symlink. It should be a symlink to ~/.rd/bin/docker-compose.
- The ~/.rd/bin directory has not been added to the PATH, so command-line utilities are not configured in your bash shell.

**Comment by adamkpickering** [comment] 2022-11-07 17:17
Hi @grahambunce, all of those messages are normal. If you're interested in resolving them feel free to message me on Slack and I'd be happy to help you with that. Note that you can also mute those diagnostics.

These messages aren't in the same category as the ones that are the topic of this issue, though, so we'll keep this closed.
