### ISSUE TITLE
macOS has been stuck in download k8s，The docker command connection failed

### ISSUE THREAD

**Issue by bimoQi** [rancher-sandbox/rancher-desktop#4216] opened 2023-03-17 09:12 UTC
### Actual Behavior

The startup program has the k8s option enabled by default, The specified version is set.
The k8s won't start.
docker failed to run the connection.

### Steps to Reproduce

Install according to the official website

### Result

![image](https://user-images.githubusercontent.com/22308917/225861163-1997aece-5e3e-4a63-bfbf-149fdedd0398.png)
![image](https://user-images.githubusercontent.com/22308917/225861427-88a2404f-8e3f-44c8-a1ab-46e008b5e86f.png)
![image](https://user-images.githubusercontent.com/22308917/225861997-97e9739c-595e-4a06-ba2c-3cbc76a9382a.png)
![image](https://user-images.githubusercontent.com/22308917/225861644-b4b932c6-6055-48f8-8953-a2921fe896b2.png)

### Expected Behavior

Hope to run k8s and docker successfully

### Rancher Desktop Version

1.8.0

### Rancher Desktop K8s Version

1.25.7

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by torchiaf** [comment] 2023-03-17 12:40
The issue is that the k3s version **1.25.7** download runs very slow to the point that it appears to be stuck, but it is completely random behaviour.
I was able to replicate it ~1/10 times, using the browser to download the image file as well.
Could you try to do a factory reset on your Rancher Desktop and select again version 1.25.7?

**Comment by torchiaf** [comment] 2023-03-22 09:27
Closing since the issue in downloading k8s is not related to Rancher Desktop.

**Closed by torchiaf** 2023-03-22 09:27 UTC
Labels: kind/bug
