### ISSUE TITLE
proxy-url removed from ~/.kube/config for non-RD clusters

### ISSUE THREAD

**Issue by vrevelas** [rancher-sandbox/rancher-desktop#2515] opened 2022-07-11 12:24 UTC
### Actual Behavior

I have a handful of contexts in my ~/.kube/config, some of which require a proxy for connectivity. I accomplish this by setting proxy-url for those clusters as follows:
```
apiVersion: v1
kind: Config
clusters:
  - name: my-non-rd-cluster
    cluster:
      proxy-url: http://username:password@proxy.fqdn:8080
      server: https://k8s-url
```
On starting up Rancher Desktop, the proxy-url setting disappears from the file.

### Steps to Reproduce

Add a proxy-url setting to ~/.kube/config for a context other than rancher-desktop, as shown above

### Result

After starting Rancher Desktop, the proxy-url line no longer exists in ~/.kube/config

### Expected Behavior

proxy-url should still exist in ~/.kube/config

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

1.23.8

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

18.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by jandubois** [comment] 2022-07-11 22:20
I can confirm that on macOS as well. I've added the definition above verbatim to my `~/.kube/config` file:

```yaml
clusters:
  - name: my-non-rd-cluster
    cluster:
      proxy-url: http://username:password@proxy.fqdn:8080/
      server: https://k8s-url/
```

After starting RD (wait until the node is running), the entry has been changed to:

```yaml
clusters:
  - name: my-non-rd-cluster
    cluster:
      server: https://k8s-url
      insecure-skip-tls-verify: false
```

Previously reported: https://github.com/rancher-sandbox/rancher-desktop/issues/1503#issuecomment-1035195711

**Comment by jandubois** [comment] 2022-07-20 06:46
The problem is that the merged kubeconfig is written out using the https://github.com/kubernetes-client/javascript library: https://github.com/rancher-sandbox/rancher-desktop/blob/206c716dd55e3a768b3398f54eb10f1163521759/src/k8s-engine/k3sHelper.ts#L846

The `exportConfig` function https://github.com/kubernetes-client/javascript/blob/4ea2b0f60ba724eee1f2ab1485e39e9ff1390507/src/config.ts#L383-L395 

```ts
    public exportConfig(): string {
        const configObj = {
            apiVersion: 'v1',
            kind: 'Config',
            clusters: this.clusters.map(exportCluster),
            users: this.users.map(exportUser),
            contexts: this.contexts.map(exportContext),
            preferences: {},
            'current-context': this.getCurrentContext(),
        };

        return JSON.stringify(configObj);
    }
```

restricts the the cluster definitions via the `exportCluster` function https://github.com/kubernetes-client/javascript/blob/574e0f7c118e83ce0aecfce2fa1c0c92a1ef8f3b/src/config_types.ts#L34-L45

```ts
export function exportCluster(cluster: Cluster): any {
    return {
        name: cluster.name,
        cluster: {
            server: cluster.server,
            'certificate-authority-data': cluster.caData,
            'certificate-authority': cluster.caFile,
            'insecure-skip-tls-verify': cluster.skipTLSVerify,
            'tls-server-name': cluster.tlsServerName,
        },
    };
}
```

 which doesn't include the `proxy-url` field. This explains both why the `proxy-url` field is dropped, and why the boolean `insecure-skip-tls-verify` field is added (it can't have a null value).

The `proxy-url` field was added in [rest.Config: support configuring an explict proxy URL #81443](https://github.com/kubernetes/kubernetes/pull/81443). The proper fix will be to send a PR against the upstream library; not sure if we can apply a local workaround until then.

**Closed** 2022-07-20 23:40 UTC
Labels: kind/bug, priority/high
