### ISSUE TITLE
k8s workloads not getting deleted after a k8s downgrade

### ISSUE THREAD

**Issue by prabalsharma** [rancher-sandbox/rancher-desktop#2966] opened 2022-09-21 20:15 UTC
### Actual Behavior

Downgrading Kubernetes version did not delete deployed Kubernetes application 

### Steps to Reproduce

1. helm install --wait --timeout=20m wordpress bitnami/wordpress --set=service.type=NodePort --set=volumePermissions.enabled=true --set=mariadb.volumePermissions.enabled=true
2. Downgrade Kubernetes version
3. wait for Kubernetes to restart
4. check if wordpress workload is gone after the downgrade `kubectl get pods -A`

### Result

Wordpress was still running after downgrading k8s version

### Expected Behavior

Test case 10: All of the containers k8s is running should be gone after a Kubernetes version downgrade

### Rancher Desktop Version

1.5.0-608-g8fdebb5a

### Rancher Desktop K8s Version

1.23.10

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Catalina

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment] 2022-09-23 02:27
I can reproduce this incorrect behaviour.

From looking at the code, it looks like only `doK8sReset('fast')` will call `k8smanager.reset()`, which will delete the payloads. I can't see where it is called with the `fast` parameter at all.

When I downgrade the k8s version, it seems `doK8sReset('fullRestart')` is called instead, and that code branch does not seem to delete the payloads, but just stop and restart k8s.

Re-assigning to @mook-as because he did the most recent backend refactoring.

**Comment by mook-as** [comment] 2022-09-23 02:58
On downgrade (which is not a reset), assuming [`isDowngrade` is calculated correctly](https://github.com/rancher-sandbox/rancher-desktop/blob/dc059411ccba1ba37d947ae90498b5c6b14b365b/src/backend/lima.ts#L1450) (which it should be, otherwise nothing would be deleted):
- We then [install the backend](https://github.com/rancher-sandbox/rancher-desktop/blob/dc059411ccba1ba37d947ae90498b5c6b14b365b/src/backend/lima.ts#L1484) with `isDowngrade` set
- First thing there, we [call `deleteIncompatibleData`](https://github.com/rancher-sandbox/rancher-desktop/blob/dc059411ccba1ba37d947ae90498b5c6b14b365b/src/backend/lima.ts#L1860-L1861)
- Which is [supposed to delete Kubernetes state](https://github.com/rancher-sandbox/rancher-desktop/blob/dc059411ccba1ba37d947ae90498b5c6b14b365b/src/backend/lima.ts#L2157-L2164).

I'll dig deeper later to see if something is going wrong there.

**Comment by jandubois** [comment] 2022-09-23 03:56
It is probably unrelated to this issue, but I've been wondering:

We shutdown the VM and then start it again, so containers are stopped, so we can deleted the data.

But then the `containerd` service must be started before we can install k3s, and containerd will restart any containers that had been created with `--restart=always`. So by the time `kubeBackend.install` calls `deleteIncompatibleData`, this data may very well be in use again.

**Comment by mook-as** [comment] 2022-09-23 16:28
Good catch — while we _do_ start `containerd` manually, we do it too early (before `kubeBackend.install`).

**Closed** 2022-09-23 23:46 UTC
Labels: kind/bug, regression, area/kubernetes
