### ISSUE TITLE
A failure in K3s stop should not be a fatal error 

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#2726] opened 2022-08-10 22:08 UTC
### Actual Behavior

Tried to do a factory reset but it failed and rancher desktop did not shut down as expected.

### Steps to Reproduce

1- Start rancher desktop
2- Got this error message: "This Rancher Desktop installation appears to be older than the version that created your existing Kubernetes cluster. Please either update Rancher Desktop or reset Kubernetes and container images."
3- Click the Factory Reset button in Troubleshooting tab

### Result

When shutting down Rancher Desktop, the progress bar was hidden and factory reset was not executed.
Got the description of the error in lima/background.log file
By running 
`limactl --debug shell --workdir=. 0 sudo /sbin/rc-service --ifstarted k3s stop`
Got fatal error rc-service: service `k3s' does not exist
RD does not shutdown for a factory reset due to this error.

### Expected Behavior

Should be able to execute the factory reset ignoring any errors of rancher desktop's current state.

### Rancher Desktop Version

v1.5.0-49-g471952c7

### Rancher Desktop K8s Version

1.24.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

x64

**Comment by ericpromislow** [comment] 2022-09-29 21:38
Duplicate of #3022

**Closed by ericpromislow** 2022-09-29 21:38 UTC
Labels: kind/bug
