### ISSUE TITLE
Latest intel version fails to start

### ISSUE THREAD

**Issue by rkazak** [rancher-sandbox/rancher-desktop#1952] opened 2022-04-01 04:47 UTC
### Actual Behavior

From the error reporting panel

```
Kubernetes Error
Error Starting Kubernetes
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
Last command run:
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl start --tty=false 0

Context:
Starting virtual machine
```

### Steps to Reproduce

Install Rancher Desktop
start it up

### Result

Second part of the error panel

```
Some recent logfile lines:
time="2022-03-31T21:36:40-07:00" level=info msg="Using the existing instance \"0\""
time="2022-03-31T21:36:40-07:00" level=info msg="Starting switch daemon for \"rancher-desktop-shared\" network"
time="2022-03-31T21:36:40-07:00" level=fatal msg="failed to run [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run]: stdout=\"\", stderr=\"sudo: a password is required\\n\": exit status 1"
2022-04-01T04:36:40.750Z: + limactl start --tty=false 0
2022-04-01T04:36:40.750Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-04-01T04:36:40.751Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8836)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

### Expected Behavior

Rancher Desktop should startup

### Additional Information

What are the steps for a full deinstall, I could try that if it was given to me?

### Rancher Desktop Version

1.2.1

### Rancher Desktop K8s Version

1.21.10

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 21.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

AppImage

**Comment by rkazak** [comment] 2022-04-01 04:52
Factory reset does not help.

**Comment by rkazak** [comment] 2022-04-01 05:21
When I try and run the failing command via the terminal it complains about a missing file, where can I find this file?
```
➜  ~ /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl start --tty=false 0
FATA[0000] open /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/share/lima/examples/default.yaml: no such file or directory 
```
Also the example directory does not exist, creating it and touch-ing the file allows it to go further.

**Comment by jandubois** [comment] 2022-04-01 06:05
Your problem is:

> sudo: a password is required

This means for whatever reason the configuration in `/etc/sudoers.d` is not working. This is a duplicate of #1615 (or #1811, which is also a duplicate of #1615).

See https://github.com/rancher-sandbox/rancher-desktop/issues/1811#issuecomment-1068791118 for more information.

Closing this as a duplicate.

**Closed by jandubois** 2022-04-01 06:05 UTC
Labels: kind/bug

**Comment by jandubois** [comment] 2022-04-01 06:08
> When I try and run the failing command via the terminal it complains about a missing file, where can I find this file?

This is misleading. You get a different result here because you have not setup the same environment variables as when Rancher Desktop executes the command internally. If you set the correct value for `LIMA_HOME` you will see the same sudo password error as in the log file.
