### ISSUE TITLE
Issue using VS Code Remote Container extension

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#1077] opened 2021-12-07 16:01 UTC
As 0.7.0.beta.1 has docker support, I am trying to get the VS Code extension [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) with Rancher Desktop.

When I tried to open a locally cloned copy of this [repo](https://github.com/microsoft/vscode-remote-try-node), I ran into below error.

`Error response from daemon: invalid mount config for type "bind": invali
d mount path: 'c:/2021/remotecontainers/vscode-remote-try-node' mount path must
be absolute.`

Note - I tried this on my Windows machine, some discussion forums say that it's a windows specific issue and this functionality might work in Mac, Linux environments.

**Comment by mook-as** [comment] 2021-12-07 22:49
This reduces down to `docker run --rm --mount "type=bind,source=${PWD},target=/host,consistency=cached" alpine` — there's a `--mount` that isn't being caught by our existing mungers.

**Comment by gunamata** [comment] 2021-12-08 17:31
the extension worked on Mac and Linux machines with Rancher Desktop.. It reduces to just the Windows environment and seems to be a problem removing a mount as mentioned by @mook-as above..

**Comment by gunamata** [comment] 2021-12-10 17:30
With @mook-as 's #1088 , I am able to get past the earlier mount error.. I see below error now.. Looks like a folder permissions issue from the error message..

`error An unexpected error occurred: "EPERM: operation not permitted, copyfile '/home/node/.cache/yarn/v6/npm-body-parser-1.18.3-5b292198ffdd553b3a0f20ded0592b956955c8b4-integrierror An unexpected error occurred: "EPERM: operation not permitted, copyfile '/home/node/.cache/yarn/v6/npm-body-parser-1.18.3-5b292198ffdd55error An unexpected error occurred: "EPERM: operation not permitted, copyfile '/home/node/.cache/yarn/v6/npm-body-parser-1.18.3-5b292198ffdd553b3a0f20ded0
592b956955c8b4-integrity/node_modules/body-parser/README.md' -> '/workspaces/vscode-remote-try-node/node_modules/body-parser/README.mderrorerror An unexpected error occurred: "EPERM: operation not permitted, copyfile '/home/node/.cache/yarn/v6/npm-body-parser-1.18.3-5b2921
98ffdd553b3a0f20ded0592b956955c8b4-integrity/node_modules/body-parser/README.md' -> '/workspaces/vscode-remote-try-node/node_modules/b     ody-parser/README.md'".`

**Comment by mook-as** [comment] 2021-12-10 22:43
The issues seems to be file ownership; if I edit `/etc/wsl.conf` in the `rancher-desktop` distribution to add under `[automount]` `options = uid=1000,gid=1000` then things work fine.

Of course, that by itself isn't going to work — we don't actually what numbers go there.  I couldn't find anything within the docker container create request that would indicate what UID will be used; the `User` field was just empty.  It's also possible that I missed it somewhere…

**Comment by mook-as** [comment] 2021-12-13 19:31
Oops, didn't mean to close this — there's still a follow-up issue with permissions.

**Comment by mook-as** [comment] 2021-12-13 22:09
The remaining issue looks like https://github.com/yarnpkg/yarn/issues/8389; however, we're already on dockerd 20.10.11, so there's nothing to upgrade.  I _think_ what they're actually saying is that there's a missing sycall in the seccomp profile, but I tried hacking in a default profile to allow everything, and it didn't seem to help (maybe I didn't set the profile up correctly, though).  I've also tried patching in [unconfined seccomp profile](https://docs.docker.com/engine/security/seccomp/#run-without-the-default-seccomp-profile), with the same results.

**Comment by mook-as** [comment] 2021-12-16 20:11
Mounting `C:` with metadata on (i.e. setting the [`metadata` option](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#automount-options) for the mount) fixes things. I'm not quite sure doing that is a great idea, but we might not have much of a choice here…

**Comment by ckihm** [comment] 2021-12-23 16:19
I am using version 0.7.1 with dockerd enabled. When I start VS code from WSL (my code is in the filesystem of an Ubuntu 20.04 distribution) and then try to start my devcontainer, this fails with the following error message:

docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: '1ddff10d-b7f5-4248-87dc-c16fa415c643' mount path must be absolute.

The command that fails is the following:

docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/ckihm/workspace/sbss-example-service,target=/workspaces/sbss-example-service --mount type=volume,src=vscode,dst=/vscode --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker-host.sock -l vsch.local.folder=\\wsl$\Ubuntu-DevEnv\home\ckihm\workspace\sbss-example-service -l vsch.quality=stable -l vsch.remote.devPort=0 --init --entrypoint /bin/sh vsc-sbss-example-service-877b6f700ecd25f2f1f2e8038c325ff9-features-uid -c echo Container started

However, the paths are correct. If I try in the shell to resolve the used paths then this works without problems.

I am quite sure that this is the only problem that currently prevents the use of VS Code devcontainer with rancher desktop. I have also tried to prefix the paths with \wsl$\Ubuntu-DevEnv\ and prober quotet the backslashes, but without luck.

@mook-as  Does the version 0.7.1 already contain your fix?

**Comment by gunamata** [comment] 2021-12-23 16:23
Enable `metadata`  fix is not part of 0.7.1.. We are planning to include in the next release.

**Comment by mook-as** [comment] 2021-12-23 17:39
Hmm, but the error message is _not_ related to the `metadata` stuff.

@ckihm: could you run `docker inspect <container>` when that happens, plus examine `~/.local/state/rancher-desktop/docker-binds.json` in your WSL distro for that guid (`1ddff10d-b7f5-4248-87dc-c16fa415c643`)?  The mount is _supposed_ to live in `/mnt/wsl/rancher-desktop/run/docker-mounts` instead…

Note that "Starting VS code from a container" is a completely different code path from "using the VS Code Remote Container extension"; the latter runs commands on the Windows side instead.

**Comment by ckihm** [comment] 2021-12-23 21:18
@mook-as: Thank you very much for your help. My setup and process looks like this:

Windows 10, Version 1909 (Build 18363.1977)

VS Code is installed on Windows. Version 1.63.2. I have installed the extensions Remote - WSL and Remote - Containers.

I have checked out my code repository in the Ubuntu distribution with git. With `code .` I start VS Code (VS Code Server is installed in the WSL Ubuntu distribution).

In my code repository I have defined a VS Code devcontainer. I open the folder in the devcontainer **(function "Reopen in Container" which is a functionality of VS Code Remote Container extension)**.

VS Code started this command which fails.

The folder `~/.local/state/rancher-desktop` is empty. 

The complete error message printed to console:

`
Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/ckihm/workspace/sbss-example-service,target=/workspaces/sbss-example-service --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=\\wsl$\Ubuntu-DevEnv\home\ckihm\workspace\sbss-example-service -l vsch.quality=stable -l vsch.remote.devPort=0 --entrypoint /bin/sh vsc-sbss-example-service-877b6f700ecd25f2f1f2e8038c325ff9-uid -c echo Container started
trap "exit 0" 15

while sleep 1 & wait $!; do :; done
`

Since the error occurs before a container can be started, I unfortunately cannot docker inspect on the container. Only on the image, which outputs the following.

docker inspect 39354ed06e90

`
[
    {
        "Id": "sha256:39354ed06e90501659b7d8bbf213dcbc28f72c170630db4b0755023490a9b1d8",
        "RepoTags": [
            "vsc-sbss-example-service-877b6f700ecd25f2f1f2e8038c325ff9-uid:latest"
        ],
        "RepoDigests": [],
        "Parent": "sha256:db0b18faeaa884f86cd5c1ee926181e81e1bb92214e8bcbb76f0709edf9f6060",
        "Comment": "",
        "Created": "2021-12-23T20:04:32.8728961Z",
        "Container": "c725b141bfa93aa35751b094fea1c3740ff71d04c64682b8cd03d5ba0398af9c",
        "ContainerConfig": {
            "Hostname": "c725b141bfa9",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/share/nvm/current/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/lib/jvm/msopenjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/gradle/current/bin",
                "JAVA_HOME=/usr/lib/jvm/msopenjdk-11",
                "LANG=en_US.UTF-8",
                "SDKMAN_DIR=/usr/local/sdkman",
                "NVM_DIR=/usr/local/share/nvm",
                "NVM_SYMLINK_CURRENT=true"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "USER root"
            ],
            "Image": "sha256:db0b18faeaa884f86cd5c1ee926181e81e1bb92214e8bcbb76f0709edf9f6060",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.visualstudio.code.devcontainers.id": "java",
                "com.visualstudio.code.devcontainers.release": "v0.209.6",
                "com.visualstudio.code.devcontainers.source": "https://github.com/microsoft/vscode-dev-containers/",
                "com.visualstudio.code.devcontainers.timestamp": "Tue, 14 Dec 2021 00:30:12 GMT",
                "com.visualstudio.code.devcontainers.variant": "11-bullseye",
                "version": "0.205.0"
            },
            "Shell": [
                "/bin/sh",
                "-c"
            ]
        },
        "DockerVersion": "20.10.11",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/share/nvm/current/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/lib/jvm/msopenjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/gradle/current/bin",
                "JAVA_HOME=/usr/lib/jvm/msopenjdk-11",
                "LANG=en_US.UTF-8",
                "SDKMAN_DIR=/usr/local/sdkman",
                "NVM_DIR=/usr/local/share/nvm",
                "NVM_SYMLINK_CURRENT=true"
            ],
            "Cmd": [
                "bash"
            ],
            "Image": "sha256:db0b18faeaa884f86cd5c1ee926181e81e1bb92214e8bcbb76f0709edf9f6060",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.visualstudio.code.devcontainers.id": "java",
                "com.visualstudio.code.devcontainers.release": "v0.209.6",
                "com.visualstudio.code.devcontainers.source": "https://github.com/microsoft/vscode-dev-containers/",
                "com.visualstudio.code.devcontainers.timestamp": "Tue, 14 Dec 2021 00:30:12 GMT",
                "com.visualstudio.code.devcontainers.variant": "11-bullseye",
                "version": "0.205.0"
            },
            "Shell": [
                "/bin/sh",
                "-c"
            ]
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 1110070867,
        "VirtualSize": 1110070867,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/50b3fa908c314523fd8989423893144568ed5fa1f734e21bcc4744555e1f7eff/diff:/var/lib/docker/overlay2/7978bd3f5c69ff68a2e8009c69e657b07bcd9278cbdc6ef0dfdeeeb3f812f2de/diff:/var/lib/docker/overlay2/ff099a0e710f7fdc0c9328c3fed115aa834c39b9313b16906bed3035323f733e/diff:/var/lib/docker/overlay2/09a9702573d7a95e1065f8bf43ac202918d12c38b040f296d68d9737e8feb5d9/diff:/var/lib/docker/overlay2/e4998c58829e43147080fef69d312a73ff6eddac40a0e640e45d33cec555dcc0/diff:/var/lib/docker/overlay2/2c98bd42d9d42cfdcd80d5cc610b7ccf203fafa02d2a433768fb9304e7c46db8/diff:/var/lib/docker/overlay2/1f9996767269504b649d5332dc0bf763cd87dce2a08c64a3d7abae4eb171c5d3/diff:/var/lib/docker/overlay2/e14e12b1d0a206f9dffacf448356db0aa1c46875427e9db1df6bc5a5bd469288/diff:/var/lib/docker/overlay2/35b5761c83c6f10eff9cfb7fce0549c5ac823c4d489733e15417eddd343b1771/diff:/var/lib/docker/overlay2/9014c2a0b4375123dc63a0794268fba0d8fe1aa1436f787b1e8c71f83667e14f/diff:/var/lib/docker/overlay2/f96768e84a8507bea6bc47380ba534c2ad653fd174daf6d0ada1ae7448c32332/diff",
                "MergedDir": "/var/lib/docker/overlay2/da718a46db0df84477a31ebc074f0bdf7aed8a063938a63bcfab994edbe5660e/merged",
                "UpperDir": "/var/lib/docker/overlay2/da718a46db0df84477a31ebc074f0bdf7aed8a063938a63bcfab994edbe5660e/diff",
                "WorkDir": "/var/lib/docker/overlay2/da718a46db0df84477a31ebc074f0bdf7aed8a063938a63bcfab994edbe5660e/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:e2e8c39e0f77177381177ba8c4025421ec2d7e7d3c389a9b3d364f8de560024f",
                "sha256:91f7336bbfffdab2b558c738b7eeddec9bd8ace8884b3e7b96f3f5bcb643cafa",
                "sha256:d3710de04cb3fb2b3cb30765805f36935699523e75f199975f2b9e827f19e615",
                "sha256:2882c51f47facc5b15543d7de62cc573bc29a216df8f936105ef2a1bfc6e885a",
                "sha256:702e9f671a7c482ba8ee9f6f014f9e649969191292af920f243f7f6976c25d8c",
                "sha256:db2b5448d15d3691ef4f2f2bdbe9a15620cd407dc38e45d3da7e903e6e563e74",
                "sha256:9f57a3cef9d2921748f70fd8a51af5af5b6978ef0072cc1b15956beb80fba44d",
                "sha256:fce4281b46fddb447d68f3bdc39765c3132c2d1d8869dc2fdfefb3638b4c157f",
                "sha256:65b1fb62293c73fc011812103e786a534c4155627736fb2fdd48b938b885c8e6",
                "sha256:c820c087522ce56e0f90f0ac9d6ae67c7a08a209e607a89826d6f1ed5521b22f",
                "sha256:a72225f24bb7167572209da286b85e158274bf5cc5ae72ad813124220130121a",
                "sha256:312808c664220ef0c182fa2dafc32a30940bd6490dc64cccecaf35d0bc725616"
            ]
        },
        "Metadata": {
            "LastTagTime": "2021-12-23T20:04:32.9194107Z"
        }
    }
]
`

The folder docker-mounts does not exist:

`
~ # ls -l /mnt/wsl/rancher-desktop/run
total 4
drwxr-xr-x   13 root     0             4096 Dec 23 19:32 data
srw-rw----    1 root     docker           0 Dec 23 10:55 docker.sock
~ #
`

**Comment by ckihm** [comment] 2021-12-23 21:56
For testing I have now used the same project as gunamata: [vscode-remote-try-node](https://github.com/microsoft/vscode-remote-try-node)

The result is the same:

Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/ckihm/workspace/vscode-remote-try-node,target=/workspaces/vscode-remote-try-node --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=\\wsl$\Ubuntu-DevEnv\home\ckihm\workspace\vscode-remote-try-node -l vsch.quality=stable -l vsch.remote.devPort=0 --entrypoint /bin/sh vsc-vscode-remote-try-node-135bee0ef1abe7e04d86d4d2eb4f9d17-uid -c echo Container started
trap "exit 0" 15

while sleep 1 & wait $!; do :; done

Interesting is that it behaves differently when I check out the repository in the windows filesystem and start vscode there. If I then use the function "Reopen in Container", a container is successfully created. The console output says:

Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=c:\Entwicklung\workspace\vscode-remote-try-node-main,target=/workspaces/vscode-remote-try-node-main,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=c:\Entwicklung\workspace\vscode-remote-try-node-main -l vsch.quality=stable -l vsch.remote.devPort=0 --entrypoint /bin/sh vsc-vscode-remote-try-node-main-e491ec68c95f7d66f4c22de542969066 -c echo Container started
Container started

After starting the devcontainer the same error occurs as descpibed by gunamata:

error An unexpected error occurred: "EPERM: operation not permitted, copyfile '/home/node/.cache/yarn/v6/npm-bytes-3.0.0-d32815404d689699f85a4ea4fa8755dd13a96048-integrity/no
de_modules/bytes/LICENSE' -> '/workspaces/vscode-remote-try-node-main/node_modules/bytes/LICENSE'".
info If you think this is a bug, please open a bug report with the information provided in "/workspaces/vscode-remote-try-node-main/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.


An inspect on the container looks like this:

[
    {
        "Id": "31f2d99e8d488aaa8d40fd45d839abcb494ea8eb2cd7d2fe9a9c54596763046b",
        "Created": "2021-12-23T21:31:10.4268267Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "echo Container started\ntrap \"exit 0\" 15\n\nwhile sleep 1 & wait $!; do :; done"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 32022,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-12-23T21:31:11.0442924Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:243faad9058c75ed9b3c1a4e0bf746d847650d13e2f49e08d2a017c917122734",
        "ResolvConfPath": "/var/lib/docker/containers/31f2d99e8d488aaa8d40fd45d839abcb494ea8eb2cd7d2fe9a9c54596763046b/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/31f2d99e8d488aaa8d40fd45d839abcb494ea8eb2cd7d2fe9a9c54596763046b/hostname",
        "HostsPath": "/var/lib/docker/containers/31f2d99e8d488aaa8d40fd45d839abcb494ea8eb2cd7d2fe9a9c54596763046b/hosts",
        "LogPath": "/var/lib/docker/containers/31f2d99e8d488aaa8d40fd45d839abcb494ea8eb2cd7d2fe9a9c54596763046b/31f2d99e8d488aaa8d40fd45d839abcb494ea8eb2cd7d2fe9a9c54596763046b-json.log",
        "Name": "/vibrant_bouman",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                42,
                191
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "bind",
                    "Source": "/mnt/c/Entwicklung/workspace/vscode-remote-try-node-main",
                    "Target": "/workspaces/vscode-remote-try-node-main",
                    "Consistency": "cached"
                },
                {
                    "Type": "volume",
                    "Source": "vscode",
                    "Target": "/vscode"
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/b1bd032861a67af66f1b1a761f3d906db97f3dcd0094320b43079a54b5716e28-init/diff:/var/lib/docker/overlay2/88f60d5a42e94ef9ad427c5b2d9a9eaf3e5cbeefb1d7aa7fd53175630e5fdb33/diff:/var/lib/docker/overlay2/8523d31feb52039dc07ea2a33804d0f8037b1a86e122a12920212d2d7ebc8f3b/diff:/var/lib/docker/overlay2/bed47b334313477b6b17367e9814ce22ec17243cc0ca75551dd99ecf41e58258/diff:/var/lib/docker/overlay2/704d0b2f541d0f3ab2919b3674f55d5dc63fd32a4c9c740bfe12951b57937c6d/diff:/var/lib/docker/overlay2/3b8336074e618135fc7e44a88f0d940fe218e228a7723f7a2de995101538ff95/diff:/var/lib/docker/overlay2/584fe15c3b40dd65353b90197c3396676889bf84ca555e39dfcc317cd2831760/diff:/var/lib/docker/overlay2/1cd65685cfd9163a7695cd8e30b25047e35bfedbe19c5cb14909ee3b7dfafbcc/diff:/var/lib/docker/overlay2/4781b2d42bbf4b72a985dd8c69da1076877065f1612e43349a59384e1def980e/diff:/var/lib/docker/overlay2/35b5761c83c6f10eff9cfb7fce0549c5ac823c4d489733e15417eddd343b1771/diff:/var/lib/docker/overlay2/9014c2a0b4375123dc63a0794268fba0d8fe1aa1436f787b1e8c71f83667e14f/diff:/var/lib/docker/overlay2/f96768e84a8507bea6bc47380ba534c2ad653fd174daf6d0ada1ae7448c32332/diff",
                "MergedDir": "/var/lib/docker/overlay2/b1bd032861a67af66f1b1a761f3d906db97f3dcd0094320b43079a54b5716e28/merged",
                "UpperDir": "/var/lib/docker/overlay2/b1bd032861a67af66f1b1a761f3d906db97f3dcd0094320b43079a54b5716e28/diff",
                "WorkDir": "/var/lib/docker/overlay2/b1bd032861a67af66f1b1a761f3d906db97f3dcd0094320b43079a54b5716e28/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/c/Entwicklung/workspace/vscode-remote-try-node-main",
                "Destination": "/workspaces/vscode-remote-try-node-main",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "vscode",
                "Source": "/var/lib/docker/volumes/vscode/_data",
                "Destination": "/vscode",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "31f2d99e8d48",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/share/npm-global/bin:/usr/local/share/nvm/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=16.13.1",
                "YARN_VERSION=1.22.15",
                "NVM_DIR=/usr/local/share/nvm",
                "NVM_SYMLINK_CURRENT=true"
            ],
            "Cmd": [
                "-c",
                "echo Container started\ntrap \"exit 0\" 15\n\nwhile sleep 1 & wait $!; do :; done"
            ],
            "Image": "vsc-vscode-remote-try-node-main-e491ec68c95f7d66f4c22de542969066",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/bin/sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.visualstudio.code.devcontainers.id": "javascript-node",
                "com.visualstudio.code.devcontainers.release": "v0.209.0",
                "com.visualstudio.code.devcontainers.source": "https://github.com/microsoft/vscode-dev-containers/",
                "com.visualstudio.code.devcontainers.timestamp": "Thu, 02 Dec 2021 21:27:52 GMT",
                "com.visualstudio.code.devcontainers.variant": "16-bullseye",
                "version": "0.203.2",
                "vsch.local.folder": "c:\\Entwicklung\\workspace\\vscode-remote-try-node-main",
                "vsch.quality": "stable",
                "vsch.remote.devPort": "0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "939e3f7d14fd426a3e322156c7c4ac07d1a2331e62f0a47fc6434ad01aa7c803",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/939e3f7d14fd",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "a1c469df43adf705c4d9b462476443686af92fa621ace6bf634baadd3f5652b7",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "2e46f625f7c3c4ca76f86d204d1bb900cb24904788526fc06b0ca4acaf801350",
                    "EndpointID": "a1c469df43adf705c4d9b462476443686af92fa621ace6bf634baadd3f5652b7",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by mook-as** [comment] 2021-12-23 22:04
@ckihm at this point I believe that is separate enough from this issue (both remote — WSL _and_ remote — Containers is involved); would you be okay with opening a new issue with that information so we can better keep track? As far as I can tell, that needs a different set of steps to reproduce. I don't want to end up closing this issue and losing your issue…
(Also, please use [triple backticks](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) for the file contents, thanks!)

**Comment by ckihm** [comment] 2021-12-23 22:26
@mook-as: I will be happy to do so. However, I just did another test which takes the remote WSL extention out of the equation again. The problem can be easily recreated:

1. Check out the repository in WSL's filesystem with git. 
2. Start VS Code under Windows and open the folder with the code. 
3. Next start the remote container with "Reopen in Container".  

The same error occurs. I think it is because the remote container extention is running under Windows, no matter if VS code was started under Windows or in WSL. However, if the workspace is in a WSL filesystem, then the full Windows path is not used, but /home/<user>/<path to workspace>.

I have installed dockerd and the docker cli directly in another WSL distribution. There it works.

**Comment by ckihm** [comment] 2022-01-03 14:59
@mook-as I opened a [new issue](https://github.com/rancher-sandbox/rancher-desktop/issues/1173)

**Comment by mook-as** [comment] 2022-01-11 17:34
Thanks! I'll take a look once all the other things on my plate are done (…still going through my mail backlog after vacation).

**Comment by mook-as** [comment] 2022-01-21 22:22
Circling back — nothing left in this issue; the spun-off #1173 has already been resolved.

**Closed by mook-as** 2022-01-21 22:22 UTC
