### ISSUE TITLE
Support for Windows Containers

### ISSUE THREAD

**Issue by e1213613-sanuk** [rancher-sandbox/rancher-desktop#7050] opened 2024-06-13 15:42 UTC
### Problem Description

Are Windows containers supported by Rancher Desktop? Currently we extensively use, modify and run Windows containers and have been recently forced to move to use Rancher Desktop exclusively. This has put us in a very tight spot and we would like to see if Windows containers can be officially supported in Rancher Desktop.

### Proposed Solution

Provide official support for Windows containers in Rancher Desktop.

**Comment by jandubois** [comment] 2024-06-13 17:42
This is a duplicate of #255.

Are you looking to run Windows containers by themselves, or via Kubernetes. The former is something we could possibly do, but haven't scheduled so far. Running Windows containers with Kubernetes is probably not going to happen with Rancher Desktop.

I'm closing this as a duplicate; please add your 👍 to #255 instead. It has more upvotes than I remembered, so we will be at least discussing it again in project planning.

**Closed** 2024-06-13 17:43 UTC
Labels: kind/enhancement
