### ISSUE TITLE
Implement a credential server inside RD answering on http(s) and forwarding to the native credential helper

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2133] opened 2022-04-29 03:17 UTC
The credentials server is part of the RD app, just like the `rdctl` server.

It listens on a random port on localhost. It only supports HTTP GET with the 4 actions defined by the [docker credential helper API](https://github.com/docker/docker-credential-helpers#development): `store`, `get`, `erase`, `list`.

Eventually we want to use mTLS, but we can initially use plain HTTP with basic auth to get started.

The server will invoke the local credential helper stored in `~/.docker/config.json` with the query path as the argument, and the body text as STDIN. It will return the STDOUT from the helper.

Example:

```console
$ HELPER="docker-credential-$(jq -r .credsStore ~/.docker/config.json)"

$ echo $HELPER
docker-credential-osxkeychain

$ $HELPER list
{"https://registry.home":"user"}

$ echo "https://registry.home" | $HELPER get
{"ServerURL":"https://registry.home","Username":"user","Secret":"password"}
```

This server should be testable using `curl`, e.g.

```console
$ curl -u user:pass -d "https://registry.home" http://localhost:2345/get
{"ServerURL":"https://registry.home","Username":"user","Secret":"password"}
```

**Comment by jandubois** [comment] 2022-05-03 02:07
> it doesn't allow a GET method to have a body

Yes, that makes sense. Could we still use `POST` for all actions? (This question will make more sense once I write the task for implementing the minimalist client side code in 3 lines of bash 😄 ).

**Comment by jandubois** [comment] 2022-05-03 02:26
Note: the basic auth credentials should be regenerated every time the server starts.

**Comment by ericpromislow** [comment] 2022-05-03 03:53
We can support POST for all the actions, as well as GET synonyms for the `list` and `get` endpoints, the latter for people using clients that won't let them supply bodies for `GET` methods. Adding a synonym is one extra entry in the lookup table, plus tests. Plus getting the arguments from the query string rather than the payload. So it's not trivial...

BTW, I should mention that I had no problem hitting the server manually with `curl` from bash. I only ran into this problem with `fetch` when writing integration tests. Maybe it's possible to configure `node-fetch` to allow `get` calls with a body, but we don't want to support other clients that use the `fetch` library. So I think synonyms are the way to go.

As for your other comment, the password *is* regenerated on every run. This is only a problem when the backend process is still running when Rancher Desktop shuts down. On the next run you get a new server, with a new password and an updated config file, but you still have an existing server handling requests and expecting to see the old password.

**Comment by jandubois** [comment] 2022-05-03 04:41
> for people using clients that won't let them supply bodies for `GET` methods.

The server is exclusively the backend for the `docker-credential-rancher-desktop` forwarder. Nothing else should ever connect to it. So neither the client nor the server of the forwarder really need to be aware of the commands at all. Just invoke the corresponding action on the host helper and pass the request body over as the STDIN, and return STDOUT as the body of the reply.

> I only ran into this problem with `fetch` when writing integration tests.

It doesn't really matter which method we use, as this will always be a local direct connection without any proxies in between. Now this reminds me: we need to unset `http_proxy` in the client script.

> So I think synonyms are the way to go.

It is not needed. Let's keep this to the minimum required to just forward the API over a tunnel.

> This is only a problem when the backend process is still running when Rancher Desktop shuts down.

I don't understand this. The server is part of Rancher Desktop, so how can it be still running when it shuts down? Are you planning to implement this as an external process? That's not how it should work!

**Comment by ericpromislow** [comment] 2022-05-03 20:37
> for people using clients that won't let them supply bodies for GET methods.
> 

> > The server is exclusively the backend for the docker-credential-rancher-desktop forwarder. Nothing else should ever connect to it. So neither the client nor the server of the forwarder really need to be aware of the commands at all. Just invoke the corresponding action on the host helper and pass the request body over as the STDIN, and return STDOUT as the body of the reply.

In that case, there's no problem.

> 
> This is only a problem when the backend process is still running when Rancher Desktop shuts down.
> 

> > I don't understand this. The server is part of Rancher Desktop, so how can it be still running when it shuts down? Are you planning to implement this as an external process? That's not how it should work!

No, I'm not. The issue is that Rancher Desktop consists of two processes, the backend and the renderer (aka the UI). Once in a while on shutdown I've observed (as well as Adam) that the backend process is still running. On the next launch, you end up with one renderer process and two backends.

Maybe this can be fixed by issue #2173

**Comment by gioppoluca** [comment] 2022-05-13 11:22
At the moment I get with RD 1.3.0 this error
```
Error saving credentials: error storing credentials - err: exec: "docker-credential-desktop": executable file not found in %PATH%, out: 
```

**Comment by jandubois** [comment] 2022-05-13 16:55
> At the moment I get with RD 1.3.0 this error
> 
> ```
> Error saving credentials: error storing credentials - err: exec: "docker-credential-desktop": executable file not found in %PATH%, out: 
> ```

Rancher Desktop 1.3.0 does not bundle the credential helpers (1.4.0 will), so you have to install them manually, e.g. with `brew install docker-credential-helper` if you are using homebrew for package management.

Then you will need to edit `~/.docker/config.json` and change the value of `credsStore` from `desktop` to `osxkeychain`. The `desktop` helper is a proprietary part of Docker Desktop and not available separately. But `osxkeychain` works the same way, and credentials stored by `desktop` can be retrieved by `osxkeychain` and vice versa.

**Closed** 2022-05-24 19:10 UTC
Labels: kind/enhancement, area/registry
