### ISSUE TITLE
Rancher Desktop stopped starting

### ISSUE THREAD

**Issue by Keij0** [rancher-sandbox/rancher-desktop#6048] opened 2023-11-24 20:18 UTC
### Actual Behavior

The icon bounces a couple times in the dock and nothing happens. It started on Monterey 12.5 and I updated to Sonoma 14.1.1 to see if it helps. 

I tried to delete all rancher directories and ~/.docker but I can't find anything that would help.

### Steps to Reproduce

Try to start the application

### Result

The application doesn't start

### Expected Behavior

The application starts

### Additional Information

I have Nix package manager (nixos.org) installed on this system. 

I have this in background.log in rancher logs: 

2023-11-24T20:00:25.225Z: Error starting up: Error: /usr/bin/security exited with code 2
 Error: /usr/bin/security exited with code 2
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:2:137659)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

### Rancher Desktop Version

1.11.0

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Sonoma 14.1.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment] 2023-11-24 20:24
Can you run `/usr/bin/security list-keychains` from the commandline, and does it list at least the login and the System keychains?

**Comment by Keij0** [comment] 2023-11-24 20:45
Here's the output of that:
`    "/Users/keijo/Library/Keychains/temp.keychain-db"
    "/Users/keijo/Library/Keychains/    "/Users/keijo/Library/Keychains/login.keychain-db"
-db"
    "/Users/keijo/Library/Keychains/login.keychain-db"
    "/Library/Keychains/System.keychain"`

**Comment by jandubois** [comment] 2023-11-24 20:56
> Here's the output of that:

The output looks garbled, but I assume this is a but&past error; I would have expected it to look like this:

```console
% /usr/bin/security list-keychains
    "/Users/keijo/Library/Keychains/login.keychain-db"
    "/Library/Keychains/System.keychain"
```

But it looks like you are able to run the command.

Can you check the `networking.log` to see if you have any errors in there?

**Comment by Keij0** [comment] 2023-11-24 20:58
<img width="639" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/20029608/0d0f30f7-2c4e-486e-8d7d-4306a3ba55cb">
It kind of looks garbled. maybe a screenshot will do it justice

**Comment by Keij0** [comment] 2023-11-24 21:00
networking.log looks like

`...certificate verification successful.
find-certificate: illegal option -- d
Usage: find-certificate [-a] [-c name] [-e emailAddress] [-m] [-p] [-Z] [keychain...]
    -a  Find all matching certificates, not just the first one
    -c  Match on "name" when searching (optional)
    -e  Match on "emailAddress" when searching (optional)
    -m  Show the email addresses in the certificate
    -p  Output certificate in pem format
    -Z  Print SHA-256 (and SHA-1) hash of the certificate
If no keychains are specified to search, the default search list is used.
        Find a certificate item.`

**Comment by jandubois** [comment] 2023-11-24 21:12
> It kind of looks garbled. maybe a screenshot will do it justice

Yes, that looks indeed very concerning. I'm also wondering what the `temp.keychain-db` is doing, but found little info on Google.

Please check the exit status of the command. Ideally it should be `0`:

```console
% /usr/bin/security list-keychains
    "/Users/keijo/Library/Keychains/login.keychain-db"
    "/Library/Keychains/System.keychain"
% echo $?
0
```

If this returns `2` instead, then this is indeed the problem that prevents Rancher Desktop from starting, as it needs to access the keychain to import CA certificates from the host into the VM.

This seems to be an issue with your machine setup and not with Rancher Desktop. I'm very reluctant to suggest any changes to you, as messing up the keychains could make your machine unusable.

If this were my machine, the next things I would look into would be `~/Library/Preferences/com.apple.security.plist` where additional keychains might be defined. Check if there are any unexpected characters in the database names.

And I would run `/Applications/Keychain Access.app` to see if that reports any problems.

**Comment by Keij0** [comment] 2023-11-24 21:15
I have to reinstall Nix every time I update macOS. Maybe it messed up keychains on some occasion. The second line looks veery weird to me. temp is something that got created during trying to build telegram desktop I see. I can delete that.

**Comment by Keij0** [comment] 2023-11-24 21:16
The command seems to return 0 though which is weird considering the fact background.log complains about it returning status code 2

**Comment by Keij0** [comment] 2023-11-24 21:19
<img width="754" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/20029608/5d5f00b1-3d48-4b49-8d68-c10bd490ee3a">
There's that weird string one in com.apple.security.plist.

**Comment by jandubois** [comment] 2023-11-24 21:23
Ok, I see the problem now. It is indeed due to the garbled output of `security list-keychains`. Rancher Desktop iterates over the list of keychains and tries to list the certificates stored in each. But in your output not every line shows a valid keychain filename. So when the loop reaches `-db` as the keychain name it runs

```
% /usr/bin/security find-certificate -a -p -db
find-certificate: illegal option -- d
Usage: find-certificate [-a] [-c name] [-e emailAddress] [-m] [-p] [-Z] [keychain...]
...
```

and fails with an exit code of `2`, which then aborts the app startup.

So the root cause remains the same; you need to fix up the keychain configuration so that `security list-keychains` returns a list with one keychain filename per line.

**Comment by Keij0** [comment] 2023-11-24 21:24
I can't seem to delete that string with `security delete-keychain`. Do you think I can just remove that dict from the plist and it'll work?

**Comment by jandubois** [comment] 2023-11-24 21:33
> Do you think I can just remove that dict from the plist and it'll work?

You should make a backup copy of the plist to begin with. I would also make sure to have a second account on the machine with Administrator rights, just in case any changes you make will prevent you from logging in again with your current account.

I can't take responsibility if you make changes to your keychain configuration, and I probably won't be able to help you to recover the machine, if something breaks. But assuming you take responsibility, you could edit the plist file and then reboot the machine. I think there is a good chance that this will fix your problem.

The entry should look like this:

```xml
		<dict>
			<key>DbName</key>
			<string>~/Library/Keychains/login.keychain</string>
			<key>GUID</key>
			<string>{87191ca3-0fc9-11d4-849a-000502b52122}</string>
			<key>SubserviceType</key>
			<integer>6</integer>
		</dict>
```

It also looks like the system has created an alternate "temp" login keychain, which may now have some overlap with your original login keychain. I can't tell if you want to try to remove the temp keychain and see if everything works with just the regular keychain again. You may be missing additional passwords and certs that have been saved after your configuration got broken.

That of course is another open question: how did you get into this state, and how can you prevent it from happening again? Unfortunately you'll have to figure this out on your own.

**Comment by Keij0** [comment] 2023-11-24 21:34
I already removed the temp keychain. It contained a certificate from a provisioning profile and it got created while I messed with building Telegram-iOS. I think it's irrelevant to the case. 

I'll create a temp admin and try to fix it. Will report back when I'm done.

**Comment by Keij0** [comment] 2023-11-24 21:35
<img width="760" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/20029608/fd52eb74-5542-4986-a1e9-dc4d8c82aae9">
There's a normal login keychain entry in there so I assume I can just remove the garbled one

**Comment by jandubois** [comment] 2023-11-24 21:39
> There's a normal login keychain entry in there so I assume I can just remove the garbled one

I would think so too. Probably just logging out and logging back in should be enough, but I would reboot after making the change, just to be sure everything is reinitialized from scratch.

Unrelated, but I'm surprised all keychain entries have the same GUID, not just on the same machine, but also across machines, and across macOS versions. Doesn't look very "globally unique" to me, but I guess that is just a bug.

**Comment by Keij0** [comment] 2023-11-24 21:40
Maybe it got bugged when it was randomized so they just left a single GUID for every macOS installation :D Okay I'm patching it and rebooting, cya in a short while.

**Comment by Keij0** [comment] 2023-11-24 21:43
<img width="390" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/20029608/961264b1-2259-4641-9032-314beae0dd5a">
<img width="511" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/20029608/6abb48b0-75b6-41fb-96e5-a6c00c67d984">


Aaaaand we have liftoff. Thanks for the swift help. I don't believe I would've figured it out myself. Maybe it's a good thing to add in troubleshooting docs?

**Comment by jandubois** [comment] 2023-11-24 21:48
> Aaaaand we have liftoff. Thanks for the swift help. I don't believe I would've figured it out myself. Maybe it's a good thing to add in troubleshooting docs?

Excellent! I'm going to close this issue now.

I don't think we need this in the Rancher Desktop docs, as this is the only time this has ever been reported here, and is not really a Rancher Desktop issue anyways. I still don't understand how you got into this situation to begin with.

**Closed by jandubois** 2023-11-24 21:48 UTC
Labels: kind/bug

**Comment by Keij0** [comment] 2023-11-24 21:50
I don't know what created that broken keychain there anyway. Good we've been able to resolve it. Thanks for the help.
