### ISSUE TITLE
nslookup in WSL rancher-desktop distro doesn't handle the host-resolver result cleanly

### ISSUE THREAD

**Issue by byjrack** [rancher-sandbox/rancher-desktop#2141] opened 2022-04-29 17:06 UTC
### Actual Behavior

IPs are being mapped to names w/o an issue.  Tested w docker and w curl as example.  

Specifically w nslookup though I am getting an error in the result.

### Steps to Reproduce

1. Enable the host-resolver
2. Start RD
3. wsl -d rancher-desktop
4. nslookup google.com

### Result

```
# nslookup google.com
Server: 172.23.172.135
Address: 172.23.172.135:53

Non-authoritative answer:
*** Can't find google.com: Parse error
```

### Expected Behavior

```
...
Non-authoritative answer:
Name: google.com
Address: 142.251.15.102
...
```

### Additional Information

Again not noticing any functional difference with host-resolver.  Just noticed that one test had an unexpected result.

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

1.23.4

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

20H2 19042.1645

### What CPU architecture are you using?

x64

**Comment by Nino-K** [comment] 2022-05-02 17:52
@byjrack thanks for filing this, I'm trying to reproduce this and I'm having a hard time. I'm getting the results below:
```
# nslookup google.com
Server:         192.168.243.70
Address:        192.168.243.70#53

Non-authoritative answer:
Name:   google.com
Address: 172.217.14.206
```
A few questions, just to make sure this is not occurring with a specific version of nslookup, what version/build of nslookup are you using? 

Also, are you able to confirm the content of the `/etc/resolv.conf`?
Below is mine at the time of my testing with no additional configuration.
```
nameserver 192.168.243.70
```
And lastly, is dig able to parse the response and resolve?

Many thanks,

**Comment by byjrack** [comment] 2022-05-02 20:58
Hey sorry for the delay.

So the TLDR is that it looks like the Busybox version of nslookup is having issues.  1.30 has 1.34.1-r5 as the base it seems and it gave me the initial parse errors.  I installed bind-tools (apk add bind-tools) for dig support and the same command worked perfectly fine using experimentalHostResolver=true.  It overwrote the distro copy so I [grabbed the most recent](https://busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox_NSLOOKUP) and the same issue occurs.

```
# experimental=false and nslookup=busybox
>nslookup -v
BusyBox v1.34.1 (2022-04-04 10:19:27 UTC) multi-call binary.

Usage: nslookup [-type=QUERY_TYPE] [-debug] HOST [DNS_SERVER]
Query DNS about HOST
QUERY_TYPE: soa,ns,a,aaaa,cname,mx,txt,ptr,srv,any

>nslookup www.google.com
Server:         172.29.160.138
Address:        172.29.160.138:53

Non-authoritative answer:
Name:   www.google.com
Address: 2607:f8b0:4004:807::2004

Non-authoritative answer:
Name:   www.google.com
Address: 172.217.12.228

# no dig available 
```

```
# experimental=false and nslookup=ISC (apk add bind-tools)
nslookup www.google.com
Server:         172.29.160.138
Address:        172.29.160.138#53

Non-authoritative answer:
Name:   www.google.com
Address: 172.217.164.68
Name:   www.google.com
Address: 2607:f8b0:4002:817::2004

>dig www.google.com

; <<>> DiG 9.16.27 <<>> www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9519
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google.com.                        IN      A

;; ANSWER SECTION:
www.google.com.         0       IN      A       172.217.164.68

;; Query time: 50 msec
;; SERVER: 172.29.160.138#53(172.29.160.138)
;; WHEN: Mon May 02 20:23:27 UTC 2022
;; MSG SIZE  rcvd: 62
Address: 2607:f8b0:4002:817::2004
```
```
# experimental=true and nslookup=ISC
nslookup www.google.com
Server:         172.29.160.138
Address:        172.29.160.138#53

Non-authoritative answer:
Name:   www.google.com
Address: 64.233.177.99
Name:   www.google.com
Address: 64.233.177.103
Name:   www.google.com
Address: 64.233.177.104
Name:   www.google.com
Address: 64.233.177.105
Name:   www.google.com
Address: 64.233.177.106
Name:   www.google.com
Address: 64.233.177.147

>dig google.com
; <<>> DiG 9.16.27 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43136
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available
;; WARNING: Message has 968 extra bytes at end

;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             5       IN      A       142.250.73.206

;; Query time: 120 msec
;; SERVER: 172.29.160.138#53(172.29.160.138)
;; WHEN: Mon May 02 20:26:42 UTC 2022
;; MSG SIZE  rcvd: 1022
```

```
# experimental=true and nslookup=busybox (1.35.0)

./busybox_NSLOOKUP www.google.com
Server:         172.29.160.138
Address:        172.29.160.138:53

Non-authoritative answer:
*** Can't find www.google.com: Parse error

Non-authoritative answer:
*** Can't find www.google.com: Parse error
```

**Comment by Nino-K** [comment] 2022-05-03 02:01
@byjrack thanks for providing more details, I managed to reproduce it as it only happens with busybox nslookup, I can see they are doing some additional checks on the receive length [here](https://elixir.bootlin.com/busybox/latest/source/networking/nslookup.c#L640) whereas bind-utils nslookup does nothing in that case.

**Comment by byjrack** [comment] 2022-05-03 02:26
Yup same thing I am seeing. I have not seen any application issues so it seems to be just limited to nslookup as you would expect. Feel free to close this one out as it came from a Slack thread. Not even sure where it could be documented as a known issue with no impact. I may do a tcpdump of the two flows to see if a PR To busybox makes sense.  They may be sticking to strict padding or protocol spec that others are not, but more info needed.

**Comment by jandubois** [comment] 2022-05-03 02:42
> I have not seen any application issues so it seems to be just limited to nslookup as you would expect.

I'm not convinced of that. The `nslookup` implementation from `busybox` is using the [ns_parse](https://github.com/bminor/musl/blob/master/src/network/ns_parse.c) code from `musl`, so this could potentially affect other tools that links against the resolver included in `musl`, including any container workloads based on Alpine.

It would be better to understand what kind of additional restrictions they impose, and then make sure we comply with those in the host-resolver responses.

**Comment by Nino-K** [comment] 2022-05-03 03:53
@byjrack the fix is here, thanks again for noticing this!

https://github.com/rancher-sandbox/rancher-desktop-host-resolver/pull/14

**Comment by byjrack** [comment] 2022-05-03 12:15
And good point @jandubois I just didn't want focus to be shifted away from the bigger features and friction points than this since at the moment it seemed pretty narrowly scoped.  @Nino-K beat me to comparing the implementations and how resolver might be triggering the situation so this one be all tied up.  Given the difference in the ISC implementation I wasn't sure what might be correct per the spec and C is far from my wheelhouse anyways.  Going to close this Issue as I think it's all taken care of with that PR.

**Comment by mook-as** [comment] 2022-05-03 19:40
Hi! Sorry, I'm temporarily reopening this issue… so that I can track that I still need to review that other PR (since we mostly work off the Rancher Desktop board).

I'll close this again once the other PR is merged (plus additional PR to pick up the new host resolver).

**Closed** 2022-05-12 18:26 UTC
Labels: kind/bug, platform/windows, area/dns
