### ISSUE TITLE
Can not launch Rancher Desktop

### ISSUE THREAD

**Issue by Luis-Monterroso** [rancher-sandbox/rancher-desktop#6881] opened 2024-05-14 17:47 UTC
### Actual Behavior

When I launch Rancher Desktop I get the following error, '--tty=false',
    '/Users/luis-monterrosocarpi/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
  ],
  stdout: '',
  stderr: 'time="2024-05-14T13:40:08-04:00" level=info msg="Terminal is not available, proceeding without opening an editor"\n' +
    'time="2024-05-14T13:40:08-04:00" level=fatal msg="instance name \\"0\\" too long: \\"/Users/luis-monterrosocarpi/Library/Application Support/rancher-desktop/lima/0/ssh.sock.1234567890123456\\" must be less than UNIX_PATH_MAX=104 characters, but is 104"\n',
  code: 1,
  [Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura start --tty=false /Users/luis-monterrosocarpi/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
}
Solutions on other threads have not fixed the issue

### Steps to Reproduce

Open Rancher Desktop with a username >= 20 characters

### Result

Rancher Desktop fails to launch

### Expected Behavior

Rancher Desktop launches without issue

### Rancher Desktop Version

1.29.4

### Rancher Desktop K8s Version

1.13.1

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Macos Ventura 13.3.1

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

AppImage

**Comment by jandubois** [comment] 2024-05-14 18:02
This is a duplicate of #797. Please check https://github.com/rancher-sandbox/rancher-desktop/issues/797#issuecomment-996510877 for a workaround!

**Closed by jandubois** 2024-05-14 18:02 UTC
Labels: kind/bug
