### ISSUE TITLE
wsl2 kernel missing on clean windows with rancher desktop install

### ISSUE THREAD

**Issue by fiburonsk** [rancher-sandbox/rancher-desktop#3349] opened 2022-11-06 22:05 UTC
### Actual Behavior

In a freshly installed Windows 10 21H2 with updates and without WSL installed the Rancher Desktop installer installs WSL for me.  After completing setup If I try to run rancher desktop after the reboot and completing the install it fails to start.  

![image](https://user-images.githubusercontent.com/10441670/200197411-7a115ed0-c3df-45ec-9da0-0cda7bc29f5c.png)

The WSL Kernel was not installed by the Rancher Desktop installer
```
wsl --status
...
The WSL 2 kernel file is not found. To update or restore the kernel please run 'wsl.exe --update'.
```

Running an elevated `wsl --update` and then starting rancher desktop works as expected.

### Steps to Reproduce

1. Start from a fresh windows 10 21h2 that is up to date with windows updates.
2. Install rancher desktop. it installs WSL and requires a reboot.
3. Finish installing rancher desktop.
4. Run rancher desktop, it fails.

### Result

![image](https://user-images.githubusercontent.com/10441670/200197411-7a115ed0-c3df-45ec-9da0-0cda7bc29f5c.png)

### Expected Behavior

After completing the rancher desktop installation my expectation would be that I can launch Rancher Desktop without errors.

### Additional Information

Running this command in an admin powershell `wsl --update` or downloading and manually installing the wsl kernel provided here: https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package on step 4.1 before running Rancher Desktop will allow it to work as expected

### Rancher Desktop Version

1.6.1

### Rancher Desktop K8s Version

1.25.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 21H2

### What CPU architecture are you using?

x64

### Windows User Only

no

**Comment by mook-as** [comment] 2022-11-07 17:51
Hi! This might be a duplicate of #1867: if your user account does not administrative access (you had to use a different account for the UAC prompt during installation), the WSL kernel isn't installed correctly (it'll get installed next time the admin account logs in instead, which may be never).

I'll close this for now (assuming it's a duplicate), but please let me know if that is _not_ the case (e.g. if you encountered this issue with different steps), and we can reopen this issue.  Thanks!

**Closed by mook-as** 2022-11-07 17:51 UTC
Labels: kind/bug
