### ISSUE TITLE
Disable k3s and keep only container management features

### ISSUE THREAD

**Issue by douglascamata** [rancher-sandbox/rancher-desktop#795] opened 2021-10-14 10:07 UTC
**For feature requests, describe what you'd like to add or change**

I would like to disable k3s completely to save resources, as I don't need it in my workflow. I only need the container management features.

**Expected behaviour**
A configuration option to enable or disable k3s.

**Comment by joao-dantas** [comment] 2021-12-10 18:36
I loved that. I am evaluating the tool too and I was looking to see if there were any feature requests for that yet.

**Comment by ericpromislow** [comment] 2022-02-09 23:53
Duplicate of #1562

**Closed by ericpromislow** 2022-02-09 23:53 UTC
Labels: kind/enhancement
