### ISSUE TITLE
Rancher Desktop 1.13.1 broken on Ubuntu 24.04

### ISSUE THREAD

**Issue by johannespfrang** [rancher-sandbox/rancher-desktop#6838] opened 2024-05-07 12:11 UTC
### Actual Behavior

The lima version bundled in Rancher Desktop 1.13.1 searches for a firmware file called `OVMF_CODE.fd`, but that file has been removed in [Debian testing](https://packages.debian.org/testing/all/ovmf/filelist) and in [Ubuntu 24.04](https://packages.ubuntu.com/noble/ovmf/filelist) in favor of `OVMF_CODE_4M.fd`. Lima added the new file name with commit https://github.com/lima-vm/lima/commit/3c4a7f34d1f1506cc56cd7ee1b52b3a6893ae830 starting with [v0.20.0](https://github.com/lima-vm/lima/releases/tag/v0.20.0).

### Steps to Reproduce

Try to run Rancher Desktop 1.13.1 on Ubuntu 24.04 (likely also affects Debian testing).

### Result

Rancher reports an error.:

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/159568713/9cee42df-c8d6-4e27-b46b-a0b5d6302e8c)

The `lima.stderr.log` shows this error:

```
{"level":"debug","msg":"firmware candidates = [/home/${removed_username}/.local/share/qemu/edk2-x86_64-code.fd /usr/share/qemu/edk2-x86_64-code.fd /usr/share/OVMF/OVMF_CODE.fd /usr/share/qemu/ovmf-x86_64-code.bin /usr/share/edk2-ovmf/x64/OVMF_CODE.fd]","time":"2024-05-07T11:51:29+02:00"}
{"level":"fatal","msg":"could not find firmware for \"/usr/bin/qemu-system-x86_64\" (hint: try setting `firmware.legacyBIOS` to `true`)","time":"2024-05-07T11:51:29+02:00"}
```

### Expected Behavior

Rancher Desktop should work on the newly released Ubuntu 24.04.

### Additional Information

Creating a symbolic link from the old path to the new path works and makes Rancher Desktop run normally.

### Rancher Desktop Version

1.13.1-3.1

### Rancher Desktop K8s Version

1.29.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Ubuntu 24.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by jandubois** [comment] 2024-05-07 16:09
Thank you for the report; it is a duplicate of #4524 and will be fixed in Rancher Desktop 1.14, which bundles Lima 0.21.0.

**Closed by jandubois** 2024-05-07 16:09 UTC
Labels: kind/bug
