### ISSUE TITLE
Support for M4 Mac?

### ISSUE THREAD

**Issue by randallweytens** [rancher-sandbox/rancher-desktop#8013] opened 2024-12-29 12:16 UTC
### Actual Behavior

I get a Kubernetes error when starting Rancher Desktop 1.16.0. In the $HOME/LibraryApplication\ Support/rancher-desktop/lima/0ha.stdout.log file these errors were found:

{"level":"debug","msg":"qemu[stderr]: Unexpected error in object_property_find_err() at ../qom/object.c:1330:","time":"2024-12-29T03:38:54-08:00"}
{"level":"debug","msg":"qemu[stderr]: qemu-system-aarch64: Property 'host-arm-cpu.sme' not found","time":"2024-12-29T03:38:54-08:00"}

This also looks like open issue #3842 

https://github.com/canonical/multipass/issues/3842

### Steps to Reproduce

Download installer, drag to Applications directory, click "OK" with the defaults.

### Result

<img width="750" alt="Screenshot 2024-12-29 at 04 04 36" src="https://github.com/user-attachments/assets/b611e3ee-e558-4c98-9208-7051f5473107" />

### Expected Behavior

Install Rancher desktop without errors.

### Rancher Desktop Version

1.16.0

### Rancher Desktop K8s Version

1.31.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Sequoia 15.2

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment] 2024-12-30 08:14
This is a duplicate of #7968. It will be fixed in 1.17.0. With 1.16.0 the only workaround is to use VZ emulation instead of QEMU.

**Closed by jandubois** 2024-12-30 08:14 UTC
Labels: kind/bug
