### ISSUE TITLE
Rancher `aarch64` build provides `x86_64` binaries causing CPU errors

### ISSUE THREAD

**Issue by mbrancato** [rancher-sandbox/rancher-desktop#7168] opened 2024-07-09 14:35 UTC
### Actual Behavior

The menubar context switcher does not switch. I already had a correct `aarch64` build of `kubectl` in my PATH, so I was not using the `kubectl` included with Rancher in my CLI. 

### Steps to Reproduce

Attempt to switch contexts on an ARM64 Mac.

### Result

```
% /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/kubectl
zsh: bad CPU type in executable: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl
% file "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl"
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl: Mach-O 64-bit executable x86_64
```

Attempting to use the menu bar context switcher, I ran into this error:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: spawn Unknown system error -86
at ChildProcess.spawn (node:internal/child_process:413:11)
at spawn (node:child_process:783:9)
at /Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:41:117630
at Ws.contextClick (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:41:117856)
at click (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:41:117498)
at MenuItem.click (node:electron/js2c/browser_init:2:31004)
at Menu._executeCommand (node:electron/js2c/browser_init:2:36400)
```
<img width="518" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/8493275/9800b8b9-df2d-4c45-b6db-b32c1d921062">

### Expected Behavior

Context should switch properly.
Correct CPU type builds should be included.

### Additional Information

SHA 512 sum of `Rancher.Desktop-1.14.2.aarch64.dmg` matches that in the GitHub releases
d232fc83af526d5927b8c361998ad46d27ea8cec4a70fe6738ef2a996297e0e8162ae3afd91310feb20f8601f6b2396be91fc0d1102f4db4f62e55e1d8a9c1be

### Rancher Desktop Version

1.14.2

### Rancher Desktop K8s Version

1.29.6

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Sonoma 14.5 (23F79)

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by mbrancato** [comment] 2024-07-09 14:43
A mix of build types are included in the package, but this only affects `kubectl` and `kuberlr`:
```
% for i in $(ls); do file $i; done
docker: Mach-O 64-bit executable arm64
docker-buildx: Mach-O 64-bit executable arm64
docker-compose: Mach-O 64-bit executable arm64
docker-credential-ecr-login: Mach-O 64-bit executable arm64
docker-credential-none: Mach-O 64-bit executable arm64
docker-credential-osxkeychain: Mach-O 64-bit executable arm64
helm: Mach-O 64-bit executable arm64
kubectl: Mach-O 64-bit executable x86_64
kuberlr: Mach-O 64-bit executable x86_64
nerdctl: Bourne-Again shell script text executable, ASCII text
rdctl: Mach-O 64-bit executable arm64
spin: Mach-O 64-bit executable arm64
```

I've tried going back to older versions of Rancher Desktop with the same result.

**Comment by mbrancato** [comment] 2024-07-09 15:03
The following replaces the `kubectl` and `kuberlr` binaries with their ARM64 versions, and the error context switching goes away.

```
curl -L https://github.com/flavio/kuberlr/releases/download/v0.4.5/kuberlr_0.4.5_darwin_arm64.tar.gz -O
tar -xzvf kuberlr_0.4.5_darwin_arm64.tar.gz --strip-components=1 -C /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin kuberlr_0.4.5_darwin_arm64/kuberlr
chmod +x /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/kubectl

curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/arm64/kubectl" -o /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/kubectl
```

**Comment by jandubois** [comment] 2024-07-09 17:39
This is a duplicate of #980. It didn't use to be an issue because you needed to install Rosetta anyways for the GUI.

We will be dropping support for Kubernetes versions older than 1.21.0 in the Rancher Desktop 1.15.0 release, which will allow us to switch to the aarch64 of version of `kuberlr` and `kubectl`. This will be tracked by #980, which is part of the 1.15 milestone.

**Closed by jandubois** 2024-07-09 17:39 UTC
Labels: kind/bug
