### ISSUE TITLE
Rancher Desktop throws an error by loading rdx-proxy image with containerd

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4840] opened 2023-06-01 22:19 UTC
### Actual Behavior

Once we select `containerd` in the first-run dialog, Rancher Desktop throws a 'Kubernetes Error" dialog, even though Kubernetes status is running. The error occurs when loading the `rdx-proxy` image. 

### Steps to Reproduce

1. Create a deployment profile like the one from the file (
[dep-profile.txt](https://github.com/rancher-sandbox/rancher-desktop/files/11630204/dep-profile.txt) )
 that enables a list of extensions only compatible with `moby` (in this example the list is: trivy-docker-extension, docker/disk-usage-extension:0.2.7, prakhar1989/dive-in)
2. Start Rancher Desktop
3. Select `containerd` as the container runtime from the first-run dialog
4. Check the error message that comes from the "Kubernetes Error" dialog

### Result

Last command run:
`nerdctl --namespace rancher-desktop-extensions image load --input /Applications/Rancher Desktop.app/Contents/Resources/resources/rdx-proxy.tgz`

Fatal error:
```
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJR3hLVEdDVVN2WGN3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOamcxTmpVMU9UQXpNQjRYRFRJek1EWXdNVEl4TkRVd00xb1hEVEkwTURVegpNVEl4TkRVd00xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJSkdmVXZ0ZUVTREtXVVIKRGkwcXNsbS9EZE4xYk11WDNXWTUxN2gzWnRFRkpxeVB6VlFEMjU1ejlkWkY4QUVCZGhybFJoZjdPWHpCbENRMwpxeERSdFM2alNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCU0xveHFZbFpFaXBUd3JLSTRhc1FKdTQwTkU2ekFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQXF4Y0dmOTZYYXkvY0o5QzFYcm5tUmFWMTZQRG1GaXFIczdWMkpEWFRDVUFDSVFET0dxOUJPWlFaY3FZMQpkU2wzbEswYU50MlJmRUxOdk14aWFkeDhTQ21Ud0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZURDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFMk9EVTJOVFU1TURNd0hoY05Nak13TmpBeE1qRTBOVEF6V2hjTk16TXdOVEk1TWpFME5UQXoKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFMk9EVTJOVFU1TURNd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBU1IvN2RVdXpDSEJSMkF6aVJGNzJOdElvTmJvYlRnU1JFQkRNdmtBaUh1CnhmVHEvejlWUjJud3pmUFg5bno2WlowblpzNGVETmU0RWxwRTkxWDBOK0RtbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVpNk1hbUpXUklxVThLeWlPR3JFQwpidU5EUk9zd0NnWUlLb1pJemowRUF3SURTUUF3UmdJaEFNZlRWVWFvWHVzaUpvVVRzVzhHeHJCd1I2UmF5L0dXClJsaDUrRVZuT2ZsNUFpRUFra3dOcEV2ekJIVU85ZmhwOUNiY0p1WXFpTG4reHRYS04wbFhGVlhhRGU4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUN4bWtHQ0NrOVdrWGN6WENtY0xDSFFVcXdQOFQ1TXJGZ0xBbjZRM051R1ZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZ2taOVMrMTRSSU1wWlJFT0xTcXlXYjhOMDNWc3k1ZmRaam5YdUhkbTBRVW1ySS9OVkFQYgpublAxMWtYd0FRRjJHdVZHRi9zNWZNR1VKRGVyRU5HMUxnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
```
From `extensions.log`:
```
2023-06-01T21:44:12.496Z: Warning: cached client missing, returning nothing
2023-06-01T21:45:20.563Z: Creating new extension manager...
time="2023-06-01T21:45:19Z" level=fatal msg="open /Applications/Rancher Desktop.app/Contents/Resources/resources/rdx-proxy.tgz: no such file or directory"
Error: exit status 1
```

From `k8s.log`:
```
2023-06-01T21:44:39.473Z: Ensuring images available for K3s 1.22.7
2023-06-01T21:44:39.474Z: Will attempt to download exe https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/k3s-arm64 to /Users/iguimaraes/Library/Caches/rancher-desktop/k3s/tmp-v1.22.7+k3s1-sTrqO5/k3s-arm64
2023-06-01T21:44:39.477Z: Will attempt to download images https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/k3s-airgap-images-arm64.tar.zst to /Users/iguimaraes/Library/Caches/rancher-desktop/k3s/tmp-v1.22.7+k3s1-sTrqO5/k3s-airgap-images-arm64.tar.zst
2023-06-01T21:44:39.479Z: Will attempt to download checksum https://github.com/k3s-io/k3s/releases/download/v1.22.7+k3s1/sha256sum-arm64.txt to /Users/iguimaraes/Library/Caches/rancher-desktop/k3s/tmp-v1.22.7+k3s1-sTrqO5/sha256sum-arm64.txt
2023-06-01T21:44:50.582Z: Failed to get k3s version: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 127
 - assuming not installed.
2023-06-01T21:45:03.416Z: Waiting for K3s server to be ready on port 6443...
2023-06-01T21:45:03.428Z: Error: connect ECONNREFUSED 127.0.0.1:6443
2023-06-01T21:45:04.598Z: Updating kubeconfig /Users/iguimaraes/.kube/config...
2023-06-01T21:45:04.652Z: Error fetching services: Error: connect ECONNREFUSED 127.0.0.1:6443
```
Logs:
[Archive.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11630207/Archive.zip)

[Archive.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11630211/Archive.zip)

### Expected Behavior

Rancher Desktop should be able to successfully start with no error dialogs.

### Rancher Desktop Version

1.7.0-1527-gad348984  

### Rancher Desktop K8s Version

1.22.7

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by ericpromislow** [comment] 2023-06-01 22:52
Some notes:

From background.log:
```
2023-06-01T21:45:20.750Z: Kubernetes was unable to start: c [Error]: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/nerdctl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:15385)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  command: [
    '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/nerdctl',
    '--namespace',
    'rancher-desktop-extensions',
    'image',
    'load',
    '--input',
    '/Applications/Rancher Desktop.app/Contents/Resources/resources/rdx-proxy.tgz'
  ],
  code: 1,
  [Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/nerdctl --namespace rancher-desktop-extensions image load --input /Applications/Rancher Desktop.app/Contents/Resources/resources/rdx-proxy.tgz'
}
```

From extensions.log:
```
2023-06-01T21:45:20.563Z: Creating new extension manager...
time="2023-06-01T21:45:19Z" level=fatal msg="open /Applications/Rancher Desktop.app/Contents/Resources/resources/rdx-proxy.tgz: no such file or directory"
```

**Comment by mook-as** [comment] 2023-06-08 23:40
Is this still an issue? It appears to be a (backwards) duplicate of #4875.

**Closed** 2023-06-26 22:29 UTC
Labels: kind/bug, runtime/containerd, priority/1
