### ISSUE TITLE
WSL Nerdctl issue : lstat /Containerfile: no such file or directory

### ISSUE THREAD

**Issue by aman8goku** [rancher-sandbox/rancher-desktop#4742] opened 2023-05-23 16:19 UTC
### Actual Behavior

Hi can anyone help me with this problem in wsl, I am able to run this fine on windows PowerShell but on wsl it gives me this error

`/mnt/d/container-demo # nerdctl build --tag container-demo:latest .`
`FATA[0000] lstat /Containerfile: no such file or directory`

### Steps to Reproduce

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/53210097/582c29b3-c356-4ded-af57-d09fda5e9809)

### Result

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/53210097/5fe45e2d-827b-4444-8f74-b0e98f994c23)

### Expected Behavior

Should build container image

### Rancher Desktop Version

1.8.1

### Rancher Desktop K8s Version

na

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 22H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment] 2023-05-23 16:22
Possible duplicate of #4364

**Comment by billmurrin** [comment] 2024-10-17 19:30
Just wanted to share some information. By renaming `DockerFile to `Containerfile` I am able to get the command to build the dockerfile using nerdctl. I had touched a file named `Containerfile` in the directory to see what would happen and it said the file cannot be empty, which had a lightbulb go off to try renaming my Dockerfile. Seems like it should be a pretty straightforward fix.

**From WSL Terminal**
```
[redacted]:~/containerdemo$ nerdctl build --tag container-demo:latest .
FATA[0000] lstat /home/bmurrin/containerdemo/Containerfile: no such file or directory

[redacted]:~/containerdemo$ mv DockerFile Containerfile

[redacted]:~/containerdemo$ nerdctl build --tag container-demo:latest .
[+] Building 21.6s (13/13) FINISHED
 => [internal] load build definition from Containerfile                                                                                                                                     0.0s
 => => transferring dockerfile: 575B                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest                                                                                                                            1.6s
 => [internal] load .dockerignore                                                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                                             0.0s
 => [1/8] FROM docker.io/library/ubuntu:latest@sha256:d4f6f70979d0758d7a6f81e34a61195677f4f4fa576eaf808b79f17499fd93d1                                                                      2.4s
 => => resolve docker.io/library/ubuntu:latest@sha256:d4f6f70979d0758d7a6f81e34a61195677f4f4fa576eaf808b79f17499fd93d1                                                                      0.0s
 => => sha256:ff65ddf9395be21bfe1f320b7705e539ee44c1053034f801b1a3cbbf2d0f4056 29.75MB / 29.75MB                                                                                            1.9s
 => => extracting sha256:ff65ddf9395be21bfe1f320b7705e539ee44c1053034f801b1a3cbbf2d0f4056                                                                                                   0.5s
 => [internal] load build context                                                                                                                                                           0.0s
 => => transferring context: 471B                                                                                                                                                           0.0s
 => [2/8] RUN apt-get update                                                                                                                                                                5.7s
 => [3/8] RUN apt-get install -y nginx nodejs                                                                                                                                               8.2s
 => [4/8] RUN rm -v /etc/nginx/nginx.conf                                                                                                                                                   0.1s
 => [5/8] ADD nginx.conf /etc/nginx/                                                                                                                                                        0.0s
 => [6/8] ADD web /usr/share/nginx/html/                                                                                                                                                    0.0s
 => [7/8] ADD web /var/www/html/                                                                                                                                                            0.0s
 => [8/8] RUN echo "daemon off;" >> /etc/nginx/nginx.conf                                                                                                                                   0.1s
 => exporting to image                                                                                                                                                                      3.4s
 => => exporting layers                                                                                                                                                                     2.4s
 => => exporting manifest sha256:8ae962cb90e9dfa9378a1b2ca568b8ea909fd3fba012faac2771d413b067ee8f                                                                                           0.0s
 => => exporting config sha256:3f117e6175f677c348d5429d0bf6b314ea8c1cbd42f9ae6bba4648eebd067fc4                                                                                             0.0s
 => => naming to docker.io/library/container-demo:latest                                                                                                                                    0.0s
 => => unpacking to docker.io/library/container-demo:latest
```

**Comment by jandubois** [comment] 2024-10-17 22:16
@billmurrin Thank you for looking into this issue. The error message `last /…/Containerfile: no such file or directory` is indeed displayed if neither `Dockerfile` nor `Containerfile` can be found in the build context.

> A potential fix is to code `DefaultDockerfilename` and `ContainerfileName` to do a more insensitive comparison (e.g., toLower() or toUpper(). At a bare minimum, the error code should inform others that it is case sensitive.

This is something that would have to be done in `nerdctl` and not in Rancher Desktop.

One issue here is though that while the host filesystem on macOS and Windows may not be case-sensitive, the Linux filesystem is.

And unlike the `docker` CLI it is not possible to run the `nerdctl` program on the host; it  talks to the `containerd` API, but also needs filesystem level access to the image store.

So when you run `nerdctl` on a macOS or Windows shell, it just runs a stub program that will invoke the real `nerdctl` inside the Linux VM, working on the mounted filesystem. On Windows this stub also translates the Win32 paths to WSL paths.

So it is not really reasonable to expect `nerdctl` to consider case-insensitive filename matches while running in a case-sensitive environment.

But feel free to open an issue on the `nerdctl` repo; maybe they are willing to do some case-insensitive checking if neither `Dockerfile` nor `Containerfile` can be found.

As there isn't anything we can do about this in Rancher Desktop I'm going to close this issue now.

Thanks again for investigating this and reporting back!

**Closed by jandubois** 2024-10-17 22:16 UTC
Labels: kind/bug, platform/windows, runtime/containerd, triage/need-to-repro

**Comment by billmurrin** [comment] 2024-10-17 22:33
> @billmurrin Thank you for looking into this issue. The error message `last /…/Containerfile: no such file or directory` is indeed displayed if neither `Dockerfile` nor `Containerfile` can be found in the build context.
> 
> > A potential fix is to code `DefaultDockerfilename` and `ContainerfileName` to do a more insensitive comparison (e.g., toLower() or toUpper(). At a bare minimum, the error code should inform others that it is case sensitive.
> 
> This is something that would have to be done in `nerdctl` and not in Rancher Desktop.
> 
> One issue here is though that while the host filesystem on macOS and Windows may not be case-sensitive, the Linux filesystem is.
> 
> And unlike the `docker` CLI it is not possible to run the `nerdctl` program on the host; it talks to the `containerd` API, but also needs filesystem level access to the image store.
> 
> So when you run `nerdctl` on a macOS or Windows shell, it just runs a stub program that will invoke the real `nerdctl` inside the Linux VM, working on the mounted filesystem. On Windows this stub also translates the Win32 paths to WSL paths.
> 
> So it is not really reasonable to expect `nerdctl` to consider case-insensitive filename matches while running in a case-sensitive environment.
> 
> But feel free to open an issue on the `nerdctl` repo; maybe they are willing to do some case-insensitive checking if neither `Dockerfile` nor `Containerfile` can be found.
> 
> As there isn't anything we can do about this in Rancher Desktop I'm going to close this issue now.
> 
> Thanks again for investigating this and reporting back!

That makes a lot of sense. I think strengthening the error message so users are more mindful of OS case sensitivity would make a lot of sense. I'll open an issue on nerdctl and reference this issue. Take care.
