### ISSUE TITLE
Latest Rancher Desktop 1.12.3 fails on startup after clean install on new M3 iMac and M3MAX 16" MBP running macOS "Sonoma" 14.3.1

### ISSUE THREAD

**Issue by fseesink** [rancher-sandbox/rancher-desktop#6561] opened 2024-03-02 17:33 UTC
Experiencing same issue on two (2) new Macs:
- M3 iMac w/ 24GB RAM
- M3MAX 16" MacBook Pro w/ 64GB RAM
- both running macOS "Sonoma" v14.3.1
- Rancher Desktop 1.12.3

(This appears to be the same issue, hence reporting here.  But if you prefer this opened as a new issue, please let me know.)

This makes me think whatever is going on is not architecture specific, nor necessarily solely with 1.12.1.

Mind you these are new Macs.  So clean installs of both macOS 14.x and Rancher Desktop 1.12.3.

After getting error, rebooted system just to see if possibly something needed to be put in place (e.g., the files in `~/.rd/bin/`).  But both system exhibit same behavior.

On firing up Rancher Desktop, they take easily an excruciating 7+ minutes to try and start, eventually showing "Starting virtual machine" in the lower right with the progress bar, and at some point after that kicking up the error as shown in this screenshot take on the M3 iMac (which took nearly 9 minutes):
<img width="1348" alt="Screenshot 2024-02-22 at 11 59 39 AM" src="https://github.com/rancher-sandbox/rancher-desktop/assets/48991/7d59e01c-e184-4f08-9c47-7063756aeec2">

Also attaching the log files (in `.tar.gz` format) from both systems.

I know this is not normal behavior, as I have used Rancher Desktop on a 2019 27" iMac with an Intel Core i7 w/ 32GB RAM for well over a year now.  And usually startup time is ~1.5 minutes give or take.  This shift to the new M3 Macs I knew would bring quite some changes going from x64 to ARM64.  So I did a clean install, not migrating any files/etc.  Hence why I say a clean install, as it's both a new OS (fresh, not upgraded from "Ventura" etc.) and a new install of Rancher Desktop's latest version.

If there is anything else I can provide, please don't hesitate to ask.
[rancherlogs-imac.tar.gz](https://github.com/rancher-sandbox/rancher-desktop/files/14377069/rancherlogs-imac.tar.gz)
[rancherlogs-macbookpro.tar.gz](https://github.com/rancher-sandbox/rancher-desktop/files/14377070/rancherlogs-macbookpro.tar.gz)

As I have yet to begin working with this Rancher Desktop setup, if you need any testing done, please let me know.  I would very much like to get to something usable.

_Originally posted by @fseesink in https://github.com/rancher-sandbox/rancher-desktop/issues/6329#issuecomment-1959895133_

**Comment by fseesink** [comment] 2024-03-02 17:34
It should be noted that after clicking on `[Close]` above and then quitting Rancher Desktop, it took ~3 minutes for each one (on both M3 iMac and M3MAX MBP) to finally shut down.

That is also atypical, as on the 2019 i7 iMac, it would typically take maybe 1-1.5 minutes.

**Comment by fseesink** [comment] 2024-03-02 17:34
Not sure whether this helps or not, but after installing Rancher Desktop and trying to start it, I did modify the default configuration as follows to match what I had on my 2019 iMac:

In Preferences | Application, under General tab:
[x] Allow to acquire administrative credentials (sudo access)
[ ] Check for updates automatically
[ ] Allow collection of anonymous statistics...

In Preferences | Application, under Environment tab:
   Configure PATH (*) Manual
 
In Preferences | Virtual Machine
- 8 GB (iMac) / 16 GB (MBP)
- 3 CPUs (iMac) / 4 CPUs (MBP)

In Preferences | Container Engine
 (*) `containerd`

I left the rest alone, such as the Kubernetes version (`1.28.6 (stable)`), etc.

**Comment by fseesink** [comment] 2024-03-02 17:37
NOTE:  I originally updated issue #6329 last week with this information.  But as there hasn't been a single update since, I wasn't sure whether folks are ignoring that since that ticket's title was about Rancher Desktop 1.12.1 on macOS "Ventura".  As my setup includes two brand new M3 Macs with a clean install of the absolute latest versions of both macOS and Rancher Desktop, I thought maybe I should create a new ticket to make that clear.

[Apologies in advance if this is incorrect.  My intention is NOT to cause more tickets/noise.  And I did search existing tickets and also found #6470 and #6521.  But both of those are for Intel x64 versions of macOS.  And the issue I am experiencing is with the ARM64 version of Rancher Desktop on the latest/greatest macOS.  So you really can't get newer anything than that right now.

Also I have never created a new issue from an existing post.  So not sure how well this shows up vs. using the new issue form that requests versions/etc.  But hopefully I posted everything that's usually asked for.]

But want to make it clear that the issues experienced with 1.21.1 still exist with 1.12.3 and even with the latest version of macOS running on the latest ARM64 chips.  So it's not isolated to a single version nor a single architecture.

**Comment by mook-as** [comment] 2024-03-04 18:20
Hi! You seem to be on M3 machines. Please try using the [VZ virtualization backend](https://docs.rancherdesktop.io/ui/preferences/virtual-machine/emulation#vz); qemu (as currently shipped) doesn't work, but should be improved soon. (I just checked `rancherlogs-imac.tar.gz`; I assume the other has similar issues.)

See also #5943.

**Comment by fseesink** [comment] 2024-03-05 21:36
1. Yes, I'm on M3 machines (M3 iMac, M3MAX MBP).
2. THANKS!  That worked perfectly!  I don't know why I didn't think to check that setting.  I've typically left well enough alone.  But that does make some sense.

So yes, THANK YOU very much!  I really appreciate you taking the time to respond.

**Comment by jandubois** [comment] 2024-03-05 22:20
Closing as a duplicate of #5943

**Closed by jandubois** 2024-03-05 22:20 UTC
