### ISSUE TITLE
Rancher desktop setup fails with error code 4294967295 when initializing k8s environment 

### ISSUE THREAD

**Issue by devtea** [rancher-sandbox/rancher-desktop#959] opened 2021-11-16 14:43 UTC
Rancher desktop can't get k8s to start successfully unless I add the metadata automount option in wsl.conf. This is likely related to WSL issues [6147](https://github.com/microsoft/WSL/issues/6174) and/or [5469](https://github.com/microsoft/WSL/issues/5469) as similar I/O issues show up with non-rancher-desktop WSL distros when the metadata options aren't included in wsl.conf. Whether the issue is a WSL issue or a Rancher issue, the workaround seems fairly straight forward on the rancher side and might be able to be applied for everyone without breaking anything.

**To Reproduce**

1. Install rancher desktop or unregister the rancher-desktop* distros from WSL
2. Start rancher desktop and wait for it to error out during k8s setup

**Result**

An error dialog will pop up showing
`There was an unknown error starting Kubernetes: Error: wsl.exe exited with code 4294967295`

Contents of [wsl.log](https://github.com/rancher-sandbox/rancher-desktop/files/7547033/wsl.log) are attached.

**Expected behavior**

Rancher desktop finishes the k8s initialization successfully without error.

**Workaround steps**

1. Exit rancher desktop
3. Open a wsl console for the rancher-desktop distro: `wsl -d rancher-desktop`
4. Add the following content to /etc/wsl.conf:

```ini
[automount]
options = "metadata"
```

5. Save the file and close the console.
6. Run `wsl --shutdown` or restart the LxssManager service. This is to reset the i/o errors WSL will be seeing and to apply the new config options from wsl.conf.
7. Start rancher-desktop again
8. K8s will now be initialized properly

**Setup (please complete the following information):**

 - OS: Windows 10 build 19043.1288
 - Rancher Desktop version: 0.6.1
 - Kubernetes version: tested on 1.19.16, 1.20.12, 1.21.6

**Comment by mattfarina** [comment] 2021-11-16 15:52
@devtea thanks for providing so much detail and reporting the issue.

I've been using Rancher Desktop on Windows since before it was public. I've not needed this configuration which makes me wonder what else is going on. If you have some other customization with your WSL setup we would love to know about it so we can better understand what's happening.

In any case, we will look into this.

**Comment by devtea** [comment] 2021-11-16 17:02
@mattfarina I'm not aware of any WSL specific customizations off hand, but I'll keep thinking about it. I can say that this only happens on my company provided workstation so it makes me wonder if there's some GPO or security configuration that's causing the behavior.

**Comment by mook-as** [comment] 2021-11-16 17:35
For reference, that's [a mount option](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#mount-options).  As I understand it, that option basically turns on storing Linux-side permissions in NTFS alternate data streams.

It's unclear to me why _not_ setting that leads to "Bad address" when opening a file; looking it up, that's actually `EFAULT`, which isn't (necessarily) related to 9p…  I'm a bit uncomfortable just putting the change in if we can't be sure of the cause (and some of the comments in the issues you linked reported that it didn't help _them_).

If you can reproduce this reliably, would you be able to attach `dmesg` from around when this happens? (And any disk-related issues earlier in `dmesg`; it may be easier to do a `wsl --shutdown` before attempting to reproduce.)

**Comment by devtea** [comment] 2021-11-19 19:14
Here's two dmesg outputs, one from a freshly initted rancher-desktop distro (after unregistering it and letting rancher desktop recreate it), and one from after applying my wsl.conf config from above.

[dmesg_before.txt](https://github.com/rancher-sandbox/rancher-desktop/files/7572454/dmesg_before.txt)
[dmesg_after.txt](https://github.com/rancher-sandbox/rancher-desktop/files/7572457/dmesg_after.txt)

**Comment by gaktive** [comment] 2022-01-15 00:46
This should be fixed as part of 1.0.0 beta 1 as we introduced a solution in https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/pull/20

**Comment by gaktive** [comment] 2022-01-15 00:46
If this is still a problem, please open a new ticket.

**Closed by gaktive** 2022-01-15 00:46 UTC
Labels: kind/bug, platform/windows
