### ISSUE TITLE
On startup, the UI should have a "Starting up..." banner

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#3030] opened 2022-09-27 18:46 UTC
### Problem Description

Particularly when k8s is disabled, for about 30 seconds the UI has no banner, and then it starts initializing the VM.

What's going on is that apparently at startup running `limactl list` takes a while. There should be some kind of feedback so the user knows the app is still starting up.

### Proposed Solution

Put up some kind of banner right at the beginning.

**Comment by jandubois** [comment] 2022-09-27 20:34
> What's going on is that apparently at startup running `limactl list` takes a while.

I don't think so, as the delay also happens on Windows. I thought it is the time to get the list of k8s versions because they are needed for the dropdown in the first-run dialog.

Anyways, this seems like a duplicate of #2153

**Closed by jandubois** 2022-09-27 20:34 UTC
Labels: kind/enhancement, component/ui
