### ISSUE TITLE
Wrong version displayed in settings while RD starting

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#291] opened 2021-05-13 20:55 UTC
When RD is starting the latest version of Kubernetes is displayed. It updates once RD is started to the actual version. It shouldn't show the wrong version. We can handle this differently.

**Comment by ericpromislow** [comment] 2021-06-01 20:01
I saw this once (possibly), but can't reproduce it, on both windows and macos, with both dev and release builds.

**Comment by mook-as** [comment] 2021-06-01 20:38
This was probably fixed in #311, specifically ba2d570336e390ecf953c82734acf3540cb5efae.

**Closed by mook-as** 2021-06-01 20:38 UTC
Labels: bug

**Comment by ericpromislow** [comment] 2021-06-01 20:53
Makes sense.
