### ISSUE TITLE
Moby ERROR: no valid drivers found: Cannot connect to the Docker daemon at unix:///var/run/docker.sock.

### ISSUE THREAD

**Issue by marcofranssen** [rancher-sandbox/rancher-desktop#3420] opened 2022-11-21 09:20 UTC
### Actual Behavior

After running `docker buildx…` a couple of times I get the following error. I'm building a multi platform image for amd64 and arm64

```shell
ERROR: no valid drivers found: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
…… Error 1
```

### Steps to Reproduce

**main.go**

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello World!")
}
```

**Dockerfile**

```Dockerfile
FROM --platform=${BUILDPLATFORM} tonistiigi/xx:1.1.2 AS xx

FROM --platform=${BUILDPLATFORM} golang:1.19-alpine as builder
ARG TARGETPLATFORM
WORKDIR /build
ENV CGO_ENABLED="1"
RUN apk add --update --no-cache clang lld make git mercurial
COPY --from=xx / /
ARG TARGETPLATFORM
RUN xx-apk add --update --no-cache build-base musl-dev
COPY go.* .
RUN xx-go --wrap
# https://go.dev/ref/mod#module-cache
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY . .
RUN --mount=from=crazymax/osxcross:11.3-r8,src=/osxsdk,target=/xx-sdk \
  --mount=type=cache,target=/root/.cache/go-build \
  --mount=type=cache,target=/go/pkg/mod <<EOT
  set -ex
  CGO_ENABLED=1 go build -ldflags '-s -w -linkmode external -extldflags "-static"' -o bin/my-app
  xx-verify bin/my-app
EOT

FROM --platform=${BUILDPLATFORM} cgr.dev/chainguard/static:latest AS runtime
WORKDIR /opt/my-app
CMD []

FROM --platform=${BUILDPLATFORM} runtime AS my-app
COPY --from=builder /opt/my-app/my-app bin/my-app
ENTRYPOINT ["/opt/my-app/my-app"]
```

```shell
docker buildx build \
	--platform linux/amd64,linux/arm64,linux/arm64/v7,linux/arm64/v8
	-o type=oci,dest,my-image.tar
	.
```

### Result

```shell
ERROR: no valid drivers found: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
…… Error 1
```

### Expected Behavior

The `docker.sock` should not crash. Or at least Rancher Desktop should internally reboot Moby to fix it automatically.

### Additional Information

After rebooting Rancher desktop the Docker sock works again for a while until `buildx` makes it crash again.

Running the VM with:

- 6GB memory
- 5 CPUs
- K8s enabled

### Rancher Desktop Version

1.6.2

### Rancher Desktop K8s Version

1.25.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Ventura 13.0.1

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

AppImage

**Comment by rak-phillip** [comment] 2022-11-22 18:21
@marcofranssen thanks for raising this issue and helping to make Rancher Desktop better! 

Unfortunately, it looks like the example provided requires some additional modification in order to run. Can you provide a minimal reproduction that our team can use to help triage the issue?

**Comment by marcofranssen** [comment] 2022-11-23 11:10
Probably the easiest is to try building an image with this PR.

https://github.com/spiffe/spire/pull/3607

```shell
make images load-images
```

or

```shell
make static-images load-static-images
```

**Comment by gunamata** [comment] 2023-01-13 04:01
@marcofranssen , I could successfully build a multi platform image using `docker buildx`. I used a simple example.. Below are my steps that worked..

```
git clone https://github.com/mattfarina/hello-world-vs-bci.git
cd hello-world-vs-bci
docker buildx build --platform linux/amd64,linux/arm64 -o type=oci,dest=my-image.tar .
```

Do you still face problems using `docker buildx`?

**Comment by marcofranssen** [comment] 2023-01-13 10:23
I resolved the issue. Was some --cache argument which I used in the Dockerfile that caused this. Don't remember which one. Without that --cache it now succeeds.

**Comment by gunamata** [comment] 2023-02-08 04:39
Closing the issue as the problem seems to have got resolved.

**Closed by gunamata** 2023-02-08 04:39 UTC
Labels: kind/bug, triage/needs-information
