### ISSUE TITLE
nerdctl not working in WSL2 after installing Rancher Desktop

### ISSUE THREAD

**Issue by codeagencybe** [rancher-sandbox/rancher-desktop#1247] opened 2022-01-14 11:24 UTC
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

1.22.5 (stable)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 21H2

### What CPU architecture are you using?

x64

### Windows User Only

clean install Windows 11 pro with WSL2 and Ubuntu 

After installing RD it returns this in WSL

PS C:\Users\FabioTielen> wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
rancher-desktop-data
rancher-desktop

### Actual Behavior

nerdctl
Trying to run any nerdctl command returns below

`/mnt/c/Users/FabioTielen/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/bin/nerdctl: 4: exec: /mnt/wsl/rancher-desktop/bin/nerdctl: not found`

### Steps to Reproduce

install RD 0.7.1. on a Windows 11 with WSL2 and Ubuntu

### Result

`/mnt/c/Users/FabioTielen/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/bin/nerdctl: 4: exec: /mnt/wsl/rancher-desktop/bin/nerdctl: not found`

### Expected Behavior

run the nerdctl command

**Comment by mook-as** [comment] 2022-01-14 17:53
Hmm, we might need more details:
- Can you add the output of `wsl --list --verbose`? (This would tell me ⑴ if Rancher Desktop is running, and ⑵ which WSL version Ubuntu is using.)
- What does `/etc/wsl.conf` look like in your Ubuntu distribution?
- What is the last element to exist on the path `/mnt/wsl/rancher-desktop/bin/nerdctl`? (That is, what is the deepest directory on that path that exists? Presumably the actual executable is missing.)
- Does running `nerdctl` from Windows (outside of WSL) work?

Thanks!

**Comment by codeagencybe** [comment] 2022-01-15 10:11
Hello Mark @mook-as 

Thanks for helping me! 

Output from wsl list
<img width="413" alt="image" src="https://user-images.githubusercontent.com/7568546/149617933-6405fb02-dcf3-4a85-bcfa-a1bc03ffc50d.png">

output from /etc/wsl
<img width="501" alt="image" src="https://user-images.githubusercontent.com/7568546/149617948-4f9e7eeb-89ad-46b6-a166-9100ef703441.png">

Yes, nerdctl was running fine from powershell but not from Ubuntu WSL
<img width="996" alt="image" src="https://user-images.githubusercontent.com/7568546/149617977-0f441abc-b574-45bf-a86e-875bc0fca80a.png">

I have uninstalled everything completely and re-installed back, and now it seems to be working fine even while /etc/wsl.conf still returns no such file or directory error. 
Also I now notice that the checkbox for Ubuntu is now appearing in WSL integration. It was not showing up before after first installation of Rancher desktop. And yes, WSL Ubuntu was working fine already as I had Docker for Desktop working fine. 
I think there must have been a glitch in the first installation somehow, can't say exactly what, but an uninstall and re-install did seems to fix the problem. 

<img width="988" alt="image" src="https://user-images.githubusercontent.com/7568546/149617917-662a8fe3-9925-4607-8168-354b0944ae55.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/7568546/149617923-5d00777e-3f5b-4493-9aed-2130769cc286.png">

**Comment by mook-as** [comment] 2022-01-17 18:19
Hmm. At this point, I don't think we can get enough information to figure out what happened (since it's no longer reproducible).  I'll close it for now, but please feel free to reopen if this happens again.

If it does, please also attach your logs (there's a button in the _Troubleshooting_ page to show them).  Odd that the Ubuntu checkbox was missing; that would mean we didn't see it in `wsl --list`…

**Closed by mook-as** 2022-01-17 18:19 UTC
Labels: kind/bug
