### ISSUE TITLE
Error on trying to build the image: FATA[0000] unrecognized image format

### ISSUE THREAD

**Issue by jvahldick** [rancher-sandbox/rancher-desktop#2719] opened 2022-08-10 14:19 UTC
### Actual Behavior

I am trying to build an image using nerdctl, and for any RUN command in the dockerfile I'm getting the following issue:
```bash
error: failed to solve: process "/bin/sh -c echo abc" did not complete successfully: exit code: 127
FATA[0001] unrecognized image format
```

### Steps to Reproduce

I just created a simple Dockerfile based on a base image.

```bash
nerdctl pull ccthub/google-ad-service-php:1.1
```

Dockerfile:
```Dockerifle
FROM ccthub/google-ad-service-php:1.1
RUN echo abc
```

```bash
nerdctl build .
```

### Result

```bash
$ nerdctl build .
[+] Building 1.1s (5/5) FINISHED
 => [internal] load .dockerignore                                                                                   0.0s
 => => transferring context: 2B                                                                                     0.0s
 => [internal] load build definition from Dockerfile                                                                0.0s
 => => transferring dockerfile: 110B                                                                                0.0s
 => [internal] load metadata for docker.io/ccthub/google-ad-service-php:1.1                                         0.6s
 => CACHED [1/2] FROM docker.io/ccthub/google-ad-service-php:1.1@sha256:abb61362bdadb778ad5e0ef214c894d95f42a65d8d  0.0s
 => => resolve docker.io/ccthub/google-ad-service-php:1.1@sha256:abb61362bdadb778ad5e0ef214c894d95f42a65d8deb193b9  0.0s
 => ERROR [2/2] RUN echo abc                                                                                        0.5s
------
 > [2/2] RUN echo abc:
#0 0.091 c: applet not found
------
Dockerfile:2
--------------------
   1 |     FROM --platform=linux/amd64 ccthub/google-ad-service-php:1.1
   2 | >>> RUN echo abc
--------------------
error: failed to solve: process "/bin/sh -c echo abc" did not complete successfully: exit code: 127
FATA[0001] unrecognized image format
```

### Expected Behavior

I was expecting this to work, but I don't understand the exact issue here.

### Rancher Desktop Version

1.5.0

### Rancher Desktop K8s Version

1.22.12

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.5

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by mook-as** [comment] 2022-08-11 17:49
> #0 0.091 c: applet not found

There was a bug in Rancher Desktop 1.5.0 that caused issue running x86_64 binaries on aarch64 machines (and vice versa); please see #2659 for details, and https://github.com/rancher-sandbox/rancher-desktop/issues/2668#issuecomment-1204629914 for a temporary workaround while we work to create a patch release. Sorry for the trouble, and thank you for filing the bug!

Closing this one as a duplicate of #2659; please feel free to comment if that does not fix your issue, though.

**Closed by mook-as** 2022-08-11 17:49 UTC
Labels: kind/bug
