### ISSUE TITLE
Metrics server not working with Docker backend

### ISSUE THREAD

**Issue by wpwoodjr** [rancher-sandbox/rancher-desktop#2015] opened 2022-04-09 13:13 UTC
### Actual Behavior

The metrics server is failing to go "ready" and has repeated errors in the logs when using the Docker backend.

With containerd backend it works.  I tested on Windows and Mac, same behavior.

### Steps to Reproduce

1. Start Rancher Desktop using Docker backend.  
2. Start a pod:

```
kubectl run --image=nginx nginx
```

### Result

After a short while, the metrics server pod enters 0/1 Ready state, logs show repeated errors and metrics are not available to tools like k9s.

`kubectl describe` shows: `Warning  Unhealthy  4m22s (x49 over 19m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 500`

Logs sample:
```
E0409 13:05:07.956128       1 scraper.go:139] "Failed to scrape node" err="Get \"https://192.168.86.41:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="lima-rancher-desktop"
I0409 13:05:08.272265       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0409 13:05:10.265627       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0409 13:05:12.267414       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0409 13:05:14.268862       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0409 13:05:16.266800       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0409 13:05:18.271612       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0409 13:05:20.278665       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0409 13:05:22.266007       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
E0409 13:05:22.952394       1 scraper.go:139] "Failed to scrape node" err="Get \"https://192.168.86.41:10250/stats/summary?only_cpu_and_memory=true\": context deadline exceeded" node="lima-rancher-desktop"
```

### Expected Behavior

Metrics are working, no repeated errors in logs.

### Rancher Desktop Version

1.2.1

### Rancher Desktop K8s Version

1.22.7

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS and Windows 11

### Operating System / Build Version

macOS Monterey 12.3.1 and Windows 11

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment] 2022-04-09 17:43
Looks like a duplicate of #2012

**Closed by jandubois** 2022-04-09 17:43 UTC
Labels: kind/bug
