### ISSUE TITLE
Error Starting Kubernetes

### ISSUE THREAD

**Issue by sestegra** [rancher-sandbox/rancher-desktop#1455] opened 2022-02-02 09:57 UTC
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

1.22.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS 12.1 (21C52)

### What CPU architecture are you using?

x64

### Actual Behavior

During Kubernetes startup, the virtual machine can't be started.

### Steps to Reproduce

- Open Rancher Desktop application
- Select `Kubernetes Settings`
- Click on `Reset Kubernetes` button

### Result

```
Error Starting Kubernetes
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
Last command run:
limactl start --tty=false /Users/xxxxxxxxxxxxxxxxxxxxx/Library/Application Support/rancher-desktop/lima/_config/0.yaml

Context:
Starting virtual machine

Some recent logfile lines:
2022-02-02T09:52:36.627Z: Running command limactl list --json...
2022-02-02T09:52:37.054Z: Running command limactl start --tty=false /Users/xxxxxxxxxxxxxxxxxxxxx/Library/Application Support/rancher-desktop/lima/_config/0.yaml...
time="2022-02-02T10:52:37+01:00" level=fatal msg="instance name \"0\" too long: \"/Users/xxxxxxxxxxxxxxxxxxxxx/Library/Application Support/rancher-desktop/lima/0/ssh.sock.1234567890123456\" must be less than UNIX_PATH_MAX=104 characers, but is 105"
2022-02-02T09:52:37.498Z: + limactl start --tty=false /Users/xxxxxxxxxxxxxxxxxxxxx/Library/Application Support/rancher-desktop/lima/_config/0.yaml
2022-02-02T09:52:37.498Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-02-02T09:52:37.498Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8656)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

### Expected Behavior

The virtual machine should start whatever the length of the username.

**Comment by jandubois** [comment] 2022-02-02 20:35
This is a duplicate of #797 which also includes a workaround for this issue.

**Closed by jandubois** 2022-02-02 20:35 UTC
Labels: kind/bug
