### ISSUE TITLE
path management diagnostic doesn't seem to be working on Linux

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#6964] opened 2024-05-30 15:57 UTC
Qase 50:

As per the testcase, if PATH is set to manual at Preferences > Application > Environment, the Diagnostics page should show respective diagnostic, which is not happening.

**Comment by jandubois** [comment] 2024-05-30 16:10
This change by #6954 is by design to fix #6953.

I think this test should be removed from Qase.

The https://github.com/rancher-sandbox/rancher-desktop/blob/main/bats/tests/preferences/verify-settings.bats test is testing a similar scenario, that changing the Windows proxy setting on macOS/Linux is not supported, to make sure the validation mechanism works.

Please close this issue when you have removed Qase#50.

**Comment by mook-as** [comment] 2024-05-30 21:55
I can confirm. Also:
> Check RD_BIN_IN_BASH_PATH result: {"description":"The `~/.rd/bin` directory is found in your `PATH` as seen from **bash**.","passed":true,"fixes":[]}

So it's actually passing, which is why it's not warning. I can also confirm that my shell still has `~/.rd/bin/` in my PATH.

I can get the diagnostic to show up after I log out and back in.

**Comment by gunamata** [comment] 2024-07-16 16:05
Updated the Qase RD-50. Added a step to log off and log back in to see the expected diagnostic result.

**Comment by mook-as** [comment] 2024-07-16 21:15
No, because opening a new terminal application wouldn't have seen the change either; `.profile` (etc.) is only loaded when you log in, and that's the file we modify.

**Comment by jandubois** [comment] 2024-07-16 21:40
> No, because opening a new terminal application wouldn't have seen the change either; `.profile` (etc.) is only loaded when you log in, and that's the file we modify.

That does not sound correct. At least the intention of the code is to modify the first file of this list that exists:

```js
      const bashLoginShellFiles = [
        '.bash_profile',
        '.bash_login',
        '.profile',
      ];
```

If none of them exist, we create `.bash_profile`.

But regardless, the `bash` documentation says:

> When  bash  is  invoked as an interactive login shell, or as a non-interactive shell with the `--login` option, it first reads and executes commands from the  file  `/etc/profile`,  if  that file  exists.   After  reading  that  file,  it  looks  for `~/.bash_profile`,  `~/.bash_login`,  and  `~/.profile`,  in that order, and reads and executes commands from the first one that exists and is readable.  The `--noprofile` option may be used when the shell is started to inhibit this behavior.

So something doesn't add up here.

**Closed** 2024-09-26 21:20 UTC
Labels: kind/bug, platform/linux, area/diagnostics, qase
