### ISSUE TITLE
First-run Window is not launched after Factory Reset

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#2983] opened 2022-09-22 18:16 UTC
### Actual Behavior

First run Window is not launched after Factory Reset

### Steps to Reproduce

1. Launch Rancher Desktop
2. Click on Factory Reset in troubleshooting
3. Click Rancher Desktop icon in the dock 
4. Wait for Rancher Desktop to relaunch
5. Right click Rancher Desktop icon in the dock to check all windows

### Result

Rancher Desktop seems to be running, but the first-run window does not launch.

### Expected Behavior

Rancher Desktop should launch and display the main window and first-run window.

### Rancher Desktop Version

1.5.0-633-g9c45d491

### Rancher Desktop K8s Version

1.25.0

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

x64

**Comment by IsaSih** [comment] 2022-09-22 18:32
Workaround for this is to quit rancher Desktop and open Rancher Desktop  again.

**Comment by mook-as** [comment] 2022-09-22 18:51
Hmm, the first run window _eventually_ opened for me without manually quitting first. (I was actually looking at the logs by that point trying to figure out what was wrong; it was definitely longer than I expected.)

**Comment by jandubois** [comment] 2022-09-22 20:31
I cannot reproduce this problem, neither with 1.5.0-633-g9c45d491 nor with a later build.

Rancher Desktop starts again and shows the first-run dialog within 10s or so.

Testing on Catalina and not Monterey though.

**Comment by gaktive** [comment] 2022-09-22 23:42
Passing back to @IsaSih to repro and collect more data.

**Comment by jandubois** [comment] 2022-09-23 02:13
@IsaSih could no longer reproduce it either, so we agreed to close this issue for now.

**Closed by jandubois** 2022-09-23 02:13 UTC
Labels: kind/bug, triage/need-to-repro
